### PR TITLE
wip: improve benchmark serving

### PR DESCRIPTION
**Pull request by simon-mo**

### CODE REVIEW

**Comment by Rogerwyf** [comment]
@simon-mo Should we consolidate work together at https://github.com/vllm-project/vllm/pull/2433?

I'm totally ok with you pushing your changes directly to that PR, but if you think this PR is going to be a quick one, I can integrate the changes after it's merged into my PR too!

**Comment by ywang96** [comment]
@simon-mo Should we consolidate work together at https://github.com/vllm-project/vllm/pull/2433?

I'm totally ok with you pushing your changes directly to that PR, but if you think this PR is going to be a quick one, I can integrate the changes after it's merged into my PR too!

**Comment by simon-mo** [comment]
Can you just take my diff and incorporate it into your PR? I will close this one and review yours when it's ready!

**Comment by ywang96** [comment]
> Can you just take my diff and incorporate it into your PR? I will close this one and review yours when it's ready!

Yep!

**Pull request closed without merging**
