### PR TITLE
fix #1478 remove check_model in OpenAI API

### LINKED ISSUE #1478: OpenAI API model_check should be optional or removed
There doesn't seem to be a good reason to check the model name since a single vLLM only serves one model. Instead I would prefer to either have the `check_model` function [1] removed or be able to turn the check off through configuration.

[1] https://github.com/vllm-project/vllm/blob/v0.2.1/vllm/entrypoints/openai/api_server.py#L62

### PR DESCRIPTION
**Pull request by samos123**
The OpenAI API only serves 1 model so it's a poor UX when you get an error because the model string didn't match. This is helpful for systems that require setting a different model name in the request.

### CODE REVIEW

**Review by simon-mo — CHANGES_REQUESTED** [review]
Thank you for your contribution. I would suggest to implement this as a feature flag from the command line, something like `--no-check-model` as a boolean variable that is disabled by default. Correctness is still pretty useful in particular we don't want users to confuse the models.

**Comment by samos123** [comment]
That makes sense. I will make it into a check instead. Thanks a bunch for the quick review.

**Comment by samos123** [comment]
I can't seem to test this locally, my laptop hangs when running `pip install -e .`

**Comment by simon-mo** [comment]
Sorry about the back and forth. I discussed with team and realized that this parameter is not needed. There is already the parameter to configure model name. You can just pass in the default model name for OpenAI for your workload like `--served-model-name gpt-3.5-turbo` and it doesn't require any changes to the client. It is the same UX as disabling the check as long as the client understood it. You can also just set the model name to be like `default` and align with client on it.

**Comment by samos123** [comment]
It is needed for me because I need to be able to serve a single model under different model names. Could you please reconsider? I will have no choice but to fork and create our own OpenAI entrypoint, which is fine too just something I rather avoid if possible.

**Comment by AaronFriel** [comment]
Hey @simon-mo, could we reconsider this? When deploying models using infrastructure as code, this makes the API brittle such that one cannot roll out a change to use a new model behind a load balancer. Instead of being able to do a gradual rollout, clients, load balancers, and servers must be tightly coupled. 

In scenarios where GPUs may have limited capacity, it would be nice to be able to do a gradual rollout of servers to replace them while keeping the # relatively constant to keep serving demand.

**Pull request closed without merging**
