### PR TITLE
Refactor scheduler

### PR DESCRIPTION
**Pull request by WoosukKwon**
This PR refactors the vLLM's scheduler. For a major change, vLLM now uses a TGI-style continuous batching mechanism. For minor changes, this PR makes the scheduler code more concise by moving the logging part to `LLMEngine` and moving some data structures to `SchedulerOutputs`.

### CODE REVIEW

**Review by zhuohan123 — APPROVED** [review]
LGTM!

**Comment by zhm9484** [comment]
vLLM is an awesome library!
I'm curious about the reason why changing to the TGI-style continuous batching mechanism.
Could you elaborate on this? @WoosukKwon @zhuohan123

**Comment by Oliver-ss** [comment]
Curious too! 

It seems like the input could have both prompt tokens and generation tokens before, but now it consists of either prompt tokens or generation tokens.

From my point of view, combining prompt tokens with generation tokens in a batch might be beneficial to the total throughput as the generation token length of each sequence is always one which could not make full use of the GPU except for a very large batch size like 512.

@WoosukKwon @zhuohan123

**Comment by PanQiWei** [comment]
I'm also working on a private llm inference optimization project, which also considered TGI style continuous batching instead of vllm's previous version. My point of view is: separate prefill and decode as two operations and only execute one kind of operation at a time is better for productive deployment, for that we can tune a hyper-parameter to control the ratio of the two operations to be performed based on characteristics of the request traffic.

**Comment by SiriusNEO** [comment]
Thanks for bringing us such marvelous project! But I have a small question about this new version of scheduler: Why in L118 we let `num_batched_tokens = 0` instead of `sum of tokens in currently running seqs`?

I'm worried that this may cause the token num of later iterations exceed the constraint `scheduler_config.max_num_batched_tokens`, since you only consider the `num_batched_tokens` of the prompt running. 

@WoosukKwon @zhuohan123 @LiuXiaoxuanPKU

**Comment by lw921014** [comment]
> Curious too!
> 
> It seems like the input could have both prompt tokens and generation tokens before, but now it consists of either prompt tokens or generation tokens.
> 
> From my point of view, combining prompt tokens with generation tokens in a batch might be beneficial to the total throughput as the generation token length of each sequence is always one which could not make full use of the GPU except for a very large batch size like 512.
> 
> @WoosukKwon @zhuohan123

I agree with you. But I think, this change may be benifit from Load Balance between  prompt tokens and generation tokens especially when certain step have 90% prompt tokens and 10% generation tokens, under this situation, for generation attention(single kv attention kernel), the real batch  size is very small, which may cause low efficiency. Do you think so? @WoosukKwon @zhm9484

**Pull request merged**
