### PR TITLE
Add stram output

### PR DESCRIPTION
**Pull request by zishengwu**
add simple code to enable stream in vllm.
issue can be found in : https://github.com/vllm-project/vllm/issues/351

### CODE REVIEW

**Review by hverma-forrester — APPROVED** [review]

**Comment by Sajalj98** [comment]
Please review and approve this commit.
Thanks.

**Comment by chris-aeviator** [comment]
@Sajalj98 @zishengwu I think what we might want, and why this PR might not be merged as of yet is AsyncEngine.generate which already implements streaming https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py#L44C45-L44C45

**Comment by speggioale** [comment]
Hello! Is there any plan to merge this feature? I understand that streaming is currently possible through `AsyncEngine.generate`, but it would be fantastic to have this functionality directly in Python code without having to run the API server. Could you let us know if this is on your roadmap? Any updates on this would be greatly appreciated. Thank you!

**Comment by speggioale** [comment]
@chris-aeviator 
I've noticed that this feature is utilized in `vllm/entrypoints/api_server.py`. However, exposing it directly in the main VLLM class (with the option to enable or disable it via a flag, as proposed in this pull request) could still be beneficial. It might be a lower priority, though. In any case, thank you for your response!

**Comment by AntreasAntoniou** [comment]
I still think that this idea here is very valuable, as it's a lot more intuitive and far less complicated to just pass stream=True to the VLLM engine we know and love, rather than messing around with a new async class that seemingly requires a server to be running, or at least to use a separate class such as async_engine that has different structure from VLLM.

**Pull request closed without merging**
