### PR TITLE
[Model][LoRA]LoRA support added for Qwen

### LINKED ISSUE #3458: baichuan/qwen/chatlgm with lora adaption [feature]
### 🚀 The feature, motivation and pitch

Popular chinese llms like baichuan/baichuan2/qwen/chatglm can be supported.

### Alternatives

_No response_

### Additional context

_No response_

### LINKED ISSUE #9584: [Feature]: LoRA support for Qwen model
### 🚀 The feature, motivation and pitch

[rank0]: ValueError: Model QWenLMHeadModel does not support LoRA, but LoRA is enabled. Support for this model may be added in the future. If this is important to you, please open an issue on github.

### Alternatives

_No response_

### Additional context

_No response_

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by jeejeelee**
FILL IN THE PR DESCRIPTION HERE

FIX #3458
FIX #9584

Distinguish between Qwen LLM and VL to better support LoRA (similar treatment needed for ChatGLM as well). ~~Currently set as WIP, the main purpose is to discuss whether this solution(separate LLM and VL) is acceptable , if accepted, I will continue to complete it.~~
ping @ywang96  @DarkLight1337

### CODE REVIEW

**Review by DarkLight1337 — APPROVED** [review]
Looks good, sorry for making you wait!

**Comment by DarkLight1337** [comment]
Just realized that the Supported Models page hasn't been updated yet. @jeejeelee can you open a new PR to update that page with the new LoRA support?

**Comment by jeejeelee** [comment]
> Just realized that the Supported Models page hasn't been updated yet. @jeejeelee can you open a new PR to update that page with the new LoRA support? We should also explicitly inherit from `SupportsLoRA` in `QWenLMHeadModel`.

Okay, handling it now

**Comment by jeejeelee** [comment]
>  We should also explicitly inherit from `SupportsLoRA` in `QWenLMHeadModel`.

Why do we need to do it?

**Comment by DarkLight1337** [comment]
> > We should also explicitly inherit from `SupportsLoRA` in `QWenLMHeadModel`.
> 
> Why do we need to do it?

Easier to find which models support LoRA.

**Comment by jeejeelee** [comment]
> > > We should also explicitly inherit from `SupportsLoRA` in `QWenLMHeadModel`.
> > 
> > 
> > Why do we need to do it?
> 
> Easier to find which models support LoRA.

Get it!

**Pull request merged**
