### PR TITLE
Bump up transformers version & Remove MistralConfig

### PR DESCRIPTION
**Pull request by WoosukKwon**
Now that MistralConfig is officially supported by the stable release of HF transformers, we can remove our `MistralConfig`.

### CODE REVIEW

**Review by zhuohan123 — APPROVED** [review]
The PR LGTM! However, I think we need to make sure that the tokenizer performance is good before we merge this PR.

**Comment by TensorTemplar** [comment]
Hey i built this from source and there is an issue with the openai server:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/vllm/vllm/entrypoints/openai/api_server.py", line 616, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/src/vllm/vllm/engine/async_llm_engine.py", line 487, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/src/vllm/vllm/engine/async_llm_engine.py", line 270, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/src/vllm/vllm/engine/async_llm_engine.py", line 306, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/src/vllm/vllm/engine/llm_engine.py", line 110, in __init__
    self._init_workers(distributed_init_method)
  File "/usr/src/vllm/vllm/engine/llm_engine.py", line 142, in _init_workers
    self._run_workers(
  File "/usr/src/vllm/vllm/engine/llm_engine.py", line 694, in _run_workers
    output = executor(*args, **kwargs)
  File "/usr/src/vllm/vllm/worker/worker.py", line 68, in init_model
    self.model = get_model(self.model_config)
  File "/usr/src/vllm/vllm/model_executor/model_loader.py", line 61, in get_model
    model_class = _get_model_architecture(model_config.hf_config)
  File "/usr/src/vllm/vllm/model_executor/model_loader.py", line 55, in _get_model_architecture
    raise ValueError(
ValueError: Model architectures ['MistralModel'] are not supported for now. Supported architectures: ['AquilaModel', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'FalconForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MPTForCausalLM', 'OPTForCausalLM', 'QWenLMHeadModel', 'RWForCausalLM']
```

Does it work for you with these changes?

**Comment by WoosukKwon** [comment]
> The PR LGTM! However, I think we need to make sure that the tokenizer performance is good before we merge this PR.

@zhuohan123 I think the performance issue is orthogonal to the PR, since new users will install the newest version of transformers and experience the performance issue anyway.

**Comment by irasin** [comment]
Hi @WoosukKwon, @zhuohan123, I found a slight performance down(about 0.04 request/sec for llama7B) from transformers==4.33.1 to transformers==4.34.0. I'm curious what causes the performance issue.

**Pull request merged**
