### PR TITLE
[Core] Use Appropriate `torch.dtype` for FP8 KV Cache

### PR DESCRIPTION
**Pull request by jon-chuang**
More strictly enforce storage format to be well-typed

FIX https://github.com/vllm-project/vllm/pull/7208#discussion_r1709610732
> Other code or outstanding PR may depend implicitly on this behaviour. This refactor to store fp8 KV cache not in uint8 dtype is unrelated to this PR and prefer if it is done separately.

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by mgoin — COMMENTED** [review]
This looks good to me in principle, but I would need to look through the c++ code to understand if anything depends on the type being uint8

**Comment by comaniac** [comment]
Yeah I'm wondering how this works without changing anything in the kernel...

**Comment by jon-chuang** [comment]
Yes I looked through the code but found no evidence of behaviour depending specifically on the torch dtype being uint8.

**Comment by comaniac** [comment]
I manually triggered kernel testing to make sure this change works for them. Otherwise LGTM to me. Also cc @mgoin

**Comment by comaniac** [comment]
Seems related. Please run this test locally with the fix then

**Comment by jon-chuang** [comment]
@comaniac turns out some kernels have implicit dep on uint8, but it's not serious. Please see the updated code for the changes required.

Note: I'm not entirely convinced storing in fp8 format as resting data type is strictly good way to go. There is a tradeoff between complexity of handling the implicit storage dtype and converting to required dtype for consumption by things like torch or triton.

I think there is friction either way and perhaps the previous behaviour to store the resting format as uint8 and convert into fp8-specific is better as it reduces the number of formats one need to keep track of implicitly.

**Comment by jon-chuang** [comment]
Closing this; too many kernels depend on implicit uint8 and I think changing to fp8-typed storage has no real benefit

**Comment by pavanimajety** [comment]
@jon-chuang I was hoping to use Neural Magic's `-KV` models for FP8 KV Cache with FlashInfer(#7798) by removing the assertion added by @mgoin for k_scale and v_scale in flashinfer.py backend. I was running into numerical errors which I think are rooted in the fact that provided KV Scales don't work with uint8 datatype used for reshaping kv_cache using `reshape_and_cache_flash`. Since you have some experience with this, what would you say is required to get this function to work with "float8_e4m3" datatype?  

@mgoin Please let me know if you have any insights here.

**Comment by jon-chuang** [comment]
@pavanimajety the answer is quite straightforward, simply view the uint8 tensor in the dtype of your choosing 

https://github.com/vllm-project/vllm/blob/b98cc28f91aadbb8b831611f3676da92f892211d/vllm/attention/ops/prefix_prefill.py#L723

**Comment by mgoin** [comment]
Yes I think performing a reinterpret_cast by using view is the right move, just as you did here https://github.com/pavanimajety/vllm/blob/580b07454c2571202c11b849a35725fa8d9bdaab/vllm/attention/backends/flashinfer.py#L687-L691

FYI you can use this model for testing separately calibrated k_scale and v_scale https://huggingface.co/nm-testing/Meta-Llama-3-8B-Instruct-FP8-K-V

**Comment by pavanimajety** [comment]
Yes, so I indeed do the view to the required datatype. However, when I do the reinterpret cast before the reshape kernel, I get incorrect output. Like this:
```
    if kv_cache is not None:
            # Use the same reshape and cache kernel as flash attention.
            # The FlashInfer api requires data to be in fp8_e4m3 or fp8_e5m2
            # to process the cache in fp8
            torch_dtype = FlashInferBackend.get_fp8_dtype_for_flashinfer(
                self.kv_cache_dtype)
            assert(kv_cache.dtype in (torch.uint8, torch_dtype))
            kv_cache = kv_cache.view(torch_dtype)
            ops.reshape_and_cache_flash(
                key,
                value,
                kv_cache[:, 0],
                kv_cache[:, 1],
                attn_metadata.slot_mapping.flatten(),
                self.kv_cache_dtype,
                k_scale,
                v_scale,
            )
```
My speculation is that reshape kernel can't process float8 correctly, will take a look at it later unless you know what if I there's a different error I am missing.

**Comment by mgoin** [comment]
I see. Yes, based on these lines the `reshape_and_cache_flash` function expects to use `uint8_t` as the kv_cache dtype. It might be that in this case you need to not apply the view.

https://github.com/vllm-project/vllm/blob/eeffde1ac01f575196655ad1cc8480b86967330b/csrc/cache_kernels.cu#L328-L329

https://github.com/vllm-project/vllm/blob/eeffde1ac01f575196655ad1cc8480b86967330b/csrc/quantization/fp8/nvidia/quant_utils.cuh#L544-L554

**Comment by pavanimajety** [comment]
Great, thank you for pointing me to these. I'll try to replicate or accomodate FP8 datatype for this kernel

**Pull request closed without merging**
