### PR TITLE
[torch.compile] hide slicing under custom op for inductor

### PR DESCRIPTION
**Pull request by youkaichao**
see https://github.com/pytorch/pytorch/issues/131192 

when inductor sees a view being mutated, it will copy the tensor.

hiding the slicing operation under custom op solves the issue for inductor.

### CODE REVIEW

**Comment by youkaichao** [comment]
cc @laithsakka

**Comment by youkaichao** [comment]
after this pr, the major bug of inductor ( it tries to copy kvcache) should be fixed.

however, there are still some inefficiencies w.r.t. inductor. it cannot deal with inplace custom op well.

**Comment by bnellnm** [comment]
Thanks for finding and fixing this!

**Comment by laithsakka** [comment]
This is fixed on pytorch 2.5 by setting TORCHDYNAMO_AUTO_FUNCTIONALIZED_V2=1

**Comment by youkaichao** [comment]
you can take a look at the log when you run with inductor:

`# GPU blocks: 790`

when I turn on inductor, the blocks become smaller, which means inductor takes more memory and we have less memory for the kv cache.

**Comment by laithsakka** [comment]
> takes more memory and we have less memory for the kv cache.

I see i will create an issue to revisit this, for the models i ran inductor on , it was slightly better than not using torch.compile. I will sync with you on that
https://github.com/pytorch/pytorch/issues/136269

**Pull request merged**
