### PR TITLE
[Bugfix] Fix new Llama3.1 GGUF model loading

### LINKED ISSUE #7268: [Bug]: model loading failed for some Llama3.1 GGUF model
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

**Brief description**
- This issue is used to track the llama3.1 gguf weight loading bug reported in #5191 for clarity.

**Bug description**
- Some Llama3.1 GGUF model which using the new `llama.cpp` conversion script updated in [llama.cpp PR-8676](https://github.com/ggerganov/llama.cpp/pull/8676) will contain a `rope_freqs.weight` tensor.
- The extra rope_freqs weight cause a weight loading error as reported in #5191.
- Note that the `rope_freqs.weight` is a tensor only used for `llama.cpp` inference speedup, and it's not a exact weight of source model.

**Reproduce code**
```python
from huggingface_hub import hf_hub_download

from vllm import LLM, SamplingParams


def run_gguf_inference(model_path):
    PROMPT_TEMPLATE = "<|start_header_id|>system<|end_header_id|>\n" \
        "{system_message}<|eot_id|>\n" \
        "<|start_header_id|>user<|end_header_id|>\n" \
        "{prompt}<|eot_id|>\n" \
        "<|start_header_id|>assistant<|end_header_id|>"

    # PROMPT_TEMPLATE = "<|system|>\n{system_message}</s>\n<|user|>\n{prompt}</s>\n<|assistant|>\n"  # noqa: E501
    system_message = "You are a helpful assistant."  # noqa: E501
    # Sample prompts.
    prompts = [
        "How many helicopters can a human eat in one sitting?",
        "What's the future of AI?",
    ]
    prompts = [
        PROMPT_TEMPLATE.format(system_message=system_message, prompt=prompt)
        for prompt in prompts
    ]
    # Create a sampling params object.
    sampling_params = SamplingParams(temperature=0, max_tokens=128)

    # Create an LLM.
    llm = LLM(model=model_path, max_model_len=4096)

    outputs = llm.generate(prompts, sampling_params)
    # Print the outputs.
    for output in outputs:
        prompt = output.prompt
        generated_text = output.outputs[0].text
        print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")


if __name__ == "__main__":
    repo_id = "bullerwins/Meta-Llama-3.1-8B-Instruct-GGUF"
    filename = "Meta-Llama-3.1-8B-Instruct-Q2_K.gguf"
    model = hf_hub_download(repo_id, filename=filename)
    run_gguf_inference(model)

```

**Log**
```bash
$ python examples/gguf_inference.py 
Meta-Llama-3.1-8B-Instruct-Q2_K.gguf: 100%|███████████████████████████████████████████████████████████████| 3.18G/3.18G [01:44<00:00, 30.5MB/s]
INFO 08-07 14:20:20 config.py:1484] Downcasting torch.float32 to torch.float16.
WARNING 08-07 14:20:20 config.py:286] gguf quantization is not fully optimized yet. The speed can be slower than non-quantized models.
WARNING 08-07 14:20:20 arg_utils.py:769] Chunked prefill is enabled by default for models with max_model_len > 32K. Currently, chunked prefill might not work with some features or models. If you encounter any issues, please disable chunked prefill by setting --enable-chunked-prefill=False.
INFO 08-07 14:20:20 config.py:853] Chunked prefill is enabled with max_num_batched_tokens=512.
INFO 08-07 14:20:20 llm_engine.py:176] Initializing an LLM engine (v0.5.4) with config: model='/root/.cache/huggingface/hub/models--bullerwins--Meta-Llama-3.1-8B-Instruct-GGUF/snapshots/7701ec9902c654dfb7a573622c6b0e32276a07e4/Meta-Llama-3.1-8B-Instruct-Q2_K.gguf', speculative_config=None, tokenizer='/root/.cache/huggingface/hub/models--bullerwins--Meta-Llama-3.1-8B-Instruct-GGUF/snapshots/7701ec9902c654dfb7a573622c6b0e32276a07e4/Meta-Llama-3.1-8B-Instruct-Q2_K.gguf', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=131072, download_dir=None, load_format=LoadFormat.GGUF, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=gguf, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/root/.cache/huggingface/hub/models--bullerwins--Meta-Llama-3.1-8B-Instruct-GGUF/snapshots/7701ec9902c654dfb7a573622c6b0e32276a07e4/Meta-Llama-3.1-8B-Instruct-Q2_K.gguf, use_v2_block_manager=False, enable_prefix_caching=False)
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
INFO 08-07 14:21:36 selector.py:218] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 08-07 14:21:36 selector.py:117] Using XFormers backend.
/opt/conda/envs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/opt/conda/envs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
INFO 08-07 14:21:37 model_runner.py:721] Starting to load model /root/.cache/huggingface/hub/models--bullerwins--Meta-Llama-3.1-8B-Instruct-GGUF/snapshots/7701ec9902c654dfb7a573622c6b0e32276a07e4/Meta-Llama-3.1-8B-Instruct-Q2_K.gguf...
INFO 08-07 14:21:58 selector.py:218] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 08-07 14:21:58 selector.py:117] Using XFormers backend.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/kaggle/working/vllm/examples/gguf_inference.py", line 43, in <module>
[rank0]:     run_gguf_inference(model)
[rank0]:   File "/kaggle/working/vllm/examples/gguf_inference.py", line 29, in run_gguf_inference
[rank0]:     llm = LLM(model=model_path)
[rank0]:   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 167, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 447, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 251, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 47, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 36, in _init_executor
[rank0]:     self.driver_worker.load_model()
[rank0]:   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 150, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 723, in load_model
[rank0]:     self.model = get_model(model_config=self.model_config,
[rank0]:   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 1051, in load_model
[rank0]:     model.load_weights(
[rank0]:   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 471, in load_weights
[rank0]:     for name, loaded_weight in weights:
[rank0]:   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/model_loader/weight_utils.py", line 439, in gguf_quant_weights_iterator
[rank0]:     name = gguf_to_hf_name_map[tensor.name]
[rank0]: KeyError: 'rope_freqs.weight'
```

### PR DESCRIPTION
**Pull request by Isotr0py**
FILL IN THE PR DESCRIPTION HERE

FIX #7268 (*link existing issues this PR will resolve*)
- After the investigation about [llama.cpp PR-8676](https://github.com/ggerganov/llama.cpp/pull/8676), which introduced the `rope_freqs.weight`, seems that `rope_freqs.weight` is not an exact model weight but a tensor with rope factor for `llama.cpp` inference improvement.
- As a result, I decided to ignore these tensors like `rope_freqs.weight` not required by exact model state dict.

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by mgoin** [comment]
Could you run an eval on a Llama 3.1 GGUF checkpoint to make sure that it gives a reasonable result?

For example this is what is it like to run a gsm8k eval on Llama 3 GGUF:
```
pip install lm-eval
bash .buildkite/lm-eval-harness/run-lm-eval-gsm-vllm-baseline.sh -m Meta-Llama-3-8B-Instruct.Q4_K_M.gguf -b 32 -l 1000 -f 5 -t 1

INFO 08-07 15:58:30 config.py:1451] Downcasting torch.float32 to torch.float16.
WARNING 08-07 15:58:30 config.py:254] gguf quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 08-07 15:58:33 llm_engine.py:174] Initializing an LLM engine (v0.5.3.post1) with config: model='Meta-Llama-3-8B-Instruct.Q4_K_M.gguf', speculative_config=None, tokenizer='Meta-Llama-3-8B-Instruct.Q4_K_M.gguf', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.GGUF, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=gguf, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=1234, served_model_name=Meta-Llama-3-8B-Instruct.Q4_K_M.gguf, use_v2_block_manager=False, enable_prefix_caching=False)
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
INFO 08-07 15:58:58 ray_gpu_executor.py:117] use_ray_spmd_worker: False
INFO 08-07 15:58:58 ray_gpu_executor.py:120] driver_ip: 216.81.245.69
INFO 08-07 15:59:04 model_runner.py:720] Starting to load model Meta-Llama-3-8B-Instruct.Q4_K_M.gguf...
INFO 08-07 15:59:19 model_runner.py:732] Loading model weights took 4.7085 GB
INFO 08-07 15:59:22 distributed_gpu_executor.py:56] # GPU blocks: 33275, # CPU blocks: 2048
INFO 08-07 15:59:23 model_runner.py:1024] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 08-07 15:59:23 model_runner.py:1028] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 08-07 15:59:40 model_runner.py:1225] Graph capturing finished in 16 secs.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:02<00:00, 363.41it/s]
Running generate_until requests: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [15:35<00:00,  1.07it/s]
vllm (pretrained=Meta-Llama-3-8B-Instruct.Q4_K_M.gguf,tensor_parallel_size=1,distributed_executor_backend=ray,trust_remote_code=true,max_model_len=4096), gen_kwargs: (None), limit: 1000.0, num_fewshot: 5, batch_size: 32
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value|   |Stderr|
|-----|------:|----------------|-----:|-----------|---|----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.613|±  |0.0154|
|     |       |strict-match    |     5|exact_match|↑  |0.732|±  |0.0140|
```

**Comment by Isotr0py** [comment]
OK, I will run the evaluation on an idle GPU. This may cost some time because flash-attention is unavailable on that GPU.

**Comment by RodriMora** [comment]
I just run it with an external lm eval tool as using the .buildkite/lm-eval-harness/run-lm-eval-gsm-vllm-baseline.sh was extremely slow (>100s/it) vs 4s/it running it this way:

lm eval:
`lm_eval --model local-completions --tasks gsm8k --model_args model=/home/ubuntuai/models/Meta-Llama-3.1-8B-Instruct,base_url=http://localhost:5001/v1/completions,num_concurrent=1,max_retries=3,tokenized_requests=False`

vLLM:
`CUDA_VISIBLE_DEVICES=1 vllm serve --host 0.0.0.0 --port 5001 --gpu-memory-utilization 0.9 ~/models/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf --served-model-name /home/ubuntuai/models/Meta-Llama-3.1-8B-Instruct -tp 1 --max-model-len 8192`

```
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|
|-----|------:|----------------|-----:|-----------|---|-----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.7506|±  |0.0119|
|     |       |strict-match    |     5|exact_match|↑  |0.7081|±  |0.0125|
```

**Comment by mgoin** [comment]
@RodriMora maybe this was some issue with batching.. either way, accuracy looks good so approving, thank you!

**Review by mgoin — APPROVED** [review]

**Review by njhill — APPROVED** [review]
Thanks!

**Pull request merged**
