### PR TITLE
[Speculative decoding] Support target-model logprobs

### PR DESCRIPTION
**Pull request by cadedaniel**
This PR allows vLLM to return correct log-probabilities of sampled tokens when speculative decoding is enabled. In addition, if the user specifies `logprobs` in their request, the correct top-k logprobs are returned.

The log-probabilities are expected to be equal to the log-probabilities when speculative decoding is not used.

### Testing
* See https://github.com/vllm-project/vllm/pull/4378/files#diff-2d36a32d508a5729c33b7ef42e285d9f382ca997c10b437b005b15390b0450cb

### CODE REVIEW

**Comment by rkooo567** [comment]
btw, warning; there willl be a big sampler refactoring in this PR; https://github.com/vllm-project/vllm/pull/4309

**Comment by cadedaniel** [comment]
thanks for heads up; I think I can keep it decoupled

**Review by Yard1 — COMMENTED** [review]
This looks good to me, have you ran profiling to see the perf impact?

**Comment by richardliaw** [comment]
@cadedaniel can we get this merged today?

**Comment by cadedaniel** [comment]
@richardliaw yep

@Yard1 I benchmarked and there is room to optimize. I feel we should follow up once we have E2E spec decode numbers (the implementation is reasonably efficient)

**Review by Yard1 — APPROVED** [review]

**Pull request merged**
