### PR TITLE
[Core][Speculative Decoding] Add multi-query verifier for speculative decoding without batch expansion

### PR DESCRIPTION
**Pull request by sighingnow**
FIX P1 part of #4630 (*link existing issues this PR will resolve*)

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by mpjlu** [comment]
Have you tested this PR:https://github.com/vllm-project/vllm/pull/5691, which performance is better?

**Comment by sighingnow** [comment]
> Have you tested this PR:#5691, which performance is better?

These two PRs shouldn't have too many differences in implementation, so the performance should be roughly the same.

One comment for #5691: it must be done carefully for prompt tokens processing in sampling_metadata.py, as the prompt tokens of sequences would affect the applying penalities logic in sampler.

**Comment by mpjlu** [comment]
@sighingnow Thanks for your kindly reply. Does this PR support cuda graph now.

**Comment by sighingnow** [comment]
> @sighingnow Thanks for your kindly reply. Does this PR support cuda graph now.

Cuda graph has been supported and tested.

**Comment by cadedaniel** [comment]
I will take a pass this week. also cc @LiuXiaoxuanPKU 

one major challenge is cuda graph support. it will be necessary since the pytorch dispatch and scheduling overhead is large for small batch sizes.

**Comment by sighingnow** [comment]
@cadedaniel @mpjlu @LiuXiaoxuanPKU The cuda graph of both draft model and target model (with multi-query verifier) has been aded.

**Comment by cadedaniel** [comment]
Hi @sighingnow , thanks for adding this. Feedback:

* The MultiQueryTop1Scorer is really good
* For the cuda graph support, can we instead integrate with @LiuXiaoxuanPKU 's work in https://github.com/vllm-project/vllm/pull/6052 ? More details [here](https://docs.google.com/document/d/1I6H8bGYfwM8YappcP8HuoBhpS_pMlN0UIH2e_w9hv_M/edit#heading=h.smqr48km0plh)

One way forward is to merge the MultiQueryTop1Scorer without cuda graph support, then once https://github.com/vllm-project/vllm/pull/6052 is done we can integrate the two.

What do you think?

**Comment by sighingnow** [comment]
Hi @cadedaniel,

If the PR #6052 will be merged soon, I prefer waiting it been merged then rebasing this PR, to avoid conflicts and merging effort.

**Comment by cadedaniel** [comment]
I am not sure how soon it will be merged. cc @LiuXiaoxuanPKU

**Comment by LiuXiaoxuanPKU** [comment]
Hi @sighingnow, sorry for the very late reply.

After digging into #6052, we find there is correctness issue with cudagraph + flash_attn_varlen_func. We will look into the support. However, at the same time, we can move forward with this PR. Could you clean a bit and let us know when it's good to review. Thanks for the contribution and sorry for the delayed reply!

**Comment by cadedaniel** [comment]
cc @comaniac any thoughts on how this cuda graph approach works with model runner / prepare inputs ?

**Comment by comaniac** [comment]
Took a brief look. The approach is ok in general, but I could see that some more overheads are introduced due to more tensors/logic being processed. I could review the PR once it's rebased and ready to eliminate the overheads as possible.

**Comment by cadedaniel** [comment]
One alternative is to move this to a custom model runner, just for spec decode. Do you think that's better or worse than the current approach?

**Comment by comaniac** [comment]
> One alternative is to move this to a custom model runner, just for spec decode. Do you think that's better or worse than the current approach?

In general I imagine that would have lots of code duplications, and this logic (without CUDA graph) should be very similar as prefix caching. Another way is maybe we quickly support a version without CUDA graph first and see how good/bad is?

**Comment by cadedaniel** [comment]
SGTM. @sighingnow we can merge this PR as is if we remove the cuda graph stuff, or we can add cuda graph stuff (using one of the two approaches Cody mentions above)

**Comment by sighingnow** [comment]
I will rebase and fixes the cudagraph issue, add testsing cases for this PR during this weekend, thanks for all for your careful review.

**Pull request closed without merging**
