### PR TITLE
Update parallel_state.py

### PR DESCRIPTION
**Pull request by 0x-yuan**
commenting out all code which check parallel group initialized

### CODE REVIEW

**Comment by zhuohan123** [comment]
Thank you for your contribution! Can you elaborate more on why the changes are needed?

**Comment by zhuohan123** [comment]
Close this PR since there is no update and we will also refactor this part later.

**Comment by Alymostafa** [comment]
@zhuohan123 
The issue arises when attempting to initialize two Language Model Instances (LLMs) within a single service, triggering this error.

**Comment by Tai-Pham-2002** [comment]
from vllm import LLM

llm = LLM(model='microsoft/phi-2',trust_remote_code=True) 
AssertionError: tensor model parallel group is already initialized

**Comment by GianniGi** [comment]
> from vllm import LLM
> 
> llm = LLM(model='microsoft/phi-2',trust_remote_code=True) AssertionError: tensor model parallel group is already initialized i'm run code in gg colab

did you solve this?

**Pull request closed without merging**
