### PR TITLE
[CI/Build] fix: Add the +empty tag to the version only when the VLLM_TARGET_DEVICE envvar was explicitly set to "empty"

### PR DESCRIPTION
**Pull request by tomeras91**
Following https://github.com/vllm-project/vllm/pull/4773

Currently, pip installing vllm form pypi on mac still doesn't work OOTB. It fails with the following error:
```
Requested vllm from https://files.pythonhosted.org/packages/ec/f0/32ea866485d83d1fcde810059a0643ed4726628c17fdac8981606f58219e/vllm-0.5.5.tar.gz has inconsistent version: expected '0.5.5', but metadata has '0.5.5+empty'
```
and then tries to install an earlier version (which obviously fails since it was before https://github.com/vllm-project/vllm/pull/4773).
The issue can be solved by installing with `pip install vllm --use-deprecated=legacy-resolver`, but IMO it's better to make it work OOTB with default `pip install vllm`.

This PR fixes it by adding "+empty" to the version only if VLLM_TARGET_DEVICE envvar was explicitly set to "empty"

### CODE REVIEW

**Comment by youkaichao** [comment]
> Requested vllm from https://files.pythonhosted.org/packages/ec/f0/32ea866485d83d1fcde810059a0643ed4726628c17fdac8981606f58219e/vllm-0.5.5.tar.gz has inconsistent version: expected '0.5.5', but metadata has '0.5.5+empty'

I don't get it. do we have `'0.5.5+empty'` on pypi?

**Comment by tomeras91** [comment]
> > Requested vllm from https://files.pythonhosted.org/packages/ec/f0/32ea866485d83d1fcde810059a0643ed4726628c17fdac8981606f58219e/vllm-0.5.5.tar.gz has inconsistent version: expected '0.5.5', but metadata has '0.5.5+empty'
> 
> I don't get it. do we have `'0.5.5+empty'` on pypi?

Nope. Pypi has a manilunix wheel and a tar.gz archive: https://pypi.org/project/vllm/#files.
When pip installing on a mac, the tar.gz archive is downloaded and built locally, so the code in setup.py is executed. The problem is that lines [64-69 in setup.py](https://github.com/vllm-project/vllm/blob/bd852f2a8b9e9129de69fa7349906a9115538d5a/setup.py#L64) change `VLLM_TARGET_DEVICE` in the code to `"empty"` when building on mac. This causes `_no_device()` to return `True` so in `get_vllm_version()`, `+empty` is added. Thus, the version during build (v0.5.5+empty) doesn't match the version in the archive (which is just v0.5.5), leading to the pip error stated above.

This PR aims to fix this inconsistency by adding `+empty` to the version only the `VLLM_TARGET_DEVICE` envvar explicitly set to `empty`

**Comment by tomeras91** [comment]
Another option is to just drop the `+empty` from the version entirely

**Review by youkaichao — APPROVED** [review]
makes sense to me. thanks for the detailed investigation!

**Comment by 18595071403** [comment]
在windows中安转vllm==0.5.5时候显示版本不匹配expected '0.5.5', but metadata has '0.5.5+empty'应该怎么解决呢

**Pull request merged**
