### PR TITLE
Enable random seed option to make latency benchmarking more configurable

### PR DESCRIPTION
**Pull request by qingquansong**
Enable random seed option to make latency benchmarking more configurable.

The reason of this pr come from some findings and questions:

(1) Fact 1: It seems that fixing the seed also fix the randomness even when temperature is 1.0 (see the old analysis section below)
(2) Q1: Should we use temperature = 0.0 even without using beam search to fix them and make things more consistent? (if yes, can modify this pr to add the changes)
(3) Q2: Maybe we still need to enable this seed fix to make things more configurable as this pr shows?

==== old analysis ==== 
Current benchmarking script set temperature as 1.0 when not using beam search and does not fix random seed and produces inconsistent output length results if set output_len to be larger than 1 even with other hparams fixed (top_p and temperature, etc) causing latency benchmarking inaccurate. This pr added the seed to fix it as 42 by default.

Testing done with tinyllama model with following scripts and print out the output after the calling of `llm.generate` :
```
python benchmark_latency.py \
--model tinyllama_test/ \
--input-len 20 \
--output-len 5 \
--batch-size 1 \
--num-iters 3
```

Before fixing the seed with temperature 1.0:

```
[RequestOutput(request_id=7, prompt=None, prompt_token_ids=[2732, 9845, 3264, 4859, 9225, 7891, 4373, 5874, 6744, 3468, 705, 2599, 2222, 7768, 2897, 9893, 537, 6216, 6921, 6036], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='e employment encryption law', token_ids=[29872, 5703, 358, 20956, 4307], cumulative_logprob=-33.64984667301178, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1718261321.015641, last_token_time=1718261321.015641, first_scheduled_time=1718261321.0158198, first_token_time=1718261321.0314093, time_in_queue=0.00017881393432617188, finished_time=1718261321.0474448), lora_request=None)]
[RequestOutput(request_id=8, prompt=None, prompt_token_ids=[2732, 9845, 3264, 4859, 9225, 7891, 4373, 5874, 6744, 3468, 705, 2599, 2222, 7768, 2897, 9893, 537, 6216, 6921, 6036], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text=' automoblestart', token_ids=[3345, 711, 29880, 342, 442], cumulative_logprob=-19.766031503677368, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1718261321.047535, last_token_time=1718261321.047535, first_scheduled_time=1718261321.0477033, first_token_time=1718261321.0625982, time_in_queue=0.00016832351684570312, finished_time=1718261321.0775552), lora_request=None)]
[RequestOutput(request_id=9, prompt=None, prompt_token_ids=[2732, 9845, 3264, 4859, 9225, 7891, 4373, 5874, 6744, 3468, 705, 2599, 2222, 7768, 2897, 9893, 537, 6216, 6921, 6036], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text="v5 ' - ", token_ids=[29894, 29945, 525, 448, 29871], cumulative_logprob=-32.859960079193115, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1718261321.0776284, last_token_time=1718261321.0776284, first_scheduled_time=1718261321.077778, first_token_time=1718261321.0920112, time_in_queue=0.00014972686767578125, finished_time=1718261321.1073508), lora_request=None)]
```

After fixing the seed=42 with still temperature 1.0:

```
[RequestOutput(request_id=4, prompt=None, prompt_token_ids=[2732, 9845, 3264, 4859, 9225, 7891, 4373, 5874, 6744, 3468, 705, 2599, 2222, 7768, 2897, 9893, 537, 6216, 6921, 6036], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='. Nhts n', token_ids=[29889, 405, 400, 29879, 302], cumulative_logprob=-23.869795322418213, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1718261464.786836, last_token_time=1718261464.786836, first_scheduled_time=1718261464.7870114, first_token_time=1718261464.7999206, time_in_queue=0.00017547607421875, finished_time=1718261464.8143234), lora_request=None)]
[RequestOutput(request_id=5, prompt=None, prompt_token_ids=[2732, 9845, 3264, 4859, 9225, 7891, 4373, 5874, 6744, 3468, 705, 2599, 2222, 7768, 2897, 9893, 537, 6216, 6921, 6036], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='. Nhts n', token_ids=[29889, 405, 400, 29879, 302], cumulative_logprob=-23.869795322418213, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1718261464.8144147, last_token_time=1718261464.8144147, first_scheduled_time=1718261464.814583, first_token_time=1718261464.8276753, time_in_queue=0.00016832351684570312, finished_time=1718261464.8424041), lora_request=None)]
[RequestOutput(request_id=6, prompt=None, prompt_token_ids=[2732, 9845, 3264, 4859, 9225, 7891, 4373, 5874, 6744, 3468, 705, 2599, 2222, 7768, 2897, 9893, 537, 6216, 6921, 6036], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='. Nhts n', token_ids=[29889, 405, 400, 29879, 302], cumulative_logprob=-23.869795322418213, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1718261464.8425188, last_token_time=1718261464.8425188, first_scheduled_time=1718261464.8426938, first_token_time=1718261464.8557236, time_in_queue=0.00017499923706054688, finished_time=1718261464.8700457), lora_request=None)]
[RequestOutput(request_id=7, prompt=None, prompt_token_ids=[2732, 9845, 3264, 4859, 9225, 7891, 4373, 5874, 6744, 3468, 705, 2599, 2222, 7768, 2897, 9893, 537, 6216, 6921, 6036], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='. Nhts n', token_ids=[29889, 405, 400, 29879, 302], cumulative_logprob=-23.869795322418213, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1718261464.8701239, last_token_time=1718261464.8701239, first_scheduled_time=1718261464.870278, first_token_time=1718261464.8830173, time_in_queue=0.00015401840209960938, finished_time=1718261464.8975763), lora_request=None)]
```
Without fixing random seed, if we change temperature to 0.0, it also produced same results (though different responses as expected).

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by simon-mo** [comment]
Hmm this is weird because we have the following set which should produce exactly the number of tokens requested
```
        ignore_eos=True,
        max_tokens=args.output_len,
```

**Comment by qingquansong** [comment]
> Hmm this is weird because we have the following set which should produce exactly the number of tokens requested
> 
> ```
>         ignore_eos=True,
>         max_tokens=args.output_len,
> ```

Thanks for the response! yeah, that's my understanding as well. I'm using 0.4.1 version to test, do you think 0.4.3 or 0.5 have any fix related? Thank you!

**Comment by simon-mo** [comment]
`ignore_eos` might be broken for llama3 in certain versions I remembered... but it should be fixed 0.4.3 in the latest

**Comment by qingquansong** [comment]
> `ignore_eos` might be broken for llama3 in certain versions I remembered... but it should be fixed 0.4.3 in the latest

Gotcha. Let me try 0.4.3. Something weird I found is that dummy random ids are good sometimes, but if I'm using some real prompts, it becomes like this and stop early usually.

**Pull request closed without merging**
