### PR TITLE
[Core] Rename `PromptInputs` to `PromptType`, and `inputs` to `prompt`

### PR DESCRIPTION
**Pull request by DarkLight1337**
These changes are split out from #6869. The reason for renaming this is to avoid confusing `PromptInputs` with `LLMInputs` (which will later be renamed into `TokenInputs` and `EmbedInputs`, corresponding to `TokenPrompt` and `EmbedPrompt` respectively).

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by njhill** [comment]
@DarkLight1337 @simon-mo this is a breaking change to anyone integrating with `AsyncLLMEngine`/`LLMEngine` directly (and the `EngineClient` protocol).

It has affected some of our internal integrations and I expect may impact others if we don't address it for the upcoming release.

**Comment by simon-mo** [comment]
Let's do a revert given a release is imminent. @DarkLight1337 please try to make this backward compatible for now.

**Comment by DarkLight1337** [comment]
Sorry for breaking your code! @njhill which parts specifically do I need to make backward compatible?

**Comment by njhill** [comment]
@DarkLight1337 no problem, sorry I realize we don't really have any formal guarantees for backwards compatibility but I think these "external" interfaces may commonly be used for integrations and so we should maybe be a bit more conservative w.r.t. deprecating at least between minor vers releases.

Adding new optional args is ok but removing args we should probably do in a staged manner. I guess we should keep `PromptInputs` too during this staging at least as an alias, so that code referencing it wouldn't break.

But yes we should probably formalize exactly which external APIs we'll promise not to change without deprecation for at least one or two releases.

**Pull request merged**
