### PR TITLE
fix qwen-14b model

### PR DESCRIPTION
**Pull request by Sanster**
Support both qwen-7b and qwen-14b.

### CODE REVIEW

**Comment by ZPerling** [comment]
I've tested using this code and qwen-14b still  can not load

**Comment by Sanster** [comment]
> I've tested using this code and qwen-14b still can not load

What error did you encounter?

**Comment by fengtong-xiao** [comment]
Still encountered this error: 

RuntimeError: shape '[3, 32, 128]' is invalid for input of size 15360

**Comment by Sanster** [comment]
> Still encountered this error:
> 
> RuntimeError: shape '[3, 32, 128]' is invalid for input of size 15360

I tested it again and it works. Please make sure the changes to your local vllm code have taken effect.

**Comment by fengtong-xiao** [comment]
> > Still encountered this error:
> > RuntimeError: shape '[3, 32, 128]' is invalid for input of size 15360
> 
> I tested it again and it works. Please make sure the changes to your local vllm code have taken effect.

Thanks! This works for me, turns out I need to restart the cluster instead of detach-and-reattach.

**Comment by xiaoranchenwai** [comment]
Still encountered new error:
TypeError: hf_model_weights_iterator() takes from 1 to 3 positional arguments but 4 were given

**Review by zhuohan123 — APPROVED** [review]
LGTM! Tested with `Qwen/Qwen-14B-Chat` and it works well. Thanks for your contribution!

**Pull request merged**
