### PR TITLE
[Misc] Load FP8 kv-cache scaling factors from checkpoints

### PR DESCRIPTION
**Pull request by comaniac**
The 2nd PR for #4532.

This PR supports loading FP8 kv-cache scaling factors from a FP8 checkpoint (with `.kv_scale` parameter).
Specifically,
1. We now support `--kv-cache-dtype {auto, fp8, fp8_e4m3, fp8_e5m2}`. `auto=fp16 or bf16` and `fp8=fp8_e4m3`.
2. If the checkpoint is in FP16, then kv-cache scaling factors can only be loaded via `--quantization-param-path`; otherwise kv-scale is always 1 regardless `fp8_e4m3` or `fp8_e5m2`.
3. If the checkpoint is in FP8 (`e4m3`) AND `--kv-cache-dtype {fp8, fp8_e4m3}`, kv_scale will be loaded from the checkpoint (if the field presents).

Here is a simple benchmark on a single NVIDIA L4 GPU:
- FP16 model: meta-llama/Meta-Llama-3-8B-Instruct 
- FP8 model: nm-testing/Meta-Llama-3-8B-Instruct-FP8 (no kv-scale so use 1.0 for now).
- QPS: 1
- Total requests: 30
- Average prompt length: 512
- Average decoding length: 256 (`ignore_eos` is not enabled so the actual length may be differ).
- Temperature: 0

Model Dtype | kv-cache Dtype | GPU blocks | TTFT (ms) | ITL (ms) | e2e (s)
--|--|--|--|--|--
FP16 | FP16 | 1470 | 219.0 | 90.5 | 15.7
FP16 | FP8_e5m2 | 2940 | 219.3 | 88.2 | 14.9
FP8_e4m3 | FP16 | 4784 | 148.2 | 51.3 | 9.3
FP8_e4m3 | FP8_e4m3 | 9568 | 147.4 | 50.1 | 8.1

@robertgshaw2-neuralmagic @tlrmchlsmth can you help update nm-testing/Meta-Llama-3-8B-Instruct-FP8 to include kv-cache scaling factors so that we could test it? Thanks!

TODO
- [x] Unit test.

Also cc @pcmoritz @Yard1 

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]
Very nice! As a next step, we should create an FP8 checkpoint with appropriate scales and make sure the accuracy looks good :)

**Comment by tlrmchlsmth** [comment]
>@robertgshaw2-neuralmagic @tlrmchlsmth can you help update nm-testing/Meta-Llama-3-8B-Instruct-FP8 to include kv-cache scaling factors so that we could test it? Thanks!

I'm pinging some NeuralMagic folks to see if we can get those models updated

**Comment by mgoin** [comment]
Hey y'all, I made this model as a test https://huggingface.co/nm-testing/Meta-Llama-3-8B-Instruct-FP8-KV. I haven't tested the accuracy yet but it should be sufficient for a smoke test @comaniac @tlrmchlsmth

**Comment by comaniac** [comment]
> Hey y'all, I made this model as a test https://huggingface.co/nm-testing/Meta-Llama-3-8B-Instruct-FP8-KV. I haven't tested the accuracy yet but it should be sufficient for a smoke test @comaniac @tlrmchlsmth

Thanks! I'll use this model for testing in this PR and post back soon.

**Comment by comaniac** [comment]
Output comparison (using the example prompts in the tests):

* meta-llama/Meta-Llama-3-8B-Instruct
```
'LLM (Large Language Model) is a type of artificial intelligence (AI) model that is trained',
'Here are the major milestones in the development of artificial intelligence (AI) from 1950 to ',
'Artificial intelligence (AI) and human intelligence (HI) differ significantly in how they process information.',
'A neural network is a complex system modeled after the human brain, composed of interconnected nodes or "ne',
'In the vast, sterile laboratory, Robot 3456-Alpha, or "Alpha" for short',
'The COVID-19 pandemic has had a profound impact on global economic structures and future business models. The',
'The Mona Lisa, painted by Leonardo da Vinci in the early 16th century, is one of',
'Here are the translations:\n\n**Japanese:** (Haya aki wa mushi o tsukamu'
```

* nm-testing/Meta-Llama-3-8B-Instruct-FP8 with FP16 kv-cache
```
'LLaMA is a high-throughput and memory-efficient inference and serving engine for Large Language Models (',
'Here are the major milestones in the development of artificial intelligence (AI) from 1950 to ',
'Artificial intelligence (AI) and human intelligence (HI) differ significantly in how they process information.',
'A neural network is a complex system modeled after the human brain, consisting of interconnected nodes or "ne',
'Zeta-5, a highly advanced robot designed for menial labor, whirred to a',
'The COVID-19 pandemic has had a profound impact on global economic structures and future business models. The',
'The Mona Lisa, painted by Leonardo da Vinci in the early 16th century, is one of',
'Here are the translations:\n\n**Japanese:** (Haya aki no tori, guri o',
```

* nm-testing/Meta-Llama-3-8B-Instruct-FP8-KV with FP8 kv-cache and kv-scale=1.0
```
'LLaMA is a high-throughput and memory-efficient inference and serving engine for Large Language Models (',
'Here are the major milestones in the development of artificial intelligence (AI) from 1950 to ',
'Artificial intelligence (AI) and human intelligence (HI) differ significantly in terms of processing information.',
'A neural network is a complex system modeled after the human brain, consisting of interconnected nodes or "ne',
'Zeta-5, a highly advanced robot designed for menial labor, whirred to life',
'The COVID-19 pandemic has had a profound impact on global economic structures and future business models. The',
'The Mona Lisa, painted by Leonardo da Vinci in the early 16th century, is one of',
'Here are the translations:\n\n**Japanese:** (Haya aki no tori, guri o'
```

* nm-testing/Meta-Llama-3-8B-Instruct-FP8-KV with FP8 kv-cache and in-checkpoint kv-scale
```
'LLM (Large Language Model) is a type of artificial intelligence (AI) model that is trained',
'Here are the major milestones in the development of artificial intelligence (AI) from 1950 to ',
'Artificial intelligence (AI) and human intelligence (HI) differ significantly in how they process information.',
'A neural network is a complex system made up of several basic components that work together to enable it to',
'Zeta-5, a highly advanced robot designed for menial labor, had never experienced anything like',
'The COVID-19 pandemic has had a profound impact on global economic structures and future business models. Here',
'The Mona Lisa, painted by Leonardo da Vinci in the early 16th century, is one of',
'Here are the translations:\n\n**Japanese:** (Haya kotori wa mushi o tsuk'
```

Although we cannot judge the model quality only by these simple prompts, it should verify that the kv-scale from the checkpoint is loaded correctly.

**Comment by comaniac** [comment]
Side note: Since #4907, the flash-attn is used for both prefill and decoding. However, flash-attn doesn't support FP8 input, so now when FP8 kv-cache is enabled, vLLM will enforce to use xFormers backend (which uses paged attention kernel in decoding).

**Comment by comaniac** [comment]
All done. Final note: Per offline discussion with @mgoin, we should accept the checkpoint with HuggingFace model compatible format. In other words, the kv_scale should have the weight name `model.layers.0.self_attn.kv_scale`. On the other hand, the implementation in this PR puts `kv_scale` in `model.layers.0.self_attn.attn.kv_scale` to hide the implementation details from model implementer. We now let the model specific weight loader to deal with this re-mapping, and thus now only Llama and Mixtral could correctly load the kv-scale.

**Review by mgoin — APPROVED** [review]
Thanks for adding a solid test, I think the tradeoff with model support for checkpoint loading is fair. This falls in line with how we deal with other module replacements.

**Review by tlrmchlsmth — APPROVED** [review]

**Comment by pavanimajety** [comment]
@comaniac Could you please clarify what GPU blocks is recording in the above benchmark? It's not intuitive that the number of GPU blocks are increasing as the model weights size reduced.

**Comment by comaniac** [comment]
The GPU blocks meant the available GPU memory blocks can be used for kv-cache.

**Pull request merged**
