### PR TITLE
Merge Gemma into Llama

### PR DESCRIPTION
**Pull request by WoosukKwon**
This PR merges the Gemma model into our Llama model architecture. The Gemma model architecture is different from Llama's in the following ways:

* Gemma ties the token embeddings and the LM head (like BLOOM) while Llama has separate parameters for the two.
* Gemma normalizes the hidden states after the embedding layer.
* Gemma uses GeGLU while Llama uses SwiGLU.
* Gemma's head size (256) is not equal to `hidden_size // num_heads` (192). 
* Gemma's RMSNorm multiplies `1 + weights` instead of `weights`.

NOTE: This PR may not enable the LoRA support for Gemma, due to Gemma's tied embeddings.

Considering the above differences, I'm actually not 100% sure whether it's the right decision to merge the two models. Please push me back if you think this is not a good idea. @esmeetu @Yard1

### CODE REVIEW

**Comment by Yard1** [comment]
I think adding so many conditionals is a code smell. What we could do instead is reuse common elements, eg. MLP and attention layers. But they should be separate classes IMO.

**Comment by WoosukKwon** [comment]
@Yard1 Good point! Though I believe all the differences except the tied embeddings are pretty small. Do you think the new conditionals in this PR are too complex?

**Comment by Yard1** [comment]
I think it's a bad pattern that will make the code less maintainable, especially if we have to add more models like that. The changes to MLP and attention layers are fine though!

**Comment by esmeetu** [comment]
@WoosukKwon The decision to merge gemma into llama was a tough one, I would suggest leaving it as is, it's a bit complex, more so than `internlm2` and `qwen` that I had prepared to merge earlier, I just want to wait for `llama3` to come out maybe there will be something new🤩. 
Instead, what we could possibly look at right now is if we can decouple lora support from the model file, keep new future features separate from the model file itself, these features are loaded at load stage. @Yard1

**Comment by WoosukKwon** [comment]
Closing this PR following @Yard1 and @esmeetu's advice.

**Pull request closed without merging**
