### PR TITLE
Support Deployment on Container (or docker sometimes)

### PR DESCRIPTION
**Pull request by michaelact**
Simplifying things, vLLM can be deployed on a container instead of directly on a host, which saves time for some people.

### CODE REVIEW

**Comment by josephrocca** [comment]
It'd be awesome if there were an official hosted image on docker.io or ghcr.io - so the readme could have a one-liner 'quickstart' like TGI does - for example:
```
docker run --gpus all --shm-size 1g -p 8000:8000 -v $PWD/data:/data ghcr.io/vllm-project/vllm:0.2.0 --model-id mistralai/Mistral-7B-Instruct-v0.1
```
```
curl http://localhost:8000/generate \
  -d '{
    "prompt": "San Francisco is a",
    "use_beam_search": true,
    "n": 4,
    "temperature": 0
  }'
```

**Comment by kiamesdavies** [comment]
@michaelact great job, I think it will be also cool if you can make it into GitHub actions so that its automatically pushed into Github's container registry

**Comment by michaelact** [comment]
Sure @kiamesdavies, I am willing to help if the maintainers are also interested in this pull request.

**Comment by simon-mo** [comment]
Thank you for the PR. We recently merged a PR that builds vLLM from source and it is now part of v0.2.2 release. You can use the OpenAI compatible server https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html

**Pull request closed without merging**
