### PR TITLE
[models] add BlueLM

### LINKED ISSUE #1651: can you support BlueLMForCausalLM? model BlueLM-7B-Chat-32K
when i try to run
python -m vllm.entrypoints.openai.api_server --model BlueLM-7B-Chat-32K --port 17861 --trust-remote-code
error occurs:
Model architectures ['BlueLMForCausalLM'] are not supported for now

vllm version: 0.2.1

it's web site address:
https://github.com/vivo-ai-lab/BlueLM

### PR DESCRIPTION
**Pull request by peterjc123**
Fixes https://github.com/vllm-project/vllm/issues/1651.

### CODE REVIEW

**Comment by simon-mo** [comment]
Thank you for this PR! Can you comment on the different between this and BlueLM's implementation here? https://github.com/vivo-ai-lab/BlueLM/blob/main/example/vllm/vllm/model_executor/models/bluelm.py

Additionally can you show some example code and output to confirm it works?

**Comment by peterjc123** [comment]
> Thank you for this PR! Can you comment on the different between this and BlueLM's implementation here? https://github.com/vivo-ai-lab/BlueLM/blob/main/example/vllm/vllm/model_executor/models/bluelm.py

This is adapted from the LLAMA implementation, it's just the same, except the layernorm after the word embeddings.
 
> Additionally can you show some example code and output to confirm it works?
Could you please give me an example? I've tested it locally and it works.

**Comment by simon-mo** [comment]
Just paste in the code you use locally for test and output here will greatly help!

**Comment by peterjc123** [comment]
> Just paste in the code you use locally for test and output here will greatly help!

Code:
```py
from vllm import LLM, SamplingParams

llm = LLM(model="/path/to/bluelm_base", trust_remote_code=True)
sampling_params = SamplingParams(temperature=0.3, top_p=0.85, max_tokens=1024, repetition_penalty=1.2)

prompts = ["你好", "Hello", "Shanghai is a city that"]

raw_outputs = llm.generate(prompts, sampling_params)

for output in raw_outputs:
    print(output.prompt, '->')
    print(output.outputs[0].text)

```

Result:
```
INFO 11-14 07:42:02 llm_engine.py:72] Initializing an LLM engine with config: model='/path/to/bluelm_base', tokenizer='/path/to/bluelm_base', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_r
emote_code=True, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
WARNING 11-14 07:42:02 tokenizer.py:66] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 11-14 07:42:15 llm_engine.py:207] # GPU blocks: 7218, # CPU blocks: 512
Processed prompts: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:13<00:00,  4.34s/it]
你好 ->
，请问一下，我有个朋友在2014年3月8号晚上9点56分生了个男孩。姓陈取什么名字好？
陈嘉豪（胸怀大志、帅气）
Hello ->
, I am a 20 year old female. My boyfriend and i have been together for about two years now. We are both very sexually active people (he is bi-sexual). He has had sex with other women before me but he never cheated on me or anything like that.
I recently found out that my boyfriend was cheating on me by having oral sex with another girl while we were in the same room as eachother. The first time it happened was when we went to his friend's house over winter break from college. His friends al
l knew what they were doing so there wasn't any awkwardness between us at their party. But then after everyone left we got into bed and started making out again until she came up behind him and gave him head without telling anyone else around her. When
 this happens sometimes you can hear them moaning loudly through closed doors which made me feel really uncomfortable because I didn't know if someone could be listening outside our door! Afterward neither of us said anything about how weirded out we f
elt since no one would ever do something like that unless they wanted attention from others present during such an intimate moment...or maybe just plain curiosity?
Anyways long story short: I confronted him about why didnt tell me earlier &amp; told him not only does it make me feel bad knowing that he enjoyed being touched by another woman but also makes me wonder who else might want access too..especially consi
dering how close these guys live nextdoor&hellip;&#8230;"What should I do?"
Shanghai is a city that ->
 is known for its food. It has a lot of different types of restaurants, from fast-food chains to high-end dining establishments.
Shanghai’s cuisine can be divided into four main categories: Cantonese, Sichuanese, Hunanese and Shandongese. Each region has their own unique dishes that are popular in Shanghai. For example, the most famous dish in Guangdong province (where many peop
le come from) is dim sum; while Hunanese specialties include spicy hot pot soup with tofu balls or beef slices cooked over charcoal fireplaces at night markets!
The best way to experience all these cuisines would probably involve visiting multiple regions throughout China during your trip here – but if you only have time for one place then make sure it’s either Beijing where they serve up some amazing Peking d
uck sandwiches or Hangzhou which offers delicious steamed buns filled with pork belly inside them along side other traditional Chinese snacks like fried rice cakes made outta wheat flour dough mixed together before being deep fried until golden brown o
n both sides… And don’t forget about dessert too because there’s nothing better than having ice cream after dinner every now & again right?
If you want to try something new when traveling around Asia this year why not check out what kind of street foods they offer down south first hand instead?! You won’t regret doing so once done tasting everything available within reach without breaking
bank account balance ever again thanks goodness!!
1 What should I eat in Shanghai?
2 How much does it cost to live in Shanghai?
3 Is Shanghai expensive compared to Hong Kong?
4 Why do people move to Shanghai?
5 Are foreigners allowed to work in Shanghai?
6 Do expats get free healthcare in Shanghai?
7 Can I buy property in Shanghai?
What should I eat in Shanghai?
There are plenty of things to see and do in Shanghai, including shopping malls, museums, parks, temples, and more. But no matter how long you stay in town, chances are good that you will find yourself craving some local delicacies as well. Here are fiv
e must-try items when visiting this vibrant city by waterway.
Pork Belly Baozi: This type of baozi features tender chunks of fatty meat wrapped inside soft dough pockets topped off with an egg yolk oozing through each bite. They are usually served piping hot straight from steamers onto plates lined with chopstick
s ready for consumption immediately upon arrival back home. If possible, ask someone who knows how to cook authentic ones since they tend to taste even better when prepared properly rather than just thrown into boiling pots full of ingredients overnigh
t prior to serving customers later next day morning hours onwards depending upon availability levels among vendors selling such products locally near tourist attractions areas located close proximity distance away from downtown core area centers housin
g major commercial buildings containing offices belonging ownerships held under management control owned companies operating businesses related activities involving production processes involved manufacturing operations carried out using equipment mach
inery tools designed specifically created manufactured produced developed invented discovered originated derived evolved changed modified altered transformed converted adapted adopted introduced incorporated integrated combined coordinated matched sync
hronized aligned arranged structured organized scheduled planned executed accomplished completed finished achieved attained realized reached obtained acquired possessed received gained earned accumulated collected gathered assembled compiled constructe
d composed constructed built established maintained sustained supported guaranteed ensured assured protected preserved safeguarded guarded secured safe kept secure saved sheltered shielded defended defended defended against attacked assaulted attacked
invaded occupied conquered captured seized taken stolen robbed plundered pillaged ravished ruined destroyed demolished devastated wrecked damaged annihilated exterminated wiped clean cleaned washed scrubbed scoured polished brushed buffed rubbed scrape
d scratched gouged chipped cracked broken shattered smashed crushed pulverised ground powdered pounded beaten battered bashed bludgeoned whacked hacked slashed sliced diced chopped minced mincered grated shredded crumbled mashed kneaded rolled flattene
d pressed squeezed squashed stamped stamped printed embossed engraved carved incised inscribed imprinted impressed branded marked labeled tagged labelled designated assigned allocated appointed delegated dedicated devoted entrusted trusted relied place
d set positioned situated settled seated satiated satisfied sated contented comfortable cozy snuggle cuddled nestled nestled tucked cozied cocooned ensconced encased enclosed enshrouded enveloped encompassed embraced surrounded encircled circumscribed
confined confined contained constrained restricted restrained limited bounded bound confined constricted cramped crammed crowded packed jammed jostling shoved shoving pushed pummeled pounding hammered hammering hitched hooked hauled dragged pulled tugg
ed yanked yoked yanked jerked jackhammered drilled drubbed beatened batted battened bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded
bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bedded bed
```
Currently, I only have the weights for the base model. I have finetuned it and it works on the finetuned weights. Downloading of the chat model is in progress and will take some time. I will test the chat model afterwards.

**Comment by peterjc123** [comment]
@simon-mo The code and the output for the chat model.
Code:
```py
from vllm import LLM, SamplingParams

def format_prompt(prompt):
    return f'[|Human|]:{prompt}[|AI|]:'

llm = LLM(model="/path/to/bluelm_chat", trust_remote_code=True)
sampling_params = SamplingParams(temperature=0.3, top_p=0.85, max_tokens=1024, repetition_penalty=1.2)

prompts = ["你好", "Hello", "Shanghai is a city that"]
prompts = [format_prompt(p) for p in prompts]

raw_outputs = llm.generate(prompts, sampling_params)

for output in raw_outputs:
    print(output.prompt, '->')
    print(output.outputs[0].text)

```

Output:
```
INFO 11-14 07:58:09 llm_engine.py:72] Initializing an LLM engine with config: model='/path/to/bluelm_chat', tokenizer='/path/to/bluelm_chat', tokenizer_mode=auto, revision=None, tokenizer_revision=Non
e, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WARNING 11-14 07:58:09 tokenizer.py:66] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 11-14 07:59:08 llm_engine.py:207] # GPU blocks: 7218, # CPU blocks: 512
Processed prompts: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  5.09it/s]
[|Human|]:你好[|AI|]: ->
 你好！很高兴见到你，有什么我可以帮助你的吗？
[|Human|]:Hello[|AI|]: ->
 Hello! Nice to meet you. Is there anything I can help you with?
[|Human|]:Shanghai is a city that[|AI|]: ->
 - Has a lot of history
- Is very big
- Has many skyscrapers
- Is a global city
- Has nice parks and trees
- Is famous for its food
- Has a lot of tourist attractions
```

**Comment by dengzheng-cloud** [comment]
will int4 support？i use bluelm/vllm to implement blue, while it seems there isn't any option for bluelm int4 model

**Comment by peterjc123** [comment]
> will int4 support？i use bluelm/vllm to implement blue, while it seems there isn't any option for bluelm int4 model

I haven't tested it yet. But I guess it's fairly simple to adapt to the quantized model, but just not in this PR.

**Comment by peterjc123** [comment]
@simon-mo Is anything that I can do here to help merging the changes to the main branch?

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
Hmm I'm getting the following error


```
(base) xmo@simon-dev-l4x2:~/vllm$ python -m vllm.entrypoints.openai.api_server --model vivo-ai/BlueLM-7B-Chat-32K --trust-remote-code
INFO 11-20 19:01:40 api_server.py:638] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, model='vivo-ai/BlueLM-7B-Chat-32K', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
Downloading (…)figuration_bluelm.py: 100%|██████████████████████████████████████████| 8.26k/8.26k [00:00<00:00, 32.1MB/s]
A new version of the following files was downloaded from https://huggingface.co/vivo-ai/BlueLM-7B-Chat-32K:
- configuration_bluelm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
INFO 11-20 19:01:41 llm_engine.py:72] Initializing an LLM engine with config: model='vivo-ai/BlueLM-7B-Chat-32K', tokenizer='vivo-ai/BlueLM-7B-Chat-32K', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
Downloading tokenizer_config.json: 100%|████████████████████████████████████████████████| 960/960 [00:00<00:00, 5.62MB/s]
Downloading tokenization_bluelm.py: 100%|███████████████████████████████████████████| 9.63k/9.63k [00:00<00:00, 38.9MB/s]
A new version of the following files was downloaded from https://huggingface.co/vivo-ai/BlueLM-7B-Chat-32K:
- tokenization_bluelm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Downloading tokenizer.model: 100%|██████████████████████████████████████████████████| 1.61M/1.61M [00:00<00:00, 20.8MB/s]
Downloading added_tokens.json: 100%|███████████████████████████████████████████████████| 86.0/86.0 [00:00<00:00, 624kB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████████████████████████████████████| 644/644 [00:00<00:00, 4.96MB/s]
WARNING 11-20 19:01:42 tokenizer.py:66] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xmo/vllm/vllm/entrypoints/openai/api_server.py", line 646, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/xmo/vllm/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/home/xmo/vllm/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/xmo/vllm/vllm/engine/async_llm_engine.py", line 305, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/xmo/vllm/vllm/engine/llm_engine.py", line 110, in __init__
    self._init_workers(distributed_init_method)
  File "/home/xmo/vllm/vllm/engine/llm_engine.py", line 142, in _init_workers
    self._run_workers(
  File "/home/xmo/vllm/vllm/engine/llm_engine.py", line 700, in _run_workers
    output = executor(*args, **kwargs)
  File "/home/xmo/vllm/vllm/worker/worker.py", line 70, in init_model
    self.model = get_model(self.model_config)
  File "/home/xmo/vllm/vllm/model_executor/model_loader.py", line 91, in get_model
    model = model_class(model_config.hf_config, linear_method)
  File "/home/xmo/vllm/vllm/model_executor/models/bluelm.py", line 291, in __init__
    self.model = BlueLMModel(config, linear_method)
  File "/home/xmo/vllm/vllm/model_executor/models/bluelm.py", line 245, in __init__
    self.layers = nn.ModuleList([
  File "/home/xmo/vllm/vllm/model_executor/models/bluelm.py", line 246, in <listcomp>
    BlueLMDecoderLayer(config, linear_method)
  File "/home/xmo/vllm/vllm/model_executor/models/bluelm.py", line 174, in __init__
    self.self_attn = BlueLMAttention(
  File "/home/xmo/vllm/vllm/model_executor/models/bluelm.py", line 134, in __init__
    self.attn = PagedAttentionWithRoPE(
  File "/home/xmo/vllm/vllm/model_executor/layers/attention.py", line 320, in __init__
    self.rotary_emb = get_rope(head_size, rotary_dim, max_position, base,
  File "/home/xmo/vllm/vllm/model_executor/layers/rotary_embedding.py", line 315, in get_rope
    raise ValueError(f"Unknown RoPE scaling type {scaling_type}")
ValueError: Unknown RoPE scaling type ntkmixed
```

**Comment by WangErXiao** [comment]
@peterjc123 We have published new code to support BlueLM-7B-Chat-32K using vllm. You can merge those to your branch.

**Comment by peterjc123** [comment]
> @peterjc123 We have published new code to support BlueLM-7B-Chat-32K using vllm. You can merge those to your branch. The code are in https://github.com/vivo-ai-lab/BlueLM/tree/main/example/vllm . We add new type of RoPE ntkmixed which can support BlueLM-7B-Chat-32K model.
> 
> When using BlueLM-7B-Chat-32K chat model, the prompt must in foramt of '[|Human|]:{xxx}[|AI|]:', eg: '[|Human|]:hello[|AI|]:'

Ok, will take a look and test against the 32K chat model.

**Comment by WoosukKwon** [comment]
Closing the PR as it is pretty old and the demand for the model is not high as of now.

**Pull request closed without merging**
