### PR TITLE
[misc][core] lazy import outlines

### PR DESCRIPTION
**Pull request by youkaichao**
temp fix for https://github.com/vllm-project/vllm/issues/4193

for users who don't use guided decoding but use slurm cluster, this makes their lives eaiser.

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
Nice this is good fix for now! But the users will still have problem with the actually usage :(

**Comment by youkaichao** [comment]
yep this is a temp fix, because I heard many people are suffering from this problem but they don't use outlines at all.

for people who really want guided decoding and suffer from the problem, they can use `--guided-decoding-backend=lm-format-enforcer` :)

**Comment by youkaichao** [comment]
I'm waiting for users' confirmation to see if it works.

**Review by DarkLight1337 — APPROVED** [review]

**Comment by chujiezheng** [comment]
Tested on slurm and this pr works well for me

**Comment by alex2awesome** [comment]
when will this be released? I'm unable to build from source on my HPC server

**Comment by youkaichao** [comment]
@alex2awesome you don't need to wait for the release, we have per-commit wheel released. see

https://docs.vllm.ai/en/latest/getting_started/installation.html

**Comment by alex2awesome** [comment]
That's good to know!! unfortunately, after installing the nightly build, I'm still getting this error:

```ceback (most recent call last):
  File "/project/jonmay_231/spangher/Projects/conditional-information-retrieval/source_summaries/data_vllm_70b.py", line 19, in <module>
    from vllm import LLM,  SamplingParams
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/vllm/__init__.py", line 6, in <module>
    from vllm.entrypoints.llm import LLM
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 13, in <module>
    from vllm.model_executor.guided_decoding import (
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/vllm/model_executor/guided_decoding/__init__.py", line 8, in <module>
    from vllm.model_executor.guided_decoding.outlines_decoding import (
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/vllm/model_executor/guided_decoding/outlines_decoding.py", line 15, in <module>
    from vllm.model_executor.guided_decoding.outlines_logits_processors import (
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/vllm/model_executor/guided_decoding/outlines_logits_processors.py", line 25, in <module>
    from outlines import grammars
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/__init__.py", line 2, in <module>
    import outlines.generate
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/generate/__init__.py", line 2, in <module>
    from .cfg import cfg
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/generate/cfg.py", line 3, in <module>
    from outlines.fsm.guide import CFGGuide
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/fsm/guide.py", line 109, in <module>
    def create_states_mapping(
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/caching.py", line 93, in decorator
    memory = get_cache()
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/caching.py", line 65, in get_cache
    memory["__version__"] = outlines_version
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/diskcache/core.py", line 823, in __setitem__
    self.set(key, value, retry=True)
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/diskcache/core.py", line 806, in set
    self._row_update(rowid, now, columns)
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/diskcache/core.py", line 828, in _row_update
    sql(
sqlite3.DatabaseError: database disk image is malformed```

**Comment by youkaichao** [comment]
>   File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/vllm/model_executor/guided_decoding/__init__.py", line 8, in <module>
>    from vllm.model_executor.guided_decoding.outlines_decoding import (

your installation might be wrong. if you have the latest commit installed, line 8 should not be this one.

see https://github.com/vllm-project/vllm/blob/257afc37c5b3e4c6d491d105337387989b013aee/vllm/model_executor/guided_decoding/__init__.py#L8

**Comment by alex2awesome** [comment]
Ahh thanks @youkaichao — dumb error on my part, I just copy/pasted the instructions in the docs. The right version to use for anyone coming here is:

```export VLLM_VERSION=0.5.5
pip install https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-${VLLM_VERSION}-cp38-abi3-manylinux1_x86_64.whl```

**Comment by gustavosm** [comment]
Hello, guys!!
I'm facing same problem as @alex2awesome, but I'm not being able to get what I can do here, because I'm running a golang app to start a docker container for vllm. So, I'm not sure how to run this `pip install` mentioned above, since my container drops as soon as it tries to run.
I have tried vllm 0.5.5 version, but no success.
Any suggestion?
The error message I'm getting is exactly the same as @alex2awesome posted few comments above.

**Comment by LucWeber** [comment]
> Hello, guys!! I'm facing same problem as @alex2awesome, but I don't know what I can do here, because I'm running a golang app to start a docker container for vllm. So, I'm not sure how to run this `pip install` mentioned above, since my container drops as soon as it tries to run. I have tried vllm 0.5.5 version, but no success. Any suggestion? The error message I'm getting is exactly the same as @alex2awesome posted few comments above.
> 
> Something that might worth mention is: the problem only occurs if I run the app with my linux user... I log in with another user, everything works fine

As I understand it the fix is not yet in 0.5.5. You will have to install from source

**Comment by alex2awesome** [comment]
Hi @youkaichao , has the fix been implemented with the OpenAI-compatible inference engine yet? 

I've tested and am OK with loading the model in python, as in: https://docs.vllm.ai/en/latest/getting_started/quickstart.html

but when I try to launch an inference engine using:

```
python -m vllm.entrypoints.openai.api_server \
    --model NousResearch/Meta-Llama-3-70B-Instruct \
    --dtype float16 \
    --tensor-parallel-size $NUM_GPUS \
    --api-key token-abc123 \
    --enforce-eager &
```

I get the same errors:

```    from vllm.model_executor.guided_decoding.outlines_decoding import (  # noqa
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/vllm/model_executor/guided_decoding/outlines_decoding.py", line 15, in <module>
    from vllm.model_executor.guided_decoding.outlines_logits_processors import (
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/vllm/model_executor/guided_decoding/outlines_logits_processors.py", line 25, in <module>
    from outlines import grammars
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/__init__.py", line 2, in <module>
    import outlines.generate
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/generate/__init__.py", line 2, in <module>
    from .cfg import cfg
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/generate/cfg.py", line 3, in <module>
    from outlines.fsm.guide import CFGGuide
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/fsm/guide.py", line 109, in <module>
    def create_states_mapping(
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/caching.py", line 93, in decorator
    memory = get_cache()
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/outlines/caching.py", line 65, in get_cache
    memory["__version__"] = outlines_version
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/diskcache/core.py", line 823, in __setitem__
    self.set(key, value, retry=True)
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/diskcache/core.py", line 806, in set
    self._row_update(rowid, now, columns)
  File "/home1/spangher/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/diskcache/core.py", line 828, in _row_update
    sql(
sqlite3.DatabaseError: database disk image is malformed```

**Comment by youkaichao** [comment]
@alex2awesome it should also work for the api server.

your stack trace is incomplete, and it is unclear if you use guided decoding or not.

**Pull request merged**
