### PR TITLE
Fix incorrect image channels when dealing with 1x1 image #8954

### LINKED ISSUE #8954: [Bug]: minicpmv crash on 1x1 image
### Your current environment

<details>
</details>

### Model Input Dumps

_No response_

### 🐛 Describe the bug

```text
The channel dimension is ambiguous. Got image shape (1, 1, 3). Assuming channels are the first dimension.
ERROR 09-29 21:38:19 image.py:48] Failed to process image ([<PIL.Image.Image image mode=RGB size=1x1 at 0x7FF3D44B3E80>, <PIL.Image.Image image mode=RGB size=1x1 at 0x7FF3D44B22C
0>, <PIL.Image.Image image mode=RGB size=918x1850 at 0x7FF3D44B2C20>])
ERROR 09-29 21:38:19 async_llm_engine.py:58] Engine background task failed
ERROR 09-29 21:38:19 async_llm_engine.py:58] Traceback (most recent call last):
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 48, in _log_task_completion
ERROR 09-29 21:38:19 async_llm_engine.py:58]     return_value = task.result()
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 733, in run_engine_loop
ERROR 09-29 21:38:19 async_llm_engine.py:58]     result = task.result()
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in engine_step
ERROR 09-29 21:38:19 async_llm_engine.py:58]     request_outputs = await self.engine.step_async(virtual_engine)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 340, in step_async
ERROR 09-29 21:38:19 async_llm_engine.py:58]     outputs = await self.model_executor.execute_model_async(
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 185, in execute_model_async
ERROR 09-29 21:38:19 async_llm_engine.py:58]     output = await make_async(self.driver_worker.execute_model
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
ERROR 09-29 21:38:19 async_llm_engine.py:58]     result = self.fn(*self.args, **self.kwargs)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 303, in execute_model
ERROR 09-29 21:38:19 async_llm_engine.py:58]     inputs = self.prepare_input(execute_model_req)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 291, in prepare_input
ERROR 09-29 21:38:19 async_llm_engine.py:58]     return self._get_driver_input_and_broadcast(execute_model_req)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 253, in _get_driver_input_and_broadcast
ERROR 09-29 21:38:19 async_llm_engine.py:58]     self.model_runner.prepare_model_input(
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/worker/embedding_model_runner.py", line 142, in prepare_model_input
ERROR 09-29 21:38:19 async_llm_engine.py:58]     model_input = self._prepare_model_input_tensors(
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1123, in _prepare_model_input_tensors
ERROR 09-29 21:38:19 async_llm_engine.py:58]     builder.add_seq_group(seq_group_metadata)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 720, in add_seq_group
ERROR 09-29 21:38:19 async_llm_engine.py:58]     per_seq_group_fn(inter_data, seq_group_metadata)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 658, in _compute_multi_modal_input
ERROR 09-29 21:38:19 async_llm_engine.py:58]     mm_kwargs = self.multi_modal_input_mapper(mm_data)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/multimodal/registry.py", line 126, in map_input
ERROR 09-29 21:38:19 async_llm_engine.py:58]     input_dict = plugin.map_input(model_config, data_value)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/multimodal/base.py", line 263, in map_input
ERROR 09-29 21:38:19 async_llm_engine.py:58]     return mapper(InputContext(model_config), data)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/multimodal/image.py", line 44, in _default_input_mapper
ERROR 09-29 21:38:19 async_llm_engine.py:58]     batch_data = image_processor \
ERROR 09-29 21:38:19 async_llm_engine.py:58]     result = self.fn(*self.args, **self.kwargs)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 303, in execute_model
ERROR 09-29 21:38:19 async_llm_engine.py:58]     inputs = self.prepare_input(execute_model_req)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 291, in prepare_input
ERROR 09-29 21:38:19 async_llm_engine.py:58]     return self._get_driver_input_and_broadcast(execute_model_req)
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 253, in _get_driver_input_and_broadcast
ERROR 09-29 21:38:19 async_llm_engine.py:58]     self.model_runner.prepare_model_input(
ERROR 09-29 21:38:19 async_llm_engine.py:58]   File "/usr/local/python3/lib/python3.10/site-packages/vllm/worker/embedding_model_runner.py", line 142, in prepare_model_input
ERROR 09-29 21:38:19 async_llm_engine.py:58]     model_input = self._prepare_model_input_tensors(
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by zyddnys**
Since input is PIL image, the input data format is always channels last, this PR prevents transformers from inferring image format and thus fix #8954

### CODE REVIEW

**Review by DarkLight1337 — APPROVED** [review]
Thanks for fixing!

**Comment by DarkLight1337** [comment]
Please run `format.sh` to fix the lint errors.

**Review by DarkLight1337 — CHANGES_REQUESTED** [review]
After some offline discussion with @alex-jw-brooks, I just remembered that the input mapper for MiniCPM-V has been changed to a custom one in #8250, so this fix doesn't actually work for that model.

Moreover, not all image processors accept `data_format="channels_last"` as a keyword argument, so this change may break other models as well. To avoid this, I suggest using `inspect.get_signature` or something like that to only pass in `data_format` if it's indeed supported by the processor. For MiniCPM-V though, their image mapper doesn't support `data_format`, so you'll have to ask HF side to add this first.

**Comment by sfyumi** [comment]
How can i do to just workaround it for MiniCPM-V?

**Comment by DarkLight1337** [comment]
> How can i do to just workaround it for MiniCPM-V?

I suggest you validate the images before sending them into vLLM.

**Pull request closed without merging**
