### PR TITLE
[Model] Add Phi-2 LoRA support

### LINKED ISSUE #3562: [New Model]: Phi-2 support for LoRA
### The model to consider.

Microsoft/Phi-2 with LoRA

### The closest model vllm already supports.

_No response_

### What's your difficulty of supporting the model you want?

_No response_

### LINKED ISSUE #4141: [Feature]: Phi2 LoRA support
### Please, add the LoRA support for PhiForCausalLM.

"ValueError: Model PhiForCausalLM does not support LoRA, but LoRA is enabled. Support for this model may be added in the future. If this is important to you, please open an issue on github."

### PR DESCRIPTION
**Pull request by Isotr0py**
FILL IN THE PR DESCRIPTION HERE

FIX #4141 
FIX #3562
- #3562
- #4141 

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by Isotr0py** [comment]
### Test
```python
from vllm import LLM
from vllm import SamplingParams
from vllm.lora.request import LoRARequest

llm = LLM("/data/LLM-model/phi-2", enable_lora=True)

sql_lora_path = "/data/PEFT-LoRA/phi-2/phi-2-universal-NER"


prompts = [
    "<|im_start|>human\nText: Mit Patel here from India<|im_end|>\n<|im_start|>gpt\nI've read this text.<|im_end|>\n<|im_start|>human\nwhat is a name of the person in the text?<|im_end|>\n<|im_start|>gpt:\n",
]

sampling_params = SamplingParams(
    temperature=0.8, top_p=0.95, max_tokens=64, stop="<|im_end|>"
)

outputs = llm.generate(
    prompts, sampling_params, lora_request=LoRARequest("phi_adapter", 1, sql_lora_path)
)

# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

```

### Output
```bash
INFO 05-17 21:22:23 llm_engine.py:103] Initializing an LLM engine (v0.4.2) with config: model='/data/LLM-model/phi-2', speculative_config=None, tokenizer='/data/LLM-model/phi-2', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cpu, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=/data/LLM-model/phi-2)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WARNING 05-17 21:22:23 cpu_executor.py:112] float16 is not supported on CPU, casting to bfloat16.
WARNING 05-17 21:22:23 cpu_executor.py:115] CUDA graph is not supported on CPU, fallback to the eager mode.
WARNING 05-17 21:22:23 cpu_executor.py:142] Environment variable VLLM_CPU_KVCACHE_SPACE (GB) for CPU backend is not set, using 4 by default.
WARNING 05-17 21:22:23 punica.py:14] punica LoRA kernels require a GPU to run. But you are using the CPU version vLLM
INFO 05-17 21:22:24 selector.py:52] Using Torch SDPA backend.
INFO 05-17 21:22:35 cpu_executor.py:71] # CPU blocks: 819
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Processed prompts: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [09:09<00:00, 549.94s/it, Generation Speed: 0.02 toks/s]
Prompt: "<|im_start|>human\nText: Mit Patel here from India<|im_end|>\n<|im_start|>gpt\nI've read this text.<|im_end|>\n<|im_start|>human\nwhat is a name of the person in the text?<|im_end|>\n<|im_start|>gpt:\n", Generated text: 'Mit Patel\n'
```

**Review by rkooo567 — COMMENTED** [review]
LGTM. Consider adding a test similar to https://github.com/vllm-project/vllm/blob/main/tests/lora/test_llama.py? Also cc @Yard1

**Comment by Isotr0py** [comment]
OK, but I haven't tested this on punica kernel yet, and only tested it on the cpu kernel proposed in another PR: #4830.  I will test it in GPU environment later.

It seems that Phi-2 has a different vocab_size compared to existing punica dimension in `bgmv_config.h`, I wonder how we can determine the punica dimension in `bgmv_config.h`.

**Comment by rkooo567** [comment]
cc @Yard1 for the question above (who's more familiar with punica kernel)

**Comment by Isotr0py** [comment]
Well, this works on RTX3080 Ti with `punica` kernel so we don't need to modify the `punica` code anymore :)
```bash
INFO 05-18 01:19:13 llm_engine.py:103] Initializing an LLM engine (v0.4.2) with config: model='/data/LLM-model/phi-2', speculative_config=None, tokenizer='/data/LLM-model/phi-2', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=/data/LLM-model/phi-2)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 05-18 01:19:14 selector.py:37] Using FlashAttention-2 backend.
INFO 05-18 01:19:16 model_runner.py:145] Loading model weights took 5.1933 GB
INFO 05-18 01:19:18 gpu_executor.py:83] # GPU blocks: 948, # CPU blocks: 819
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Processed prompts: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.72it/s, Generation Speed: 27.19 toks/s]
Prompt: "<|im_start|>human\nText: Mit Patel here from India<|im_end|>\n<|im_start|>gpt\nI've read this text.<|im_end|>\n<|im_start|>human\nwhat is a name of the person in the text?<|im_end|>\n<|im_start|>gpt:\n", Generated text: 'Mit Patel\n'
```
I will add the remaining test later.

**Comment by rkooo567** [comment]
sounds great! It is awesome we just need to change supported modules specification

**Comment by Isotr0py** [comment]
Emmm, it's strange that the CI worker OOM during running `test_phi.py` in `lora-test-3`:
```
=========================== short test summary info ============================
FAILED lora/test_phi.py::test_phi2_lora - RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
FAILED lora/test_punica.py::test_lora_a_extra_shapes[11806239938951-1-256-float16] - RuntimeError: CUDA generator expects graph capture to be underway, but the current stream is not capturing.
FAILED lora/test_punica.py::test_lora_a_extra_shapes[11806239938951-1-1024-float16] - RuntimeError: CUDA generator expects graph capture to be underway, but the current stream is not capturing.
```
 Is there any way to solve this?

**Review by Yard1 — APPROVED** [review]

**Comment by Yard1** [comment]
@Isotr0py try reducing max_loras in the test to 2

**Comment by Isotr0py** [comment]
It seems that `enforce_eager=True` can solve the OOM problem, but should we use this in test CI?

**Comment by Yard1** [comment]
@Isotr0py we can keep it but can you add a comment whenever you use `enforce_eager` in test to clarify why we set it there?

**Comment by rkooo567** [comment]
yeah technically enforce_eager=False case should be already tested

**Comment by Isotr0py** [comment]
I have added a comment to mark that `enforce_eager=True` is used for `test_phi2` to reduce memory usage for CI test.

**Comment by rkooo567** [comment]
```



FAILED lora/test_phi.py::test_phi2_lora - ValueError: Head size 80 is not supported by FlashAttention. Supported head sizes are: [32, 64, 96, 128, 160, 192, 224, 256].
 

<br class="Apple-interchange-newline">
```

looks like the test is failing with this error.

**Comment by Isotr0py** [comment]
@rkooo567 I have created #4944 to fix this, and `LoRA-test-3` passed in the fix PR.

However, the `lora-long-context-distributed` test failed in that PR, can you have a look at that?

**Comment by rkooo567** [comment]
The failure looks kind of unrelated... let me retry the test

**Pull request merged**
