### PR TITLE
[CI] Add retry for agent lost

### PR DESCRIPTION
**Pull request by cadedaniel**
Some CI runs fail with -10, which I believe we should retry. Example: https://buildkite.com/vllm/ci/builds/6657#018f4ece-88d4-4901-9e71-5621d3095d36

Screenshot 2024-05-06 at 11 29 27 AM

### CODE REVIEW

**Comment by cadedaniel** [comment]
cc @simon-mo @comaniac

**Review by simon-mo — COMMENTED** [review]
can you add it to line 55 as well

**Comment by cadedaniel** [comment]
added

**Review by simon-mo — APPROVED** [review]

**Review by comaniac — APPROVED** [review]
LGTM. Thanks! I've been suffered by this for a week.

**Pull request merged**
