### PR TITLE
Implement AWQ quantization support for LLaMA

### PR DESCRIPTION
**Pull request by WoosukKwon**
This PR adds initial support for AWQ. To minimize the scope, it only covers LLaMA models for now. This PR is adopted from great previous PRs #762 and #926 written by @ri938 @casper-hansen @julian-q .

NOTE: We need to do refactoring after this PR. Especially, the weight loading logic and ParallLinear layers are messy at the moment.

Tested:
* `python examples/llm_engine_example.py --model casperhansen/vicuna-7b-v1.5-awq --quantization awq`
* `python examples/llm_engine_example.py --model casperhansen/vicuna-7b-v1.5-awq --quantization awq -tp 2`
* `python examples/llm_engine_example.py --model abhinavkulkarni/lmsys-vicuna-33b-v1.3-w4-g128-awq --quantization awq -tp 2`

### CODE REVIEW

**Review by zhuohan123 — APPROVED** [review]
This PR LGTM in general given that we will immediately refactor after we merge it. Can you also include some memory/speed profiling results of this PR? Also, can you include one quantized model in the test so we can keep track?

**Comment by viktor-ferenczi** [comment]
Built vLLM from this branch on Ubuntu 22.04 [following the docs](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#build-from-source). 

Used a venv, because otherwise some dependency installation fails with access denied error (as normal user). 

Had to install ray manually [with this workaround](https://github.com/vllm-project/vllm/issues/754).

Downloaded this AWQ model from HF: [lmdeploy/llama2-chat-13b-w4](https://huggingface.co/lmdeploy/llama2-chat-13b-w4)

Attempted to run vLLM in API mode like this:

```
#!/bin/bash
. ~/vllm/venv/bin/activate
python -O -u -m vllm.entrypoints.api_server \
    --host=0.0.0.0 \
    --port=7777 \
    --model=$HOME/models/llama2-chat-13b-w4 \
    --tokenizer=hf-internal-testing/llama-tokenizer \
    --block-size=16 \
    --swap-space=8
```

Got exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/viktor/dep/vllm/venv/lib/python3.10/site-packages/vllm-0.1.7-py3.10-linux-x86_64.egg/vllm/entrypoints/api_server.py", line 80, in <module>
  File "/home/viktor/dep/vllm/venv/lib/python3.10/site-packages/vllm-0.1.7-py3.10-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 452, in from_engine_args
  ...
/llm_engine.py", line 137, in _init_workers
  File "/home/viktor/dep/vllm/venv/lib/python3.10/site-packages/vllm-0.1.7-py3.10-linux-x86_64.egg/vllm/engine/llm_engine.py", line 688, in _run_workers
  File "/home/viktor/dep/vllm/venv/lib/python3.10/site-packages/vllm-0.1.7-py3.10-linux-x86_64.egg/vllm/worker/worker.py", line 67, in init_model
  File "/home/viktor/dep/vllm/venv/lib/python3.10/site-packages/vllm-0.1.7-py3.10-linux-x86_64.egg/vllm/model_executor/model_loader.py", line 82, in get_model
  ...
  File "/home/viktor/dep/vllm/venv/lib/python3.10/site-packages/vllm-0.1.7-py3.10-linux-x86_64.egg/vllm/model_executor/parallel_utils/tensor_parallel/layers.py", line 331, in create_weights
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 23.65 GiB total capacity; 23.01 GiB already allocated; 19.19 MiB free; 23.04 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

The PC has 2x4090 (24GB each), 64GB RAM, Ryzen 3800X

Documentation and examples on compatible models and how to run AWQ with reasonably VRAM requirement is very welcome.

Am I right that `--tensor-parallel-size` is not supported yet?

**Comment by WoosukKwon** [comment]
@zhuohan123

Throughput of FP16 LLaMA-7B:
```
Throughput: 6.28 requests/s, 3003.81 tokens/s
```

Throughput of AWQ LLaMA-7B (`casperhansen/vicuna-7b-v1.5-awq`):
```
Throughput: 4.23 requests/s, 2022.94 tokens/s
```

Probably because the AWQ kernel is not well optimized (e.g., we use a single kernel for different shapes and hardware), the throughput decreases rather than increases. This is aligned with what @julian-q reported.

**Comment by casper-hansen** [comment]
@viktor-ferenczi This PR relies on repositories that have a quant config available to load from. Repositories like AutoAWQ can generate it for you when quantizing or you can add it manually.

**Comment by WoosukKwon** [comment]
However, there's small benefit when it comes to latency.

Latency with FP16 LLaMA-7B (prompt len 32, output len 128):
```
Avg latency: 1.8855809370676677 seconds
```

Latency with AWQ LLaMA-7B (prompt len 32, output len 128):
```
Avg latency: 1.6215016047159831 seconds
```

Again, since we do not have optimized kernels for AWQ, I think currently its main benefit is just enabling serving large models on a single GPU. We may get practical speedup on GPTQ, since people have developed more mature CUDA kernels for it.

**Comment by casper-hansen** [comment]
> @zhuohan123
> 
> Throughput of FP16 LLaMA-7B:
> 
> ```
> Throughput: 6.28 requests/s, 3003.81 tokens/s
> ```
> 
> Throughput of AWQ LLaMA-7B (`casperhansen/vicuna-7b-v1.5-awq`):
> 
> ```
> Throughput: 4.23 requests/s, 2022.94 tokens/s
> ```
> 
> Probably because the AWQ kernel is not well optimized (e.g., we use a single kernel for different shapes and hardware), the throughput decreases rather than increases. This is aligned with what @julian-q reported.

Optimizing GEMM kernels for high throughput is an open problem when it comes to quantized models. My own tests indicated it is fastest below batch size 8 and it has equal performance at batch size 16 compared to FP16.

**Comment by WoosukKwon** [comment]
@casper-hansen 

> Optimizing GEMM kernels for high throughput is an open problem when it comes to quantized models. My own tests indicated it is fastest below batch size 8 and it has equal performance at batch size 16 compared to FP16.

Thanks for letting us know! Do you think it would be possible to use OpenAI Triton for writing more optimized AWQ kernel?

**Comment by TheBloke** [comment]
Great work on the merge.

I'll start releasing AWQ models this weekend. Will aim to do a couple of hundred by early next week.  Primarily Llama 2 models, plus some of the old still-popular Llama 1s.

**Comment by casper-hansen** [comment]
> @casper-hansen
> 
> > Optimizing GEMM kernels for high throughput is an open problem when it comes to quantized models. My own tests indicated it is fastest below batch size 8 and it has equal performance at batch size 16 compared to FP16.
> 
> Thanks for letting us know! Do you think it would be possible to use OpenAI Triton for writing more optimized AWQ kernel?

I would absolutely love it if someone wrote a better kernel whether in Triton or CUDA. 

I do believe a Triton kernel is possible, there is just a few obstacles like how to dequantize and how to run optimized instructions like asm volatile. Triton kernels exist for GPTQ but it has also been shown that CUDA kernels are faster (ExLlama v2).

**Comment by WoosukKwon** [comment]
> I'll start releasing AWQ models this weekend. Will aim to do a couple of hundred by early next week. Primarily Llama 2 models, plus some of the old still-popular Llama 1s.

Got it. Thanks for letting us know! Actually, there's no blocker for us to add AWQ support to other model types. Once you upload the AWQ models, we can add other model support accordingly.

**Comment by casper-hansen** [comment]
> @TheBloke
> 
> > I'll start releasing AWQ models this weekend. Will aim to do a couple of hundred by early next week. Primarily Llama 2 models, plus some of the old still-popular Llama 1s.
> 
> Got it. Thanks for letting us know! Actually, there's no blocker for us to add AWQ support to other model types. Once you upload the AWQ models, we can add other model support accordingly.

If you want something to test with, I have repositories for Falcon and MPT. I am sure The Bloke will send out so many more models soon though. 

https://huggingface.co/casperhansen/mpt-7b-8k-chat-awq
https://huggingface.co/casperhansen/falcon-7b-awq

**Comment by WoosukKwon** [comment]
@casper-hansen

> I do believe a Triton kernel is possible, there is just a few obstacles like how to dequantize and how to run optimized instructions like asm volatile. Triton kernels exist for GPTQ but it has also been shown that CUDA kernels are faster (ExLlama v2).

Got it. So you mean the dequantization logic is not easy to implement in triton, right? Hmm... I think for now we will focus on code cleaning & supporting different quantization schemes without considering much about their performance, and later will get back to this performance issue.

**Comment by casper-hansen** [comment]
> @casper-hansen
> 
> > I do believe a Triton kernel is possible, there is just a few obstacles like how to dequantize and how to run optimized instructions like asm volatile. Triton kernels exist for GPTQ but it has also been shown that CUDA kernels are faster (ExLlama v2).
> 
> Got it. So you mean the dequantization logic is not easy to implement in triton, right? Hmm... I think for now we will focus on code cleaning & supporting different quantization schemes without considering much about their performance, and later will get back to this performance issue.

Yes, dequantization is easily the most tricky part to get right. The rest is normal FP16 operations. 

I agree on the strategy. When you get to GPTQ, you should definitely explore all the optimized work like Exllama V2. It’s the fastest repository for running GPTQ models at batch size 1 but has not been tested much for high throughput.

**Comment by esmeetu** [comment]
@WoosukKwon Doesn't it support Turing arch? my GPU's compute capabitlity is 7.5.

build Error message:

  `ptxas /tmp/tmpxft_0006e7c4_00000000-6_gemm_kernels.ptx, line 928; error   : Feature '.m16n8k16' requires .target sm_80 or higher`

**Comment by casper-hansen** [comment]
> @WoosukKwon Doesn't it support Turing arch? my GPU's compute capabitlity is 7.5. CUDA-12.1.
> 
> build Error message:
> 
> `ptxas /tmp/tmpxft_0006e7c4_00000000-6_gemm_kernels.ptx, line 928; error : Feature '.m16n8k16' requires .target sm_80 or higher`
> 
> If not, hope can add backward compatibility for kernel build.

No, it supports SM80 and up. So Ampere and later is supported.

**Comment by esmeetu** [comment]
@casper-hansen Ok..., do you mean AWQ quant doesn't support <8.0? And For <8.0, only choice is GPTQ for now?

**Comment by casper-hansen** [comment]
> @casper-hansen Ok..., do you mean AWQ quant doesn't support <8.0? And For <8.0, only choice is GPTQ for now?

Yes, so Turing is not supported. T4 is not supported. The GEMM kernel makes use of tensor cores, but some instructions in the kernel make it incompatible with 7.5.

**Comment by esmeetu** [comment]
@casper-hansen Thanks for you reply.

**Comment by ryanshrott** [comment]
@WoosukKwon Would you mind providing example usage of AWQ support for a llama2 fine-tuned variant like this one?
https://huggingface.co/rshrott/description-awq-4bit/tree/main

**Comment by casper-hansen** [comment]
> Got it. So you mean the dequantization logic is not easy to implement in triton, right? Hmm... I think for now we will focus on code cleaning & supporting different quantization schemes without considering much about their performance, and later will get back to this performance issue.

After more research, I found dequantization int4 kernels for Triton below. Seems doable, just needs to fit the AWQ format.
https://github.com/ModelTC/lightllm/blob/main/lightllm/common/basemodel/triton_kernel/dequantize_gemm_int4.py

**Comment by AniZpZ** [comment]
We tested awq with vllm as well and found it's hard to get throughouts improvement with W4A16 method. Therefore, we impelement W8W8 method(get weight weith smoothquant) which can increase throughoutsin this pr: https://github.com/vllm-project/vllm/pull/1112

**Comment by viktor-ferenczi** [comment]
It is not only about the throughput. It is also the much worse quality (perplexity) of 4-bit weight quantized models than the 8-bit ones. I've tested 4-bit AWQ for my use cases and it is just not cutting it. The heavily quantized model makes frequent small mistakes. Running the same model at full 16 bits (or from a 8 bit GGUF using `ctransformers`) don't make such mistakes at all. I'm looking forward for the W8A8 quantization mostly because of this. Model: WizardCoder 13B and 34B

**Comment by gesanqiu** [comment]
@casper-hansen 
> My own tests indicated it is fastest below batch size 8 and it has equal performance at batch size 16 compared to FP16.

I wonder how you get the conclusion that batch size below 8 is faster than batch size bigger than 8? Is meaning of batch suitable to vLLM's continuous batch or just a normal batch? Is the test happened on the vLLM's `benchmark_throughput.py`?
I test the throughput of CodeLlama-13B, quantized with your AutoAWQ and control the batch size with `max_num_seqs` parameter, but found that smaller value reduce to samller throughput.
Here is my test result:
| max_num_seqs | throughput |
| ----------- | ----------- |
| 4 | 300.07 tokens/s |
| 8 | 493.16 tokens/s |
| 16 |  690.29 tokens/s |
In my understand, bigger batch size will always bring higher throughput. So does the faster means the inference latency is lower?

**Comment by vince62s** [comment]
How did you guys deal with this: https://github.com/casper-hansen/AutoAWQ/issues/234
GEMM and GEMV have their param reversed (out, in) "standard way for GEMV but (in, out) for GEMM which trigger a different way to slice when using tensor parallel.

**Comment by vedantroy** [comment]
@WoosukKwon 

I implemented Triton kernels for AWQ inference. They are much faster then the existing CUDA kernels, especially at larger batch sizes:
image

They are also simpler (core kernel is ~ 50-100 lines of Triton).

The weights format is a bit different (it's using the most recent AWQ weight format, albeit weights are transposed):
```
    a: (M, K)
    qw: (K // pack_num, N)
    scales: (K // group_size, N)
    qzeros: (K // group_size // pack_num, N)
```

You can find the code here: https://github.com/vedantroy/gpu_kernels/tree/main
I'd be very interested to see a benchmark that shows how these kernels affect overall AWQ throughput.
Warning: I'm pretty sure my kernels are correct, but not 100%. I'll be emailing the authors to double-check.

**Pull request merged**
