### PR TITLE
[BugFix] Fix metrics error for --num-scheduler-steps > 1

### LINKED ISSUE #8233: [Bug]: Metrics error for --num-scheduler-steps > 1
### Your current environment

Your output of `python collect_env.py` here

### 🐛 Describe the bug

When `--num-scheduler-steps=n`, `do_log_stats()` is called only once every `n` step. However, when calculating `num_generation_tokens` within `do_log_stats()`, it only adds one generation token for each seq_group. This results in the `Avg generation throughput` metrics output being incorrect.

image

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by yuleil**
Fix #8233

Before the fix:
image

After the fix:
image

### CODE REVIEW

**Review by comaniac — APPROVED** [review]
LGTM. cc @SolitaryThinker

**Review by SolitaryThinker — APPROVED** [review]
Good catch thank you!

**Comment by Syst3m1cAn0maly** [comment]
Hi !
Is there still some work to be done to complete the PR ?
The problem is still present on v0.6.2 as it is not yet merged.

Thanks in advance

**Comment by comaniac** [comment]
We can merge once the CI is passed (or force merge if the failed tests are flaky)

**Comment by njhill** [comment]
@yuleil could you merge in main one more time? tests should be fixed now...

**Comment by ashgold** [comment]
Can you check if TPOT has also been resolved by this change?

**Comment by njhill** [comment]
cc @robertgshaw2-neuralmagic

**Pull request merged**
