### PR TITLE
[Bugfix] Fix for inconsistent behaviour related to sampling and repetition penalties 

### LINKED ISSUE #5607: [Bug]: Concurrent requests messing up GREEDY responses
### Your current environment

```text
The output of `python collect_env.py`

Collecting environment information...
/opt/vllm/lib64/python3.11/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux 9.4 (Plow) (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: Could not collect
CMake version: version 3.29.5
Libc version: glibc-2.34

Python version: 3.11.7 (main, Jan 22 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (64-bit runtime)
Python platform: Linux-4.18.0-372.46.1.el8_6.x86_64-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-80GB
Nvidia driver version: 535.104.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          80
On-line CPU(s) list:             0-79
Vendor ID:                       GenuineIntel
Model name:                      Intel Xeon Processor (Icelake)
CPU family:                      6
Model:                           134
Thread(s) per core:              2
Core(s) per socket:              20
Socket(s):                       2
Stepping:                        0
BogoMIPS:                        5600.04
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid fsrm md_clear arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       2.5 MiB (80 instances)
L1i cache:                       2.5 MiB (80 instances)
L2 cache:                        160 MiB (40 instances)
L3 cache:                        32 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-39
NUMA node1 CPU(s):               40-79
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] torch==2.3.0
[pip3] transformers==4.41.2
[pip3] triton==2.3.0
[pip3] vllm-nccl-cu12==2.18.1.0.4.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.3
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	NIC0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	PIX	0-39	0		N/A
NIC0	PIX	 X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0

```

## Issue

While sending concurrent requests, `greedy` responses become inconsistent and become affected due to the other concurrent sampling request.

In the example below, if only the `greedy` request is sent, the output is 100% `Once upon a time, there was an old man`.
But, as soon as another concurrent sampling request is sent along with the `greedy` request, the `greedy` response sometimes changes to `Once upon a time, there was a young woman` -> which should not be the case.

(Note: not consistent behavior, but happens like 2/5 times)

## Server
```
python -m vllm.entrypoints.api_server --model LLaMa/models/hf/13B-F
```
## Sample client
```
import json
import concurrent.futures
import requests
import traceback

def post_http_request(api_url: str, pload) -> requests.Response:
    headers = {"User-Agent": "Test Client"}
    pload = pload
    response = requests.post(api_url, headers=headers, json=pload, stream=True)
    data = json.loads(response.content)
    output = data["text"]
    print(output)


if __name__ == "__main__":

    prompt = "Once upon a time,"
    api_url = f"http://localhost:8000/generate"

    sampling_params = []
    sampling_params.append(
        {
            "prompt": prompt,
            "temperature": 0.0,
            "max_tokens": 5,
            "repetition_penalty": 2,
        }
    )
    sampling_params.append(
        {
            "prompt": prompt,
            "seed": 99,
            "max_tokens": 4,
            "top_k": 1,
        }
    )
    sampling_params = sampling_params * 10

    with concurrent.futures.ThreadPoolExecutor(max_workers=20) as executor:
        futures = []
        for param in sampling_params:
            futures.append(
                executor.submit(post_http_request, api_url=api_url, pload=param)
            )

        # Waiting for all futures to complete
        for future in concurrent.futures.as_completed(futures):
            try:
                future.result()
            except Exception as exc:
                # printing stack trace
                traceback.print_exc()
                print(f"exception: {exc}")

```

## Output
```
❯ python3 sample_client.py
['Once upon a time, there was a young']
['Once upon a time, there was a young']
['Once upon a time, there was a young']
['Once upon a time, there was a young']
['Once upon a time, there was a young']
['Once upon a time, there was a young']
['Once upon a time, there was a young']
['Once upon a time, there was a young']
['Once upon a time, there was a young']
['Once upon a time, there was a young']
['Once upon a time, there was an old man']
['Once upon a time, there was an old man']
['Once upon a time, there was an old man']
['Once upon a time, there was an old man']
['Once upon a time, there was a young woman']
['Once upon a time, there was an old man']
['Once upon a time, there was an old man']
['Once upon a time, there was an old man']
['Once upon a time, there was an old man']
['Once upon a time, there was a young woman']
```

### PR DESCRIPTION
**Pull request by tdoublep**
Fixes #5607 

I tracked this down to the `prompt_tokens` and `output_tokens` within `SamplingTensors` having the wrong shape, and determined that the correct/incorrect behaviour depends on the order of the requests within the batch. I found that it was enough to reproduce this with just two concurrent requests hitting the server with sampling params:
```python
sampling_params = []
    sampling_params.append(
        {
            "prompt": prompt,
            "temperature": 0.0,
            "max_tokens": 5,
            "repetition_penalty": 2,
        }
    )
    sampling_params.append(
        {
            "prompt": prompt,
            "seed": 99,
            "max_tokens": 4,
            "top_k": 1,
        }
    )
```
The bug relates to how we compute `do_penalties` on the fly inside `from_sampling_metadata`. If we hit the request with `repetition_penalty=2` first, then `do_penalties=True` also for the second request which results in `prompt_tokens` and `output_tokens` having length 2 (see [this line](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/sampling_metadata.py#L399-L400)) and we have the correct behaviour. On the other hand, if we hit the request without `repetition_penalty` first, then this results in `prompt_tokens` and `output_tokens` having length 1, which leads to incorrect sampling behaviour. 

A simple fix is just to do a quick pass through to compute `do_penalties` upfront, thus making it independent of the order of requests.

### CODE REVIEW

**Comment by njhill** [comment]
Thanks @tdoublep, nice find! I think it might be slightly better to actually move the `if do_penalties` logic to after the existing loop instead of a separate loop before. That way in the typical case nothing additional needs to be done.

**Comment by tdoublep** [comment]
@njhill yes makes sense, will update later today.

**Comment by tdoublep** [comment]
@njhill Pushed that change now.

**Review by njhill — APPROVED** [review]
Thanks @tdoublep!

**Comment by simon-mo** [comment]
Thanks! It would be great if we can have a regression test here

**Comment by tdoublep** [comment]
@simon-mo added simple test case to catch this: #5659

**Comment by ChenJian7578** [comment]
So, how can we set it up in the request to effectively avoid this problem？the value of repetition_penalty?

**Pull request merged**
