### PR TITLE
YaRN tests

### PR DESCRIPTION
**Pull request by viktor-ferenczi**
Issue: #980

- YaRN paper: https://arxiv.org/abs/2309.00071
- YaRN repository: https://github.com/jquesnelle/yarn
- Smallest model to test with: https://huggingface.co/NousResearch/Yarn-Llama-2-7b-64k

Currently the branch has preliminary code to test the context window quality with pass key retrieval tasks. It does not plot a graph, that's not the goal of the test. It allows for running the same test on both the reference implementation of YaRN using Transformers and vLLM using parameters to provide similar output, therefore allows for comparing our upcoming implementation with the reference one.

__TODO__
- Implement YaRN in vLLM
- Verify model output and context window quality
- Turn the test code into a pytest test case

### CODE REVIEW

**Comment by casper-hansen** [comment]
Thanks for giving this a shot @viktor-ferenczi. YaRN models look impressive because of their low perplexity and long contest windows, so I’m sure the community will love to test this out once it’s ready.

**Comment by trannhatquy** [comment]
please finish this pull request, it will really help because this model is very good

**Comment by viktor-ferenczi** [comment]
I don't have extensive LLM (or vLLM) development experience yet. I'm learning into it on the job here, so it won't be implemented fast (unless I get help on this). I'm dedicated to complete it at some point, but also need to find the time working on this. (I have a day job.)

**Comment by trannhatquy** [comment]
@zhuohan123 @WoosukKwon please see this pull request

**Comment by Yard1** [comment]
Hi @viktor-ferenczi, I would be willing to contribute the implementation, unless you have already started work on this.

**Comment by viktor-ferenczi** [comment]
I just added tests and haven't written the actual YaRN code yet. 

What may help you is that #464 was merged recently.

Please go ahead with the implementation, because I lack the time to work on it right now.

**Comment by Yard1** [comment]
Implementation PR: https://github.com/vllm-project/vllm/pull/1264

**Pull request closed without merging**
