### PR TITLE
[Misc] Define from_dict and to_dict in InputMetadata

### PR DESCRIPTION
**Pull request by WoosukKwon**
This PR adds `from_dict` and  `to_dict` to `InputMetadata` so that the code in model runner becomes a bit cleaner.

### CODE REVIEW

**Review by zhuohan123 — APPROVED** [review]
LGTM! This looks great!

**Comment by WoosukKwon** [comment]
@zhuohan123 Thanks for the quick review! 😄

**Comment by youkaichao** [comment]
Is it possible to use `dataclass` or something like that?

**Comment by youkaichao** [comment]
I actually find `transformers` uses lots of `dataclasses`:

https://github.com/huggingface/transformers/blob/00c1d87a7d5c8dfb4554370983b5a3f7c069edd7/src/transformers/models/maskformer/modeling_maskformer_swin.py#L36-L67

And I think many configs in `vLLM` can also be `dataclasses`, too. We don't need to write these `from_dict` and `to_dict`, we also get nice `str` and `repr` implementation.

**Comment by WoosukKwon** [comment]
@youkaichao Thanks for the suggestion! Merged your PR and fixed a bug.

**Pull request merged**
