### PR TITLE
[core][distributed] allow custom allreduce when pipeline parallel size > 1

### PR DESCRIPTION
**Pull request by youkaichao**
when pipeline parallel size > 1, we can still use custom allreduce in the tensor parallel group.

### CODE REVIEW

**Review by andoorve — APPROVED** [review]
This looks good to me. Do we need a test?

**Comment by youkaichao** [comment]
I think you already have it:

> TP_SIZE=2 PP_SIZE=2 EAGER_MODE=1 CHUNKED_PREFILL=0 pytest -v -s distributed/test_pipeline_parallel.py

**Comment by andoorve** [comment]
I mean should we also test with and without ENABLE_ALL_REDUCE?

**Comment by youkaichao** [comment]
> I mean should we also test with and without ENABLE_ALL_REDUCE?

the current main does not test it. it is on by default, and might be turned off when hardware does not support it.

**Comment by andoorve** [comment]
Sure, it makes sense to me

**Comment by youkaichao** [comment]
merge as failed tests are unrelated

**Pull request merged**
