### PR TITLE
[model] Reduce medusa weight

### PR DESCRIPTION
**Pull request by skylee-01**
Medusa predicts N tokens in speculative decoding and trains N lheads，In actual deployments, only ResidualBlock is usually trained, not lm_head.So I just keep a copy of lm_head and share it in different heads. In practice, every lm_head saved will reduce 1G of HBM, which is crucial on graphics cards such as the 4090.At the same time, medusa can be predicted longer.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Is `original_lm_head` a common config field for this type of model? Imo if it's just for personal use, you can use [OOT registration](https://docs.vllm.ai/en/latest/models/adding_model.html#out-of-tree-model-integration) to handle this case instead of updating the main repo. (Sorry I didn't look into this deeply earlier)

**Comment by skylee-01** [comment]
> Is `original_lm_head` a common config field for this type of model? Imo if it's just for personal use, you can use [OOT registration](https://docs.vllm.ai/en/latest/models/adding_model.html#out-of-tree-model-integration) to handle this case instead of updating the main repo. (Sorry I didn't look into this deeply earlier)

original_lm_head is only available in the medusa model. This strategy can reduce HBM very well. I think it is an optimization of usage and improves the length of medusa prediction. The original author only considered the case of qps=1, which is not consistent with the vllm scenario. In the scenario I'm exposed to, sharing lm_head is a good strategy. If necessary, I can do some experiments to test its effect.

**Comment by DarkLight1337** [comment]
For future reference, can you link an example HF repo which uses this config field?

**Comment by skylee-01** [comment]
> For future reference, can you link an example HF repo which uses this config field?

I also really agree with your point on where I should connect to.

**Comment by skylee-01** [comment]
> For future reference, can you link an example HF repo which uses this config field?

Here is a config example. In medusa if your weights are not trained on lm_head, you can configure original_lm_head: true so that all heads will share the original lm_head and reduce HBM.
https://huggingface.co/SkyLee-01/Medusa/blob/main/config.json

**Review by DarkLight1337 — APPROVED** [review]

**Comment by DarkLight1337** [comment]
Sorry for the false ping.

**Comment by DarkLight1337** [comment]
Thanks for adding this optimization!

**Pull request merged**
