### PR TITLE
[Misc] Minor change to improve FP8 thoughtput by 2%

### PR DESCRIPTION
**Pull request by elfiegg**
[Misc] Minor change to improve FP8 thoughtput by ~2%

This eliminates the extra called kernel `void at::native::vectorized_elementwise_kernel<(int)4, at::native::FillFunctor<float>..>`.

- Before the change: Throughput: 12.13 requests/s, 5840.23 tokens/s.

- After the change: Throughput: 12.35 requests/s, 5957.66 tokens/s.

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]
Thanks for fixing this :)

**Review by mgoin — APPROVED** [review]
Interesting find, thanks!

**Review by pcmoritz — CHANGES_REQUESTED** [review]
Unfortunately this doesn't quite work (it produces incorrect results), since the maximum is atomically updated here https://github.com/vllm-project/vllm/blob/main/csrc/quantization/fp8/common.cu#L67

So it needs to be zero at the beginning :)

**Comment by pcmoritz** [comment]
If you find another way to optimize this, feel free to update the PR :)

**Comment by Yard1** [comment]
why not just cache the 1.0 scale tensor?

**Comment by elfiegg** [comment]
Thanks for the discussion, I'll think about it.

**Comment by elfiegg** [comment]
Is there a script in the pipeline to test model accuracy?

**Comment by zhangfzR** [comment]
which model is used in this experiment?

**Pull request closed without merging**
