### PR TITLE
support jetson AGX Orin

### PR DESCRIPTION
**Pull request by johnnynunez**

### CODE REVIEW

**Review by mgoin — COMMENTED** [review]
If you want the wheel to support this, you need to also change the dockerfile https://github.com/vllm-project/vllm/blob/151ef4efd2fb52554f4d30408aca619e181ea751/Dockerfile#L57

We can look at the impact on the wheel size after to help make a decision.

**Comment by johnnynunez** [comment]
> If you want the wheel to support this, you need to also change the dockerfile
> 
> https://github.com/vllm-project/vllm/blob/151ef4efd2fb52554f4d30408aca619e181ea751/Dockerfile#L57
> 
> We can look at the impact on the wheel size after to help make a decision.

but it is arm, so the wheel of the dockerfile must be arm, it is different. So, I'm building vllm in jetson-containers.
http://jetson.webredirect.org/jp6/cu126 https://github.com/dusty-nv/jetson-containers/tree/master/packages/llm/vllm

**Review by mgoin — COMMENTED** [review]
Okay I think it is reasonable for us to allow building for this platform, although it would be nice if users wouldn't build for it by default

**Comment by johnnynunez** [comment]
@mgoin 
jetson thor is coming, and jetson agx orin will be supported until 2027

**Comment by mgoin** [comment]
@johnnynunez please see this PR instead https://github.com/vllm-project/vllm/pull/9735

**Comment by mgoin** [comment]
Thanks - Closing as completed!

**Pull request closed without merging**
