### PR TITLE
[Core] Support tensor parallelism for GGUF quantization

### LINKED ISSUE #7662: [Feature]: GGUF quantization with tensor parallelism
### 🚀 The feature, motivation and pitch

When I launch vllm using a gguf (Q8_0 snapshot) and ray (--tensor-parallel-size 8, across 2 nodes of 4 gpus) I get the following error message: 

(RayWorkerWrapper pid=11033) ERROR 08-19 16:07:35 worker_base.py:438] ValueError: GGUF quantization hasn't supported tensor parallelism yet. [repeated 2x across cluster]

Please could you add tensor parallelism for GGUF with quantization.  

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Isotr0py**
FILL IN THE PR DESCRIPTION HERE

FIX https://github.com/vllm-project/vllm/issues/7662
- In previous #5191, we introduced GGUF quantization without tensor parallelism.
- This PR adds tensor parallelism support for gguf quantization.

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by mgoin — COMMENTED** [review]
This looks reasonable and would be a nice to have. Have you tested it/is it ready?

**Comment by Isotr0py** [comment]
This is not ready yet, because I encountered result divergence on one of test prompts when running the test with `tp_size=2`. I need some time to investigate this issue.

AssertionError when `tp_size=2`:
```
>                   assert output_id_0 in logprobs_elem_1, fail_msg
E                   AssertionError: Test0:
E                   Matched tokens:     [13]
E                   original:   '\n3. OpenAI GPT-3: OpenAI GPT-3 is a language model pre-trained on a vast corpus of text data' {29941: Logprob(logprob=-1.9912292957305908, rank=1, decoded_token='3'), 29906: Logprob(logprob=-2.006854295730591, rank=2, decoded_token='2'), 29946: Logprob(logprob=-2.795916795730591, rank=3, decoded_token='4'), 1576: Logprob(logprob=-2.858416795730591, rank=4, decoded_token='The'), 29896: Logprob(logprob=-3.108416795730591, rank=5, decoded_token='1')}
E                   gguf:       '\nThe LASER system is designed to be highly scalable and can handle large data sets with millions of examples per second without any significant performance degradation'    {1576: Logprob(logprob=-1.9153773784637451, rank=1, decoded_token='The'), 3563: Logprob(logprob=-2.806002378463745, rank=2, decoded_token='Over'), 797: Logprob(logprob=-2.970064878463745, rank=3, decoded_token='In'), 2208: Logprob(logprob=-3.845064878463745, rank=4, decoded_token='LL'), 1762: Logprob(logprob=-3.852877378463745, rank=5, decoded_token='To')}

tests/models/utils.py:111: AssertionError
```

**Comment by mgoin** [comment]
Okay no worries, just wanted to make sure you weren't forgotten. Ping me when ready

**Comment by Isotr0py** [comment]
I evaluated the `Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf` model with `tp_size=2` on gsm8k dataset, and the result looks good.

**VLLM server cmd**
```bash
vllm serve Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf --tensor-parallel-size 2 --dtype half --api-key token-abc123 --max-model-len 8192
```
**LM-eval cmd**
```bash
export OPENAI_API_KEY=token-abc123
lm_eval --model local-completions --tasks gsm8k --batch_size 8 -L 400 \
    --output_path Meta-Llama-3.1-8B-Instruct-Q4_K_M-Result \
    --model_args model=Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf,base_url=http://localhost:8000/v1/,tokenizer=TroyDoesAI/Llama-3.1-8B-Instruct,tokenizer_backend=huggingface
```
**Result**
```
2024-08-18:04:28:45,392 INFO     [_client.py:1026] HTTP Request: POST http://localhost:8000/v1/completions "HTTP/1.1 200 OK"
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [40:47<00:00, 48.95s/it]
local-completions (model=Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf,base_url=http://localhost:8000/v1/,tokenizer=TroyDoesAI/Llama-3.1-8B-Instruct,tokenizer_backend=huggingface), gen_kwargs: (None), limit: 400.0, num_fewshot: None, batch_size: 8
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|
|-----|------:|----------------|-----:|-----------|---|-----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.7575|±  |0.0215|
|     |       |strict-match    |     5|exact_match|↑  |0.7425|±  |0.0219|
```
The result divergence may be unrelated to the tensor parallelism implementation but the test itself.

**Review by mgoin — APPROVED** [review]
Thanks!!

**Pull request merged**
