### PR TITLE
[Core][Frontend][Doc] Initial support for LLaVA-NeXT and GPT-4V Chat Completions API

### LINKED ISSUE #2058: Support VLM model and GPT4V API
VLM model: Qwen-VL/LLaVA etc
VLM API: GPT-4V API https://platform.openai.com/docs/guides/vision

### PR DESCRIPTION
**Pull request by DarkLight1337**
To combat scope creep, this PR has been split into smaller ones.

- [x] VLM backend
  - [x] #4197
  - [x] #4199
- [x] OpenAI API server
  - [x] ~~#4200~~ #5237
- [x] QA
  - [x] #5380

The branch associated with this PR has been frozen (except for critical fixes). Once all dependencies have been merged, I will compare this branch against the merged (`main`) branch to verify that I didn't miss any changes.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Just a heads-up that I'm developing this in parallel with #4028, so you'll see occasional merges with my [`openai-typing`](https://github.com/DarkLight1337/vllm-rocm/tree/openai-typing) branch.

**Comment by ywang96** [comment]
Thank you very much for your contribution @DarkLight1337! I'm very interested in testing and reviewing this PR, but could you let me know when it's ready to go? (it seems that you're still iterating on it, and you can always mark this PR back to draft if that's indeed the case)

**Comment by DarkLight1337** [comment]
> Thank you very much for your contribution @DarkLight1337! I'm very interested in testing and reviewing this PR, but could you let me know when it's ready to go? (it seems that you're still iterating on it, and you can always mark this PR back to draft if that's indeed the case)

@ywang96 I have finished the main content for this PR. However, to minimize diffs, let's wait until #4028 has been merged first (since this PR depends on some of the changes there).

**Comment by DarkLight1337** [comment]
I've noticed poor performance when applying LLaVA (whether served locally or using OpenAPI server). Originally, I thought that it was because of the implementation of the vision tower, but it turns out that the input image was not preprocessed according to the `config.json` on HuggingFace. See if this commit fixes the problem.

**Comment by DarkLight1337** [comment]
This force push squashes the commits that were used to debug failing tests., such that their fixes are all contained in a single commit.

**Comment by DarkLight1337** [comment]
This force push consolidates the commits for testing the revision loading logic of image processor.

**Comment by DarkLight1337** [comment]
This patch is in response to [this comment in #4008](https://github.com/vllm-project/vllm/issues/4008#issuecomment-2058858461) so we can see whether the patch actually works. As noted, this patch is only temporary and will be removed before this PR is merged (although the tests will be here to stay)

**Comment by DarkLight1337** [comment]
Hmm, seems that the GPU memory fails to be freed between testing each model. Does anyone know how to fix this issue?

**Comment by DarkLight1337** [comment]
Accidentally pushed local WIP changes, so I reverted that using force-push

**Comment by DarkLight1337** [comment]
@ywang96 Regarding your latest comment in #3042:
> I'm working on a RFC to share some thoughts for refactoring and will send out tomorrow.

Actually, I have also been working on supporting LLaVA-NeXT as well. As part of the effort, I have further refactored the image processing pipeline to output a dictionary which are used to input `kwargs` into the model in order to accept `image_size`. This preserves the contract between the output of HuggingFace processor and the input into the HuggingFace model. As long as those keyword arguments do not conflict with the ones we have in vLLM, I think this is a good way to make the framework flexible enough to support other multi-modal architectures.

**Comment by ywang96** [comment]
> As part of the effort, I have further refactored the image processing pipeline to output a dictionary which are used to input kwargs into the model in order to accept image_size.

Yep - this is exactly what I had in my mind as well, but I think there are more issues in addition to it that we may want to address. For example, do we want to support the prompt format the same way as huggingface to make user experience easier, or at least keep it the same on the Interface level? I do think these are worth discussing (and the refactoring can happen later after we merge model support and API server support depending on how much work it will be).

**Comment by DarkLight1337** [comment]
I have just added support for LLaVA-NeXT, with one big caveat: the size of the input image is fixed, otherwise the feature size (i.e. number of `<image>` tokens to duplicate) would vary for each input.

**Comment by DarkLight1337** [comment]
This force push consolidates the fixes to `test_llava`.

**Comment by DarkLight1337** [comment]
Thes force pushes consolidates the fixes to the LLaVA test and example code.

**Comment by DarkLight1337** [comment]
@ywang96 I think that this PR is suffering from scope creep. Perhaps I should break apart the changes into smaller segments to facilitate the conversation in #4194? I could split the changes as follows (listed in the form of a dependency tree):

1. VLM backend
  a. Refactor `MultiModalData` to support image processing.
  b. Introduce LLaVA-NexT along with the refactored LLaVA-1.5
2. OpenAI API server
  a. Refactor OpenAPI backend (i.e. #2058)
  b. Add GPT-4V support [also depends on 1(a)]

**Comment by ywang96** [comment]
> @ywang96 I think that this PR is suffering from scope creep. Perhaps I should break apart the changes into smaller segments to facilitate the conversation in #4194? I could split the changes as follows (listed in the form of a dependency tree):
> 
> 1. VLM backend
>    a. Refactor `MultiModalData` to support image processing.
>    b. Introduce LLaVA-NexT along with the refactored LLaVA-1.5
> 2. OpenAI API server
>    a. Refactor OpenAPI backend (i.e. [Support VLM model and GPT4V API #2058](https://github.com/vllm-project/vllm/issues/2058))
>    b. Add GPT-4V support [also depends on 1(a)]

I agree - I think OpenAI API server will be a good starting point since they interface should agree with OpenAI protocol anyways, and I'm sorry that this PR suffered :/

One suggestion I have is for a big change like this - it's probably good to have a series of PRs anyways. Take a look at Speculative decoding or Chunked Prefill - those are great examples.

**Comment by DarkLight1337** [comment]
Added #4197.

**Comment by DarkLight1337** [comment]
I have created the child PRs

**Comment by DarkLight1337** [comment]
All of the child PRs have been completed, so I'm closing this now.

**Pull request closed without merging**
