### PR TITLE
support baichuan 13b

### PR DESCRIPTION
**Pull request by gameofdimension**

### CODE REVIEW

**Comment by gameofdimension** [comment]
by running on a nvidia A100 40G, we can see an improvement of 548.05 tokens/s vs 89.44 tokens/s
```
python3 benchmarks/benchmark_throughput.py --model "baichuan-inc/baichuan-13B" --dataset ./ShareGPT_V3_unfiltered_cleaned_split.json --trust-remote-code
python3 benchmarks/benchmark_throughput.py --num-prompts 100 --model "baichuan-inc/baichuan-13B" --dataset ./ShareGPT_V3_unfiltered_cleaned_split.json --backend hf --hf-max-batch-size 4 --trust-remote-code
```

**Comment by gesanqiu** [comment]
What's the difference with #512? It mentioned that there still some issue when use TP(#513)

**Comment by gameofdimension** [comment]
i have no resources to test tp, but this pr is based on present 7b implementation, it will has no tp problem unless the current 7b has tp problem too

**Comment by ericzhou571** [comment]
> i have no resources to test tp, but this pr is based on present 7b implementation, it will has no tp problem unless the current 7b has tp problem too

current 7b implementation do suffer tp problem. Hope someone can find the solution

Best

**Comment by luohao123** [comment]
@ericzhou571 But 7B can load in a single GPU most cases, but 13B don't.

**Comment by ericzhou571** [comment]
> @ericzhou571 But 7B can load in a single GPU most cases, but 13B don't.

we use A100 40G, so it is not a problem for us

**Comment by Mr-Nineteen** [comment]
1. run script:
`python3 api_server.py --model=baichuan-inc/Baichuan-13B-Chat --tensor-parallel-size=2 --trust-remote-code`
2. log:
INFO 07-25 09:57:03 llm_engine.py:67] Initializing an LLM engine with config: model='/workspace/models/baichuan-inc/Baichuan-13B-Chat', tokenizer='/workspace/models/baichuan-inc/Baichuan-13B-Chat', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.bfloat16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=2, seed=0)
WARNING 07-25 09:57:03 tokenizer.py:63] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
(RayWorker pid=3770) [W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:53263 (errno: 97 - Address family not supported by protocol).
(RayWorker pid=3770) [W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:10.189.108.239]:53263 (errno: 97 - Address family not supported by protocol).
(RayWorker pid=3770) [W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:10.189.108.239]:53263 (errno: 97 - Address family not supported by protocol).
Traceback (most recent call last):
  File "api_server.py", line 78, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 96, in __init__
    self._init_workers_ray(placement_group)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 148, in _init_workers_ray
    self._run_workers("init_worker",
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 388, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 2493, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::RayWorker.execute_method() (pid=3771, ip=10.189.108.239, actor_id=523fa5c8812c743a4102e49c01000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x15281ff56df0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RaySystemError: System error: No module named 'transformers_modules'
traceback: Traceback (most recent call last):
ModuleNotFoundError: No module named 'transformers_modules'
(RayWorker pid=3770) No module named 'transformers_modules'
(RayWorker pid=3770) Traceback (most recent call last):
(RayWorker pid=3770)   File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 387, in deserialize_objects
(RayWorker pid=3770)     obj = self._deserialize_object(data, metadata, object_ref)
(RayWorker pid=3770)   File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 268, in _deserialize_object
(RayWorker pid=3770)     return self._deserialize_msgpack_data(data, metadata_fields)
(RayWorker pid=3770)   File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 223, in _deserialize_msgpack_data
(RayWorker pid=3770)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(RayWorker pid=3770)   File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 213, in _deserialize_pickle5_data
(RayWorker pid=3770)     obj = pickle.loads(in_band)
(RayWorker pid=3770) ModuleNotFoundError: No module named 'transformers_modules'
(RayWorker pid=3771) [W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:10.189.108.239]:53263 (errno: 97 - Address family not supported by protocol). [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(RayWorker pid=3771) No module named 'transformers_modules'
(RayWorker pid=3771) Traceback (most recent call last):
(RayWorker pid=3771)   File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 387, in deserialize_objects
(RayWorker pid=3771)     obj = self._deserialize_object(data, metadata, object_ref)
(RayWorker pid=3771)   File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 268, in _deserialize_object
(RayWorker pid=3771)     return self._deserialize_msgpack_data(data, metadata_fields)
(RayWorker pid=3771)   File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 223, in _deserialize_msgpack_data
(RayWorker pid=3771)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(RayWorker pid=3771)   File "/usr/local/lib/python3.8/dist-packages/ray/_private/serialization.py", line 213, in _deserialize_pickle5_data
(RayWorker pid=3771)     obj = pickle.loads(in_band)
(RayWorker pid=3771) ModuleNotFoundError: No module named 'transformers_modules'

**Comment by luohao123** [comment]
@ericzhou571 Not everyone have A100....

**Comment by Mr-Nineteen** [comment]
> i have no resources to test tp, but this pr is based on present 7b implementation, it will has no tp problem unless the current 7b has tp problem too

I can test and the service can start, but the inference is nonsense.

**Comment by luohao123** [comment]
Actually same issue here.

**Comment by zhuohan123** [comment]
> > i have no resources to test tp, but this pr is based on present 7b implementation, it will has no tp problem unless the current 7b has tp problem too
> 
> current 7b implementation do suffer tp problem. Hope someone can find the solution
> 
> Best

@ericzhou571 Can you actually file an issue for this? Also paste the log you get to show the TP issue.

**Comment by zhuohan123** [comment]
Close this PR since #643 is a simpler solution. Please check out the latest main branch to test baichuan-13b! Again, thanks @gameofdimension for the great work!

**Pull request closed without merging**
