### PR TITLE
added support for json and regex formating

### PR DESCRIPTION
**Pull request by itaybar**
solving #2204

### CODE REVIEW

**Comment by tom-doerr** [comment]
What is the performance hit when using this? From the lm-format-enforcer:
```
    # Note on batched generation:
    # For some reason, I achieved better batch performance by manually adding a loop similar to this:
    # https://github.com/vllm-project/vllm/blob/main/examples/llm_engine_example.py,
    # I don't know why this is faster than simply calling llm.generate() with a list of prompts, but it is from my tests.
```

**Comment by itaybar** [comment]
> ach

When calling the API you cannot pass multi inputs anyways...

**Comment by itaybar** [comment]
@tom-doerr What do you think?

**Comment by tom-doerr** [comment]
@itaybar I don't have the ability to do reviews, but really like the feature. 
@simon-mo agreed in this issue (bottom) https://github.com/vllm-project/vllm/issues/1707  that that would be a good idea.

**Comment by simon-mo** [comment]
Thanks! This feature is indeed needed but we are actively evaluating Outlines as it seems to be higher performance for serving because it pre-compile all the logit masks. I'll continue benchmark and post result here.

**Comment by itaybar** [comment]
> Thanks! This feature is indeed needed but we are actively evaluating Outlines as it seems to be higher performance for serving because it pre-compile all the logit masks. I'll continue benchmark and post result here.

Any updates?

**Comment by simon-mo** [comment]
Outlines integration has been added. Now the general structure is in place. We welcome PR that adapt to lm-format-enforcer backend as well.

**Comment by simon-mo** [comment]
Please let me know once this PR is updated, or a new PR!

**Comment by itaybar** [comment]
There is similar feature already implemented "guided_json"

**Comment by hmellor** [comment]
@itaybar do you still plan to add support for `lm-format-enforcer`?

**Comment by itaybar** [comment]
> @itaybar do you still plan to add support for `lm-format-enforcer`?

For now i dont see reason to support lm forcer as well so closing this

**Pull request closed without merging**
