### PR TITLE
Use FP32 in RoPE initialization

### LINKED ISSUE #883: Code llama output gibberish code.
Test on this
[https://huggingface.co/docs/transformers/main/model_doc/code_llama](https://huggingface.co/docs/transformers/main/model_doc/code_llama)

Env:
1. model: `Code Llama 7b Instruct`
2. `vLLM` `main` branch 0.1.4 on [4b6f069](https://github.com/vllm-project/vllm/commit/4b6f069b6fbb4f2ef7d4c6a62140229be61c5dd3).
3. transformers: 4.33.0.dev0 (build from main branch on [960807f](https://github.com/huggingface/transformers/commit/960807f62e53676723ab8281019219864ef3db4d))
4. torch_dtype=torch.float16 (my gpu doesn't support bfloat16)

Generated text from `transformers`:
```Python
def remove_non_ascii(s: str) -> str:
    """ Remove non-ASCII characters from a string.

    Args:
        s (str): The string to remove non-ASCII characters from.

    Returns:
        str: The string with non-ASCII characters removed.
    """
    result = ""
    for c in s:
        if ord(c) < 128:
            result += c
    return result


def remove_non_ascii_and_spaces(s: str) -> str:
    """ Remove non-ASCII and space characters from a string.


    return result
```

Generated text from `vLLM`:
```python
<- Prompt ->:
def remove_non_ascii(s: str) -> str:
    """ <FILL_ME>
    return result

<- Answer ->:

   For comments

    """
        Remove non ascii inplace of special characters from a given string.""""
        non ascii => blank space, punctuation""""""codepointpython| nap string""" in Python"""test_safe
    u""
    
    among'".
   328
    <PDFutable       # tring control chars's to be "-"a"

    value.
// Dasailss
    ASCII characters so:""""
   
    X" 
    :5
	 Non-""
    <
```

Engine Log:
```
Received request cmpl-31a97cd2e50f4c18a9ac9e5fc4df4920: prompt: 'def remove_non_ascii(s: str) -> str:\n    """ <FILL_ME>\n    return result\n', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, temperature=1.0, top_p=1.0, top_k=-1, use_beam_search=False, stop=[], ignore_eos=False, max_tokens=128, logprobs=None), prompt token ids: [1, 822, 3349, 29918, 5464, 29918, 294, 18869, 29898, 29879, 29901, 851, 29897, 1599, 851, 29901, 13, 1678, 9995, 529, 3738, 2208, 29918, 2303, 29958, 13, 1678, 736, 1121, 13].
```

### PR DESCRIPTION
**Pull request by WoosukKwon**
Fixes #883

This PR uses FP32 for initializing the cos and sin cache in RoPE. This resolves the precision issues when using a large `base` like 1000000 with FP16.

NOTE: This change is aligned with the [RoPE definition](https://github.com/huggingface/transformers/blob/95b374952dc27d8511541d6f5a4e22c9ec11fb24/src/transformers/models/llama/modeling_llama.py#L99) in HuggingFace. However, as mentioned in #863, this may not align with the original definition of Meta's LLaMA. In the original implementation, FP32 is not only used for initialization, but is also used for calculating RoPE. The original implementation can be supported by slightly modifying the kernel.

### CODE REVIEW

**Comment by esmeetu** [comment]
Thanks! LGTM. Last implemement may change output everytime using same prompt. Generation of this version is stable for me.

**Comment by WoosukKwon** [comment]
@esmeetu Thanks for the confirmation!

**Review by zhuohan123 — APPROVED** [review]
LGTM! Thanks for the fix!

**Comment by fxmarty** [comment]
I am getting `RuntimeError: expected scalar type Half but found Float` when passing `cos_sin_cache`as fp32.

**Pull request merged**
