### PR TITLE
[BugFix] get_num_kv_heads

### PR DESCRIPTION
**Pull request by beginlner**

### CODE REVIEW

**Comment by WoosukKwon** [comment]
Hi @beginlner, thanks for submitting this PR. Could you describe the bug this PR fixes or attach any related issue?

**Comment by beginlner** [comment]
Hi @WoosukKwon, I'm working with a LLaMA-like model that has a single kv head. Without this adjustment, I'm unable to execute it using tensor parallelism.

**Comment by WoosukKwon** [comment]
@zhuohan123 A dumb question: how does this work with our weight loading logic to replicate the KV heads when `num_kv_heads` < `tensor_parallel_size`? Don't we have to fix this together with the weight loading?

**Comment by WoosukKwon** [comment]
Also, don't we have to apply this change to other if statements?

**Comment by WoosukKwon** [comment]
Hi @beginlner, we fixed this issue as a part of #1622. Please feel free to re-open this PR if the problem isn't solved.

**Pull request closed without merging**
