### PR TITLE
[Model][AMD] ROCm support for 256 head dims for Gemma

### LINKED ISSUE #3073: Serving for Google Gemma model failing on AMD MI 300X GPUs
The vLLM serving for the Google Gemma models is failing on AMD MI 300X GPUs  with the latest version of the vLLM (0.3.2) and ROCm 6.0.2 version.

Reproducing steps:

1. Clone the vllm repo and switch to [tag v0.3.2](https://github.com/vllm-project/vllm/tree/v0.3.2)
2. Build the Dockerfile.rocm dockerfile with instructions from [Option 3: Build from source with docker -Installation with ROCm](https://docs.vllm.ai/en/latest/getting_started/amd-installation.html#build-from-source-docker-rocm)

    build command:
    ```sh
    docker build  -f Dockerfile.rocm -t vllm-rocm:latest .
    ```

3. The vLLM serving command used:
    ```sh
    python3 -m vllm.entrypoints.openai.api_server --model google/gemma-7b --dtype bfloat16
    ```

The error below:
```sh
 File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.3.2+rocm603-py3.9-linux-x86_64.egg/vllm/model_executor/models/gemma.py", line 160, in forward
    attn_output = self.attn(q, k, v, k_cache, v_cache, input_metadata)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.3.2+rocm603-py3.9-linux-x86_64.egg/vllm/model_executor/layers/attention.py", line 196, in forward
    out = xops.memory_efficient_attention_forward(
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 244, in memory_efficient_attention_forward
    return _memory_efficient_attention_forward(
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 341, in _memory_efficient_attention_forward
    out, *_ = op.apply(inp, needs_gradient=False)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/xformers/ops/fmha/flash.py", line 458, in apply
    out, softmax_lse, rng_state = cls.OPERATOR(
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/xformers/ops/fmha/flash.py", line 130, in _flash_fwd
    ) = _C_flashattention.varlen_fwd(
RuntimeError: FlashAttention forward only supports head dimension at most 128
```

**Issues:**
1. This issue is for serving both Gemma 2B and 7B variants on the AMD MI 300X GPUs

### PR DESCRIPTION
**Pull request by jamestwhedbee**
Thanks to @jpvillam-amd's contributions on https://github.com/vllm-project/vllm/pull/3643, Gemma should have ROCm support

In my testing, I had to make these additional but trivial tweaks to actually use google/gemma-2b-it

This was tested on an MI100

FIX #3073 (*link existing issues this PR will resolve*)

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by WoosukKwon** [comment]
@jpvillam-amd Is head size 256 supported by the Triton kernel?

**Comment by shajrawi** [comment]
@WoosukKwon it is. We fully support this PR. Tested Triton with head sizes up to 256. In fact, this resolves https://github.com/vllm-project/vllm/issues/3073

**Review by shajrawi — APPROVED** [review]
Fixes #3073 - LGTM

**Review by WoosukKwon — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
