### PR TITLE
[doc] add back Python 3.8 ABI

### PR DESCRIPTION
**Pull request by youkaichao**
cc @russellb @DarkLight1337

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Could you elaborate on why we need to keep the same wheel name?

**Comment by youkaichao** [comment]
we need to keep a consistent url for people to use. there are already many people using that url to install the latest vllm wheel.

**Review by DarkLight1337 — APPROVED** [review]
I see, thanks for the explanation! Let's keep this for now then. Do you have plans to update the link in the future?

**Comment by youkaichao** [comment]
The ultimate solution would be https://github.com/vllm-project/vllm/issues/9831 , we have an index website for people to install vllm, so that people don't need to touch wheel names directly.

**Pull request merged**
