### PR TITLE
[Model][LoRA]LoRA support added for glm-4v

### PR DESCRIPTION
**Pull request by linitra24**
To facilitate Lora support, the language model and VL model have been separated. I tested it locally, but it seems I encountered the same issue as [this Comment](https://github.com/vllm-project/vllm/pull/9242#issuecomment-2407659939), where the results from vllm differ slightly from those of transformers. However, there is no issue with loading the Lora model, and the results appear to be reasonable.

### CODE REVIEW

**Review by jeejeelee — APPROVED** [review]
Thanks for your contribution, LGTM, please add related docs!
ping @DarkLight1337  Could you plz look at this PR,thanks

**Review by DarkLight1337 — APPROVED** [review]
Thanks for adding support!

**Comment by DarkLight1337** [comment]
Oh, I forgot again that we need to update the Supported Models page. Can you open another PR for that? Thanks.

**Comment by B-201** [comment]
> Oh, I forgot again that we need to update the Supported Models page. Can you open another PR for that? Thanks.

Sure, I will open another PR to update the docs.

**Pull request merged**
