### PR TITLE
[V1] `get_computed_blocks` avoids recompute

### PR DESCRIPTION
**Pull request by Abatom**
Use `self.req_to_blocks[request.request_id]` instead of recompute.

### CODE REVIEW

**Comment by comaniac** [comment]
I don't think this is correct. In this way you only share the blocks within a request.

**Comment by Abatom** [comment]
@comaniac Thank you, I will think about it again.

**Comment by comaniac** [comment]
What I'm saying is you change makes blocks cannot be shared "across" requests.

**Comment by Abatom** [comment]
I think the orange blocks in the picture are shared across requests.

**Comment by comaniac** [comment]
How do you hit cached blocks for a new request, which hasn't been added to req_to_blocks[request.request_id]?

**Comment by comaniac** [comment]
Ok I see what you meant. Yes this saves hash computation, but I'm afraid that this makes the code complicate. Did you have benchmark numbers to show the overhead is negligible so we have to introduce this optimization?

**Comment by Abatom** [comment]
Alright, I'll think about how to conduct benchmark testing.

**Comment by Abatom** [comment]
@comaniac I have written a comparison test, and this PR reduces the latency by 28.6%(28ns->20ns).

Test

```python
#test_prefix_caching.py
import time
from vllm.inputs import token_inputs
from vllm.sampling_params import SamplingParams
from vllm.v1.core.kv_cache_manager import KVCacheManager, Request

def make_request(request_id, prompt_token_ids):
    return Request(
        request_id=request_id,
        inputs=token_inputs(prompt_token_ids=prompt_token_ids),
        sampling_params=SamplingParams(max_tokens=17),
        eos_token_id=100,
        arrival_time=0,
        lora_request=None,
    )

def test_get_computed_blocks():
    block_size = 16
    manager = KVCacheManager(
        block_size=block_size,
        num_gpu_blocks=100,
        sliding_window=False,
        enable_caching=True,
        num_preallocate_tokens=0,
    )

    all_token_ids = [i for i in range(10) for _ in range(16)]
    req0 = make_request("0", all_token_ids)
    num_tokens = block_size * 10
    manager.allocate_slots(req0, num_tokens, [])

    req1 = make_request("1", all_token_ids)
    time1 = time.time()
    computed_blocks = manager.get_computed_blocks(req1)
    time2 = time.time()
    assert len(computed_blocks) == 10
    assert computed_blocks[0].block_id == 0

    req2 = make_request("2", all_token_ids[:block_size * 5])
    computed_blocks = manager.get_computed_blocks2(req2)
    assert len(computed_blocks) == 5
    assert computed_blocks[0].block_id == 0
    req2.append_output_token_ids(all_token_ids[block_size * 5:])

    time3 = time.time()
    computed_blocks = manager.get_computed_blocks2(req2)
    time4 = time.time()
    assert len(computed_blocks) == 10
    assert computed_blocks[0].block_id == 0

    print(f"time_old: {(time2 - time1) * 1000:0.6f}ms, time_new: {(time4 - time3) * 1000:0.6f}ms")

test_get_computed_blocks()
```

Output
```bash
# python3 tests/v1/core/test_prefix_caching.py 
time_old: 0.028133ms, time_new: 0.020504ms
# python3 tests/v1/core/test_prefix_caching.py 
time_old: 0.028610ms, time_new: 0.020504ms
# python3 tests/v1/core/test_prefix_caching.py 
time_old: 0.028849ms, time_new: 0.021458ms
# python3 tests/v1/core/test_prefix_caching.py 
time_old: 0.029564ms, time_new: 0.021219ms
# python3 tests/v1/core/test_prefix_caching.py 
time_old: 0.027895ms, time_new: 0.021219ms
# python3 tests/v1/core/test_prefix_caching.py 
time_old: 0.028133ms, time_new: 0.020981ms
# python3 tests/v1/core/test_prefix_caching.py 
time_old: 0.028133ms, time_new: 0.020981ms
# python3 tests/v1/core/test_prefix_caching.py 
time_old: 0.028610ms, time_new: 0.020981ms
# python3 tests/v1/core/test_prefix_caching.py 
time_old: 0.029564ms, time_new: 0.020742ms
# python3 tests/v1/core/test_prefix_caching.py 
time_old: 0.028372ms, time_new: 0.020504ms
```

**Comment by comaniac** [comment]
Can you use end to end benchmarking? Like the benchmarking scripts under benchmarks/benchmark_prefix_caching.py? Few ns seems not a big deal in the case of several ms latency.

**Comment by comaniac** [comment]
I'm not saying few nanoseconds is not important. What I meant was the code complexity your PR introduced doesn't worth for just a few nanosecond improvement, considering the readability and maintainability. In other words, I don't think the change you made in this PR can be easily understood by anyone who just comes and reads the code. 

If you could come up with a more clean solution (e.g. better refactoring, code comments, utility functions, system level mechanism, etc) that avoids redundant hash computation in general then I'll be happy to review and merge.

**Comment by Abatom** [comment]
@comaniac I apologize for the misunderstanding. I made another revision today, could you take a look at it? The latest version should be easier to understand.

**Comment by comaniac** [comment]
1. Please add comments to the code. The current code has too many implications.
2. Please add a unit test to make sure the behavior is expected.

**Comment by Abatom** [comment]
@comaniac After run benchmarks/benchmark_prefix_caching.py, I found that this PR seems to lack a corresponding real-world scenario, so I've decided to close it. Thank you for communicating with me.

**Pull request closed without merging**
