### PR TITLE
[Benchmark] Refactor sample_requests in benchmark_throughput

### PR DESCRIPTION
**Pull request by gty111**
Sample_requests in benchmark_throughput.py is time consuming, because it will tokenize all the prompts and completions by default. But we only use a part of them. So we can generate dataset on the fly instead of tokenizing everything.

```
time python3 benchmarks/benchmark_throughput.py --dataset ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 100
```

Before 
```
Throughput: 10.07 requests/s, 4755.11 tokens/s

real    1m0.832s
user    37m7.098s
sys     1m17.297s
```
After
```
Throughput: 11.45 requests/s, 5739.42 tokens/s

real    0m32.236s
user    0m24.767s
sys     0m17.651s
```

And the difference of throughput can be caused by the random selection.

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by ywang96 — COMMENTED** [review]
Thanks for the PR! This change makes sense to me and the time saved definitely adds up if you need to run this script repetitively. 

Could you just do a quick run and compare the total number of input & output tokens from default args (1000 prompts) before and after this PR? Ideally we would like to avoid any surprises (I don't think there will be any, but just making sure).

**Comment by gty111** [comment]
> Could you just do a quick run and compare the total number of input & output tokens from default args (1000 prompts) before and after this PR? Ideally we would like to avoid any surprises (I don't think there will be any, but just making sure).

Sure.

Before
```
# input tokens : 21445
# output toekns : 25780
```

After 
```
# input tokens : 24444
# output toekns : 25680
```

**Comment by rkooo567** [comment]
I am confused why it affects the e2e throughput? Seems like sampling requests happen before we measure the elapsed time?

**Comment by gty111** [comment]
> I am confused why it affects the e2e throughput? Seems like sampling requests happen before we measure the elapsed time?

Because the requests are randomly sampled, so the test requests before this PR are different from those after this PR (random.sample VS random.shuffle).

**Comment by ywang96** [comment]
> I am confused why it affects the e2e throughput? Seems like sampling requests happen before we measure the elapsed time?

@rkooo567 Request sampling does happen before we measure the elapsed time, but as @gty111 mentioned the set of requests is different now since the dataset is randomly shuffled first, then the first N prompts & expected outputs are tokenized to be counted (and passed if needed).

I think since input & output tokens do fall in the same ballpark, this QoL PR is worth merging especially for people who run this script a lot.

**Review by ywang96 — APPROVED** [review]

**Comment by WoosukKwon** [comment]
@ywang96 Can we merge this? Just wondering what blocks the merge.

**Comment by ywang96** [comment]
> @ywang96 Can we merge this? Just wondering what blocks the merge.

@WoosukKwon Yea of course (back then I didn't have the merge permission)

**Comment by WoosukKwon** [comment]
@ywang96 I see. 🤣 Please merge this if you think it's ready.

**Comment by ywang96** [comment]
@zhuohan123 Just FYI this will change the sampling slightly so don't be surprised to see the results change since you have been running this script a lot...

**Pull request merged**
