### PR TITLE
[Bugfix] Fix IndexError when output.logprobs is []

### LINKED ISSUE #8988: [Bug]: openai.serving_chat tries to call _create_chat_logprobs when the output.text is empty
### Your current environment

<details>
<summary>The output of `python send_llama3_128k.py`</summary>

```text
Your output of `python send_llama3_128k.py` here

b'data: {"id":"chat-9307f8bb26c94c7ba34890b5b2db2707","object":"chat.completion.chunk","created":1727754209,"model":"vllm-model","choices":[{"index":0,"delta":{"role":"assistant"},"logprobs":null,"finish_reason":null}]}'
Request aborted due to an exception: Response ended prematurely
```

</details>

### Model Input Dumps

server start command
```
# Version: vllm/vllm-openai:v0.6.2
# server:
docker run -tid --gpus \"device=0,1,2,3\" --shm-size 5g \
        -p 8081:8000 -v /mnt/data/models:/models \
        --ulimit nofile=65535:65535 \
        --name vllm-v0.6.2-llama3.1-70b-4gpus-128k \
        vllm/vllm-openai:v0.6.2 \
        --tensor-parallel-size=4 \
        --disable-log-requests \
        --model=/models/Meta-Llama-3.1-70B-Instruct \
        --enable-chunked-prefill \
        --served-model-name=vllm-model 

```

The input prompt is too long and github doesn't support .py so I had to override it to .txt
[send_llama3_128k.py.txt](https://github.com/user-attachments/files/17199893/send_llama3_128k.py.txt)

### 🐛 Describe the bug

When I try to run the above script `send_llama3_128k.py`, the server raises an error:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/starlette/responses.py", line 257, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.12/dist-packages/starlette/responses.py", line 253, in wrap
    await func()
  File "/usr/local/lib/python3.12/dist-packages/starlette/responses.py", line 230, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 555, in receive
    await self.message_event.wait()
  File "/usr/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fdb0f1c8950

  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.12/dist-packages/starlette/responses.py", line 253, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.12/dist-packages/starlette/responses.py", line 242, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/serving_chat.py", line 408, in chat_completion_stream_generator
    |     logprobs = self._create_chat_logprobs(
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/serving_chat.py", line 777, in _create_chat_logprobs
    |     step_top_logprobs = top_logprobs[i]
    |                         ~~~~~~~~~~~~^^^
    | IndexError: list index out of range
    +------------------------------------
```

Upon debugging, I think the issue here is that for the first few chunks, the output.text is empty, aka `''`, output.logprobs is [], essentially there is no logprobs available. 

I am uncertain why the output.text is empty, but here we should add a check, if the output.text is empty, we can skip create logprobs.
```
                    if output.text and request.logprobs and request.top_logprobs is not None:  # check output.text is not empty
                        assert output.logprobs is not None, (
                            "Did not output logprobs")
                        logprobs = self._create_chat_logprobs(
                            token_ids=output.token_ids,
                            top_logprobs=output.logprobs,
                            tokenizer=tokenizer,
                            num_output_top_logprobs=request.top_logprobs,
                        )
                    else:
                        logprobs = None
```

After adding the above line, the new output of `python send_llama3_128k.py` is:
```
b'data: {"id":"chat-4c7bcc2aac344da2b71fa7c07460e4c2","object":"chat.completion.chunk","created":1727761213,"model":"vllm-model","choices":[{"index":0,"delta":{"role":"assistant","content":""},"logprobs":null,"finish_reason":null}]}'
b'data: {"id":"chat-4c7bcc2aac344da2b71fa7c07460e4c2","object":"chat.completion.chunk","created":1727761213,"model":"vllm-model","choices":[{"index":0,"delta":{"content":""},"logprobs":null,"finish_reason":null}]}'
b'data: {"id":"chat-4c7bcc2aac344da2b71fa7c07460e4c2","object":"chat.completion.chunk","created":1727761213,"model":"vllm-model","choices":[{"index":0,"delta":{"content":""},"logprobs":null,"finish_reason":null}]}'
b'data: {"id":"chat-4c7bcc2aac344da2b71fa7c07460e4c2","object":"chat.completion.chunk","created":1727761213,"model":"vllm-model","choices":[{"index":0,"delta":{"content":""},"logprobs":null,"finish_reason":null}]}'
b'data: {"id":"chat-4c7bcc2aac344da2b71fa7c07460e4c2","object":"chat.completion.chunk","created":1727761213,"model":"vllm-model","choices":[{"index":0,"delta":{"content":""},"logprobs":null,"finish_reason":null}]}'
b'data: {"id":"chat-4c7bcc2aac344da2b71fa7c07460e4c2","object":"chat.completion.chunk","created":1727761213,"model":"vllm-model","choices":[{"index":0,"delta":{"content":""},"logprobs":null,"finish_reason":null}]}'
b'data: {"id":"chat-4c7bcc2aac344da2b71fa7c07460e4c2","object":"chat.completion.chunk","created":1727761213,"model":"vllm-model","choices":[{"index":0,"delta":{"content":""},"logprobs":null,"finish_reason":null}]}'
b'data: {"id":"chat-4c7bcc2aac344da2b71fa7c07460e4c2","object":"chat.completion.chunk","created":1727761213,"model":"vllm-model","choices":[{"index":0,"delta":{"content":""},"logprobs":null,"finish_reason":null}]}'
b'data: {"id":"chat-4c7bcc2aac344da2b71fa7c07460e4c2","object":"chat.completion.chunk","created":1727761213,"model":"vllm-model","choices":[{"index":0,"delta":{"content":"B"},"logprobs":{"content":[{"token":"B","logprob":-0.8135526776313782,"bytes":[66],"top_logprobs":[{"token":"B","logprob":-0.8135526776313782,"bytes":[66]},{"token":"The","logprob":-1.6885526180267334,"bytes":[84,104,101]},{"token":"This","logprob":-1.9385526180267334,"bytes":[84,104,105,115]},{"token":"**","logprob":-2.3135526180267334,"bytes":[42,42]},{"token":"Here","logprob":-2.8135526180267334,"bytes":[72,101,114,101]}]}]},"finish_reason":null}]}'
b'data: {"id":"chat-4c7bcc2aac344da2b71fa7c07460e4c2","object":"chat.completion.chunk","created":1727761213,"model":"vllm-model","choices":[{"index":0,"delta":{"content":"TS"},"logprobs":{"content":[{"token":"TS","logprob":-0.000028729025871143676,"bytes":[84,83],"top_logprobs":[{"token":"TS","logprob":-0.000028729025871143676,"bytes":[84,83]},{"token":"ts","logprob":-12.437528610229492,"bytes":[116,115]},{"token":" TS","logprob":-12.562528610229492,"bytes":[32,84,83]},{"token":" BTS","logprob":-13.062528610229492,"bytes":[32,66,84,83]},{"token":"IO","logprob":-13.437528610229492,"bytes":[73,79]}]}]},"finish_reason":null}]}'
``` 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by CatherineSue**
FILL IN THE PR DESCRIPTION HERE

FIX #8988 (*link existing issues this PR will resolve*)

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Adding or changing kernels</h3>
<p>Each custom kernel needs a schema and one or more implementations to be registered with PyTorch.</p>
<ul>
    <li>Make sure custom ops are registered following PyTorch guidelines: <a href="https://pytorch.org/tutorials/advanced/cpp_custom_ops.html#cpp-custom-ops-tutorial">Custom C++ and CUDA Operators</a> and <a href="https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU">The Custom Operators Manual</a></li>
    <li>Custom operations that return <code>Tensors</code> require meta-functions. Meta-functions should be implemented and registered in python so that dynamic dims can be handled automatically. See above documents for a description of meta-functions.</li>
    <li>Use <a href="https://pytorch.org/docs/stable/library.html#torch.library.opcheck"><code>torch.libary.opcheck()</code></a> to test the function registration and meta-function for any registered ops.  See <code>tests/kernels</code> for examples.</li>
    <li>When changing the C++ signature of an existing op, the schema must be updated to reflect the changes.</li>
    <li>If a new custom type is needed, see the following document: <a href="https://docs.google.com/document/d/18fBMPuOJ0fY5ZQ6YyrHUppw9FA332CpNtgB6SOIgyuA">Custom Class Support in PT2</a>.
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by njhill** [comment]
I agree with @ywang96 that this likely isn't the correct fix. I can take a look later today since I suspect this may have been introduced by https://github.com/vllm-project/vllm/pull/7381.

**Comment by CatherineSue** [comment]
Thanks @njhill . FYI we can reproduce this issue in v0.5.3.post1. The above PR is not merged in until v0.6.0.

**Comment by CatherineSue** [comment]
Close this PR. It is not the correct fix for the bug.

**Pull request closed without merging**
