### PR TITLE
[ci/build] Configure dependabot to update pip dependencies 

### PR DESCRIPTION
**Pull request by khluu**
Configure dependabot to update versions of the existing `requirements-*.txt` file and also generated `requirements-*.txt` file from running `pip-compile` on `*.in` file

### CODE REVIEW

**Comment by khluu** [comment]
GHA only runs what's on `main`...

**Comment by khluu** [comment]
Looks like our GHA setting doesn't allow this yet: `GitHub Actions is not permitted to create or approve pull requests. - `

**Comment by simon-mo** [comment]
why not dependabot?

**Review by russellb — APPROVED** [review]
The PR lgtm. I had some questions about some of the expected behavior, but I think it'll be easier just to see the PRs it generates and tweak from there.

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
