### PR TITLE
[Bugfix] FIx benchmark args for randomly sampled dataset

### PR DESCRIPTION
**Pull request by haichuan1221**
add benchmark testing; compared the existing test, new test has two advantages:
1. the input is random sampled with fixed length
2. the output is also fixed

### CODE REVIEW

**Comment by DarkLight1337** [comment]
To speed up the CI queue, I've cancelled the distributed tests for the latest CI run in this PR since they won't pass anyway until #5905 has been merged. Now that it has been merged, please merge `main` into your branch so that the CI can pass once again.

**Comment by haichuan1221** [comment]
> To speed up the CI queue, I've cancelled the distributed tests for the latest CI run in this PR since they won't pass anyway until #5905 has been merged. Now that it has been merged, please merge `main` into your branch so that the CI can pass once again.

Already done this

**Comment by ywang96** [comment]
@haichuan1221 Ah looks like this is for patching the previous PR I merged, sorry that I didn't catch the error.

**Review by ywang96 — APPROVED** [review]

**Comment by haichuan1221** [comment]
> @haichuan1221 Ah looks like this is for patching the previous PR I merged, sorry that I didn't catch the error.

I didn't catch the error either, sorry for the inconvenience

**Pull request merged**
