### PR TITLE
[Model] Consolidate ViTs attention implementation without mask

### PR DESCRIPTION
**Pull request by Isotr0py**
- This PR adds a `MultiHeadAttention` layer to consolidate existing duplicate attention forward implementation in ViTs.
- ViTs that use attention mask are not modified: Qwen2-VL, Pixtral, Mllama.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Unblocked multi-modal tests to see if all of those models still have the correct output.

**Review by DarkLight1337 — APPROVED** [review]
No new errors are introduced by this PR (compared to [this nightly build](https://github.com/vllm-project/vllm/commit/f877a7d12a0490705e6bea0987c89548d1a015ea)), so it should be fine.

**Comment by DarkLight1337** [comment]
Would be nice if you could fix the InternVL tests here as well though!

**Comment by Isotr0py** [comment]
The failing internvl tests should also be fixed in new commit now.

**Pull request merged**
