### PR TITLE
[Testing] Add test_config.py to CI

### PR DESCRIPTION
**Pull request by cadedaniel**
In review of https://github.com/vllm-project/vllm/pull/3373 I missed that the test wasn't added to CI.

Thanks to @a516072575 for [catching this](https://github.com/vllm-project/vllm/pull/3377#issuecomment-1998927548)!

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by richardliaw** [comment]
tests failing?

**Comment by simon-mo** [comment]
try? huggingface network issue again? 🙃

**Comment by richardliaw** [comment]
do you recommend retry by merging master?

**Comment by simon-mo** [comment]
Or clicking retry in buildkite/push empty commit.

**Review by carrey-feng — COMMENTED** [review]
LGTM

**Comment by cadedaniel** [comment]
fixed merge conflict;

**Pull request merged**
