### PR TITLE
[Core] Update `_earliest_arrival_time` calculation of the waiting seq_groups

### PR DESCRIPTION
**Pull request by Felix-Zhenghao**
When `Scheduler._schedule_prefills()` is called, we <a href="https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py#L628-L630">assume the waiting queue is sorted</a>. Therefore, we can directly <a href="https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py#L634C24-L634C41">access</a> the sequence group coming earliest through `waiting_queue[0]` in `Scheduler._schedule_prefills()`.

However, in the `Scheduler._passed_delay()` implementation, we access the `earliest_arrival_time` by <a href="https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py#L1116C13-L1117">iterating the whole `self.waiting`</a>, which is unnecessary if we assume `self.waiting` is sorted.

This PR changes the `Scheduler._passed_delay()` implementation to make sure that it can benefits from the "sorted" assumption as well.

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
Btw, this is always not 100% guaranteed upon preemption (because we always appendleft preempted requests). Do you think this can cause any issues in this case?

**Comment by rkooo567** [comment]
also lint failure!

**Comment by Felix-Zhenghao** [comment]
> Btw, this is always not 100% guaranteed upon preemption (because we always appendleft preempted requests). Do you think this can cause any issues in this case?
Thanks for pointing it out. I think that's not a problem.

Since in `_schedule_prefills()`, seq_groups are always scheduled to run in time order. Thus for those preempted seq_groups, their arrival time is always earlier than those seq_groups in `self.waiting` list. The only question left is whether the preempted list is sorted.

When `_schedule_running()`, the running seq_groups are sorted. Each preemption is done to the lowest-prority seq_group. Newly preempted seq_group is appended to the preempted list. Thus, the the preempted list is sorted as well.

As stated above, `self.waiting[0].metrics.arrival_time` can correctly get the earliest arrival time and will not be have problem even there exist preempted requests. @rkooo567 

> also lint failure!

`yapf` lint failure has been fixed.

**Comment by rkooo567** [comment]
Hmm actually, we may need to reverse this order to guarantee the ordering? https://github.com/vllm-project/vllm/blob/190bc838e17196733526896bf2861f8d05bd3f43/vllm/core/scheduler.py#L772

the reason is we append to preempted https://github.com/vllm-project/vllm/blob/190bc838e17196733526896bf2861f8d05bd3f43/vllm/core/scheduler.py#L433, meaning preempted list is sorted in the reverse order (from low -> high priority). And when we do appendleft, it means the lower priority will be in the top of the list?

**Pull request closed without merging**
