### PR TITLE
[Doc][CI/Build] Update docs and tests to use `vllm serve`

### PR DESCRIPTION
**Pull request by DarkLight1337**
Follow-up to #5090. As a sanity check, I have also updated the entrypoints tests to use the new CLI.

After this, we can update the Docker images and performance benchmarks to use the new CLI.

cc @EthanqX

### CODE REVIEW

**Comment by simon-mo** [comment]
I want to hold this off until the release. So people visiting the nightly docs can directly use the CLI

**Comment by simon-mo** [comment]
In the meantime, please feel free to start improving it!!!

**Review by mgoin — COMMENTED** [review]
Does `--model` still work or will it cause issues with `vllm serve`? I'm curious if it is sufficient to replace `python -m vllm.entrypoints.openai.api_server` with `vllm serve` or if it specifically replaces `python -m vllm.entrypoints.openai.api_server --model`

**Comment by DarkLight1337** [comment]
> Does `--model` still work or will it cause issues with `vllm serve`?

`model_tag` is a required positional arg in `vllm serve` so you have to pass it like vllm serve <model_tag>`, regardless of whether `--model` is passed.

**Review by mgoin — APPROVED** [review]
Thanks for the clarity, this is a nice PR to update usage LGTM!

**Comment by DarkLight1337** [comment]
@simon-mo since `v0.5.2` has been released, can we merge this?

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
