### PR TITLE
Added support for inference of chatglm2 on multiple GPUs, which inherits from #649

### PR DESCRIPTION
**Pull request by David-webb**
Updated the load_weights function following the principles of tensor parallelism for #649. However, due to limitations in GQA（group_nums=2）,inference with more than 2 GPUs is not supported. Even though more GPUs (provided they are divisible by num_attention_heads) can be utilized, the results are incorrect. and i tested it, the inference results with 2 GPUs are consistent with single GPU inference.

### CODE REVIEW

**Comment by David-webb** [comment]
update my api_server.py



发自我的iPhone


------------------ Original ------------------
From: Pastel！ ***@***.***&gt;
Date: Thu,Sep 21,2023 1:20 PM
To: vllm-project/vllm ***@***.***&gt;
Cc: DAVID WEBB ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [vllm-project/vllm] Added support for inference of chatglm2 onmultiple GPUs, which inherits from #649 (PR #1109)





  
Updated the load_weights function following the principles of tensor parallelism for #649. However, due to limitations in GQA（group_nums=2）,inference with more than 2 GPUs is not supported. Even though more GPUs (provided they are divisible by num_attention_heads) can be utilized, the results are incorrect. and i tested it, the inference results with 2 GPUs are consistent with single GPU inference.
  
Thanks for your great work and I've tried with your new PR! The single GPU inference result matches.
 But when I launched the original vllm.entrypoints.api_server with tp=2, following Error message emerges.
 "You are using a model of type chatglm to instantiate a model of type . This is not supported for all configurations of models and can yield errors." Is there any difference between your commited api_server and the original one?

**Comment by David-webb** [comment]
> Updated the load_weights function following the principles of tensor parallelism for #649. However, due to limitations in GQA（group_nums=2）,inference with more than 2 GPUs is not supported. Even though more GPUs (provided they are divisible by num_attention_heads) can be utilized, the results are incorrect. and i tested it, the inference results with 2 GPUs are consistent with single GPU inference.

**Comment by David-webb** [comment]
I add a README-glm.md which shows my work scripts.

**Comment by David-webb** [comment]
> > I add a README-glm.md which shows my work scripts.
> 
> Thanks for your dedicated work and I've tried with your PR! One thing confused me is that the vLLM inference result is subtle, nearly first half of the generated tokens are aligned with the hugging face output while the second half mismatch. You can reproduce this issue by setting prompt = '请给出一个字数100字左右的A股投资方案？' and SamplingParams(temperature=0.6, top_p=0.9, max_tokens=30, top_k=1)
> 
> vLLM: 在当前A股市场环境下，投资策略需要注重风险控制和长期价值。以下是一个注重风险控制和长期价值的A股投资方案:
> 
>     1. 选择高质量的公司：选择具有稳健业绩、良好前景和高增长潜力的高质量公司，避免过度追逐热门概念和短期涨幅。
> 
>     2. 分散投资风险：不要把所有鸡蛋放在同一个篮子里，通过投资多个行业和多个公司来分散投资风险，降低单一投资的风险。
> 
>     3. 长期投资：长期投资是A股市场的重要策略，选择具有稳健成长和高增长潜力的公司，适当延迟短期收益，注重长期价值。
> 
>     4. 关注社会责任：关注公司的社会责任和环保政策，选择具有良好社会责任和环保意识的上市公司。
> 
>     5. 定期检查和调整：定期检查和调整投资策略，根据市场环境变化和公司业绩变化进行修正，保持投资组合的稳定和可持续发展。
>        最后，需要强调的是，投资有风险，需要谨慎对待。在投资前，请充分了解公司的基本面和风险特点，并做好风险评估和控制。
> 
> 
> HF: 在当前A股市场环境下，投资策略需要注重风险控制和长期价值。以下是一个注重风险控制和长期价值的A股投资方案:
> 
>     1. 选择高质量的公司：选择具有稳健业绩、良好前景和高增长潜力的高质量公司，避免过度追逐热门概念和短期涨幅。
> 
>     2. 分散投资风险：不要把所有鸡蛋放在同一个篮子里，通过投资多个行业和多个公司，降低投资风险。
> 
>     3. 长期投资：注重长期价值，寻找那些能够稳定成长的优质公司，适当长期持有，不要被短期波动所干扰。
> 
>     4. 定期调整：定期审视投资组合，根据市场环境和个人需求进行调整，保持投资组合的稳定和健康。
> 
>     5. 关注社会责任：关注公司的社会责任和公益活动，选择那些具有良好社会责任心的公司，为社会做出贡献。
>        这个投资方案注重风险控制和长期价值，通过选择高质量的公司、分散投资风险、长期投资、定期调整以及关注社会责任等方式，为投资者创造一个良好的投资环境，实现稳健成长。

Turn down the temperature if you want stable answers after multiple attempts of the same question. By the way, the max_tokens=30 is too small; the inference will stop when it reaches the EOS or the stop key you've specified.

**Comment by David-webb** [comment]
> > > > I add a README-glm.md which shows my work scripts.
> > > 
> > > 
> > > Thanks for your dedicated work and I've tried with your PR! One thing confused me is that the vLLM inference result is subtle, nearly first half of the generated tokens are aligned with the hugging face output while the second half mismatch. You can reproduce this issue by setting prompt = '请给出一个字数100字左右的A股投资方案？' and SamplingParams(temperature=0.6, top_p=0.9, max_tokens=30, top_k=1)
> > > vLLM: 在当前A股市场环境下，投资策略需要注重风险控制和长期价值。以下是一个注重风险控制和长期价值的A股投资方案:
> > > ```
> > > 1. 选择高质量的公司：选择具有稳健业绩、良好前景和高增长潜力的高质量公司，避免过度追逐热门概念和短期涨幅。
> > > 
> > > 2. 分散投资风险：不要把所有鸡蛋放在同一个篮子里，通过投资多个行业和多个公司来分散投资风险，降低单一投资的风险。
> > > 
> > > 3. 长期投资：长期投资是A股市场的重要策略，选择具有稳健成长和高增长潜力的公司，适当延迟短期收益，注重长期价值。
> > > 
> > > 4. 关注社会责任：关注公司的社会责任和环保政策，选择具有良好社会责任和环保意识的上市公司。
> > > 
> > > 5. 定期检查和调整：定期检查和调整投资策略，根据市场环境变化和公司业绩变化进行修正，保持投资组合的稳定和可持续发展。
> > >    最后，需要强调的是，投资有风险，需要谨慎对待。在投资前，请充分了解公司的基本面和风险特点，并做好风险评估和控制。
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > HF: 在当前A股市场环境下，投资策略需要注重风险控制和长期价值。以下是一个注重风险控制和长期价值的A股投资方案:
> > > ```
> > > 1. 选择高质量的公司：选择具有稳健业绩、良好前景和高增长潜力的高质量公司，避免过度追逐热门概念和短期涨幅。
> > > 
> > > 2. 分散投资风险：不要把所有鸡蛋放在同一个篮子里，通过投资多个行业和多个公司，降低投资风险。
> > > 
> > > 3. 长期投资：注重长期价值，寻找那些能够稳定成长的优质公司，适当长期持有，不要被短期波动所干扰。
> > > 
> > > 4. 定期调整：定期审视投资组合，根据市场环境和个人需求进行调整，保持投资组合的稳定和健康。
> > > 
> > > 5. 关注社会责任：关注公司的社会责任和公益活动，选择那些具有良好社会责任心的公司，为社会做出贡献。
> > >    这个投资方案注重风险控制和长期价值，通过选择高质量的公司、分散投资风险、长期投资、定期调整以及关注社会责任等方式，为投资者创造一个良好的投资环境，实现稳健成长。
> > > ```
> > 
> > 
> > Turn down the temperature（how about 0.1）if you want stable answers after multiple attempts of the same question. By the way, the max_tokens=30 is too small; the inference will stop when it reaches the EOS or the stop key you've specified.
> 
>     1. Sorry, I made a mistake, max_tokens is 1024 here not 30. And even Greedy Search results mismatch, which means setting top_p=1, top_k=-1, temperature=0. By the way, simillar inconsistency occurs in [Add support for chatglm2 #649](https://github.com/vllm-project/vllm/pull/649).
> 
>     2. Here is more information tested on single and 2x 3090. On a single 3090 it is nearly 38 tokens/s while with tp=2 it is only 25 tokens/s. What do you think of this disparity?
> 
>     3. To illustrate the difference between vLLM and HF, suppose max_tokens=1024, and generating 300 Chinese characters at all. It keeps same at the beginning 100 characters while differs from 101 to 300 which sounds a little wizard. Moreover, if you do not set the seed option in HF, answers from HF may vary and vLLM's mismatched result is among HF's. PagedAttentionwithRoPE or 8-multiplier alignment may be the key and it is worth digging into this problem.


> > > > I add a README-glm.md which shows my work scripts.
> > > 
> > > 
> > > Thanks for your dedicated work and I've tried with your PR! One thing confused me is that the vLLM inference result is subtle, nearly first half of the generated tokens are aligned with the hugging face output while the second half mismatch. You can reproduce this issue by setting prompt = '请给出一个字数100字左右的A股投资方案？' and SamplingParams(temperature=0.6, top_p=0.9, max_tokens=30, top_k=1)
> > > vLLM: 在当前A股市场环境下，投资策略需要注重风险控制和长期价值。以下是一个注重风险控制和长期价值的A股投资方案:
> > > ```
> > > 1. 选择高质量的公司：选择具有稳健业绩、良好前景和高增长潜力的高质量公司，避免过度追逐热门概念和短期涨幅。
> > > 
> > > 2. 分散投资风险：不要把所有鸡蛋放在同一个篮子里，通过投资多个行业和多个公司来分散投资风险，降低单一投资的风险。
> > > 
> > > 3. 长期投资：长期投资是A股市场的重要策略，选择具有稳健成长和高增长潜力的公司，适当延迟短期收益，注重长期价值。
> > > 
> > > 4. 关注社会责任：关注公司的社会责任和环保政策，选择具有良好社会责任和环保意识的上市公司。
> > > 
> > > 5. 定期检查和调整：定期检查和调整投资策略，根据市场环境变化和公司业绩变化进行修正，保持投资组合的稳定和可持续发展。
> > >    最后，需要强调的是，投资有风险，需要谨慎对待。在投资前，请充分了解公司的基本面和风险特点，并做好风险评估和控制。
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > HF: 在当前A股市场环境下，投资策略需要注重风险控制和长期价值。以下是一个注重风险控制和长期价值的A股投资方案:
> > > ```
> > > 1. 选择高质量的公司：选择具有稳健业绩、良好前景和高增长潜力的高质量公司，避免过度追逐热门概念和短期涨幅。
> > > 
> > > 2. 分散投资风险：不要把所有鸡蛋放在同一个篮子里，通过投资多个行业和多个公司，降低投资风险。
> > > 
> > > 3. 长期投资：注重长期价值，寻找那些能够稳定成长的优质公司，适当长期持有，不要被短期波动所干扰。
> > > 
> > > 4. 定期调整：定期审视投资组合，根据市场环境和个人需求进行调整，保持投资组合的稳定和健康。
> > > 
> > > 5. 关注社会责任：关注公司的社会责任和公益活动，选择那些具有良好社会责任心的公司，为社会做出贡献。
> > >    这个投资方案注重风险控制和长期价值，通过选择高质量的公司、分散投资风险、长期投资、定期调整以及关注社会责任等方式，为投资者创造一个良好的投资环境，实现稳健成长。
> > > ```
> > 
> > 
> > Turn down the temperature（how about 0.1）if you want stable answers after multiple attempts of the same question. By the way, the max_tokens=30 is too small; the inference will stop when it reaches the EOS or the stop key you've specified.
> 
>     1. Sorry, I made a mistake, max_tokens is 1024 here not 30. And even Greedy Search results mismatch, which means setting top_p=1, top_k=-1, temperature=0. By the way, simillar inconsistency occurs in [Add support for chatglm2 #649](https://github.com/vllm-project/vllm/pull/649).
> 
>     2. Here is more information tested on single and 2x 3090. On a single 3090 it is nearly 38 tokens/s while with tp=2 it is only 25 tokens/s. What do you think of this disparity?
> 
>     3. To illustrate the difference between vLLM and HF, suppose max_tokens=1024, and generating 300 Chinese characters at all. It keeps same at the beginning 100 characters while differs from 101 to 300 which sounds a little wizard. Moreover, if you do not set the seed option in HF, answers from HF may vary and vLLM's mismatched result is among HF's. PagedAttentionwithRoPE or 8-multiplier alignment may be the key and it is worth digging into this problem.



Regarding the first and third question, I've noticed that the behavior observed is not exclusive to ChatGLM on vLLM; Llama also exhibits similar behavior. Additionally, in the case of ChatGLM2, the answers for both tp=2 and tp=1 are identical, suggesting that this issue might not be the root cause. The inconsistency in #649 is entirely different; it appears to have attempted to avoid using "repeat_interleave" outside of PageAttentionRoPE, resulting in a perplexing response.

Regarding the second question, the adoption of tensor parallelism can indeed lead to increased communication costs, especially as the degree of tensor parallelism (tp) grows. This heightened cost arises because the all-reduce operations for self-attention and MLP share the same shape across each GPU, potentially causing latency to be slower than in previous configurations. On a related note, Page-Attention is a technology designed to enhance throughput. Therefore, you might consider using load testing tools that support concurrent request volumes, such as Locust. In my tests, I've observed that with dual GPUs, we were able to achieve a minimum throughput of 306 new tokens per second.

**Comment by David-webb** [comment]
> > > > > > I add a README-glm.md which shows my work scripts.
> > > > > 
> > > > > 
> > > > > Thanks for your dedicated work and I've tried with your PR! One thing confused me is that the vLLM inference result is subtle, nearly first half of the generated tokens are aligned with the hugging face output while the second half mismatch. You can reproduce this issue by setting prompt = '请给出一个字数100字左右的A股投资方案？' and SamplingParams(temperature=0.6, top_p=0.9, max_tokens=30, top_k=1)
> > > > > vLLM: 在当前A股市场环境下，投资策略需要注重风险控制和长期价值。以下是一个注重风险控制和长期价值的A股投资方案:
> > > > > ```
> > > > > 1. 选择高质量的公司：选择具有稳健业绩、良好前景和高增长潜力的高质量公司，避免过度追逐热门概念和短期涨幅。
> > > > > 
> > > > > 2. 分散投资风险：不要把所有鸡蛋放在同一个篮子里，通过投资多个行业和多个公司来分散投资风险，降低单一投资的风险。
> > > > > 
> > > > > 3. 长期投资：长期投资是A股市场的重要策略，选择具有稳健成长和高增长潜力的公司，适当延迟短期收益，注重长期价值。
> > > > > 
> > > > > 4. 关注社会责任：关注公司的社会责任和环保政策，选择具有良好社会责任和环保意识的上市公司。
> > > > > 
> > > > > 5. 定期检查和调整：定期检查和调整投资策略，根据市场环境变化和公司业绩变化进行修正，保持投资组合的稳定和可持续发展。
> > > > >    最后，需要强调的是，投资有风险，需要谨慎对待。在投资前，请充分了解公司的基本面和风险特点，并做好风险评估和控制。
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > HF: 在当前A股市场环境下，投资策略需要注重风险控制和长期价值。以下是一个注重风险控制和长期价值的A股投资方案:
> > > > > ```
> > > > > 1. 选择高质量的公司：选择具有稳健业绩、良好前景和高增长潜力的高质量公司，避免过度追逐热门概念和短期涨幅。
> > > > > 
> > > > > 2. 分散投资风险：不要把所有鸡蛋放在同一个篮子里，通过投资多个行业和多个公司，降低投资风险。
> > > > > 
> > > > > 3. 长期投资：注重长期价值，寻找那些能够稳定成长的优质公司，适当长期持有，不要被短期波动所干扰。
> > > > > 
> > > > > 4. 定期调整：定期审视投资组合，根据市场环境和个人需求进行调整，保持投资组合的稳定和健康。
> > > > > 
> > > > > 5. 关注社会责任：关注公司的社会责任和公益活动，选择那些具有良好社会责任心的公司，为社会做出贡献。
> > > > >    这个投资方案注重风险控制和长期价值，通过选择高质量的公司、分散投资风险、长期投资、定期调整以及关注社会责任等方式，为投资者创造一个良好的投资环境，实现稳健成长。
> > > > > ```
> > > > 
> > > > 
> > > > Turn down the temperature（how about 0.1）if you want stable answers after multiple attempts of the same question. By the way, the max_tokens=30 is too small; the inference will stop when it reaches the EOS or the stop key you've specified.
> > > 
> > > 
> > > ```
> > > 1. Sorry, I made a mistake, max_tokens is 1024 here not 30. And even Greedy Search results mismatch, which means setting top_p=1, top_k=-1, temperature=0. By the way, simillar inconsistency occurs in [Add support for chatglm2 #649](https://github.com/vllm-project/vllm/pull/649).
> > > 
> > > 2. Here is more information tested on single and 2x 3090. On a single 3090 it is nearly 38 tokens/s while with tp=2 it is only 25 tokens/s. What do you think of this disparity?
> > > 
> > > 3. To illustrate the difference between vLLM and HF, suppose max_tokens=1024, and generating 300 Chinese characters at all. It keeps same at the beginning 100 characters while differs from 101 to 300 which sounds a little wizard. Moreover, if you do not set the seed option in HF, answers from HF may vary and vLLM's mismatched result is among HF's. PagedAttentionwithRoPE or 8-multiplier alignment may be the key and it is worth digging into this problem.
> > > ```
> > 
> > 
> > > > > > I add a README-glm.md which shows my work scripts.
> > > > > 
> > > > > 
> > > > > Thanks for your dedicated work and I've tried with your PR! One thing confused me is that the vLLM inference result is subtle, nearly first half of the generated tokens are aligned with the hugging face output while the second half mismatch. You can reproduce this issue by setting prompt = '请给出一个字数100字左右的A股投资方案？' and SamplingParams(temperature=0.6, top_p=0.9, max_tokens=30, top_k=1)
> > > > > vLLM: 在当前A股市场环境下，投资策略需要注重风险控制和长期价值。以下是一个注重风险控制和长期价值的A股投资方案:
> > > > > ```
> > > > > 1. 选择高质量的公司：选择具有稳健业绩、良好前景和高增长潜力的高质量公司，避免过度追逐热门概念和短期涨幅。
> > > > > 
> > > > > 2. 分散投资风险：不要把所有鸡蛋放在同一个篮子里，通过投资多个行业和多个公司来分散投资风险，降低单一投资的风险。
> > > > > 
> > > > > 3. 长期投资：长期投资是A股市场的重要策略，选择具有稳健成长和高增长潜力的公司，适当延迟短期收益，注重长期价值。
> > > > > 
> > > > > 4. 关注社会责任：关注公司的社会责任和环保政策，选择具有良好社会责任和环保意识的上市公司。
> > > > > 
> > > > > 5. 定期检查和调整：定期检查和调整投资策略，根据市场环境变化和公司业绩变化进行修正，保持投资组合的稳定和可持续发展。
> > > > >    最后，需要强调的是，投资有风险，需要谨慎对待。在投资前，请充分了解公司的基本面和风险特点，并做好风险评估和控制。
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > HF: 在当前A股市场环境下，投资策略需要注重风险控制和长期价值。以下是一个注重风险控制和长期价值的A股投资方案:
> > > > > ```
> > > > > 1. 选择高质量的公司：选择具有稳健业绩、良好前景和高增长潜力的高质量公司，避免过度追逐热门概念和短期涨幅。
> > > > > 
> > > > > 2. 分散投资风险：不要把所有鸡蛋放在同一个篮子里，通过投资多个行业和多个公司，降低投资风险。
> > > > > 
> > > > > 3. 长期投资：注重长期价值，寻找那些能够稳定成长的优质公司，适当长期持有，不要被短期波动所干扰。
> > > > > 
> > > > > 4. 定期调整：定期审视投资组合，根据市场环境和个人需求进行调整，保持投资组合的稳定和健康。
> > > > > 
> > > > > 5. 关注社会责任：关注公司的社会责任和公益活动，选择那些具有良好社会责任心的公司，为社会做出贡献。
> > > > >    这个投资方案注重风险控制和长期价值，通过选择高质量的公司、分散投资风险、长期投资、定期调整以及关注社会责任等方式，为投资者创造一个良好的投资环境，实现稳健成长。
> > > > > ```
> > > > 
> > > > 
> > > > Turn down the temperature（how about 0.1）if you want stable answers after multiple attempts of the same question. By the way, the max_tokens=30 is too small; the inference will stop when it reaches the EOS or the stop key you've specified.
> > > 
> > > 
> > > ```
> > > 1. Sorry, I made a mistake, max_tokens is 1024 here not 30. And even Greedy Search results mismatch, which means setting top_p=1, top_k=-1, temperature=0. By the way, simillar inconsistency occurs in [Add support for chatglm2 #649](https://github.com/vllm-project/vllm/pull/649).
> > > 
> > > 2. Here is more information tested on single and 2x 3090. On a single 3090 it is nearly 38 tokens/s while with tp=2 it is only 25 tokens/s. What do you think of this disparity?
> > > 
> > > 3. To illustrate the difference between vLLM and HF, suppose max_tokens=1024, and generating 300 Chinese characters at all. It keeps same at the beginning 100 characters while differs from 101 to 300 which sounds a little wizard. Moreover, if you do not set the seed option in HF, answers from HF may vary and vLLM's mismatched result is among HF's. PagedAttentionwithRoPE or 8-multiplier alignment may be the key and it is worth digging into this problem.
> > > ```
> > 
> > 
> > Regarding the first and third question, I've noticed that the behavior observed is not exclusive to ChatGLM on vLLM; Llama also exhibits similar behavior. Additionally, in the case of ChatGLM2, the answers for both tp=2 and tp=1 are identical, suggesting that this issue might not be the root cause. The inconsistency in #649 is entirely different; it appears to have attempted to avoid using "repeat_interleave" outside of PageAttentionRoPE, resulting in a perplexing response.
> > Regarding the second question, the adoption of tensor parallelism can indeed lead to increased communication costs, especially as the degree of tensor parallelism (tp) grows. This heightened cost arises because the all-reduce operations for self-attention and MLP share the same shape across each GPU, potentially causing latency to be slower than in previous configurations. On a related note, Page-Attention is a technology designed to enhance throughput. Therefore, you might consider using load testing tools that support concurrent request volumes, such as Locust. In my tests, I've observed that with dual GPUs, we were able to achieve a minimum throughput of 306 new tokens per second.
> 
> Thanks for your detailed explanation and the second question is mainly based on the experience of llama2-7b, which shows that on dual GPUs, the 1-batch inference speed did not increase much and did not decrease as well.

Yes, when high concurrency is encountered, the power of vLLM becomes evident. I haven't specifically tested the latency of single inference, but what I do know is that vLLM version 0.1.5 and above utilizes xformers' flash-attention to accelerate the process.

**Comment by David-webb** [comment]
> > Yes, the power of vLLM becomes evident when there is high concurrency. I haven't specifically tested the latency of single inferences, but what I do know is that vLLM version 0.1.5 and above leverages xformers' flash-attention for acceleration. Additionally, in tensor parallelism, using multiple GPUs doesn't necessarily increase throughput and inference speed due to communication reasons. It depends on hardware conditions. In my experience, with 2 * 3090 GPUs on Llama2-7b, 2 GPUs achieve the best QPS for the given 1.4k prompts. Increasing parallelism beyond that can lead to a decline in performance, and it's not as linear as running multiple vLLM services.
> 
> Is there any space to further accelerate the inference speed, I mean writing some CUDA kernels instead of pure Python?

You can try out fastllm or exllama

**Comment by zhuohan123** [comment]
Again, thank you for your contribution! We merged https://github.com/vllm-project/vllm/pull/1261 and the current main branch supports ChatGLM now. Let us know if the main branch does not look good and feel free to propose any changes!

**Pull request closed without merging**
