### PR TITLE
[LoRA][Kernel] Remove the unused libentry module

### PR DESCRIPTION
**Pull request by jeejeelee**
vLLM's current Triton version is `3.1.0`, it's safe to remove the `libentry` module. See: https://github.com/vllm-project/vllm/pull/5036#issuecomment-2243396245
ping @DarkLight1337

### CODE REVIEW

**Comment by DarkLight1337** [comment]
The triton version doesn't appear to be specified for all vLLM backends.

**Comment by jeejeelee** [comment]
> The triton version doesn't appear to be specified for all vLLM backends.

The current triton in vLLM comes from PyTorch, so it might be safe to remove it.

**Comment by DarkLight1337** [comment]
Can you point to where I can find that information?

**Comment by jeejeelee** [comment]
> Can you point to where I can find that information?

See: https://github.com/vllm-project/vllm/pull/4061

**Comment by DarkLight1337** [comment]
I see, thanks. In that case let's merge this.

**Review by DarkLight1337 — APPROVED** [review]

**Comment by jeejeelee** [comment]
> I see, thanks. In that case let's merge this.

Thanks. 
On one hand, libentry indeed doesn't have much use for the current vllm anymore. 
Another reason is that libentry has a potential risk that prevents triton kernels from completing multi-GPU testing, which means we cannot verify whether issues like #9794 can be resolved.

**Pull request merged**
