### PR TITLE
Add repetition_penalty aligned with huggingface(porting pr #886 to latest branch)

### PR DESCRIPTION
**Pull request by yanxiyue**
thanks to @Abraham-Xu  for his great work on pr #886. Since I've been waiting for #886 to be merged and it hasn't been, I've gone ahead and merged it into my fork.

### CODE REVIEW

**Comment by BaiMoHan** [comment]
Great job! One more thing, the api-server should add those parameters

**Comment by bohea** [comment]
I tested this branch
but output of vllm and HF transformers is still  inconsistent

**Comment by yanxiyue** [comment]
> I tested this branch but output of vllm and HF transformers is still inconsistent

I have test Baichuan 13b and found that the differences in the sampling process have been largely eliminated. 
Could you please provide more details about the model and the request parameters that led to differences on your end?

It's worth noting that the floating-point calculation order in the forward propagation phase may vary between different inference frameworks, which can result in cumulative errors, especially for long sequences. Unfortunately, a satisfactory solution for this difference has not been found yet.

However, the most important thing is to assess whether the generated results are usable, rather than pursuing complete consistency.

**Comment by bohea** [comment]
> > I tested this branch but output of vllm and HF transformers is still inconsistent
> 
> I have test Baichuan 13b and found that the differences in the sampling process have been largely eliminated. Could you please provide more details about the model and the request parameters that led to differences on your end?
> 
> It's worth noting that the floating-point calculation order in the forward propagation phase may vary between different inference frameworks, which can result in cumulative errors, especially for long sequences. Unfortunately, a satisfactory solution for this difference has not been found yet.
> 
> However, the most important thing is to assess whether the generated results are usable, rather than pursuing complete consistency.

I understand and agree not to pursue complete consystency.

but I tested on codellama-13b-hf

codellama was trained by infilling training, so it can fill code in the middle

e.g.  input propmt
```
def return_sum(a, b):
    <FILL_ME>      
    return c
```

by giving above input propmt, output of hf transformers is always (temperature from 0 - 1.0)
```
c = a + b
```
which is a good demonstration of infilling ability 

but output of vllm is not 

when temperature = 0.1 - 1.0

one output sample is 
```
c = a + b
    return c

c = a + b
    
    return c

def return_sum_with_print(a, b):
    c = a + b
    print(c)
```

when temperature = 0, output is :
```
c = a + b
```

we found that when temperature != 0, output of vllm will ignore infilling

**Comment by zhuohan123** [comment]
I merged #1424 since that code looks simpler. But again, thank you for your contribution! Let me know if there is any issue with #1424.

**Comment by zwj536** [comment]
I'm getting inconsistent results between HF and vllm with llama-7b @yanxiyue 
```
## hf
import torch
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM
)

MODEL_NAME = "huggyllama/llama-7b"
#MODEL_NAME = "huggyllama/llama-13b"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, torch_dtype=torch.float16).cuda()  

prompt = [
    "Hello, what is apple?  ",
]
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.cuda()
generated_ids = model.generate(
    input_ids, 
    do_sample=False, 
    repetition_penalty=1.2, 
    max_new_tokens=64,
)

texts = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
""" OUTPUT
Hello, what is orange?   \nHello, what are you doing here?\n— _The Wizard of Oz_ , L. Frank Baum (1900)\n#  **What Is a Computer?**\nA computer is an electronic device that can store and process information in the'
"""

## vllm
from vllm import LLM, SamplingParams

# Sample prompts.
prompts = [
    "Hello, what is apple?  ",
]
sampling_params = SamplingParams(
    temperature=0,
    max_tokens=64, 
    frequency_penalty=1.2
)

MODEL_NAME = "huggyllama/llama-7b"
#MODEL_NAME = "huggyllama/llama-13b"

llm = LLM(
    model=MODEL_NAME,
    trust_remote_code=True,
)
outputs = llm.generate(prompts, sampling_params)
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

""" OUTPUT
Hello, what is apple?  \nHello, what is apple?  \nHello, what is apple?  \nHello, what is apple?  \nWhat\'s that you say?  What\'s that you say?"  And so on. The child will repeat the question until he gets an answer
"""
```

**Pull request closed without merging**
