### PR TITLE
Avoid connection error when vLLM is inside a container without internet access

### PR DESCRIPTION
**Pull request by payoto**
I observed an `OSError` when trying to run vLLM within a container without internet access. We shouldn't remove the attempt to connect as it might affect the IP that is returned in `getsockname`.

### CODE REVIEW

**Comment by hmellor** [comment]
Closes #3170

**Comment by hmellor** [comment]
@simon-mo I think this is ready for review now

**Comment by simon-mo** [comment]
Please reconcile with the merged PR https://github.com/vllm-project/vllm/pull/3176

**Comment by hmellor** [comment]
@simon-mo the error thrown by the issue in #3176 is a subclass if `OSError`, so it is handled by the logic implemented in this PR if the DNS is not reachable. So I'll resolve the conflict by keeping my changes.

**Comment by hmellor** [comment]
I am already using this PR in an internet denied environment, so can confirm that it works for that use case.

**Comment by gqjia** [comment]
nice job!

**Comment by simon-mo** [comment]
Sorry I merged #3419. If this still applies please fix the conflict and I'll merge.

**Comment by hmellor** [comment]
It looks like the functionality of this PR is entirely contained within the combination of #3176 and #3419.

I'd say it's no longer needed.

**Pull request closed without merging**
