### PR TITLE
[torch.compile] use depyf to dump torch.compile internals

### PR DESCRIPTION
**Pull request by youkaichao**
depyf https://github.com/thuml/depyf is a library ( I maintain ) that is dedicated for dumping all sorts of internals from torch.compile .

with this pr, run `vllm serve meta-llama/Meta-Llama-3-8B -O '{"level": 3, "inductor_specialize_for_cudagraph_no_more_than": 1, "debug_dump_path": "depyf_dump"}'` , and we can get:

```text
tree depyf_dump/rank_0 
depyf_dump/rank_0
├── __compiled_fn_1.AFTER_POST_GRAD.0.py
├── __compiled_fn_1.AFTER_POST_GRAD.1.py
├── __compiled_fn_1.AFTER_POST_GRAD.2.py
├── __compiled_fn_1.after_split.0.py
├── __compiled_fn_1.before_split.0.py
├── __compiled_fn_1.Captured_Graph.0.py
├── __compiled_fn_1.Forward_graph.0.py
├── __compiled_fn_1.Forward_graph.1.py
├── __compiled_fn_1.Forward_graph.2.py
├── __compiled_fn_1.Forward_graph.3.py
├── __compiled_fn_1.Forward_graph.4.py
├── __compiled_fn_1.Forward_graph.5.py
├── __compiled_fn_1.kernel_0.py
├── __compiled_fn_1.kernel_10.py
├── __compiled_fn_1.kernel_11.py
├── __compiled_fn_1.kernel_12.py
├── __compiled_fn_1.kernel_13.best_config
├── __compiled_fn_1.kernel_13.py
├── __compiled_fn_1.kernel_14.best_config
├── __compiled_fn_1.kernel_14.py
├── __compiled_fn_1.kernel_15.best_config
├── __compiled_fn_1.kernel_15.py
├── __compiled_fn_1.kernel_16.best_config
├── __compiled_fn_1.kernel_16.py
├── __compiled_fn_1.kernel_17.py
├── __compiled_fn_1.kernel_18.best_config
├── __compiled_fn_1.kernel_18.py
├── __compiled_fn_1.kernel_19.best_config
├── __compiled_fn_1.kernel_19.py
├── __compiled_fn_1.kernel_1.py
├── __compiled_fn_1.kernel_20.best_config
├── __compiled_fn_1.kernel_20.py
├── __compiled_fn_1.kernel_21.best_config
├── __compiled_fn_1.kernel_21.py
├── __compiled_fn_1.kernel_22.best_config
├── __compiled_fn_1.kernel_22.py
├── __compiled_fn_1.kernel_23.best_config
├── __compiled_fn_1.kernel_23.py
├── __compiled_fn_1.kernel_24.best_config
├── __compiled_fn_1.kernel_24.py
├── __compiled_fn_1.kernel_25.best_config
├── __compiled_fn_1.kernel_25.py
├── __compiled_fn_1.kernel_26.py
├── __compiled_fn_1.kernel_27.py
├── __compiled_fn_1.kernel_28.py
├── __compiled_fn_1.kernel_29.py
├── __compiled_fn_1.kernel_2.best_config
├── __compiled_fn_1.kernel_2.py
├── __compiled_fn_1.kernel_30.py
├── __compiled_fn_1.kernel_31.py
├── __compiled_fn_1.kernel_32.py
├── __compiled_fn_1.kernel_33.py
├── __compiled_fn_1.kernel_34.py
├── __compiled_fn_1.kernel_35.py
├── __compiled_fn_1.kernel_36.py
├── __compiled_fn_1.kernel_37.py
├── __compiled_fn_1.kernel_38.py
├── __compiled_fn_1.kernel_39.py
├── __compiled_fn_1.kernel_3.best_config
├── __compiled_fn_1.kernel_3.py
├── __compiled_fn_1.kernel_40.py
├── __compiled_fn_1.kernel_41.py
├── __compiled_fn_1.kernel_42.py
├── __compiled_fn_1.kernel_43.py
├── __compiled_fn_1.kernel_44.py
├── __compiled_fn_1.kernel_45.py
├── __compiled_fn_1.kernel_46.py
├── __compiled_fn_1.kernel_47.py
├── __compiled_fn_1.kernel_48.py
├── __compiled_fn_1.kernel_49.py
├── __compiled_fn_1.kernel_4.py
├── __compiled_fn_1.kernel_50.py
├── __compiled_fn_1.kernel_51.py
├── __compiled_fn_1.kernel_52.py
├── __compiled_fn_1.kernel_53.py
├── __compiled_fn_1.kernel_54.py
├── __compiled_fn_1.kernel_55.py
├── __compiled_fn_1.kernel_56.py
├── __compiled_fn_1.kernel_57.best_config
├── __compiled_fn_1.kernel_57.py
├── __compiled_fn_1.kernel_5.py
├── __compiled_fn_1.kernel_6.best_config
├── __compiled_fn_1.kernel_6.py
├── __compiled_fn_1.kernel_7.py
├── __compiled_fn_1.kernel_8.best_config
├── __compiled_fn_1.kernel_8.py
├── __compiled_fn_1.kernel_9.best_config
├── __compiled_fn_1.kernel_9.py
├── __compiled_fn_1.post_split_module.0.py
├── __compiled_fn_1.pre_insert_deferred_runtime_asserts___compiled_fn_1.0.py
├── __compiled_fn_1.pre_split_module.0.py
├── full_code_for_forward_0.py
└── __transformed_code_0_for_forward.py
```

it includes the dynamo compiled bytecode, inductor generated kernels, max-autotune configs, graph module during all transformations, etc.

### CODE REVIEW

**Comment by ProExpertProg** [comment]
How does depyf know to output after every pass? If it's not automatic, maybe we could add an annotation that can be added to the `__call__` function so the graph is printed. And still provide a way to print mid-pass (for fusion, there's a two-step process so printing in the middle helps).

Finally, could you post an example output file from depyf?

**Comment by youkaichao** [comment]
> How does depyf know to output after every pass?

it hooks the `lazy_format_graph_code` function. so we just need to call it after every pass. NOTE: just `lazy_format_graph_code`, not `logger.debug("%s", lazy_format_graph_code("before split", self.graph))`.

> could you post an example output file from depyf?

see https://drive.google.com/drive/folders/1gBVguoCbCGKpKb8SveKrbZkIhiZe9jeS?usp=sharing

**Review by ProExpertProg — APPROVED** [review]
This looks good! If we could reduce the verbosity of the output that would be nice but happy to deal with that later

**Comment by youkaichao** [comment]
yeah we can further organize the output in the future, to debug and improve the performance of inductor.

**Pull request merged**
