### PR TITLE
Splitting attention kernel file

### PR DESCRIPTION
**Pull request by maleksan85**
Split paged attention kernel into two files for v1 and v2 to speed up compilation when template instantiation explodes.

side effect: support Navi32

### CODE REVIEW

**Review by tlrmchlsmth — COMMENTED** [review]
Seems reasonable. Do you have measurements for compile time for these files before and with this change?

**Comment by maleksan85** [comment]
> Seems reasonable. Do you have measurements for compile time for these files before and with this change?

I didn't measure but on my non server machine I stopped to see timeouts during build. Also there will be change that moves compile time constant to be runtime. Different for AMD MI and AMD Navi thus increasing number of template instantiations and compile time.

**Comment by maleksan85** [comment]
@tlrmchlsmth are you OK with the change or there are some concerns? If OK, please approve.

**Review by tlrmchlsmth — APPROVED** [review]

**Comment by DarkLight1337** [comment]
@mergify-io rebase

**Comment by russellb** [comment]
> @mergify-io rebase

oops, sorry, should be @mergifyio rebase

**Comment by DarkLight1337** [comment]
https://github.com/Mergifyio rebase

**Pull request merged**
