### PR TITLE
[Fix] Correct OpenAI batch response format

### PR DESCRIPTION
**Pull request by zifeitong**
The response body should be nested into another object as in https://platform.openai.com/docs/api-reference/batch/request-output.

### CODE REVIEW

**Comment by simon-mo** [comment]
@wuisawesome can you help review? thanks!

**Review by wuisawesome — APPROVED** [review]
lgtm.

thinking about why the test didn't catch this, i wonder if `test_openai_run_batch.py` should use the openai package's types to validate the model instead of our own pydantic models?

**Comment by wuisawesome** [comment]
@simon-mo do you think this should go into the next 0.5.0 post release?

**Comment by simon-mo** [comment]
If merged, this will go into the next regular release in two weeks.

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
