### PR TITLE
[Kernel] Replaced `blockReduce[...]` functions with `cub::BlockReduce`

### PR DESCRIPTION
**Pull request by ProExpertProg**
Replace all uses of the custom (and buggy) blockReduce function with the idiomatic cub::BlockReduce.

I also removed the runtime dispatching for block sizes per @LucasWilkinson's suggestion. 

[Here are the results of the layernorm and quant microbenchmarks](https://docs.google.com/spreadsheets/d/14laJwm_aQVhwr-4hUt1EmlecBksGzWFFtCsXj4eRB9U/edit?usp=sharing).

The summary is that the cub version is (geomean) 0.2% faster for layernorm and 1.3% slower for quant, but that's most likely just noise. That's because different shapes & dtypes produce vastly different ratios of the `cub` and `main` runtimes. And there don't seem to be any patterns.

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by tlrmchlsmth — APPROVED** [review]
Nice cleanup, thanks!

**Comment by tlrmchlsmth** [comment]
@ProExpertProg could  you check if the kernels-test-3 failure is related to your changes?

**Comment by mawong-amd** [comment]
> I also removed the runtime dispatching for block sizes per @LucasWilkinson's suggestion.

Would appreciate a link to this suggestion/discussion if it's public! Is there a reason why this is done. The runtime dispatch for block sizes was done for performance reasons: smaller block sizes allow better occupancy on CUs for memory latency hiding during the prefill phase. If CUB avoids this issue/nonetheless provides performance improvement over the current implementation, happy to have this change.

**Comment by ProExpertProg** [comment]
@mawong-amd there were a few bugs:
- It used the values from all threads instead of using active threads only, which returns undefined for inactive threads, but it happened to be 0 which worked for sum and max (but not min).
- Similarly, it used 0 as the sentinel value which worked for sum and absmax but not min or max where negative values are involved.
-  It used static shared memory which meant two separate invocations could interact with each other which was unintuitive. Perhaps not a bug per-se but it took a while to diagnose. `cub::BlockReduce` is more explicit about its shared memory use.

> smaller block sizes allow better block occupancy on CUs for memory latency hiding during the prefill phase
We still use a smaller block size, we just have a single block reduction size as opposed to 2 separate ones which will still take up the same amount of shared memory space (because we pick between them at kernel runtime). See [6050cae](https://github.com/vllm-project/vllm/pull/7233/commits/6050caec2076ba3ec2932e62db93ec2eab89575e).

If we care about the size of shared memory in the kernel, I can add a template parameter so we can avoid the branch and specialize.

**Comment by LucasWilkinson** [comment]
> Would appreciate a link to this suggestion/discussion if it's public! Is there a reason why this is done? The runtime dispatch for block sizes was done for performance reasons: smaller block sizes allow better block occupancy on CUs for memory latency hiding during the prefill phase (or from a more agnostic view: when num_tokens = kernel grid size is sufficiently large, so enough blocks can be scheduled). If CUB avoids this issue/provides performance improvement over the current implementation, happy to have this change. I'm curious if we'll still see the same gains in prefill when having smaller block sizes.
The kernels are still being launched based on [this](https://github.com/vllm-project/vllm/blob/469b3bc538bcbdc1d9b7d30c415bdb0361853871/csrc/layernorm_kernels.cu#L327-L331) but @ProExpertProg  just removed templating 2 separate block reduce implementations and runtime dispatching between those [here](https://github.com/vllm-project/vllm/blob/469b3bc538bcbdc1d9b7d30c415bdb0361853871/csrc/layernorm_kernels.cu#L273-L276), with cub both those cases can be handle but just correctly setting `num_valid`.

> Out of curiosity, what bugs have you seen?
Its not buggy, but its opaque api design can easily lead people to introducing bugs, this occurred with us by doing some thing like:
```
float a = ....;
float b = ....;
float x = blockReduceSum<float>(a);
float y = blockReduceSum<float>(b);
if (threadIdx.x == 0) {
   // do something with x and y
}
```
in this case x could non-deterministically include incorrect results since the `float y = blockReduceSum<float>(b);` could trash the shared memory `float x = blockReduceSum<float>(a);`. This is fixed by doing:
```
float a = ....;
float b = ....;
float x = blockReduceSum<float>(a);
__syncthreads();
float y = blockReduceSum<float>(b);
if (threadIdx.x == 0) {
   // do something with x and y
}
```
but its hard to for a user to know that `blockReduceSum` is allocating and using shared memory from the callsite alone, cub fixes this by forcing the user to allocate the shared memory outside of the reduce making it more obvious to the reader a `__syncthreads();` may be required. 

Also just from software engineering perspective I think it makes sense for use to leverage hardened Nvidia implementations of common routines when possible. (as a bonus we benefit from their docs, which in this case would explain the need for sync threads: https://nvidia.github.io/cccl/cub/developer_overview.html#id5)

**Comment by mawong-amd** [comment]
> It used the values from all threads instead of using active threads only, which returns undefined for inactive threads, but it happened to be 0 which worked for sum and max (but not min).
Similarly, it used 0 as the sentinel value which worked for sum and absmax but not min or max where negative values are involved.

Great catch!

> It used static shared memory which meant two separate invocations could interact with each other which was unintuitive. Perhaps not a bug per-se but it took a while to diagnose. cub::BlockReduce is more explicit about its shared memory use.

Coincidentally I thought about this a few weeks ago while reviewing code, but I eventually reasoned that `static _shared__` shouldn't differ from `__shared__`. Reason being, shared memory is implemented in L1 cache and is reserved per-block when the block is assigned to a EU, and is also released when the block completes execution (with some [caveats for Compute Capability 9.0+](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#distributed-shared-memory)). In particular, it's not persistent across different kernel invocations. So there shouldn't be a clash between simultaneously executing kernels. Feel free to correct me if I'm mistaken.

**Comment by mawong-amd** [comment]
> with cub both those cases can be handle but just correctly setting num_valid
I see! I'm not too familiar with CUB, but in that case, this removal makes sense.

> I think it makes sense for use to leverage hardened Nvidia implementations of common routines when possible. (as a bonus we benefit from their docs, which in this case would explain the need for sync threads: https://nvidia.github.io/cccl/cub/developer_overview.html#id5)
I agree completely. I believe there are still a few places in vLLM where people implement their own unoptimized `blockReduce` (ignoring the vLLM implementation), so by using higher quality implementations like in this PR, hopefully that fragmentation will be reduced.

**Comment by ProExpertProg** [comment]
@mawong-amd if you point me to those places I'd be happy to consolidate and try to replace them in this PR (or another) if we want to do that.

**Comment by ProExpertProg** [comment]
@tlrmchlsmth I checked and `test_flash_attn` fails on current `main` as well, so it's not related to this PR

**Review by mgoin — APPROVED** [review]

**Comment by tlrmchlsmth** [comment]
@ProExpertProg could you share some performance numbers with the benchmark you wrote?

**Comment by ProExpertProg** [comment]
Yep, sorry, took a little longer than expected. [Here are the results of the layernorm and quant microbenchmarks](https://docs.google.com/spreadsheets/d/14laJwm_aQVhwr-4hUt1EmlecBksGzWFFtCsXj4eRB9U/edit?usp=sharing).

The summary is that the cub version is (geomean) 0.2% faster for layernorm and 1.3% slower for quant, but that's most likely just noise. That's because different shapes & dtypes produce vastly different ratios of the `cub` and `main` runtimes. And there don't seem to be any patterns.

**Pull request merged**
