### PR TITLE
[WIP][1/N] Chunked Prefill

### PR DESCRIPTION
**Pull request by rkooo567**
WIP. RFC link: https://github.com/vllm-project/vllm/issues/3130

### CODE REVIEW

**Comment by tdene** [comment]
Is the goal of this PR and #3121 not the same?

**Comment by rkooo567** [comment]
> There is already an attention kernel context_attention_fwd in vLLM that covers the case of prefill with kv cache. It was originally created for Manual Prefix Caching (and will be used for Automatic Prefix Caching as well). I have not looked too much into the implementation of context_attention_fwd (so I'm not sure of the performance relative to the flash attention implementation), but just wanted to make sure you were aware

Yes! I am aware of this. I think it must be possible to use this kernel as well, but our internal benchmark shows it is pretty slow actually (I don't know much detail here though).

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks @rkooo567

**Comment by zhr2001** [comment]
After trying with the provided code, I think the implementation is not completely finished and it still leaves some bugs.

**Comment by rkooo567** [comment]
@zhr2001 actually this is stale. did you try https://github.com/vllm-project/vllm/pull/3884#issuecomment-2041306314?

**Comment by zhr2001** [comment]
I have tried.It's excellent, thanks for your contribution.
However, I just got result 7.09it/s for benchmark_serving, while without chunkedprefill the result was 3.44it/s within llama-13B,A40,tp2, max-num-batched-token and sonnet data-set.I wonder how to get the following result in the picture below.
chunk

**Comment by rkooo567** [comment]
@zhr2001 I am starting the benchmark from tomorrow. Btw, what does `7.09it/s for benchmark_serving` mean (does it mean it is better or worse)? I am not familiar with this benchmark

For the result above, it is the result with our internal repo (the implementation is almost the same, but our repo has cuda-graph for prefill whereas OSS currently doesn't have it). The environment is basically sending a requests with similar length with a certain QPS

**Pull request closed without merging**
