### PR TITLE
[Misc] update benchmark backend for scalellm

### PR DESCRIPTION
**Pull request by zhyncs**
FILL IN THE PR DESCRIPTION HERE

support scalellm

```bash
# install from https://github.com/vectorch-ai/ScaleLLM/releases

# server
python3 -m scalellm.serve.api_server --model /workdir/Llama-2-13b-chat-hf

# client
python3 benchmark_serving.py --backend scalellm --host 127.0.0.1 --port 8080 --dataset /workdir/ShareGPT_V3_unfiltered_cleaned_split.json  --model Llama-2-13b-chat-hf --tokenizer /workdir/Llama-2-13b-chat-hf --num-prompts 1000 --request-rate 128
```

Hi @ywang96 @mgoin May you help review this PR? Thanks.

I know this can be achieved by specifying the backend `openai` to make benchmark work. And I would like to say that this is **a very promising project and worth listing separately**.  Cheers. cc @guocuimi

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by ywang96 — APPROVED** [review]
LGTM! I assume you have run the benchmark against `scalellm` and verified it indeed works without an issue?

**Comment by zhyncs** [comment]
> LGTM! I assume you have run the benchmark against `scalellm` and verified it indeed works without an issue?

Exactly. It’s blazing fast!

**Comment by zhyncs** [comment]
ref https://github.com/vectorch-ai/ScaleLLM/issues/144#issuecomment-2199530934

**Comment by zhyncs** [comment]
Hi @ywang96 May you help trigger the failed checks? Thanks.

**Comment by ywang96** [comment]
I'll have this PR force merged since it doesn't touch anything related to the CI.

**Comment by mgoin** [comment]
This seems like we could just use `--backend openai`, or am I missing something? If it's a small cosmetic change, I don't see the value in explicitly calling it out as a backend string. This pattern could lead to a lot of "integrations" that seem overly complex when it is just using openai.

Also in that performance link you mentioned, it seems slower than TurboMind? I'm not going to block, just a bit confused on the value of this change to be explicit with the backend if not necessary.
```
# TurboMind
============ Serving Benchmark Result ============
Successful requests:                     1000
Benchmark duration (s):                  108.19
Total input tokens:                      245995
Total generated tokens:                  196273
Request throughput (req/s):              9.24
Input token throughput (tok/s):          2273.65
Output token throughput (tok/s):         1814.09

# ScaleLLM
============ Serving Benchmark Result ============
Successful requests:                     1000
Benchmark duration (s):                  115.64
Total input tokens:                      245995
Total generated tokens:                  195334
Request throughput (req/s):              8.65
Input token throughput (tok/s):          2127.27
Output token throughput (tok/s):         1689.17

**Comment by ywang96** [comment]
> This seems like we could just use `--backend openai`, or am I missing something? If it's a small cosmetic change, I don't see the value in explicitly calling it out as a backend string. This pattern could lead to a lot of "integrations" that seem overly complex when it is just using openai.
> 
> Also in that performance link you mentioned, it seems slower than TurboMind? I'm not going to block, just a bit confused on the value of this change to be explicit with the backend if not necessary.
> 
> ```
> # TurboMind
> ============ Serving Benchmark Result ============
> Successful requests:                     1000
> Benchmark duration (s):                  108.19
> Total input tokens:                      245995
> Total generated tokens:                  196273
> Request throughput (req/s):              9.24
> Input token throughput (tok/s):          2273.65
> Output token throughput (tok/s):         1814.09
> 
> # ScaleLLM
> ============ Serving Benchmark Result ============
> Successful requests:                     1000
> Benchmark duration (s):                  115.64
> Total input tokens:                      245995
> Total generated tokens:                  195334
> Request throughput (req/s):              8.65
> Input token throughput (tok/s):          2127.27
> Output token throughput (tok/s):         1689.17
> ```

I think the point is that by explicitly listing as a "backend" option, it's easier to compare benchmark results after they're saved in the json format (Otherwise it'll be listed as "openai" and that is rather inconvenient).

**Comment by zhyncs** [comment]
Thanks to the previous design and development work by @ywang96, the benchmark script of vLLM is professional and user-friendly, especially for comparing various inference frameworks. Currently, most inference frameworks support OpenAI's interface, such as LMDeploy, vLLM, and also including the ScaleLLM mentioned here. I believe this is a project with great potential, even though it currently lags slightly behind TurboMind in performance. ScaleLLM is still under development with many performance optimization features in progress, which is very exciting. This also demonstrates that integrating the FlashInfer library for an inference framework on NVIDIA GPUs plays a significant role. Additionally, the differentiation in names mentioned by @ywang96 is also an important point.

**Pull request merged**
