### PR TITLE
[Bugfix][Kernel] Use int64_t for indices in fp8 quant kernels

### PR DESCRIPTION
**Pull request by tlrmchlsmth**
Running `neuralmagic/Mistral-Nemo-Instruct-2407-FP8`, we are accessing an illegal memory address because our loop counters over the number of elements are int32_t, and the model has a maximum sequence length of 1 million.

Let's change these to int64_t. We should also strongly consider compiling with `-Wconversion` or even `-Werror=conversion` to prevent these. I tried adding `-Wconversion` in this PR but it's extremely noisy right now, and it will be a much larger change to fix the warnings it cases.

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by robertgshaw2-redhat — APPROVED** [review]

**Review by mgoin — APPROVED** [review]

**Comment by comaniac** [comment]
Out of curiosity, do you observe any performance regression with int64 indices? I previously saw an issue in triton reported by someone that since int64 uses 2 registers.

**Comment by tlrmchlsmth** [comment]
@comaniac I did some quick e2e decode runs -- looks like we may be very slightly slower using int64. But IMO we should still land the PR. Are there any micro-benchmarks for just these kernels?

```
python3 benchmarks/benchmark_latency.py --model neuralmagic/Meta-Llama-3-8B-Instruct-FP8 \
--batch-size 16 --input-len 1 --output-len 512
```

This PR:
```
Avg latency: 3.4161813993162164 seconds
10% percentile latency: 3.3850670562125744 seconds
25% percentile latency: 3.3872151313116774 seconds
50% percentile latency: 3.3914742909837514 seconds
75% percentile latency: 3.451796793495305 seconds
90% percentile latency: 3.4673959348350762 seconds
99% percentile latency: 3.554096885798499 seconds
```

main:
```
Avg latency: 3.4008890725672245 seconds
10% percentile latency: 3.3801775192841887 seconds
25% percentile latency: 3.380847539170645 seconds
50% percentile latency: 3.3822259346488863 seconds
75% percentile latency: 3.431579362368211 seconds
90% percentile latency: 3.4506909909192474 seconds
99% percentile latency: 3.462752147950232 seconds
```

**Comment by comaniac** [comment]
Thanks for the benchmarking and it seems ok.
For micro-benchmark I feel you could base on `benchmarks/cutlass_benchmarks/w8a8_benchmarks.py`.

**Comment by comaniac** [comment]
btw do you think it makes sense to have a unit test (if it doesn't take unaccepted long time) to cover this bug?

**Comment by tlrmchlsmth** [comment]
I added a unit test but going to try to get the memory footprint down as it takes over 16 GB right now

**Review by comaniac — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
