### PR TITLE
[Misc] Upgrade to `torch==2.3.0`

### PR DESCRIPTION
**Pull request by mgoin**
Now that there is an [xformers release](https://github.com/facebookresearch/xformers/releases/tag/v0.0.26.post1) and [flash-attn release](https://github.com/Dao-AILab/flash-attention/releases/tag/v2.5.8) with PyTorch 2.3.0 support, we can consider upgrading to PyTorch 2.3.0.

PyTorch 2.3.0 is an useful version because it allows using `torch._scaled_mm` on Ada Lovelace GPUs (CUDA compute capability 8.9) for running native FP8 matmuls. (We will enable and test this in a follow-up PR)

Performance benchmarks using a Marlin quantized Llama 7B on RTX 4090:
https://docs.google.com/spreadsheets/d/1sYIzF7bLEvpcg-p9IS-6XvZhdv4h95GvjhLIbvpW1l4/edit?usp=sharing
vLLM TTFT between torch 2 2 1 and 2 3 0
vLLM TPOT between torch 2 2 1 and 2 3 0

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by robertgshaw2-redhat — APPROVED** [review]

**Comment by youkaichao** [comment]
Be sure to check the blocks of memory we can use, before and after the upgrade.

e.g. `# GPU blocks: 881, # CPU blocks: 0` in `Basic Correctness Test`

**Comment by youkaichao** [comment]
I feel we can parse these stats and present them in the dashboard, too, especially for the GPU blocks. @simon-mo 

> # GPU blocks: 881, # CPU blocks: 0

**Comment by mgoin** [comment]
Thanks for the suggestion @youkaichao, here are my results for kv cache block allocation using an A6000.

There is a roughly a ~1 block difference for common 7B models. The worst case is `facebook/opt-125m` which can allocate 75937 GPU blocks on main and 75934 GPU blocks on this PR, a difference of 3 blocks. I think this is acceptable.

Using main's current HEAD commit 73c8d677e57e42374bcfb2271b8f1cf7f2c0a486:
```
> python -c 'from vllm import LLM;LLM("facebook/opt-125m")'
INFO 04-29 19:12:30 gpu_executor.py:118] # GPU blocks: 75937, # CPU blocks: 7281

> python -c 'from vllm import LLM;LLM("meta-llama/Meta-Llama-3-8B-Instruct")'
INFO 04-29 19:12:48 gpu_executor.py:118] # GPU blocks: 13248, # CPU blocks: 2048

> python -c 'from vllm import LLM;LLM("teknium/OpenHermes-2.5-Mistral-7B")'
INFO 04-29 19:13:07 gpu_executor.py:118] # GPU blocks: 12735, # CPU blocks: 2048

> python -c 'from vllm import LLM;LLM("TheBloke/Llama-2-7B-GPTQ")'
INFO 04-29 19:13:19 gpu_executor.py:118] # GPU blocks: 4877, # CPU blocks: 512

> python -c 'from vllm import LLM;LLM("TheBloke/zephyr-7B-beta-AWQ")'
INFO 04-29 19:13:37 gpu_executor.py:118] # GPU blocks: 17641, # CPU blocks: 2048

> python -c 'from vllm import LLM;LLM("mgoin/phi-2-super-marlin")'
INFO 04-29 19:13:51 gpu_executor.py:118] # GPU blocks: 8214, # CPU blocks: 819
```

With this PR:
```
> python -c 'from vllm import LLM;LLM("facebook/opt-125m")'
INFO 04-29 19:03:36 gpu_executor.py:119] # GPU blocks: 75934, # CPU blocks: 7281

> python -c 'from vllm import LLM;LLM("meta-llama/Meta-Llama-3-8B-Instruct")'
INFO 04-29 19:04:43 gpu_executor.py:119] # GPU blocks: 13247, # CPU blocks: 2048

> python -c 'from vllm import LLM;LLM("teknium/OpenHermes-2.5-Mistral-7B")'
INFO 04-29 19:09:23 gpu_executor.py:119] # GPU blocks: 12734, # CPU blocks: 2048

> python -c 'from vllm import LLM;LLM("TheBloke/Llama-2-7B-GPTQ")'
INFO 04-29 19:10:47 gpu_executor.py:119] # GPU blocks: 4877, # CPU blocks: 512

> python -c 'from vllm import LLM;LLM("TheBloke/zephyr-7B-beta-AWQ")'
INFO 04-29 19:11:09 gpu_executor.py:119] # GPU blocks: 17640, # CPU blocks: 2048

> python -c 'from vllm import LLM;LLM("mgoin/phi-2-super-marlin")'
INFO 04-29 19:11:26 gpu_executor.py:119] # GPU blocks: 8213, # CPU blocks: 819
```

**Review by zhouyuan — APPROVED** [review]
Thanks for covering the CPU part - there's a minor performance increase in CPU backend also mostly due to `torch.linear` improvement in 2.3

**Review by youkaichao — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
