### PR TITLE
[Misc] Manage HTTP connections in one place

### PR DESCRIPTION
**Pull request by DarkLight1337**
This PR adds `vllm.connections.HTTP_CONNECTION` so that we can reuse the same sync/async client session. It also encapsulates the boilerplate code for common uses of `requests` and `aiohttp` libraries.

### CODE REVIEW

**Comment by ywang96** [comment]
@simon-mo WDYT of this PR? I think it makes sense to me to unify the management of HTTP connections.

**Comment by simon-mo** [comment]
Code style wise, I would prefer something like `get_global_http_client` `get_global_async_http_client` instead of a seemingly constant variable. 

But good direction!

**Comment by DarkLight1337** [comment]
> Code style wise, I would prefer something like `get_global_http_client` `get_global_async_http_client` instead of a seemingly constant variable.
> 
> But good direction!

See if f4cfb65 suits you.

**Comment by DarkLight1337** [comment]
Any update? @simon-mo

**Review by simon-mo — APPROVED** [review]

**Comment by hmellor** [comment]
I'm not 100% sure how, but this PR appears to have broken the dev documentation.

Setup environment:
```console
cd docs
python -m venv venv
. venv/bin/activate
pip install -r requirements-docs.txt
```

Start HTTP server:
```console
python -m http.server -d build/html/
```

Checkout commit prior to this PR and build:
```console
git checkout c051bfe4eb77b82eba90504360bbd4e61d9e489a
make clean && make html
```
Navigate to http://localhost:8001/dev/sampling_params.html and see a populated page.

Checkout merge commit from this PR and build:
```console
git checkout 97234be0ec67f48ed5e65bc0290f329dfb33798e
make clean && make html
```
Navigate to http://localhost:8001/dev/sampling_params.html and see an empty page.

**Comment by hmellor** [comment]
This can be fixed by adding 

```python
    "aiohttp",
```

to `autodoc_mock_imports` in `vllm/docs/source/conf.py`

@DarkLight1337 do you want to do this?

**Pull request merged**
