### PR TITLE
[Bugfix][Misc]: fix graph capture for decoder

### PR DESCRIPTION
**Pull request by yudian0504**
This PR fixes a bug introduced by https://github.com/vllm-project/vllm/issues/8645.

related issues: https://github.com/vllm-project/vllm/issues/9448 & https://github.com/vllm-project/vllm/issues/9417 & https://github.com/vllm-project/vllm/issues/9409

### CODE REVIEW

**Review by comaniac — APPROVED** [review]
Approved the unblock. Meanwhile, I'm not sure how encoder-decoder works in this case. @varun-sundar-rabindranath PTAL. Also cc @sroy745

**Review by varun-sundar-rabindranath — APPROVED** [review]
My mistake !! Thanks for the fix @yudian0504 🙌

**Comment by jeejeelee** [comment]
Good catch, this solved a bug I encountered.

**Review by jeejeelee — APPROVED** [review]

**Comment by xfalcox** [comment]
This bug fix is so important, we need a release for the new docker image cc @DarkLight1337

**Comment by DarkLight1337** [comment]
> This bug fix is so important, we need a release for the new docker image cc @DarkLight1337

For now, you can use the Docker image [here](https://docs.vllm.ai/en/latest/getting_started/installation.html#install-the-latest-code) using the latest commit.

**Pull request merged**
