### PR TITLE
feat(config): support parsing torch.dtype

### PR DESCRIPTION
**Pull request by aarnphm**
Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>

### CODE REVIEW

**Comment by WoosukKwon** [comment]
Hi @aarnphm, thanks for submitting the PR! Could you elaborate more on the context that you need this change?

**Comment by aarnphm** [comment]
Oh I think in case that users already have a `torch.dtype` , then `AsyncEngineArgs` or `EngineArgs` should be able to accept that torch.dtype and only does validation? So this basically save one call cycle, which is pretty minuscule.

This is not that high priority since users can always parse back from `torch.dtype` to string?

**Comment by WoosukKwon** [comment]
@aarnphm I see. I think the PR makes sense and does not hurt vLLM at all. Could you resolve the merge conflict?

**Comment by aarnphm** [comment]
> @aarnphm I see. I think the PR makes sense and does not hurt vLLM at all. Could you resolve the merge conflict?

cc @WoosukKwon fixed.

**Review by WoosukKwon — APPROVED** [review]
LGTM! Thanks for submitting the PR.

**Pull request merged**
