### PR TITLE
[Model] Add base class for LoRA-supported models

### PR DESCRIPTION
**Pull request by DarkLight1337**
Similar to #4809, this PR adds a base class for models that support LoRA so that it becomes easier to enforce a consistent interface. The docs have also been updated to instruct users to inherit from the base class to enable LoRA support.

**Note:** This will break existing LoRA-supporting vLLM models that are defined outside the library; such models will have to inherit from the base LoRA class introduced by this PR to be recognized by vLLM again. Since we never officially defined such an interface, I think this breaking change is fine.

### CODE REVIEW

**Comment by Yard1** [comment]
I am worried this will not be an extensible pattern as we keep adding more base classes. Multiple inheritance/mixins get really confusing really fast.

**Comment by DarkLight1337** [comment]
> I am worried this will not be an extensible pattern as we keep adding more base classes. Multiple inheritance/mixins get really confusing really fast.

Tbh it's not strictly necessary for this to be a base class. We can alternatively use an `typing.Protocol` to indicate the interface,

**Comment by DarkLight1337** [comment]
> > I am worried this will not be an extensible pattern as we keep adding more base classes. Multiple inheritance/mixins get really confusing really fast.
> 
> Tbh it's not strictly necessary for this to be a base class. We can alternatively use a `typing.Protocol` to indicate the interface, if that would address your concerns.

@Yard1 any thoughts on this?

**Comment by Yard1** [comment]
Yes, I think a protocol makes sense. Then we should check that the class conforms to the protocol (methods/attributes exist)

**Review by Yard1 — APPROVED** [review]
Looks good! I think we can get rid of `supports_lora = True` now.

**Comment by DarkLight1337** [comment]
`supports_lora = True` is to make it more explicit that the model supports LoRA. I have improve the warning message so that it warns in the following cases:

- `supports_lora = True` but the other LoRA attributes fail to be set
- Other LoRA attributes have been set but `supports_lora = False`

**Comment by DarkLight1337** [comment]
> `supports_lora = True` is to make it more explicit that the model supports LoRA. I have improved the warning message so that it warns in the following cases:
> 
> * `supports_lora = True` but the other LoRA attributes fail to be set
> * Other LoRA attributes have been specified but `supports_lora = False` or is unset
> 
> This lets `supports_lora` act as a sort of confirmation to better guard against the above mistakes.

@Yard1 is this okay with you? If so, we can enable auto-merge.

**Comment by DarkLight1337** [comment]
@Yard1 can we merge this?

**Comment by DarkLight1337** [comment]
To facilitate upcoming changes to VLMs, I'm merging this first.

**Pull request merged**
