### PR TITLE
enforce eager mode with bnb quantization temporarily

### PR DESCRIPTION
**Pull request by chenqianfzh**
Temporarily enforce eager_mode in bitsandbytes quantization before the known issue (https://github.com/vllm-project/vllm/issues/5569) is fixed.

### CODE REVIEW

**Comment by chenqianfzh** [comment]
@mgoin Thanks for comments. Updated.

**Review by mgoin — APPROVED** [review]

**Comment by devlup** [comment]
https://github.com/bitsandbytes-foundation/bitsandbytes/issues/1308 this issue got fixed , this will enable not to enforce eager mode ? @chenqianfzh @kylesayrs

**Comment by mgoin** [comment]
@devlup correct but we need a new release of bitsandbytes to be made since we use the pypi package

**Pull request merged**
