### PR TITLE
remove floats == 0 comparison 

### PR DESCRIPTION
**Pull request by LiuXiaoxuanPKU**
fix for #71

### CODE REVIEW

**Review by Ying1123 — CHANGES_REQUESTED** [review]
Thanks for the contribution. Could you change it to 1e-5? We also use 1e-5 in FastChat in the main branch now, which is safer for temperature.
https://github.com/lm-sys/FastChat/blob/69d085eadab8e9fcf831a97e17e132658c3d2272/fastchat/serve/inference.py#L141

**Review by zhuohan123 — COMMENTED** [review]
In addition to @Ying1123's comment, maybe we can set a constant `SAMPLING_EPS = 1e-4`, and use `SAMPLING_EPS` to replace all the zeros?

**Comment by zhuohan123** [comment]
Could you also help fix the comparisons in `sampling_params.py`? For example:

https://github.com/vllm-project/vllm/blob/bdd6b4c8bc3e5ac93553436514171ffad5926f0c/vllm/sampling_params.py#L109

**Review by Ying1123 — APPROVED** [review]

**Review by zhuohan123 — APPROVED** [review]
LGTM! Thank you for your contribution.

**Pull request merged**
