### PR TITLE
Fixes#1595 | set seed before generation

### LINKED ISSUE #1595: How to set seed before generation?
I know, you can set any seed during model loading, but how specific seed can be set before each generation (without reloading model every time) or even better for every N prompt you feed to generator?

Thank you in advance!

### PR DESCRIPTION
**Pull request by avirlrma**
fixes #1595

### CODE REVIEW

**Comment by simon-mo** [comment]
@zhuohan123 please take a look! This looks reasonable to me.

**Comment by zhuohan123** [comment]
Thanks for the contribution! I believe the biggest issue here is that we have batching. The batching behavior will change the sample outputs of each individual request even if you fixed the seed at the beginning. Ideally, we should have a CUDA kernel that can set different seeds for different kernels and still have good batching inference performance. 

Is my understanding correct? @avirlrma

**Comment by avirlrma** [comment]
> The batching behaviour will change the sample outputs of each individual request even if you fixed the seed at the beginning

Hey @zhuohan123, Could you point me in code where I can take a look at the batching behaviour that you are mentioning here?

**Comment by simon-mo** [comment]
@avirlrma I would recommend take a look at the scheduler.py code https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py.

**Comment by timothylimyl** [comment]
this PR will be very useful, especially since LLM models (small size) are pretty brittle. Minor changes to prompt can deteriorate performance. Thus, will be good to seed vLLM when prompt engineering.

**Comment by esmeetu** [comment]
> The batching behavior will change the sample outputs of each individual request even if you fixed the seed at the beginning

Hi, @zhuohan123. When i benchmarked humaneval on codellm using batching request(more than 100 concurrent request) with greedy sampling, i got slightly different result everytime. Is that what you're talking about?

**Comment by simon-mo** [comment]
Seed is already supported in #2514

**Pull request closed without merging**
