### PR TITLE
[Bugfix] Fix internlm2 tensor parallel inference

### LINKED ISSUE #8017: [Bug]: InternVL2-2B outputs gibberish with tensor parallel inference
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

**Reproduce**
- Just run `examples/offline_inference_vision_language.py` with `tensor_parallel_size=2`.
- The inference with `tensor_parallel_size=1` works normally.

**Outputs**
```
Processed prompts: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.52s/it, est. speed input: 1192.65 toks/s, output: 26.96 toks/s]
1.
1.
1/2
3/2
1
  for example
�2/定有了一个iSA诉快的队/纳厄/否化，4.
INFO 08-30 03:22:42 multiproc_worker_utils.py:136] Terminating local vLLM worker processes
(VllmWorkerProcess pid=9476) INFO 08-30 03:22:42 multiproc_worker_utils.py:237] Worker exiting
```

**The root issue**
- This is broken by the `split_qkv` function for `internlm2` backbone introduced in #7187 to make compatible with awq model.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by Isotr0py**
FILL IN THE PR DESCRIPTION HERE

- FIX #8017 (*link existing issues this PR will resolve*)

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by Isotr0py** [comment]
@SovereignRemedy Could you help me check if this PR also fixes garbled characters when tensor_parallel_size>2? Thanks!

InternVL2 models (unquantized/awq) with InternLM2 backbone work with `tensor_parallel_size=2`, but I would like to double check tensor_parallel_size>2.

**Comment by DarkLight1337** [comment]
This looks good to me on paper. I'll approve the PR once the fix is confirmed to work.

**Comment by SovereignRemedy** [comment]
> @SovereignRemedy Could you help me check if this PR also fixes garbled characters when tensor_parallel_size>2? Thanks!
> 
> InternVL2 models (unquantized/awq) with InternLM2 backbone work with `tensor_parallel_size=2` now, but I would like to double check tensor_parallel_size>2.

thanks！
I pulled the pr code locally and used the official demo
Still seems to be the similar garbled.

my env:
image


run
`python offline_inference_vision_language.py -m internvl_chat`
The default parameter will
image
Only some parameters have been modified
```
# InternVL
def run_internvl(question):

    model_name = "/home/tdj/model/InternVL2-26B"
    print("xssx1!!!!!!!---------!!!!")
    llm = LLM(
        model=model_name,
        trust_remote_code=True,
        gpu_memory_utilization=0.9,
        tensor_parallel_size=4,
        max_num_batched_tokens=8192,
        max_model_len=4096,
    )
    print("!!!!!ssss!!!!!!-----")
    tokenizer = AutoTokenizer.from_pretrained(model_name,
                                              trust_remote_code=True)
    messages = [{'role': 'user', 'content': f"<image>\n{question}"}]
    prompt = tokenizer.apply_chat_template(messages,
                                           tokenize=False,
                                           add_generation_prompt=True)

    # Stop tokens for InternVL
    # models variants may have different stop tokens
    # please refer to the model card for the correct "stop words":
    # https://huggingface.co/OpenGVLab/InternVL2-2B#service
    stop_tokens = ["<|endoftext|>", "<|im_start|>", "<|im_end|>", "<|end|>"]
    stop_token_ids = [tokenizer.convert_tokens_to_ids(i) for i in stop_tokens]
    return llm, prompt, stop_token_ids
```

output  garbled
image

**Comment by Isotr0py** [comment]
@SovereignRemedy How about `tensor_parallel_size=2`? Is it also having this issue?

**Comment by SovereignRemedy** [comment]
> @SovereignRemedy How about `tensor_parallel_size=2`? Is it also having this issue?

local model is InternVL2-26B. 2xA10 cuda oom 

 2  NVIDIA A10                     On  | 00000000:71:00.0 Off |                    0 |
|  0%   30C    P8              15W / 150W |      4MiB / 23028MiB |      0%      Default |

**Comment by Isotr0py** [comment]
@SovereignRemedy You can test on 8B since they all have same backbone.

**Comment by SovereignRemedy** [comment]
> @SovereignRemedy You can test on 8B since they all have same backbone.

image

```
def run_internvl(question):

    model_name = "/home/tdj/model/InternVL2-8B"
    print("xssx1!!!!!!!---------!!!!")
    llm = LLM(
        model=model_name,
        trust_remote_code=True,
#        gpu_memory_utilization=0.8,
        tensor_parallel_size=2,
        max_num_batched_tokens=8192,
        max_model_len=4096,
    )
    print("!!!!!ssss!!!!!!-----")
    tokenizer = AutoTokenizer.from_pretrained(model_name,
                                              trust_remote_code=True)
    messages = [{'role': 'user', 'content': f"<image>\n{question}"}]
    prompt = tokenizer.apply_chat_template(messages,
                                           tokenize=False,
                                           add_generation_prompt=True)

    # Stop tokens for InternVL
    # models variants may have different stop tokens
    # please refer to the model card for the correct "stop words":
    # https://huggingface.co/OpenGVLab/InternVL2-2B#service
    stop_tokens = ["<|endoftext|>", "<|im_start|>", "<|im_end|>", "<|end|>"]
    stop_token_ids = [tokenizer.convert_tokens_to_ids(i) for i in stop_tokens]
    return llm, prompt, stop_token_ids

```

Seem the same

**Comment by SovereignRemedy** [comment]
> @SovereignRemedy You can test on 8B since they all have same backbone.

8B tensor_parallel_size=1, seem ok
image

**Comment by Isotr0py** [comment]
This is strange, because I can generate normal result on 8B with `tensor_parallel_size=2`:
QQ截图20240902133749

Can you reinstall from this branch in a clear environment and check again? I guess there may be something wrong in the environment and the installation not overrided.

**Comment by SovereignRemedy** [comment]
> This is strange, because I can generate normal result on 8B with `tensor_parallel_size=2`: QQ截图20240902133749
> 
> ```python
> # InternVL
> def run_internvl(question):
>     model_name = "OpenGVLab/InternVL2-8B"
>     # model_name = "OpenGVLab/InternVL2-8B-AWQ"
> 
>     llm = LLM(
>         model=model_name,
>         dtype="half",
>         # quantization="awq",
>         trust_remote_code=True,
>         max_num_seqs=5,
>         tensor_parallel_size=2,
>         max_num_batched_tokens=8192,
>         max_model_len=4096,
>     )
> 
>     tokenizer = AutoTokenizer.from_pretrained(model_name,
>                                               trust_remote_code=True)
>     messages = [{'role': 'user', 'content': f"<image>\n{question}"}]
>     prompt = tokenizer.apply_chat_template(messages,
>                                            tokenize=False,
>                                            add_generation_prompt=True)
> 
>     # Stop tokens for InternVL
>     # models variants may have different stop tokens
>     # please refer to the model card for the correct "stop words":
>     # https://huggingface.co/OpenGVLab/InternVL2-2B#service
>     stop_tokens = ["<|endoftext|>", "<|im_start|>", "<|im_end|>", "<|end|>"]
>     stop_token_ids = [tokenizer.convert_tokens_to_ids(i) for i in stop_tokens]
>     return llm, prompt, stop_token_ids
> ```
> 
> Can you reinstall from this branch in a clear environment and check again? I guess there may be something wrong in the environment and the installation is not overrided.

8B  tensor_parallel_size=2:
image

When I rebuilt the environment, 8B tensor_parallel_size=2, the operation was OK. However, 26B tensor_parallel_size=4 generates the following error
Changing to tensor_parallel_size 3,5,8 all have similar errors.

26B tensor_parallel_size=4 
image

**Comment by Isotr0py** [comment]
@SovereignRemedy This is because ViTs have supported TP in #7186, and the ViT of 26B has `"num_attention_heads": 25`, which can't be divided by the `tp_size=4`.

Anyway, we can test 8B whose ViT has `"num_attention_heads": 16` with `tensor_parallel=4` for this PR. I think we can add a fallback for ViT to disable TP if unavailable in another PR.

**Comment by Isotr0py** [comment]
> The latest test result 8b tensor_parallel_size=4 runs normally.

@DarkLight1337 This fix is confirmed to work now. Please take a look :)

**Review by DarkLight1337 — APPROVED** [review]
Thanks for implementing and testing this!

**Pull request merged**
