### PR TITLE
[Bugfix] Hermes tool parser fails to check for & handle `None` values in some cases

### LINKED ISSUE #9693: [Bug]: Function calling with stream vs without stream, arguments=None when stream option is enabled
### Your current environment

Dockerfile: vllm/vllm-openai:v0.6.3

Parameters:
`--enable-auto-tool-choice --tool-call-parser hermes`

### Model Input Dumps

_No response_

### 🐛 Describe the bug

I'm using the VLLM library with a Docker container as a REST API, specifically the `v1/chat/completion/` endpoint with the OpenAI client.

When I run chat completions without streaming, it returns `tool_calls` with the tool name and its arguments as expected. However, when I enable the streaming option, it only returns the tool name, with arguments set to `None`. I'm not sure why this is happening.

I've tried searching for related issues but haven’t found anything helpful.
Have tried `stream_options={"include_usage": True}` and it gives same output.

Model generate this output:
```
<tool_call>
{"arguments": {"n1": 2, "n2": 2}, "name": "sum"}
</tool_call>
```

```
chat_completion = client.chat.completions.create(
        model="tgi",
        messages=messages,
        stream=True,
        max_tokens=2000,
        temperature=0.3,
        tools=tools,
        tool_choice="auto",
    )
chunks = []
for chunk in chat_completion:
    chunks.append(chunk)
    if chunk.choices[0].delta.tool_calls:
        print(chunk.choices[0].delta.tool_calls[0])
    else:
        print(chunk.choices[0].delta)


chat_completion = client.chat.completions.create(
        model="tgi",
        messages=messages,
        stream=False,
        max_tokens=2000,
        temperature=0.3,
        tools=tools,
        tool_choice="auto",
    )
print(chat_completion.choices[0].message.tool_calls[0])
```

Output:
- with stream:
```
ChoiceDelta(content='', function_call=None, refusal=None, role='assistant', tool_calls=None)
ChoiceDeltaToolCall(index=0, id='chatcmpl-tool-ac7886c6cea04451b439d4e24b21ab7a', function=ChoiceDeltaToolCallFunction(arguments=None, name='sum'), type='function')
ChoiceDelta(content='', function_call=None, refusal=None, role=None, tool_calls=None)
```
- Without stream
```
ChatCompletionMessageToolCall(id='chatcmpl-tool-736bd066f6744f9985817df30c73aad3', function=Function(arguments='{"n1": 2, "n2": 2}', name='sum'), type='function')
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### LINKED ISSUE #9874: [Bug]: Function calling with Qwen & Streaming ('NoneType' object has no attribute 'get')
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### Model Input Dumps

_No response_

### 🐛 Describe the bug

# vLLM Version
`v0.6.3.post1`

# Model
`Qwen2.5-7B-Instruct`

# Docker command for vLLM
`command: --host 0.0.0.0 --model /hf/Qwen-Qwen2.5-7B-Instruct --max-model-len 32768 --gpu_memory_utilization 0.9 --enable-auto-tool-choice --tool-call-parser hermes`

# Parsing from my own fastapi

```
async def stream_response(payload: dict, log: RequestLogger) -> AsyncGenerator[str, None]:
    """Handle streaming response from vLLM."""
    async with httpx.AsyncClient() as client:
        try:
            async with client.stream(
                'POST',
                VLLM_API_BASE,
                json=payload,
                headers={"Content-Type": "application/json"},
                timeout=30.0
            ) as response:
                if response.status_code != 200:
                    error_msg = f"vLLM API error: {response.status_code}"
                    log(error_msg, level='error')
                    yield f"data: {json.dumps({'error': error_msg})}\n\n"
                    return

                async for line in response.aiter_lines():
                    if not line or not line.startswith('data: '):
                        continue
                        
                    line = line.removeprefix('data: ')
                    if line.strip() == '[DONE]':
                        log("Stream completed")
                        yield 'data: [DONE]\n\n'
                        break
                    
                    try:
                        parsed = json.loads(line)
                        log("Streaming chunk", parsed)

                        # Handle tool calls in streaming response
                        if 'choices' in parsed and parsed['choices']:
                            choice = parsed['choices'][0]
                            if 'delta' in choice and 'tool_calls' in choice['delta']:
                                tool_call = choice['delta']['tool_calls'][0]
                                
                                if ('function' in tool_call and 
                                    'name' in tool_call['function'] and 
                                    'arguments' in tool_call['function']):
                                    
                                    func_name = tool_call['function']['name']
                                    args = json.loads(tool_call['function']['arguments'])
                                    
                                    if func_name == 'add_numbers':
                                        result = add_numbers(args['a'], args['b'])
                                        yield f'data: {json.dumps({"choices": [{"delta": {"content": str(result)}}]})}\n\n'
                                        continue

                        yield f'data: {line}\n\n'
                    except json.JSONDecodeError as e:
                        log(f"Failed to parse streaming response: {str(e)}", level='error')
                        continue

        except httpx.RequestError as e:
            error_msg = f"Streaming request failed: {str(e)}"
            log(error_msg, level='error')
            yield f"data: {json.dumps({'error': error_msg})}\n\n"
        
    log("Stream connection closed")
```

# vLLM error

`vllm  | ERROR 10-30 14:55:01 hermes_tool_parser.py:337] Error trying to handle streaming tool call.
vllm  | ERROR 10-30 14:55:01 hermes_tool_parser.py:337] Traceback (most recent call last):
vllm  | ERROR 10-30 14:55:01 hermes_tool_parser.py:337]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py", line 226, in extract_tool_calls_streaming
vllm  | ERROR 10-30 14:55:01 hermes_tool_parser.py:337]     function_name: Union[str, None] = current_tool_call.get("name")
vllm  | ERROR 10-30 14:55:01 hermes_tool_parser.py:337]                                       ^^^^^^^^^^^^^^^^^^^^^
vllm  | ERROR 10-30 14:55:01 hermes_tool_parser.py:337] AttributeError: 'NoneType' object has no attribute 'get'`

Please note that everything works if

1. Streaming with no tools
2. Not streaming with tools

Any guidance ? 
Thanks in advance everyone

PS: I have seen the posts from https://github.com/vllm-project/vllm/issues/9693 but my issue seems different since i actually use a "supported" model.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by K-Mistele**
This PR patches a bug in the hermes tool parser where certain edge conditions (which are not fully understood, as I have not been able to replicate them) can result in values being set to `None` which causes downstream issues due to a lack of handling `None` in those values. 

While I have not been able to replicate the issue, @ankush13r was kind enough to point me at the specific lines causing the issue. Appropriate checks & handling have been added. 

cc @DarkLight1337 @githebs @ankush13r

FIX #9693 
FIX #9874 

Recommended debugging process for @githebs @ankush13r to determine if this fixes the behavior you are experiencing:

1. Copy the entire updated `HermesToolParser` from this PR onto your local disk. 
2. change the plugin name in the ToolParserManager decorator from this:

    ```python
    @ToolParserManager.register_module("hermes")
    ```
    to this:
    ```python
    @ToolParserManager.register_module("hermes_patched")
    ```

    This prevents the patched version that you'll be testing with, from conflicting with the parser that vLLM comes packaged with.

3. Run vLLM with the following configuration for tools: 
    ```bash
        --enable-auto-tool-choice \
        --tool-parser-plugin /path/to/plugin/file.py \
        --tool-call-parser hermes_patched \ # the renamed tool parser
        --chat-template <your chat template>  # can omit this if you're using your model's default 
    ```
4. Try to reproduce the issue however you encountered it. If you do not have the same issue, then this PR fixes 
#9693 
and #9874. 
If you encounter the same issue, then there is a different problem 

Once this has been tested by @ankush13r and @githebs and they confirm that this fixes their issues, i will move this from a draft to an open PR. 

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Adding or changing kernels</h3>
<p>Each custom kernel needs a schema and one or more implementations to be registered with PyTorch.</p>
<ul>
    <li>Make sure custom ops are registered following PyTorch guidelines: <a href="https://pytorch.org/tutorials/advanced/cpp_custom_ops.html#cpp-custom-ops-tutorial">Custom C++ and CUDA Operators</a> and <a href="https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU">The Custom Operators Manual</a></li>
    <li>Custom operations that return <code>Tensors</code> require meta-functions. Meta-functions should be implemented and registered in python so that dynamic dims can be handled automatically. See above documents for a description of meta-functions.</li>
    <li>Use <a href="https://pytorch.org/docs/stable/library.html#torch.library.opcheck"><code>torch.libary.opcheck()</code></a> to test the function registration and meta-function for any registered ops.  See <code>tests/kernels</code> for examples.</li>
    <li>When changing the C++ signature of an existing op, the schema must be updated to reflect the changes.</li>
    <li>If a new custom type is needed, see the following document: <a href="https://docs.google.com/document/d/18fBMPuOJ0fY5ZQ6YyrHUppw9FA332CpNtgB6SOIgyuA">Custom Class Support in PT2</a>.
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by githebs** [comment]
Hello @K-Mistele thanks for the ping on the two issues https://github.com/vllm-project/vllm/issues/9693 and https://github.com/vllm-project/vllm/issues/9674

Here is what i tried

- Downloaded the new HermesToolParser located at https://github.com/vllm-project/vllm/blob/9ada2b4408924fe1b7c0ac8f7c7abf3dcb7f1f51/vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py
- Changed  the plugin name in the ToolParserManager decorator to `@ToolParserManager.register_module("hermes_patched")` 
- Run vLLm with the command `command: --host 0.0.0.0 --model /models/Qwen-Qwen2.5-7B-Instruct --max-model-len 32768 --gpu_memory_utilization 0.9 --enable-auto-tool-choice  --tool-parser-plugin /tools/hermes_tool_parser.py --tool-call-parser hermes_patched`

The patch did **not** fix the issue, while streaming tools won't worked here is the new error
```
vllm  | INFO 11-01 10:47:43 engine.py:290] Added request chat-0c85bd4ed3ac4c84ae7df36d59ee63bc.
vllm  | INFO 11-01 10:47:43 metrics.py:349] Avg prompt throughput: 47.6 tokens/s, Avg generation throughput: 1.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.6%, CPU KV cache usage: 0.0%.
vllm  | Error trying to handle streaming tool call.
vllm  | Traceback (most recent call last):
vllm  |   File "/tools/hermes_tool_parser.py", line 219, in extract_tool_calls_streaming
vllm  |     flags) if tool_call_portion else None
vllm  |               ^^^^^^^^^^^^^^^^^
vllm  | UnboundLocalError: cannot access local variable 'tool_call_portion' where it is not associated with a value
```

I confirm that normal discussion works and tools without streaming works 
I can jump on the vLLM discord to reproduce the bug on screenshare if needed

**Comment by githebs** [comment]
Just in case it might help i've included a draft of a fastapi endpoint to test vllm with Qwen and that's what made me discover the issue 

I might be totally wrong in the implementation 

```python
import logging
import json
from datetime import datetime
from typing import Dict, Any, List, Optional, AsyncGenerator
import httpx
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from pathlib import Path

# Ensure logs directory exists
Path("logs").mkdir(exist_ok=True)

# API Constants
VLLM_API_BASE = "http://192.168.1.100:9000/v1/chat/completions"
DEFAULT_MODEL = "/models/Qwen-Qwen2.5-7B-Instruct"

# Define tools at module level
DEFAULT_TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_public_ip",
            "description": "Get the public IP address of the server",
            "parameters": {
                "type": "object",
                "properties": {},
                "required": []
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "add_numbers",
            "description": "Add two numbers together",
            "parameters": {
                "type": "object",
                "properties": {
                    "a": {"type": "number", "description": "First number"},
                    "b": {"type": "number", "description": "Second number"}
                },
                "required": ["a", "b"]
            }
        }
    }
]

router = APIRouter()

class ChatRequest(BaseModel):
    messages: List[Dict[str, str]] = [
        {"role": "assistant", "content": "You are a useful assistant."},
        {"role": "user", "content": "hello"}
    ]
    temperature: Optional[float] = 0.7
    tools: Optional[List[Dict]] = DEFAULT_TOOLS

class RequestLogger:
    def __init__(self):
        self.start_time = datetime.now()
        
        # Create a unique log file for this request using detailed timestamp
        log_dir = Path("logs")
        log_dir.mkdir(exist_ok=True)
        
        # Format: chat_YYYYMMDD_HHMMSS_microseconds.log
        self.request_id = self.start_time.strftime("%Y%m%d_%H%M%S_%f")
        self.file_handler = logging.FileHandler(
            f'logs/chat_{self.request_id}.log'
        )
        
        # Configure formatter
        formatter = logging.Formatter(
            '%(asctime)s - %(levelname)s - %(message)s'
        )
        self.file_handler.setFormatter(formatter)
        
        # Create a logger specific to this request
        self.logger = logging.getLogger(f'chat.{self.request_id}')
        self.logger.setLevel(logging.INFO)
        self.logger.addHandler(self.file_handler)
        
        # Prevent propagation to root logger
        self.logger.propagate = False

    def __call__(self, msg: str, data: Any = None, level: str = 'info'):
        elapsed = (datetime.now() - self.start_time).total_seconds()
        
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'request_id': self.request_id,
            'elapsed_seconds': round(elapsed, 3),
            'message': msg,
            'data': data
        }
        
        getattr(self.logger, level)(
            json.dumps(log_entry, ensure_ascii=False)
        )

    def __del__(self):
        # Clean up handlers when the logger is destroyed
        if hasattr(self, 'file_handler'):
            self.file_handler.close()
            self.logger.removeHandler(self.file_handler)

def add_numbers(a: float, b: float) -> float:
    """Simple addition function."""
    return a + b

def get_public_ip() -> str:
    """Get the public IP address using ifconfig.me."""
    try:
        response = httpx.get("https://ifconfig.me", timeout=5)
        return response.text.strip()
    except httpx.RequestError as e:
        return f"Failed to get IP: {str(e)}"

async def stream_response(payload: dict, log: RequestLogger) -> AsyncGenerator[str, None]:
    """Handle streaming response from vLLM."""
    async with httpx.AsyncClient() as client:
        try:
            async with client.stream(
                'POST',
                VLLM_API_BASE,
                json=payload,
                headers={"Content-Type": "application/json"},
                timeout=30.0
            ) as response:
                if response.status_code != 200:
                    error_msg = f"vLLM API error: {response.status_code}"
                    log(error_msg, level='error')
                    yield f"data: {json.dumps({'error': error_msg})}\n\n"
                    return

                async for line in response.aiter_lines():
                    if not line or not line.startswith('data: '):
                        continue
                        
                    line = line.removeprefix('data: ')
                    if line.strip() == '[DONE]':
                        log("Stream completed")
                        yield 'data: [DONE]\n\n'
                        break
                    
                    try:
                        parsed = json.loads(line)
                        log("Streaming chunk", parsed)

                        # Handle tool calls in streaming response
                        if 'choices' in parsed and parsed['choices']:
                            choice = parsed['choices'][0]
                            if 'delta' in choice and 'tool_calls' in choice['delta']:
                                tool_call = choice['delta']['tool_calls'][0]
                                
                                if ('function' in tool_call and 
                                    'name' in tool_call['function'] and 
                                    'arguments' in tool_call['function']):
                                    
                                    func_name = tool_call['function']['name']
                                    args = json.loads(tool_call['function']['arguments'])
                                    
                                    if func_name == 'add_numbers':
                                        result = add_numbers(args['a'], args['b'])
                                        yield f'data: {json.dumps({"choices": [{"delta": {"content": str(result)}}]})}\n\n'
                                        continue

                        yield f'data: {line}\n\n'
                    except json.JSONDecodeError as e:
                        log(f"Failed to parse streaming response: {str(e)}", level='error')
                        continue

        except httpx.RequestError as e:
            error_msg = f"Streaming request failed: {str(e)}"
            log(error_msg, level='error')
            yield f"data: {json.dumps({'error': error_msg})}\n\n"
        
    log("Stream connection closed")

@router.post("/chat/completions")
async def chat_completion(request: ChatRequest, raw_request: Request):
    log = RequestLogger()
    
    # Parse raw request to check for streaming
    request_body = await raw_request.json()
    is_streaming = request_body.get('stream', False)
    
    # Use default tools if none provided
    tools = request.tools if request.tools is not None else DEFAULT_TOOLS
    
    log("Received chat completion request", {
        "messages": request.messages,
        "temperature": request.temperature,
        "tools": tools,
        "stream": is_streaming
    })

    try:
        payload = {
            "model": DEFAULT_MODEL,
            "messages": request.messages,
            "temperature": request.temperature,
            "stream": is_streaming,
            "tools": tools
        }

        log("Sending request to vLLM", payload)
        
        if is_streaming:
            return StreamingResponse(
                stream_response(payload, log),
                media_type='text/event-stream'
            )

        # Non-streaming response handling
        async with httpx.AsyncClient() as client:
            response = await client.post(
                VLLM_API_BASE,
                headers={"Content-Type": "application/json"},
                json=payload,
                timeout=30.0
            )

            if not response.content:
                log("Empty response from vLLM API", level='error')
                raise HTTPException(status_code=500, detail="Empty response from API")

            result = response.json()
            log("Received response from vLLM", result)

            # Handle tool calls if present
            if "choices" in result and result["choices"] and "message" in result["choices"][0]:
                message = result["choices"][0]["message"]
                if "tool_calls" in message and message["tool_calls"]:
                    log("Processing tool calls", message["tool_calls"])
                    
                    # Add assistant's tool call message to conversation
                    messages = request.messages + [{
                        "role": "assistant",
                        "content": None,
                        "tool_calls": message["tool_calls"]
                    }]

                    for tool_call in message["tool_calls"]:
                        try:
                            func_name = tool_call["function"]["name"]
                            args = json.loads(tool_call["function"]["arguments"])
                            
                            if func_name == "get_public_ip":
                                tool_result = get_public_ip()
                            elif func_name == "add_numbers":
                                tool_result = add_numbers(args["a"], args["b"])
                            else:
                                raise ValueError(f"Unknown tool: {func_name}")
                            
                            log(f"Tool execution result for {func_name}", tool_result)
                            
                            # Add tool result to messages
                            messages.append({
                                "role": "tool",
                                "tool_call_id": tool_call["id"],
                                "name": func_name,
                                "content": str(tool_result)
                            })

                        except Exception as e:
                            error_msg = f"Tool execution failed: {str(e)}"
                            log(error_msg, level='error')
                            raise HTTPException(status_code=500, detail=error_msg)

                    # Make another call to vLLM with tool results
                    final_payload = {
                        "model": DEFAULT_MODEL,
                        "messages": messages,
                        "temperature": request.temperature,
                        "stream": is_streaming,
                        "tools": tools
                    }
                    
                    final_response = await client.post(
                        VLLM_API_BASE,
                        headers={"Content-Type": "application/json"},
                        json=final_payload,
                        timeout=30.0
                    )
                    
                    result = final_response.json()
                    log("Received final response from vLLM", result)

            return result

    except httpx.RequestError as e:
        error_msg = f"Request to vLLM failed: {str(e)}"
        log(error_msg, level='error')
        raise HTTPException(status_code=500, detail=error_msg)
    except Exception as e:
        error_msg = f"Unexpected error: {str(e)}"
        log(error_msg, level='error')
        raise HTTPException(status_code=500, detail=error_msg)
```

**Comment by K-Mistele** [comment]
Out of curiosity, are you trying to get the model to call the function with the empty arguments object? I wonder if that's the issue; the parser may not handle that case properly due to how the streaming extraction works. If you're trying that, can you try to get it to call a version of the function with non-empty arguments and see if that resolve the issue? I will dig in more in the meantime

**Comment by K-Mistele** [comment]
cc @frei-x 

https://github.com/vllm-project/vllm/issues/9874#issuecomment-2456329070

**Comment by githebs** [comment]
I re-implemented from scratch with and without the openai package and i can confirm that all parser versions fail if the tool doesn't have arguments

i can reproduce the bug each time and it goes away (with streaming) if arguments are present

**Pull request closed without merging**
