### PR TITLE
[CI/Build] Check transformers v4.47

### PR DESCRIPTION
**Pull request by DarkLight1337**
See if it's safe to update to transformers v4.47 by running our CI on the new version.

### CODE REVIEW

**Comment by Isotr0py** [comment]
Seems that `test_video.py` for entrypoint test is failing, let me run it locally to have a look...

**Comment by DarkLight1337** [comment]
I think it's just a timeout error from downloading the video.

**Comment by Isotr0py** [comment]
Oh, yea, just realized it's due to timeout. The entrypoint test CI log is too long to read. 😅

**Review by Isotr0py — APPROVED** [review]
LGTM since the failing entrypoint test passed on my side. 

BTW, we need to address the failling mamba test in a following PR as well.

**Pull request merged**
