### PR TITLE
[Doc] Add the start of an arch overview page

### PR DESCRIPTION
**Pull request by russellb**
My intent with this page is to provide a high-level architectural
overview of the major components of vLLM by taking a look one layer at
a time. So far, I have the first two sections: entrypoints and the LLM
engine.

The diagrams here were build with [excalidraw](https://excalidraw.com),
which embeds diagram metadata into the PNG file, allowing others to
load the image back into the tool and edit the diagram in the future
if needed.

Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Comment by simon-mo** [comment]
great start, please lmk when it is ready for review. I believe adding it here will be useful https://docs.vllm.ai/en/latest/design/class_hierarchy.html 

Please also feel free to reference https://docs.google.com/document/d/16AljLGnJpBh8_jStNo05Hk3c323fV6JEf735yb8zCIE/edit?tab=t.0#heading=h.10kvp2c16c3d

**Comment by russellb** [comment]
> great start, please lmk when it is ready for review. I believe adding it here will be useful https://docs.vllm.ai/en/latest/design/class_hierarchy.html

Ah, yes, there's some overlap with that page. I think I can combine them.
 
> Please also feel free to reference https://docs.google.com/document/d/16AljLGnJpBh8_jStNo05Hk3c323fV6JEf735yb8zCIE/edit?tab=t.0#heading=h.10kvp2c16c3d

Thanks!

**Comment by russellb** [comment]
@simon-mo I think it's ready for review. I merged with the class hierarchy doc. I think it's a reasonable checkpoint. There's a ton more that could be added, but I've got to make sure I don't put too much time on anything that'll be irrelevant soon under the V1 work.  cc @youkaichao 

https://vllm--10368.org.readthedocs.build/en/10368/design/arch_overview.html

**Review by youkaichao — COMMENTED** [review]
great job! note that this line also needs to be updated:

https://github.com/vllm-project/vllm/blob/272e31c0bd8640c15e85211c74fc9b428ad86902/vllm/model_executor/model_loader/loader.py#L108

**Comment by youkaichao** [comment]
I will leave it for @simon-mo  for the final review.

**Review by simon-mo — APPROVED** [review]

**Comment by russellb** [comment]
> great job! note that this line also needs to be updated:
> 
> https://github.com/vllm-project/vllm/blob/272e31c0bd8640c15e85211c74fc9b428ad86902/vllm/model_executor/model_loader/loader.py#L108

sorry for missing this! A fix is in #10455

**Pull request merged**
