### PR TITLE
fix : stream async-cancelled

### PR DESCRIPTION
**Pull request by lots-o**
In the current implementation of `vllm.entry_points.api_server.py`, the **stream** operation **does not gracefully handle user request cancellations.**

To address this concern, I have made the following modification:
- Added code to handle the `asyncio.CancelledError` and perform the necessary abort operation when it occurs.

I kindly request your review and feedback on this proposed change.

### CODE REVIEW

**Comment by esmeetu** [comment]
hey, @lots-o  i haven't reproduced this issue.
Could you share your example?

**Comment by lots-o** [comment]
> hey, @lots-o  i haven't reproduced this issue.
> Could you share your example?
> Please refer to comments in #1102

Hi, @esmeetu 

I read the #1102, but in my test environment, the "finished" log is recorded after inference without immediately aborting the request('stream=true').My test environment is as follows:

1. Launch the api_server for a custom model.
2. Request 'stream=true' from the Thunder API extension in vscode. (Generate a long sentence that may cause a delay during inference)
3. Cancel the request in the Thunder extension.
4. The "finished" log is recorded after the inference is completed without immediately aborting the request.

I tested it specifically in a Docker environment with 'nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04'

**Comment by lots-o** [comment]
@esmeetu  
image
I think I was mistaken. Just as you said, when I executed `python -m vllm.entrypoints.api_server`, it worked well without any issues upon retesting. However, when I ran the Python file like `python api_server.py` , it didn't work that way. Is there a possibility that I misunderstood something? If so, could you please clarify? (The api_server code remains the same.)

**Comment by zhuohan123** [comment]
@esmeetu Given what you said in #1102, do you think this PR is necessary to be merged?

**Comment by esmeetu** [comment]
@zhuohan123 I will attempt to replicate this using the python api_server for testing and provide feedback later.

**Comment by esmeetu** [comment]
@lots-o It still can't be reproduced.
@zhuohan123 Could you reproduce this? I have no idea.

More info:

python vllm/entrypoints/api_server.py --model /CodeLlama-7b-Instruct-hf --tensor-parallel-size 2 --host 0.0.0.0 --port 8060 --dtype half --max-model-len 8192
WARNING 09-28 06:03:58 config.py:348] Casting torch.bfloat16 to torch.float16.
2023-09-28 06:04:00,738 INFO worker.py:1633 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
INFO 09-28 06:04:01 llm_engine.py:72] Initializing an LLM engine with config: model='/CodeLlama-7b-Instruct-hf', tokenizer='/CodeLlama-7b-Instruct-hf', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=None, seed=0)
INFO 09-28 06:04:01 tokenizer.py:30] For some LLaMA V1 models, initializing the fast tokenizer may take a long time. To reduce the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
INFO 09-28 06:04:24 llm_engine.py:202] # GPU blocks: 1809, # CPU blocks: 1024
INFO:     Started server process [3213836]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8060 (Press CTRL+C to quit)
INFO:     127.0.0.1:64173 - "POST /generate HTTP/1.1" 200 OK
INFO 09-28 06:05:52 async_llm_engine.py:371] Received request d18046e37add4f29aac7e21448de4b26: prompt: '[INST] implement quick sort [/INST]', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, temperature=0, top_p=1.0, top_k=-1, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], ignore_eos=False, max_tokens=512, logprobs=None, skip_special_tokens=True), prompt token ids: None.
INFO 09-28 06:05:52 llm_engine.py:613] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 09-28 06:05:57 llm_engine.py:613] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 31.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.6%, CPU KV cache usage: 0.0%
INFO 09-28 06:05:58 async_llm_engine.py:134] Aborted request d18046e37add4f29aac7e21448de4b26.

image

**Comment by esmeetu** [comment]
@lots-o I check your log again. Your async_llm_engine is not right where line 100 doesn't have a Finished log.
Could you check again? Be sure use latest branch without local modifications.

**Comment by lots-o** [comment]
@esmeetu I'll double-check it once again and provide feedback. Thank you for checking!

**Comment by lots-o** [comment]
image

@esmeetu  I'm so sorry.. It was my mistake.

As you suggested, I checked the version and tested it, and there doesn't seem to be any issue!

Thank you for your attention!!

**Pull request closed without merging**
