### PR TITLE
Include tokens from prompt phase in `counter_generation_tokens`

### PR DESCRIPTION
**Pull request by ronensc**
I noticed that the `counter_generation_tokens` metric was missing tokens generated during the prompt phase, only counting those from the autoregressive generation phase. This PR addresses that by incorporating tokens from both phases into the counter. Also, I've added a simple unit test to verify the counter.

### CODE REVIEW

**Comment by rib-2** [comment]
@ronensc 

Just so I am clear, the need for this comes from the fact that `num_batched_tokens` in the `prompt_run` case only includes the prefill tokens and none of the new tokens generated?

**Comment by ronensc** [comment]
> @ronensc
> 
> Just so I am clear, the need for this comes from the fact that `num_batched_tokens` in the `prompt_run` case only includes the prefill tokens and none of the new tokens generated?

correct.

**Review by NikolaBorisov — APPROVED** [review]
LGTM. 
Yeah, we missed counting those. We can merge this.

**Comment by NikolaBorisov** [comment]
@simon-mo This is safe to merge.

**Comment by NikolaBorisov** [comment]
@simon-mo Can we merge this. I reviewed it. It is safe and good

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
