### PR TITLE
[Bugfix] Fix prefix strings for quantized VLMs

### PR DESCRIPTION
**Pull request by mgoin**
The prefix strings were not being constructed correctly for many VLMs, particularly due to the use of sub-models. This was causing `quant_config` to be enabled for modules that are ignored within the `quantization_config` of the model, causing failures during weight loading.

It's important to note that the "XForCausalLM" classes can be used as sub-models in VLMs (Gemma and Llama are easy examples), so we need to have the ability to optionally specify the prefix to those classes. For example in Llama you could have a module name `model.layers.0.mlp.down_proj`, but when it is used within a VLM that module name should be `language_model.model.layers.0.mlp.down_proj`
I propose a `maybe_prefix(prefix, name)` function that handles this logic. 

I think in the future we should consider making `prefix` a required argument in many cases to make issues less likely, rather than a default empty string.

Tested models:
* `nm-testing/MiniCPM-V-2_6-FP8-dynamic`
* `nm-testing/paligemma-3b-mix-224-FP8-dynamic`
* `neuralmagic/Llama-3.2-11B-Vision-Instruct-FP8-dynamic`
* `nm-testing/Qwen2-VL-7B-Instruct-FP8-dynamic`
* `nm-testing/pixtral-12b-FP8-dynamic`
* `nm-testing/Phi-3.5-vision-instruct-FP8-dynamic`
* `nm-testing/llava-onevision-qwen2-7b-ov-hf-FP8-dynamic`

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Thanks for taking the time and effort for adding this! I think this should solve most of the quantization-related GH issues?
- #6932
- #7724
- #7727
- #8463
- #9324

**Comment by mgoin** [comment]
@DarkLight1337 A few of the issues you linked (and shared earlier with me) are specific to bitsandbytes support, so will require more work but I want to tackle those in future PRs since BNB is special

**Review by DarkLight1337 — APPROVED** [review]
LGTM then. See if @Isotr0py is ok with this approach as well.

**Review by Isotr0py — APPROVED** [review]
LGTM! 

BTW, if we want to broadcast the BNB support to most of VLMs, we might need to implement quantized `multi_modal_proj` (if they have) as well. Because user will possibly create a fully quantized (even the `lm_head` and `multi_modal_proj`) BNB model if they refer to the guidance in `transformers`...

**Pull request merged**
