### PR TITLE
[Bugfix] Revert "[Bugfix] use SoftLockFile instead of LockFile (#3578)"

### PR DESCRIPTION
**Pull request by WoosukKwon**
Reverts #3578 for backward compatibility.

### CODE REVIEW

**Review by zhuohan123 — APPROVED** [review]

**Comment by kota-iizuka** [comment]
@WoosukKwon Please use `lockfile.Lockfile(mode=666)` to fix bugs with multi-user usage. https://github.com/vllm-project/vllm/pull/3578#issuecomment-2016731684

**Comment by youkaichao** [comment]
Let me send a fix.

**Comment by youkaichao** [comment]
@kota-iizuka can you test if this branch works as you want now?

**Comment by kota-iizuka** [comment]
> can you test if this branch works as you want now?

@youkaichao I did an experiment, but contrary to expectations I got the same permission denied error. I'll look into the method a little more

**Comment by kota-iizuka** [comment]
> I'll look into the method a little more

This modification in vLLM is OK for me.

I found the bug is in `filelock`. https://github.com/tox-dev/filelock/blob/main/src/filelock/_unix.py#L38 uses `os.O_CREAT`, so if a file already created by another user exists, It will be the permission error.

**Comment by youkaichao** [comment]
If multiple users use one server together, they should have their own directory for storing models.

> This modification in vLLM is OK for me.

Then I will merge it now.

**Pull request merged**
