### PR TITLE
[CI/Build] Increasing timeout for multiproc worker tests

### PR DESCRIPTION
**Pull request by akondrat-amd**
On ROCm we have to use spawn instead of fork and it creates an overhead, so five seconds might not be enough to create and destroy eight worker processes.
Please note, increasing the timeout to 60 seconds will not impact the test execution time unless there is a problem.

FIX #xxxx (*link existing issues this PR will resolve*)

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by Alexei-V-Ivanov-AMD** [comment]
This PR fixes the "AMD Engine Test". The int argument of the join() operator defines the maximal count of seconds to wait for joining. Increasing this parameter doesn't result in the delay, rather it increases resilience of the tests that might be run on different machines, in different computational contexts, with different levels of host occupancy.

**Comment by simon-mo** [comment]
@njhill is increasing this timeout okay?

**Comment by njhill** [comment]
@Alexei-V-Ivanov-AMD this test exercises the multiproc worker mechanics in isolation, with dummy worker impls. I don’t think the time difference it takes to start these dummy workers with spawn vs fork would be very significant?

**Comment by alexeykondrat** [comment]
> @Alexei-V-Ivanov-AMD this test exercises the multiproc worker mechanics in isolation, with dummy worker impls. I don’t think the time difference it takes to start these dummy workers with spawn vs fork would be very significant?

@njhill The experiment shows that it takes approximately 5-6 seconds to spawn those processes and less than a second if we fork them. So, 5 second timeout is not enough.

**Comment by Alexei-V-Ivanov-AMD** [comment]
@njhill 

From https://docs.python.org/3.10/library/multiprocessing.html#contexts-and-start-methods

"Starting a process using this method [spawn] is rather slow compared to using fork or forkserver."

**Comment by youkaichao** [comment]
just chiming in, if you cannot resolve the disagreement, you can introduce an env var like `VLLM_MP_JOIN_TIMEOUE`, set it to 2 by default, and override it in the rocm backend, just like what I did in https://github.com/vllm-project/vllm/blob/de80783b6907eb084493a76ef9ec3e3941cc2087/vllm/platforms/rocm.py#L13-L17

**Comment by Alexei-V-Ivanov-AMD** [comment]
@youkaichao I don't think this divergence between the platforms is necessary. As mentioned above, setting the time count to a reasonably large value will only affect our expectations on when the wait for the join operator becomes a burden. That way we only increase resilience of the test (something that is opposite to "flakiness", and we all want that test to be resilient). If join occurs faster, the execution continues without a delay.

**Comment by youkaichao** [comment]
makes sense to me, let me chat with @njhill

**Comment by njhill** [comment]
Hey sorry ... no disagreement and sorry didn't mean to make a big deal of this, I was just trying to understand because this should be a platform-agnostic test. My only hesitation to bumping the timeout that much higher is in case we make some change to the mechanics that causes it to unintentionally take much longer, then we wouldn't catch it.

How about just increasing to something not quite as large, like 20 sec?

**Comment by Alexei-V-Ivanov-AMD** [comment]
@njhill 

>How about just increasing to something not quite as large, like 20 sec?

IMHO it'll work fine.

**Review by njhill — APPROVED** [review]
Thanks @alexeykondrat @Alexei-V-Ivanov-AMD

**Pull request merged**
