### PR TITLE
[Model] Add AWQ quantization support for InternVL2 model

### PR DESCRIPTION
**Pull request by Isotr0py**
FILL IN THE PR DESCRIPTION HERE

FIX #xxxx (*link existing issues this PR will resolve*)
- This PR add support for AWQ quantized InternVL2 model like [OpenGVLab/InternVL2-2B-AWQ](https://huggingface.co/OpenGVLab/InternVL2-2B-AWQ) etc

**TODO**
- [x] Add AWQ support for InternVL2 model
- [x] Add quantized VLM test

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by Isotr0py** [comment]
Let's see whether the 26B awq can work on test CI.

**Comment by Isotr0py** [comment]
The 26B AWQ model test costs about 22GB on my local environment with an RTX3090Ti:
```shell
$ pytest -s -v tests/models/test_internvl.py::test_large_models
================================================================================== test session starts ===================================================================================
platform linux -- Python 3.12.3, pytest-8.3.2, pluggy-1.5.0 -- /root/miniconda3/bin/python
cachedir: .pytest_cache
rootdir: /root/autodl-tmp/vllm
configfile: pyproject.toml
plugins: shard-0.1.2, rerunfailures-14.0, forked-1.6.0, asyncio-0.23.8, anyio-4.4.0
asyncio: mode=Mode.STRICT
collected 1 item                                                                                                                                                                         
Running 1 items in this shard: tests/models/test_internvl.py::test_large_models[128-half-expected_outputs0-/root/autodl-tmp/InternVL2-26B-AWQ]

tests/models/test_internvl.py::test_large_models[128-half-expected_outputs0-/root/autodl-tmp/InternVL2-26B-AWQ] WARNING 08-09 11:08:27 config.py:1483] Casting torch.bfloat16 to torch.float16.
WARNING 08-09 11:08:27 config.py:286] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 08-09 11:08:27 llm_engine.py:176] Initializing an LLM engine (v0.5.4) with config: model='/root/autodl-tmp/InternVL2-26B-AWQ', speculative_config=None, tokenizer='/root/autodl-tmp/InternVL2-26B-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=1024, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/root/autodl-tmp/InternVL2-26B-AWQ, use_v2_block_manager=False, enable_prefix_caching=False)
WARNING 08-09 11:08:27 tokenizer.py:137] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 08-09 11:08:27 model_runner.py:721] Starting to load model /root/autodl-tmp/InternVL2-26B-AWQ...
Loading pt checkpoint shards:   0% Completed | 0/13 [00:00<?, ?it/s]
Loading pt checkpoint shards:   8% Completed | 1/13 [00:00<00:09,  1.21it/s]
Loading pt checkpoint shards:  15% Completed | 2/13 [00:02<00:12,  1.15s/it]
Loading pt checkpoint shards:  23% Completed | 3/13 [00:03<00:12,  1.22s/it]
Loading pt checkpoint shards:  31% Completed | 4/13 [00:04<00:11,  1.26s/it]
Loading pt checkpoint shards:  38% Completed | 5/13 [00:06<00:10,  1.29s/it]
Loading pt checkpoint shards:  46% Completed | 6/13 [00:07<00:09,  1.32s/it]
Loading pt checkpoint shards:  54% Completed | 7/13 [00:08<00:06,  1.07s/it]
Loading pt checkpoint shards:  62% Completed | 8/13 [00:09<00:05,  1.08s/it]
Loading pt checkpoint shards:  69% Completed | 9/13 [00:10<00:04,  1.14s/it]
Loading pt checkpoint shards:  77% Completed | 10/13 [00:11<00:03,  1.13s/it]
Loading pt checkpoint shards:  85% Completed | 11/13 [00:12<00:02,  1.02s/it]
Loading pt checkpoint shards:  92% Completed | 12/13 [00:13<00:01,  1.04s/it]
Loading pt checkpoint shards: 100% Completed | 13/13 [00:14<00:00,  1.07s/it]
Loading pt checkpoint shards: 100% Completed | 13/13 [00:14<00:00,  1.12s/it]

INFO 08-09 11:08:45 model_runner.py:733] Loading model weights took 21.7726 GB
WARNING 08-09 11:08:45 model_runner.py:898] Computed max_num_seqs (min(256, 2048 // 3328)) to be less than 1. Setting it to the minimum value of 1.
WARNING 08-09 11:08:46 tokenizer.py:137] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 08-09 11:08:51 gpu_executor.py:102] # GPU blocks: 209, # CPU blocks: 1365
```

It's strange that the CI will OOM with L4 having same VRAM as 3090 refer to [CI log](https://buildkite.com/vllm/ci-aws/builds/6471#01913293-7889-456c-87f6-3b06ab6da4ea).

**Comment by Isotr0py** [comment]
@DarkLight1337 Seems that the CI still has not enough VRAM to run the 26B-AWQ model refer to [latest CI log](https://buildkite.com/vllm/ci-aws/builds/6471#01913293-7889-456c-87f6-3b06ab6da4ea).

**Comment by DarkLight1337** [comment]
> The 26B AWQ model test costs about 22GB on my local environment with an RTX3090Ti:
> ```shell
> $ pytest -s -v tests/models/test_internvl.py::test_large_models
> ================================================================================== test session starts ===================================================================================
> platform linux -- Python 3.12.3, pytest-8.3.2, pluggy-1.5.0 -- /root/miniconda3/bin/python
> cachedir: .pytest_cache
> rootdir: /root/autodl-tmp/vllm
> configfile: pyproject.toml
> plugins: shard-0.1.2, rerunfailures-14.0, forked-1.6.0, asyncio-0.23.8, anyio-4.4.0
> asyncio: mode=Mode.STRICT
> collected 1 item                                                                                                                                                                         
> Running 1 items in this shard: tests/models/test_internvl.py::test_large_models[128-half-expected_outputs0-/root/autodl-tmp/InternVL2-26B-AWQ]
> 
> tests/models/test_internvl.py::test_large_models[128-half-expected_outputs0-/root/autodl-tmp/InternVL2-26B-AWQ] WARNING 08-09 11:08:27 config.py:1483] Casting torch.bfloat16 to torch.float16.
> WARNING 08-09 11:08:27 config.py:286] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
> INFO 08-09 11:08:27 llm_engine.py:176] Initializing an LLM engine (v0.5.4) with config: model='/root/autodl-tmp/InternVL2-26B-AWQ', speculative_config=None, tokenizer='/root/autodl-tmp/InternVL2-26B-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=1024, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/root/autodl-tmp/InternVL2-26B-AWQ, use_v2_block_manager=False, enable_prefix_caching=False)
> WARNING 08-09 11:08:27 tokenizer.py:137] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
> INFO 08-09 11:08:27 model_runner.py:721] Starting to load model /root/autodl-tmp/InternVL2-26B-AWQ...
> Loading pt checkpoint shards:   0% Completed | 0/13 [00:00<?, ?it/s]
> Loading pt checkpoint shards:   8% Completed | 1/13 [00:00<00:09,  1.21it/s]
> Loading pt checkpoint shards:  15% Completed | 2/13 [00:02<00:12,  1.15s/it]
> Loading pt checkpoint shards:  23% Completed | 3/13 [00:03<00:12,  1.22s/it]
> Loading pt checkpoint shards:  31% Completed | 4/13 [00:04<00:11,  1.26s/it]
> Loading pt checkpoint shards:  38% Completed | 5/13 [00:06<00:10,  1.29s/it]
> Loading pt checkpoint shards:  46% Completed | 6/13 [00:07<00:09,  1.32s/it]
> Loading pt checkpoint shards:  54% Completed | 7/13 [00:08<00:06,  1.07s/it]
> Loading pt checkpoint shards:  62% Completed | 8/13 [00:09<00:05,  1.08s/it]
> Loading pt checkpoint shards:  69% Completed | 9/13 [00:10<00:04,  1.14s/it]
> Loading pt checkpoint shards:  77% Completed | 10/13 [00:11<00:03,  1.13s/it]
> Loading pt checkpoint shards:  85% Completed | 11/13 [00:12<00:02,  1.02s/it]
> Loading pt checkpoint shards:  92% Completed | 12/13 [00:13<00:01,  1.04s/it]
> Loading pt checkpoint shards: 100% Completed | 13/13 [00:14<00:00,  1.07s/it]
> Loading pt checkpoint shards: 100% Completed | 13/13 [00:14<00:00,  1.12s/it]
> 
> INFO 08-09 11:08:45 model_runner.py:733] Loading model weights took 21.7726 GB
> WARNING 08-09 11:08:45 model_runner.py:898] Computed max_num_seqs (min(256, 2048 // 3328)) to be less than 1. Setting it to the minimum value of 1.
> WARNING 08-09 11:08:46 tokenizer.py:137] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
> INFO 08-09 11:08:51 gpu_executor.py:102] # GPU blocks: 209, # CPU blocks: 1365
> ```
> 
> It's strange that the CI will OOM on L4 with 24G VRAM refer to [CI log](https://buildkite.com/vllm/ci-aws/builds/6471#01913293-7889-456c-87f6-3b06ab6da4ea).

vLLM only uses 90% of the GPU memory by default. You can try setting `gpu_memory_utilization` to a higher value in your test. If this doesn't work, we might have to test the model in distributed tests which can split it over multiple GPUs.

**Comment by Isotr0py** [comment]
I have passed `gpu_memory_utilization=1.0` and `cpu_offload_gb=4` to `vllm_runner` but it still keeps OOM. I agree that we can add this model to distributed tests.

**Comment by Isotr0py** [comment]
@DarkLight1337 The VLM tests have passed again. Can you please take a look at this? Thanks!

**Review by DarkLight1337 — APPROVED** [review]
Thanks for enabling this!

**Pull request merged**
