### PR TITLE
[CI/Build] Unpin outlines

### LINKED ISSUE #4153: [Feature]: No `outlines` strong dependency
### 🚀 The feature, motivation and pitch

https://github.com/vllm-project/vllm/blob/main/requirements-common.txt

Here vllm has `outlines == 0.0.34`
But starting from [v0.0.38](https://github.com/outlines-dev/outlines/releases/tag/0.0.38) outlines has VLLM integration https://github.com/outlines-dev/outlines/pull/772

But I can't update to latest vllm to use it, as it rises versioning error
This error can be ignored
But can somehow this be resolved?

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by br3no**
Unpin the outlines dependency.

FIX #4153

Since work on #4109 will take a bit longer...

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by simon-mo** [comment]
I think the reason for the pin is exactly the error here in test... 
```

_________ ERROR collecting tests/entrypoints/test_guided_processors.py _________
--
  | ImportError while importing test module '/vllm-workspace/tests/entrypoints/test_guided_processors.py'.
  | Hint: make sure your test modules/packages have valid Python names.
  | Traceback:
  | /usr/lib/python3.10/importlib/__init__.py:126: in import_module
  | return _bootstrap._gcd_import(name[level:], package, level)
  | entrypoints/test_guided_processors.py:8: in <module>
  | from vllm.model_executor.guided_decoding import (
  | /usr/local/lib/python3.10/dist-packages/vllm/model_executor/guided_decoding/__init__.py:5: in <module>
  | from vllm.model_executor.guided_decoding.lm_format_enforcer_decoding import (
  | /usr/local/lib/python3.10/dist-packages/vllm/model_executor/guided_decoding/lm_format_enforcer_decoding.py:15: in <module>
  | from vllm.model_executor.guided_decoding.outlines_decoding import (
  | /usr/local/lib/python3.10/dist-packages/vllm/model_executor/guided_decoding/outlines_decoding.py:15: in <module>
  | from vllm.model_executor.guided_decoding.outlines_logits_processors import (
  | /usr/local/lib/python3.10/dist-packages/vllm/model_executor/guided_decoding/outlines_logits_processors.py:24: in <module>
  | from outlines.fsm.fsm import CFGFSM, FSM, RegexFSM
  | E   ImportError: cannot import name 'FSM' from 'outlines.fsm.fsm' (/usr/local/lib/python3.10/dist-packages/outlines/fsm/fsm.py)


```

**Comment by br3no** [comment]
I have removed the `FSM` import that made this particular test fail. 

The thing is that the underlying implementation is the same as with the `Guide` interface and the issue reported in https://github.com/outlines-dev/outlines/issues/856 will break tests again.

I'm afraid we'll have to wait for this issue to be fixed.

I'm inclined to close this PR...

**Comment by saattrupdan** [comment]
> I have removed the `FSM` import that made this particular test fail.
> 
> The thing is that the underlying implementation is the same as with the `Guide` interface and the issue reported in [outlines-dev/outlines#856](https://github.com/outlines-dev/outlines/issues/856) will break tests again.
> 
> I'm afraid we'll have to wait for this issue to be fixed.
> 
> I'm inclined to close this PR...

There are several of us who are not using the `vllm` implementation of `outlines`, but we are merely using standard `vllm` with the `JSONLogitsProcessor` from `outlines` directly - this works perfectly fine. I don't really see why `vllm` needs its own "copy" of the `outlines` code, rather than just importing it? In any case, I would be perfectly happy if all imports from `outlines` in the `vllm` code could be packed away in a function, since that's what's blocking me right now.

**Comment by br3no** [comment]
It's up for the maintainers of vLLM to decide what exactly is to be done here.

We can:
1. wait for https://github.com/outlines-dev/outlines/issues/856 to be fixed and only then unpin outlines
2. unpin outlines and disable the failing test (this is a regression) and re-enable the test once the issue above is fixed
3. make the dependency of outlines optional (@saattrupdan if you feel strongly about this, then I would recommend you open a PR for it...)

**Comment by simon-mo** [comment]
>  I don't really see why vllm needs its own "copy" of the outlines code, rather than just importing it?

This is recommended by the outlines maintainers for us to maintain the logits processor interface and keep the interface between libraries at the FSM/Guide level.

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
Hmmm. It's generating '3.5.0.10653515246264', maybe tune the temperature or prompting? 
https://buildkite.com/vllm/ci/builds/6481#018f3d50-d8eb-4258-8260-ef486c1466ca/51-578

**Comment by br3no** [comment]
@simon-mo that’s the regression described in https://github.com/outlines-dev/outlines/issues/856. This is a bug in outlines. 

We can either disable the test, or wait for the fix, as I listed above.

**Comment by br3no** [comment]
I have identified the source of the problem in outlines and am waiting for a PR (https://github.com/outlines-dev/outlines/pull/874) to get merged with the fix. Once this is done, we can move on with the migration to the `Guide` API. 

I'll close this PR in favor of #4109.

**Comment by rlouf** [comment]
I merged the PR that fixes https://github.com/outlines-dev/outlines/pull/874. Indeed @saattrupdan I think it makes more sense to have the processors in vLLM so Outlines is not concerned with details of the implementation and can focus on structured generation alone.

**Comment by saattrupdan** [comment]
> Indeed @saattrupdan I think it makes more sense to have the processors in vLLM so Outlines is not concerned with details of the implementation and can focus on structured generation alone.

Ah, so the plan is to remove the vLLM integration from the outlines code, and instead ask users to use the one in vLLM?

**Pull request closed without merging**
