### PR TITLE
Fix #issues/320

### PR DESCRIPTION
**Pull request by metacryptom**
client disconnect never executed cause task schedule stucked

### CODE REVIEW

**Comment by metacryptom** [comment]
try:
       async for request_output in results_generator:
            if await request.is_disconnected():

The  await request.is_disconnected is never excueted if something error happed(maybe length over max) ,so the request is nevert quiet cause the schedule to stuck

**Comment by metacryptom** [comment]
[#325 ](https://github.com/vllm-project/vllm/issues/320)

**Comment by zhuohan123** [comment]
@metacryptom Thanks for your contribution! Please correct me if I'm wrong. If this is merely for fixing the `ValueError` that happened when the input is too long, #273 is actually fixing it. If this is for fixing for the case when a client disconnects during streaming, I believe FastAPI automatically shut down the coroutine and calls the following background task to abort the request:

https://github.com/vllm-project/vllm/blob/598dc4b79a0078fe14e0c134d0b53b4842a8b227/vllm/entrypoints/api_server.py#L50-L52

If both these two cases can be effectively handled as what I understand, is this PR still necessary?

**Comment by metacryptom** [comment]
Not just the case  the input is too long, when the request can't be runned and added to swap queue ,the new comming request  can't be executed either . I think the main problems here are that when in none stream mode , the disconnect check can't code can't be executed before the generator yield some outputs  ,this code will cause potential issues ,the long input is just one of them.  The better way is to check disconnected on the generator loop .

**Comment by Ted8000** [comment]
yes, i find some special tokens decode would also cause stucked. All other requests are blocked.

**Comment by zhuohan123** [comment]
Close this PR since we did a major refactor of `async_llm_engine.py` recently and this issue should have been fixed. Feel free to open a new PR if this issue persists.

**Pull request closed without merging**
