### PR TITLE
docs: add instructions for Langchain

### PR DESCRIPTION
**Pull request by mspronesti**
Hi! A month ago I made a few contributions to Langchain to support vLLM and its OpenAI-compatible server. 

This PR aims at updating vLLM's documentation to showcase how to use vLLM with Langchain and to redirect to the tutorial I wrote there for further details. Hope you find this contribution meaningful.

### CODE REVIEW

**Comment by pvtoan** [comment]
Hi @mspronesti , does this LangChain-VLLM support quantized model?

Because the vllm-project already supported quantized model (AWQ format) as shown in https://github.com/vllm-project/vllm/pull/1032

However, when I use the same way and just pass "quantization='awq" to your LangChain-VLLM, it seems does not work and just show OOM.

model_path = "/home/quadrep/toan/projects/LLMs/weights/vicuna-33B-AWQ"
model = VLLM(model=model_path, tensor_parallel_size=2, trust_remote_code=True, max_new_tokens=512, quantization='awq')
--> Error: torch.cuda.OutOfMemoryError: CUDA out of memory.

**Comment by mspronesti** [comment]
Hi @pvtoan, `quantization` is not an explicit parameter of langchain's vLLM. You need to pass it as follows 

```py
model = VLLM(
  model=model_path, 
  tensor_parallel_size=2, 
  trust_remote_code=True, 
  max_new_tokens=512, 
  vllm_kwargs={"quantization": "awq"}
)
```

Also, notice that `tensor_parallel_size=2` implies you want to serve the model in a distributed manner, with 2 GPUs. Hope this helps :)

**Comment by mspronesti** [comment]
Btw @WoosukKwon  I have also resolved the conflicts in this PR, in case you are interested in merging It.

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
Thank you for your contribution!

**Pull request merged**
