### PR TITLE
Add check for `transformers` version to fix some CodeLlama-based models' behaviors

### PR DESCRIPTION
**Pull request by HermitSun**
Supports for CodeLlama have been added in `transformers` 4.33.0 (https://github.com/huggingface/transformers/pull/25740). This pr introduces the `rope_theta` param for RoPE scaling.

However, some CodeLLaMA-based models weights are released before this pr merged. That is to say, those models did not take the `rope_theta` into considerations. And if we directly use the `rope_theta` from their configs like [this](https://huggingface.co/WizardLM/WizardCoder-Python-34B-V1.0/blob/d869ce178715f8d6e8141e2ed50e6290985eedb0/config.json#L21), those models will give gebbrish outputs.

Fortunately, there is a `transformers_version` attribute in hf models' `config.json`. So we can add a check to solve this problem: if we find the model use the legacy version of `transformers`, we simply use the default `rope_theta` value.

And after applying this patch, I think at least the following models will work normally (tested on A100 with CUDA 11.8):
1. WizardLM/WizardCoder-Python-13B-V1.0
2. WizardLM/WizardCoder-Python-34B-V1.0

### CODE REVIEW

**Comment by WoosukKwon** [comment]
Hi @HermitSun, is setting `rope_theta` as 10000 a correct implementation of the model? According to the discussion in #883, it seems 1000000 (the value in config.json) is actually correct, while it requires Rope in FP32 precision (#870).

**Comment by HermitSun** [comment]
> Hi @HermitSun, is setting `rope_theta` as 10000 a correct implementation of the model? According to the discussion in #883, it seems 1000000 (the value in config.json) is actually correct, while it requires Rope in FP32 precision (#870).

Thank you for pointing this out! It seems that this problem is caused by fp16 precision overflow in some cases and I missed it😭. I will double check it in my case.

And what do you think about adding this version check when using CodeLlama-based models? I mean, if you don't think my current change is so necessary, I think I can change it to simply printing a warning when a version mismatch is detected, and then I will try to working on this precision problem in another new pr.

**Comment by viktor-ferenczi** [comment]
Related: I'm trying to run `WizardLM/WizardCoder-Python-13B-V1.0` (A Code Llama fine-tune). It gives gibberish output (I used the right prompt template), while the original Code Llama 13B works. I guess the `config.json` is different.

```
llm = LLM(model='WizardLM/WizardCoder-Python-13B-V1.0', tokenizer='hf-internal-testing/llama-tokenizer', tensor_parallel_size=2, seed=42)
sampling_params = SamplingParams(n=10, max_tokens=2000, temperature=0.3, top_p=0.95, stop=['</s>'])
```

**Comment by HermitSun** [comment]
> Related: I'm trying to run `WizardLM/WizardCoder-Python-13B-V1.0` (A Code Llama fine-tune). It gives gibberish output (I used the right prompt template), while the original Code Llama 13B works. I guess the `config.json` is different. Another fine-tune `OpenAssistant/codellama-13b-oasst-sft-v10` works fine.
> 
> ```
> llm = LLM(model='WizardLM/WizardCoder-Python-13B-V1.0', tokenizer='hf-internal-testing/llama-tokenizer', tensor_parallel_size=2, seed=42)
> sampling_params = SamplingParams(n=10, max_tokens=2000, temperature=0.3, top_p=0.95, stop=['</s>'])
> ```

I noticed that this code uses a `hf-internal-testing/llama-tokenizer`. What if this code had used the model's tokenizer?

**Comment by WoosukKwon** [comment]
Hi @HermitSun 

>  I will try to working on this precision problem in another new pr.

No worries. @imoneoi and I made a PR #1004 to fix this issue.

> Since transformers before 4.33.0 does not really support CodeLlama, models using a legacy version are more likely to use a default rope_theta value, and this check will work as a reminder.

Actually, I don't understand. Isn't `rope_theta: 1000000` correct for the `WizardLM/WizardCoder-Python-13B-V1.0` and `WizardLM/WizardCoder-Python-34B-V1.0` models? Do you need to reset this to 10000?

**Comment by esmeetu** [comment]
imk，wizardcoder-34b was trained using transformers==4.31.0, which doesn't support rope theta, change  to base 10000 will be ok.
@HermitSun @WoosukKwon

**Comment by HermitSun** [comment]
After applying the changes in PR https://github.com/vllm-project/vllm/pull/1004, I find the model works well(at least it looks well!). It seems that we **do not have to** change the `rope_theta` if the precision problem is solved.

But as @esmeetu says, I think it's ok to use 10000 as default, since `transformers` had not supported this param when the model was trained.

And I originally opened this pr to check the `transformers` version mismatch. If the precision problem is fixed, maybe we can give a warning instead of changing `rope_theta`. Or maybe we can have a better way to check the version instead if just leave a comment in the code.

**Comment by viktor-ferenczi** [comment]
The HF repos of the `WizardLM/WizardCoder-Python-13B-V1.0` and `WizardLM/WizardCoder-Python-34B-V1.0` models have 1000000 in their `config.json`. If I change them to 10000 in the downloaded model folder vLLM starts to work properly with them. So a default of 10000 seems to be correct, indeed.

**Comment by HermitSun** [comment]
I additionally did some simple experiments with WizardLM/WizardCoder-Python-34B-V1.0:

| **rope_theta** | **RoPE precision** | **pass@1** |
|----------------|--------------------|------------|
| 10000          | fixed (PR #1004)   | 0.6646     |
| 10000          | not fixed          | 0.6585     |
| 1000000        | fixed (PR #1004)   | 0.6037     |

Because the model will give gibberish outputs when `rope_theta=1000000` and RoPE precision is not fixed, I did not do that experiment. As the result shows, `rope_theta=10000` gives a better result on the human-eval benchmark. And the precision problem **does** affect the result.

**Comment by esmeetu** [comment]
@HermitSun What is interesting is that adding rope theta slightly (ex. 16384) might improve the score.

**Comment by HermitSun** [comment]
> @HermitSun What is interesting is that adding rope theta slightly (ex. 16384) might improve the score.

Amazing! I will update my results below, and it seems to prove that `rope_theta` around 10000 performs better:

| **rope_theta** | **RoPE precision** | **pass@1** |
|----------------|--------------------|------------|
| 16384          | not fixed          | 0.7012     |
| 16384          | fixed (PR #1004)   | 0.6829     |
| 10000          | fixed (PR #1004)   | 0.6646     |
| 10000          | not fixed          | 0.6585     |
| 1000000        | fixed (PR #1004)   | 0.6037     |
| 1000000        | not fixed          | 0.0        |

And I wonder if this conclusion (i.e. slightly increase of `rope_theta` will improve the model's performance) suitable for all CodeLlama-based models?

**Comment by WoosukKwon** [comment]
@HermitSun Thanks a lot for the evaluation. Could you please share the script you used for it?

And, if possible, could you measure the accuracy on the `rope-fp32` branch as well? It uses FP32 not only for initialization, but also for calculating the RoPE (without changing the base value). It requires installing vLLM from source:
```bash
git checkout rope-fp32
pip install -e .
```

**Comment by viktor-ferenczi** [comment]
The same issue is discussed at `llama.cpp`: https://github.com/ggerganov/llama.cpp/issues/3090

**Comment by HermitSun** [comment]
I used the latest code and applied fp32 precision patches, the updated results are here:

| **rope_theta** | **RoPE precision** | **pass@1** |
|----------------|--------------------|------------|
| 10000          | PR #1004   | 0.6646     |
| 10000          | not fixed          | 0.6646     |
| 10000          | branch rope-fp32          | 0.6585     |
| 16384          | branch rope-fp32          | 0.6890     |
| 16384| not fixed          | 0.6890     |
| 16384| PR #1004   | 0.6829     |
| 1000000        | branch rope-fp32          | 0.6098        |
| 1000000        | PR #1004   | 0.6037     |
| 1000000        | not fixed          | N/A       |

It seems that PR #1004 performs better when using default `rope_theta` value 10000, and branch rope-fp32 performs better when `rope_theta` is larger.

**Comment by WoosukKwon** [comment]
Hi @HermitSun, thanks for the benchmark results. It seems #1004 is enough for the precision problem.

Then, I believe users should be responsible for setting the right `rope_theta` for their models. It's out of vLLM's scope. As the value can be easily configured by modifying the model's `config.json` file, I think there's nothing we need to do about it here.

> I think I can change it to simply printing a warning when a version mismatch is detected

While it makes sense to me, I'm wondering what the exact logic would be. 99% of the models in HF model hub are trained with transformers < 4.33.1. How can we tell when we should warn? If I understand correctly, your PR will warn every llama model trained before 4.33.1, including LLaMA V1. How can we minimize such false positives?

**Comment by HermitSun** [comment]
Hi @WoosukKwon, I think you're right, maybe we should not introduce extra workload for an inference framework.

As for the version mismatch detection problem, I think we can add some heuristic rules to check the `_name_or_path` of `config.json`. If `CodeLlama` or some other keywords appear in `_name_or_path`, then we can raise a warning. But maybe we should not do this in the framework, this is JUST a requirement of my case rather than a generic one.

If you feel this pr (including replacing the `rope_theta` check with rule-based alerts) is less necessary, I'll close it.

**Pull request closed without merging**
