### PR TITLE
Add Gemma model

### PR DESCRIPTION
**Pull request by xiangxu-google**
https://blog.google/technology/developers/gemma-open-models/

The PR contains the Gemma model implementation which is able to load checkpoints from HF:
- google/gemma-2b
- google/gemma-2b-it
- google/gemma-7b
- google/gemma-7b-it

### CODE REVIEW

**Review by WoosukKwon — APPROVED** [review]
LGTM! Thanks for submitting the PR!

**Comment by MrRace** [comment]
@xiangxu-google 
After deploying Gemma using the VLLM deployment in the OpenAI API format, it seems that inputs from the Chat API are not supported. 

The deployment command used is:

```
python3 -m vllm.entrypoints.openai.api_server --served-model-name gemma-2b-it --model /data/share_model_zoo/LLM/google/gemma-2b-it
```

The test request used is:

```
curl http://localhost:8000/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "gemma-2b-it",
        "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Hello"}
        ]
    }'
```

The response returned is as follows:

```
{"object":"error","message":"System role not supported","type":"BadRequestError","param":null,"code":400}
```

**Comment by xiangxu-google** [comment]
Is this error Gemma specific? This PR added the modeling code only, which should not affect the API server.

**Comment by simon-mo** [comment]
The chat template doesn't support system role https://huggingface.co/google/gemma-2b-it/blob/718cb189da9c5b2e55abe86f2eeffee9b4ae0dad/tokenizer_config.json#L59

**Pull request merged**
