### PR TITLE
Reduce sampler CPU overhead

### PR DESCRIPTION
**Pull request by beginlner**

### CODE REVIEW

**Review by zhuohan123 — COMMENTED** [review]
Thanks for bringing this up! Does this actually have speed difference? I benchmarked this before and found the `.cpu` and `.item` design is slightly faster.

**Comment by beginlner** [comment]
The `.tolist` design has one pytorch operator, while the .cpu and .item design has `batch_size + 1` pytorch operators. Base on my test on `batch_size = 256, prompt_len = 1024`, the former design is about 1% faster than the latter design per iteration.

**Comment by simon-mo** [comment]
@zhuohan123 upon second look, I think the performance is basically the same, but this refactoring is slightly easier to read?

**Comment by zhuohan123** [comment]
> @zhuohan123 upon second look, I think the performance is basically the same, but this refactoring is slightly easier to read?

Not really, because we do need some 2D indexing in the sampler code:

https://github.com/vllm-project/vllm/blob/660a7fcfa40d62305ecba6bc6352c4026d56d680/vllm/model_executor/layers/sampler.py#L365-L366

Using `.tolist` somewhere and `.item` somewhere else can be confusing

**Comment by zhuohan123** [comment]
Close this PR according to the discussions above. Feel free to re-open if you have anything to add!

**Pull request closed without merging**
