### PR TITLE
[Worker] Fix input_metadata.selected_token_indices in worker

### PR DESCRIPTION
**Pull request by ymwangg**
This PR fixes a bug when sequences have different prompt lens.

### CODE REVIEW

**Review by Yard1 — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by irasin** [comment]
Hi @Yard1, just wonder when this PR can be merged into the main branch

**Comment by Yard1** [comment]
@irasin I do not have the permissions to do that. cc @WoosukKwon @zhuohan123

**Review by zhuohan123 — APPROVED** [review]
LGTM! Thanks for your contribution!

**Pull request merged**
