### PR TITLE
[Misc] Add CustomOp Interface to UnquantizedFusedMoEMethod

### PR DESCRIPTION
**Pull request by WoosukKwon**
Currently, `UnquantizedFusedMoEMethod` directly imports the Triton fused MoE kernel and related CUDA kernels, preventing other hardware backends from supporting MoE models. This PR adds the `CustomOp` interface to it so that the kernels are imported only for NVIDIA and AMD GPUs.

### CODE REVIEW

**Comment by robertgshaw2-neuralmagic** [comment]
Does this need to be added to the fp8 method as well? Or are we handling quantization separately?

https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/quantization/fp8.py#L220

**Comment by WoosukKwon** [comment]
@robertgshaw2-neuralmagic We haven't used the `CustomOp` interface for the quantization-related ops, since they usually only support NVIDIA or AMD GPUs. Do you want to apply the interface to the quant ops?

**Comment by robertgshaw2-neuralmagic** [comment]
> @robertgshaw2-neuralmagic We haven't used the `CustomOp` interface for the quantization-related ops, since they usually only support NVIDIA or AMD GPUs. Do you want to apply the interface to the quant ops?

I think its okay to leave it for now and make the modifications once we have a need for it

**Review by robertgshaw2-redhat — APPROVED** [review]

**Comment by WoosukKwon** [comment]
This PR seems to break Mixtral. Let me check the reason.

**Comment by robertgshaw2-neuralmagic** [comment]
What TP is it running at? @WoosukKwon

**Comment by WoosukKwon** [comment]
@comaniac Thanks for the confirmation! It works well.

**Pull request merged**
