### PR TITLE
[doc] add warning about comparing hf and vllm outputs

### PR DESCRIPTION
**Pull request by youkaichao**
A lesson learned from https://github.com/vllm-project/vllm/issues/1069#issuecomment-2507775281 .

In our ci, we always use `do_sample=False` for huggingface models, so it is not a problem.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Let's merge this first. Later we can implement #10758

**Review by DarkLight1337 — APPROVED** [review]

**Comment by DarkLight1337** [comment]
I would argue that #10758 is the "intended" behavior. To avoid breaking changes, we can log a warning for a while before finally switching over to using `generation_config.json` as the default.

**Comment by youkaichao** [comment]
`generation_config.json` is aligned with huggingface `generate` function, if we take default values from the file, the implementation will be coupled.

**Comment by DarkLight1337** [comment]
Let's move the discussion to that issue so we can gather thoughts from the OP as well.

**Pull request merged**
