### PR TITLE
[Model] EXAONE 3.0 model support

### PR DESCRIPTION
**Pull request by Deepfocused**
Hello, I am deepfocused from the AI ​​engineering Team at LG CNS.
we want to integrate the recently opened model EXAONE-3.0-7.8B-Instruct model into vLLM.

Previously, we have been servicing models such as EXAONE v1, v2, etc. to our customers as vLLM through the vLLM + EXAONE build. Unlike these previous models, EXAONE 3.0 was released as an open model, so we are requesting integration.
```
Paper: [EXAONE 3.0 7.8B Instruction Tuned Language Model](https://huggingface.co/papers/2408.03541)
HuggingFace: [LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct](https://huggingface.co/LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct)
Github: [LG-AI-EXAONE/EXAONE-3.0](https://github.com/LG-AI-EXAONE/EXAONE-3.0)
```
It was written based on the llama.py model, 
To run the EXAONE 3.0 model, 
For offline execution, 
```
import os
os.environ['HF_TOKEN'] = "your key"
llm = LLM(model="EXAONE-3.0-7.8B-Instruct", 
           ...)
```
For vllm server execution,
```
export HF_TOKEN="your key"
vllm serve LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct 
```

❗ Added exaone configuration file to vllm/transformers_utils to allow omitting trust_remote_code or --trust-remote-code at runtime. 
Once Exaone is integrated into the transformer library, the above tasks will no longer be necessary ~

thank you. 

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by mgoin — COMMENTED** [review]
This seems to work locally for me and seems reasonable, thanks!

```python
>>> from vllm import LLM
>>> model = LLM("LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct")
>>> model.chat([{"role":"user","content":"Hello!"}])
Processed prompts: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.86it/s, est. speed input: 102.15 toks/s, output: 77.82 toks/s]
[RequestOutput(request_id=1, prompt='[|system|][|endofturn|]\n[|user|]Hello!\n[|assistant|]', prompt_token_ids=[420, 453, 47982, 453, 422, 361, 560, 420, 453, 14719, 453, 422, 33381, 362, 560, 420, 453, 1167, 8659, 453, 422], encoder_prompt=None, encoder_prompt_token_ids=None, prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I help you today? If you have any questions or need', token_ids=array('l', [33381, 362, 2417, 1093, 768, 2347, 904, 4963, 392, 2386, 904, 1072, 1491, 5344, 913, 1788]), cumulative_logprob=None, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1724860809.4073465, last_token_time=1724860809.4073465, first_scheduled_time=1724860809.408349, first_token_time=1724860809.4238176, time_in_queue=0.0010025501251220703, finished_time=1724860809.6029909, scheduler_time=0.000975252129137516, model_forward_time=None, model_execute_time=None), lora_request=None)]
```

Also ran an eval on gsm8k
```
lm_eval --model vllm --model_args pretrained=LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct,max_model_len=4096,enable_chunked_prefill=True --tasks gsm8k --batch_size auto
vllm (pretrained=LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct,max_model_len=4096,enable_chunked_prefill=True), gen_kwargs: (None), limit: None, num_fewshot: None, batch_size: auto
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|
|-----|------:|----------------|-----:|-----------|---|-----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.8044|±  |0.0109|
|     |       |strict-match    |     5|exact_match|↑  |0.8021|±  |0.0110|
```

**Review by mgoin — APPROVED** [review]

**Comment by Deepfocused** [comment]
The existing unopened exaone v1 and exaonev2 models had a different structure from llama, but the newly released exaone v3 model has the same structure as llama3, but there are differences in variable names. Therefore, in order to run EXAONE3.0 in the hugging face on vllm, several variable names and weight names had to be changed in the llama structure.

For example,
down_proj -> self.c_proj
gate_proj -> c_fc_0
up_proj" -> c_fc_1
config.rms_norm_eps -> config.layer_norm_epsilon
There are a few more. (Refer to the code)

There were variable changes such as these.
EXAONE 3.0 seems to focus more on data and training methods based on the llama structure rather than changing the model structure.

**Comment by Deepfocused** [comment]
> This seems to work locally for me and seems reasonable, thanks!
> 
> ```python
> >>> from vllm import LLM
> >>> model = LLM("LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct")
> >>> model.chat([{"role":"user","content":"Hello!"}])
> Processed prompts: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.86it/s, est. speed input: 102.15 toks/s, output: 77.82 toks/s]
> [RequestOutput(request_id=1, prompt='[|system|][|endofturn|]\n[|user|]Hello!\n[|assistant|]', prompt_token_ids=[420, 453, 47982, 453, 422, 361, 560, 420, 453, 14719, 453, 422, 33381, 362, 560, 420, 453, 1167, 8659, 453, 422], encoder_prompt=None, encoder_prompt_token_ids=None, prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I help you today? If you have any questions or need', token_ids=array('l', [33381, 362, 2417, 1093, 768, 2347, 904, 4963, 392, 2386, 904, 1072, 1491, 5344, 913, 1788]), cumulative_logprob=None, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1724860809.4073465, last_token_time=1724860809.4073465, first_scheduled_time=1724860809.408349, first_token_time=1724860809.4238176, time_in_queue=0.0010025501251220703, finished_time=1724860809.6029909, scheduler_time=0.000975252129137516, model_forward_time=None, model_execute_time=None), lora_request=None)]
> ```
> 
> Also ran an eval on gsm8k
> 
> ```
> lm_eval --model vllm --model_args pretrained=LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct,max_model_len=4096,enable_chunked_prefill=True --tasks gsm8k --batch_size auto
> vllm (pretrained=LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct,max_model_len=4096,enable_chunked_prefill=True), gen_kwargs: (None), limit: None, num_fewshot: None, batch_size: auto
> |Tasks|Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|
> |-----|------:|----------------|-----:|-----------|---|-----:|---|-----:|
> |gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.8044|±  |0.0109|
> |     |       |strict-match    |     5|exact_match|↑  |0.8021|±  |0.0110|
> ```

thank you!!!

**Comment by simon-mo** [comment]
Merged #7819

**Pull request closed without merging**
