### PR TITLE
multi-lora documentation fix

### PR DESCRIPTION
**Pull request by ElefHead**
Minor fixes to the documentation for open-ai compatible server.

### CODE REVIEW

**Comment by simon-mo** [comment]
Hi @ElefHead, thank you for your PR, however, at the beginning of the `api_server.py`, we noted:

https://github.com/vllm-project/vllm/blob/71bcaf99e2cb2c677bf3a9addb9e8039cbcab22a/vllm/entrypoints/api_server.py#L1-L5

Please revert the change in api_server, we are happy to accept the documentation change!

**Comment by ElefHead** [comment]
@simon-mo Thanks for letting me know, i missed it. I reverted changes and made small addition to the docs. Cheers!

**Comment by findalexli** [comment]
Thanks! Was just confused between using `vllm.entrypoints.openai.api_server` and `vllm.entrypoints.api_server`

**Review by simon-mo — APPROVED** [review]

**Comment by sleepwalker2017** [comment]
Hello, why only support s-lora in openai api? 

Any plans to support it in `vllm.entrypoints.api_server`

**Comment by simon-mo** [comment]
The `generate` server API is not recommended for production usage. We kept it not to break existing usage. The OpenAI server provide a superset of functionality and uses the same engine under the hood.

**Pull request merged**
