### PR TITLE
[Core] implement disaggregated prefilling via KV cache transfer

### PR DESCRIPTION
**Pull request by KuntaiDu**
This is a follow-up PR for #5557 .

Goal: implement disaggregated prefilling by launching 2 vllm instances (one for prefilling, one for decoding), and forward the KV cache from prefilling instance to decoding instance.

A rough roadmap:
- [x] Benchmark the idealized version of disaggregated prefilling (idealized in terms of the KV cache transfer can be done immediately).
- [x] Implement API calls in vllm to import / export KV cache
- [x] Implement an agent that can transfer KV cache between prefilling and decoding instance
- [x] Implement end-to-end prototype
- [x] Benchmark and improve the performance
- [ ] Beta test (ongoing)
- [ ] Support different tp/pp between prefill and decode instance

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by KuntaiDu** [comment]
An example of disaggregated prefill can be much better than chunked prefill:
image
- model: llama70B fp8
- device: 8xH100
- workload: QPS 4, input tokens 2048, output tokens 11
- 3 approaches
  - chunked prefill — tp8
  - chunked prefill — 2x tp4
  - disaggregated prefill — 1x tp4 prefill, 1x tp4 decode

**Comment by KuntaiDu** [comment]
I updated the measurements and now let me summarize the insight.
- For long context (long: #input token >=1k when #output token=128), we should use disaggregated prefilling instead of chunked prefill.
- The maximum overhead of disaggregated prefilling (caused by KV cache transfer) is 40ms. An ideal implementation should have less than 10 ms overhead.

**Comment by AndyZZt** [comment]
Hi Kuntai，我看了您目前对代码的改动，想跟您确认一下目前是没有实际进行KV Cache传输的对吗，也就是roadmap 1所说的KV cache transfer can be done immediately。通过调整输出长度=1、跳过prefill，直接起两个server各自模拟分离后各自的耗时？
另外似乎您是想通过模型并行来达到PD分离的目的，但是我理解这会给PD使用不同并行设置的情况带来麻烦，还是我理解错误了呢？ 感谢您的答复！

**Comment by liurupeng** [comment]
regarding the implementation, in the long term, we expect having multiple vLLM prefill instances and multiple decode instances, do you see the current design will naturally supports it?

**Comment by KuntaiDu** [comment]
> regarding the implementation, in the long term, we expect having multiple vLLM prefill instances and multiple decode instances, do you see the current design will naturally supports it?

The current architecture can be naturally extended to multiple vLLM instances. The current plan is to support 1 prefill - 1 decode with same tp and pp first.

**Comment by KuntaiDu** [comment]
Now my implementation works with TP, and now it is the time to do a quick overhead measurement.

- Model: Llama 70B, with tp=4
- Hardware: 8xH100, 4 for prefill, 4 for decode
- Input length: 2048
- Num prompts: 50
- Output length: 1
- QPS: 1
- Overhead: **mean 30.91 ms, median 30.30 ms, P99 40.97 ms**

Here is how I measure this overhead:
The workflow of my code is:
(1) Send a request to prefill instance --> (2) receive first token and then immediately send the request again to decode instance --> (3) receive first token again from decode instance --> (4) receive remaining tokens
And the overhead I am measuring is the time gap between (2) and (3)
This overhead can be further optimized. Currently, I send the request to the decode instance after receiving the first token. The request can be sent much earlier --- ideally right after the prefill instance finishes prefilling, which can reduce the overhead by the time of sampling and detokenizing the first token.

**Comment by KuntaiDu** [comment]
A back-to-back comparison between chunked prefill and disaggregated prefill:

- Input length: 2048
- Output length: 150
- Dataset: sonnet
- Num of prompts: 400
- QPS: 2,4,6,8
- Methods:
  - chunked prefill: 2 vllm instances, tp4, with chunked prefill enabled, 2 instances share the workload in a round-robin manner
  - disagg prefill: 2 vllm instances, tp4, one for prefill and one for decode
    - My current implementation can let us get the first token before implementation overheads (like KV transfer and waiting until decode instance is ready to receive generated KV cache) happen by fetching the first token from the prefill instance, but for benchmarking’s sake I count these overheads into TTFT by fetching the first token from decode instance.
- Results:
  - lower median TTFT and median ITL when QPS<=6 (at QPS=8 the decode instance is backlogging)
  - worse p99 ITL ---- Sometimes the KV cache transfer may fail (this appears rarely and I am not sure why for now), forcing the decoding instance to redo the prefill by itself, which makes ITL worse.

image
image
image
image

**Comment by wjj19950828** [comment]
> A back-to-back comparison between chunked prefill and disaggregated prefill:
> 
> * Input length: 2048
> * Output length: 150
> * Dataset: sonnet
> * Num of prompts: 400
> * QPS: 2,4,6,8
> * Methods:
>   
>   * chunked prefill: 2 vllm instances, tp4, with chunked prefill enabled, 2 instances share the workload in a round-robin manner
>   * disagg prefill: 2 vllm instances, tp4, one for prefill and one for decode
>     
>     * My current implementation can let us get the first token before implementation overheads (like KV transfer and waiting until decode instance is ready to receive generated KV cache) happen by fetching the first token from the prefill instance, but for benchmarking’s sake I count these overheads into TTFT by fetching the first token from decode instance.
> * Results:
>   
>   * lower median TTFT and median ITL when QPS<=6 (at QPS=8 the decode instance is backlogging)
>   * worse p99 ITL ---- Sometimes the KV cache transfer may fail (this appears rarely and I am not sure why for now), forcing the decoding instance to redo the prefill by itself, which makes ITL worse.
> 
> image image image image

@KuntaiDu Why are some concurrency TTFT indicators reaching 5000-10000ms? Is it pending?

But I feel that under 70b tp4, the qps on the H100 card should not be so low

**Comment by KuntaiDu** [comment]
> > A back-to-back comparison between chunked prefill and disaggregated prefill:
> > 
> > * Input length: 2048
> > * Output length: 150
> > * Dataset: sonnet
> > * Num of prompts: 400
> > * QPS: 2,4,6,8
> > * Methods:
> >   
> >   * chunked prefill: 2 vllm instances, tp4, with chunked prefill enabled, 2 instances share the workload in a round-robin manner
> >   * disagg prefill: 2 vllm instances, tp4, one for prefill and one for decode
> >     
> >     * My current implementation can let us get the first token before implementation overheads (like KV transfer and waiting until decode instance is ready to receive generated KV cache) happen by fetching the first token from the prefill instance, but for benchmarking’s sake I count these overheads into TTFT by fetching the first token from decode instance.
> > * Results:
> >   
> >   * lower median TTFT and median ITL when QPS<=6 (at QPS=8 the decode instance is backlogging)
> >   * worse p99 ITL ---- Sometimes the KV cache transfer may fail (this appears rarely and I am not sure why for now), forcing the decoding instance to redo the prefill by itself, which makes ITL worse.
> > 
> > image image image image
> 
> @KuntaiDu Why are some concurrency TTFT indicators reaching 5000-10000ms? Is it pending?
> 
> But I feel that under 70b tp4, the qps on the H100 card should not be so low

Yes, the requests are pending and that's why the TTFT is high. As for the QPS, let me double check.

**Comment by LesLieZC0324** [comment]
It is a nice work! However, I meet some problems in actual use. 
In this PR, chunked prefill with tp4 used `round_robin_proxy.sh` to forward polling requests for port 8000 to ports 8100 and 8200. However, when I used it, once the `socat` process is started and starts listening on port 8000, it will continue to receive all subsequent connections without calling the `get_next_port` function again to select another port.
Looking forward to your reply！

**Comment by MazarineGlacier** [comment]
A friendly reminder here: chunked prefill feature needs a parameter `--max-num-batched-tokens`. In the original post of chunked prefill, the author found a fact that instead of the default 512, using 2048 on A100 gave a better result. 

For Disaggregated prefill, it might be interesting to set this parameter differently on prefill and decode instances. Since prefill  stage is compute bound and decode stage is memory bound, my intuition is to set a small max batched tokens to prefill and a large max batched tokens to decode

For instance, when I was benchmarking llama3-8B with prefilll tp2 A100 and decode tp2 A100, I have set prefill instance to `--max-num-batched-tokens 4096` and set decode instance to `--max-num-batched-tokens 32768`. With these settings, I have achieved a slightly better result. 
image

**Comment by wjj19950828** [comment]
@KuntaiDu @MazarineGlacier Have you ever tested Disaggregated prefill vs normal version (without chunk prefill)? I tested P2D2 vs tp4 and found no benefit. Is this normal?

**Comment by MazarineGlacier** [comment]
>   I tested P2D2 vs tp4 and found no benefit. Is this normal?

In your case, disaggregate prefill will behave worse in TTFT. This is because default VLLM prioritizes prefill and tp4 has (less than) twice the compute capability during prefill than P2D2.

I am not certain about TPOT/ITL though, that depends on the real batched tokens.  

After all, it is possible that no benefit is found.

**Comment by wjj19950828** [comment]
> > I tested P2D2 vs tp4 and found no benefit. Is this normal?
> 
> In your case, disaggregate prefill will behave worse in TTFT. This is because default VLLM prioritizes prefill and tp4 has (less than) twice the compute capability during prefill than P2D2.
> 
> I am not certain about TPOT/ITL though, that depends on the real batched tokens.
> 
> After all, it is possible that no benefit is found.

In our scenario, disaggregate prefill on TTFT/TPOP/ITL is much worse than TP4. I don’t know where the problem is, so I wonder in which scenarios disaggregate prefill will be beneficial.

**Comment by MazarineGlacier** [comment]
> In our scenario, disaggregate prefill on TTFT/TPOP/ITL is much worse than TP4. I don’t know where the problem is, so I wonder in which scenarios disaggregate prefill will be beneficial.

This paper might answer your question: https://arxiv.org/html/2401.11181v1. In this paper, when workload is too large on both prefill and decode, disaggregate prefill failed.

**Comment by ChuanhongLi** [comment]
> > > I tested P2D2 vs tp4 and found no benefit. Is this normal?
> > 
> > 
> > In your case, disaggregate prefill will behave worse in TTFT. This is because default VLLM prioritizes prefill and tp4 has (less than) twice the compute capability during prefill than P2D2.
> > I am not certain about TPOT/ITL though, that depends on the real batched tokens.
> > After all, it is possible that no benefit is found.
> 
> In our scenario, disaggregate prefill on TTFT/TPOP/ITL is much worse than TP4. I don’t know where the problem is, so I wonder in which scenarios disaggregate prefill will be beneficial.

Me too. But I did it on 4090. Maybe the overhead is too high without nvlink.

**Comment by wjj19950828** [comment]
> > > > I tested P2D2 vs tp4 and found no benefit. Is this normal?
> > > 
> > > 
> > > In your case, disaggregate prefill will behave worse in TTFT. This is because default VLLM prioritizes prefill and tp4 has (less than) twice the compute capability during prefill than P2D2.
> > > I am not certain about TPOT/ITL though, that depends on the real batched tokens.
> > > After all, it is possible that no benefit is found.
> > 
> > 
> > In our scenario, disaggregate prefill on TTFT/TPOP/ITL is much worse than TP4. I don’t know where the problem is, so I wonder in which scenarios disaggregate prefill will be beneficial.
> 
> Me too. But I did it on 4090. Maybe the overhead is too high without nvlink.

Yes, I am studying the kv cache transmission overhead here. I see the author said it is about 30ms, which is definitely unacceptable.

**Comment by LesLieZC0324** [comment]
> > > > > I tested P2D2 vs tp4 and found no benefit. Is this normal?
> > > > 
> > > > 
> > > > In your case, disaggregate prefill will behave worse in TTFT. This is because default VLLM prioritizes prefill and tp4 has (less than) twice the compute capability during prefill than P2D2.
> > > > I am not certain about TPOT/ITL though, that depends on the real batched tokens.
> > > > After all, it is possible that no benefit is found.
> > > 
> > > 
> > > In our scenario, disaggregate prefill on TTFT/TPOP/ITL is much worse than TP4. I don’t know where the problem is, so I wonder in which scenarios disaggregate prefill will be beneficial.
> > 
> > 
> > Me too. But I did it on 4090. Maybe the overhead is too high without nvlink.
> 
> Yes, I am studying the kv cache transmission overhead here. I see the author said it is about 30ms, which is definitely unacceptable.

In our scenario, there is a barrier in the KV Cache transmission, which makes TTFT and ITL (which includes TTFT) increase.

**Comment by wjj19950828** [comment]
@KuntaiDu In fact, I don't think it is necessary to do tolist operation for hash calculation, as follows:
```input_tokens_tuple = tuple(model_input.input_tokens.tolist())```
This will cause the d2h copy to be time-consuming. Do you have any other recommended methods for calculating hash? Thanks~

**Comment by KuntaiDu** [comment]
> > > > I tested P2D2 vs tp4 and found no benefit. Is this normal?
> > > 
> > > 
> > > In your case, disaggregate prefill will behave worse in TTFT. This is because default VLLM prioritizes prefill and tp4 has (less than) twice the compute capability during prefill than P2D2.
> > > I am not certain about TPOT/ITL though, that depends on the real batched tokens.
> > > After all, it is possible that no benefit is found.
> > 
> > 
> > In our scenario, disaggregate prefill on TTFT/TPOP/ITL is much worse than TP4. I don’t know where the problem is, so I wonder in which scenarios disaggregate prefill will be beneficial.
> 
> Me too. But I did it on 4090. Maybe the overhead is too high without nvlink.

The NVLink or Infinityband is a must for disaggregated prefilling in order for it to be better than chunked prefill. The time delta allowed for data transfer is less than 50ms.

**Comment by KuntaiDu** [comment]
> > > > > I tested P2D2 vs tp4 and found no benefit. Is this normal?
> > > > 
> > > > 
> > > > In your case, disaggregate prefill will behave worse in TTFT. This is because default VLLM prioritizes prefill and tp4 has (less than) twice the compute capability during prefill than P2D2.
> > > > I am not certain about TPOT/ITL though, that depends on the real batched tokens.
> > > > After all, it is possible that no benefit is found.
> > > 
> > > 
> > > In our scenario, disaggregate prefill on TTFT/TPOP/ITL is much worse than TP4. I don’t know where the problem is, so I wonder in which scenarios disaggregate prefill will be beneficial.
> > 
> > 
> > Me too. But I did it on 4090. Maybe the overhead is too high without nvlink.
> 
> Yes, I am studying the kv cache transmission overhead here. I see the author said it is about 30ms, which is definitely unacceptable.


There are several performance optimization opportunities I am not exploring yet. In the current implementation, the first token has been sampled twice, and the model input data is constructed twice. These overheads can be bypassed by engineering. and will be optimized after the implementation is stable.

I am now working on an upcoming vllm performance post, will circle back to this right after that.

**Comment by KuntaiDu** [comment]
> It is a nice work! However, I meet some problems in actual use. In this PR, chunked prefill with tp4 used `round_robin_proxy.sh` to forward polling requests for port 8000 to ports 8100 and 8200. However, when I used it, once the `socat` process is started and starts listening on port 8000, it will continue to receive all subsequent connections without calling the `get_next_port` function again to select another port. Looking forward to your reply！

Oh let me double check and fix it.

**Comment by gursimar** [comment]
> ut I did it on 4090. Maybe the overhead is to

I'm interested to build upon this implementation for faster kv cache transfer

1. What is the current method of kv cache transfer is you are not using nvlink?
2. Why can't we simply use torch.distributed.isend and torch.distributed.irecv to do the transfer using nccl?

**Comment by wenqf11** [comment]
thans for your work, I got a question, can I start like 6 prefill instances and 2 decode instances on 8 GPUs and how ?

**Comment by WhatGhost** [comment]
hi, i just want to know what's the relationship between your work and the pr#2809 . it seems  you both want to implement something like "disaggregated prefilling" to separate profile and generation phases. 

I wonder what the difference.

Looking forward to your reply！
Thanks！

**Comment by junna2016** [comment]
I meet a problem when I concat k and v tensor together for each layer to send and recv, Llama-2-7B output results will be random and uncorrect. Why does concating k and v lead to this result?

**Comment by KuntaiDu** [comment]
Close this PR now (I did a large-scale refactor and it is now in #8498 )

**Comment by KuntaiDu** [comment]
> Thanks for your work, I got a question, can I start like 6 prefill instances and 2 decode instances on 8 GPUs and how ?

Not implemented directly in the new PR but yeah, it is on the roadmap and will soon be implemented.

**Comment by KuntaiDu** [comment]
> @KuntaiDu hi, i just want to know what's the relationship between your work and the pr[#2809](https://github.com/vllm-project/vllm/pull/2809) . it seems you both want to implement something like "disaggregated prefilling" to separate profile and generation phases.
> 
> I wonder what the difference.
> 
> Looking forward to your reply！ Thanks！

Not sure about that thread. I skimmed their code and my implementation is lighter weighted and overhead is tolerable (though definitely will be larger).

**Pull request closed without merging**
