### PR TITLE
[Bugfix] Fix PP for ChatGLM and Molmo, and weight loading for Qwen2.5-Math-RM

### PR DESCRIPTION
**Pull request by DarkLight1337**
#9242 accidentally removed PP support from ChatGLM. On the other hand, `MolmoModel` already supports PP but the top-level `MolmoForCausalLM` does not. This PR fixes both of these issues.

The input processors of these models and Qwen2-VL have also been cleaned up a bit.

Also fixes https://github.com/vllm-project/vllm/pull/9090#issuecomment-2418413863

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Sorry for breaking your code! @lixiaolx can you test out this PR and see if you can load Qwen/Qwen2.5-Math-RM-72B now?

**Review by Isotr0py — APPROVED** [review]
`GLM4-V` and `Molmo` PP tests all passed on my devices. LGTM once Qwen2-RM is also confirmed to work.

**Comment by lixiaolx** [comment]
> Sorry for breaking your code! @lixiaolx can you test out this PR and see if you can load Qwen/Qwen2.5-Math-RM-72B now?

@DarkLight1337 , I tried adding lm_head filtering to the model.py file of qwen_rm. Now I can load the model, but the final results of my test reference are all nan https://github.com/vllm-project/vllm/pull/8896. I tried printing the weights of the model, but it seemed that the weights were not loaded correctly.

add print code in
https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/model_loader/loader.py#L413
`for name, param in model.named_parameters():
            print(f"Parameter '{name}' =====tensor=======: {param}")`
image

**Comment by DarkLight1337** [comment]
> > Sorry for breaking your code! @lixiaolx can you test out this PR and see if you can load Qwen/Qwen2.5-Math-RM-72B now?
> 
> @DarkLight1337 , I tried adding lm_head filtering to the model.py file of qwen_rm. 
> `loader = AutoWeightsLoader(self,skip_prefixes=["lm_head"])`  
> Now I can load the model, but the final results of my test reference are all nan https://github.com/vllm-project/vllm/pull/8896. I tried printing the weights of the model, but it seemed that the weights were not loaded correctly.
> 
> add print code in
> https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/model_loader/loader.py#L413
> `for name, param in model.named_parameters():
>             print(f"Parameter '{name}' =====tensor=======: {param}")`
> image
> 

Can you add print statements inside `AutoWeightLoader` and list out the weight names in the iterator? This should provide enough information for me to figure out the discrepancies.

**Comment by DarkLight1337** [comment]
> > > Sorry for breaking your code! @lixiaolx can you test out this PR and see if you can load Qwen/Qwen2.5-Math-RM-72B now?
> > 
> > 
> > @DarkLight1337 , I tried adding lm_head filtering to the model.py file of qwen_rm.
> > `loader = AutoWeightsLoader(self,skip_prefixes=["lm_head"])`
> > Now I can load the model, but the final results of my test reference are all nan #8896. I tried printing the weights of the model, but it seemed that the weights were not loaded correctly.
> > add print code in
> > https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/model_loader/loader.py#L413
> > `for name, param in model.named_parameters(): print(f"Parameter '{name}' =====tensor=======: {param}")`
> > image
> 
> Can you add print statements inside `AutoWeightLoader` and list out the weight names in the iterator? This should provide enough information for me to figure out the discrepancies and fix them.

Any update? Otherwise, I'll merge this PR first and fix the model in another PR.

**Comment by DarkLight1337** [comment]
> > > > Sorry for breaking your code! @lixiaolx can you test out this PR and see if you can load Qwen/Qwen2.5-Math-RM-72B now?
> > > 
> > > 
> > > @DarkLight1337 , I tried adding lm_head filtering to the model.py file of qwen_rm.
> > > `loader = AutoWeightsLoader(self,skip_prefixes=["lm_head"])`
> > > Now I can load the model, but the final results of my test reference are all nan #8896. I tried printing the weights of the model, but it seemed that the weights were not loaded correctly.
> > > add print code in
> > > https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/model_loader/loader.py#L413
> > > `for name, param in model.named_parameters(): print(f"Parameter '{name}' =====tensor=======: {param}")`
> > > image
> > 
> > 
> > Can you add print statements inside `AutoWeightLoader` and list out the weight names in the iterator? This should provide enough information for me to figure out the discrepancies and fix them.
> 
> Any update? Otherwise, I'll merge this PR first and fix the model in another PR.

I think I fixed the problem, so I'm going to merge this now. Please tell me if it still doesn't work.

**Pull request merged**
