### PR TITLE
[Misc] Remove unused vllm/block.py

### PR DESCRIPTION
**Pull request by Ghjk94522**
Since this file is no longer referenced, it can be removed from the project.

### CODE REVIEW

**Comment by Ghjk94522** [comment]
@youkaichao 
hope you can review this PR at your convenience.

**Comment by hmellor** [comment]
To add some additional context, the teo classes defined in this file:
- `PhysicalTokenBlock` only used in `block.py` and only referenced in comments in `core/evictor.py`
- `BlockTable` also defined in `vllm/core/block/block_table.py` and is only every imported from the latter file

**Comment by mgoin** [comment]
LGTM, I also don't see these classes used in code anywhere.

> PhysicalTokenBlock only used in `vllm/block.py` (the file being removed) and only referenced in comments in `vllm/core/evictor.py`

The comments `vllm/core/evictor.py` should be updated to reflect the removal of this class.

**Comment by hmellor** [comment]
You're right, the new class to reference is `Block` which is defined in `vllm/core/block/interfaces.py`

**Review by comaniac — APPROVED** [review]

**Pull request merged**
