### PR TITLE
[Misc] Enable chunked prefill by default for long context models

### PR DESCRIPTION
**Pull request by WoosukKwon**
This PR enables chunked prefill by default for long context (>32K) models, to avoid possible OOM errors during the initial memory profiling.

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by WoosukKwon** [comment]
@rkooo567 Could you double check the condition to enable chunked prefill in this PR?

**Review by rkooo567 — APPROVED** [review]
looks good! probably need to update test_models.py if there's any model with max model len > 32K

**Comment by WoosukKwon** [comment]
> probably need to update test_models.py if there's any model with max model len > 32K

@rkooo567 Why do we have to update those models? IIUC, the correctness should be unchanged regardless of chunked prefill. Could you say more?

**Review by lanking520 — APPROVED** [review]

**Review by mgoin — APPROVED** [review]
Thank you! I saw a lot of issues reported with Mistral Nemo because it had a very large max seq length

**Comment by rkooo567** [comment]
> @rkooo567 Why do we have to update those models? IIUC, the correctness should be unchanged regardless of chunked prefill. Could you say more?

Oh, mainly because now max model len > 32K + no chunked prefill is not tested anymore.

**Pull request merged**
