### PR TITLE
Setting default for EmbeddingChatRequest.add_generation_prompt to False

### PR DESCRIPTION
**Pull request by noamgat**
Continuing the excellent work done on reward modeling in vLLM, I believe that the default for this parameter should be false.
It was likely copied over from the chat request, where adding the assistant turn before the beginning of the completion is desired by default. However, in embedding / reward modeling, the model is not expected to generate a textual response, but to output an embedding vector.

I'm not even sure that these parameters should be optional, but at the very least they should default to False.

@DarkLight1337 what do you think?

### CODE REVIEW

**Review by DarkLight1337 — APPROVED** [review]
Seems reasonable, thanks for fixing this!

**Comment by DarkLight1337** [comment]
Feel free to remove the parameter altogether (and add a comment explaining why)

**Comment by noamgat** [comment]
Created a different PR based on this discussion:
https://github.com/vllm-project/vllm/pull/10551

**Comment by DarkLight1337** [comment]
Closing as superseded by #10551

**Pull request closed without merging**
