### PR TITLE
chore(vllm): codespell for spell checking 

### PR DESCRIPTION
**Pull request by mspronesti**

### CODE REVIEW

**Comment by WoosukKwon** [comment]
@simon-mo What do you think about this? It looks useful to me.

**Comment by simon-mo** [comment]
looks good indeed. Would be great to add this to format.sh as well!

**Comment by mspronesti** [comment]
@simon-mo @WoosukKwon Done. I also fixed some ruff errors being raised because of the `benchmarks` folder - reproducible running `format.sh` with no parameters.

**Comment by mspronesti** [comment]
@WoosukKwon @simon-mo Is there anything else you would like me to change here?

**Comment by zhuohan123** [comment]
@simon-mo let's merge this?

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
