### PR TITLE
Support LoRA adapter

### PR DESCRIPTION
**Pull request by mymusise**
hi guys, 
We found that infer with vllm can greatly improve performance! But we need to use LoRA(`peft`) in inference.
We also found that the community has a strong demand for lora. https://github.com/vllm-project/vllm/issues/182
After reading the model implementation of vllm, we found there are some differences from huggingface's transformer, so we cannot directly use peft to add LoRA with vllm.

So we added an extra to add LoRA weights to `qkv`. The following is an example of use:
```python
from vllm import LLM, SamplingParams
from vllm.model_executor.adapters import lora

# Create an LLM.
llm = LLM(model="facebook/opt-125m", gpu_memory_utilization=0.05)

# Add LoRA adapter
lora.LoRAModel.from_pretrained(llm.llm_engine.workers[0].model, "edbeeching/opt-125m-imdb-lora")

prompts = [
    "Hello, my name is",
    "The capital of France is",
    "The future of AI is",
]

sampling_params = SamplingParams(temperature=0, top_k=-1)

outputs = llm.generate(prompts, sampling_params)

for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

Currently only supports the lora model with `["q_proj", "v_proj"]` target modules, like `opt`, `llama`.

And, it's not yet supported to use LoRA in the case of using parallel

### CODE REVIEW

**Comment by Saiteja-Tallam-Infrrd** [comment]
@FarziBuilder  The code is not yet merged to main. @mymusise When can we expect this to be merged to main branch ?

**Comment by efraisse** [comment]
@Saiteja-Tallam-Infrrd what fork are you referring to?

**Comment by efraisse** [comment]
@Saiteja-Tallam-Infrrd I think I made a mistake while cloning the repo. I was able to get it to work as well.

**Comment by nivibilla** [comment]
Hey, I see that this only works for q,v loras. However most of the Qlora fine tunes use all k,q,v,o,up and down proj layers. Is there a way to get all of them to work?

**Comment by admangan** [comment]
Do you have to pull down Llama2 commits and merge them together in the meantime to work with L2 models?

**Comment by WangYipeng0624** [comment]
It seems that it works only on single gpu inference and does not support tensor parallel. Could it be support in future or any quick way to make it work with Ray?

**Comment by SuperBruceJia** [comment]
> ```python
> edbeeching/opt-125m-imdb-lora
> ```

Thank you very much for your excellent work! It really helps.

There is an error on my side:
```python
File "/projectnb/pnn/test_2/IntuitLLMProject/lib/data_manager.py", line 135, in d_eval_g_data_loader
  lora.LoRAModel.from_pretrained(pipe.llm_engine.workers[0].model, g_saver_dir + '/adapter')
File "/projectnb/pnn/test_2/vllm/vllm/model_executor/adapters/lora.py", line 62, in from_pretrained
  cls.load_adapter(layers, config)
File "/projectnb/pnn/test_2/vllm/vllm/model_executor/adapters/lora.py", line 70, in load_adapter
  new_model = VllmLoRA(
File "/projectnb/pnn/test_2/vllm/vllm/model_executor/adapters/lora.py", line 34, in __init__
  self.active_adapter = adapter_name
File "/usr4/ec523/brucejia/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1754, in __setattr__
  super().__setattr__(name, value)
AttributeError: can't set attribute
```

Thank you very much in advance!

**Comment by SuperBruceJia** [comment]
> > ```python
> > edbeeching/opt-125m-imdb-lora
> > ```
> 
> Thank you very much for your excellent work! It really helps.
> 
> There is an error on my side:
> 
> ```python
> File "/projectnb/pnn/test_2/IntuitLLMProject/lib/data_manager.py", line 135, in d_eval_g_data_loader
>   lora.LoRAModel.from_pretrained(pipe.llm_engine.workers[0].model, g_saver_dir + '/adapter')
> File "/projectnb/pnn/test_2/vllm/vllm/model_executor/adapters/lora.py", line 62, in from_pretrained
>   cls.load_adapter(layers, config)
> File "/projectnb/pnn/test_2/vllm/vllm/model_executor/adapters/lora.py", line 70, in load_adapter
>   new_model = VllmLoRA(
> File "/projectnb/pnn/test_2/vllm/vllm/model_executor/adapters/lora.py", line 34, in __init__
>   self.active_adapter = adapter_name
> File "/usr4/ec523/brucejia/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1754, in __setattr__
>   super().__setattr__(name, value)
> AttributeError: can't set attribute
> ```
> 
> My `adapter_config.json` file is as follows:
> 
> ```json
> {
>   "alpha_pattern": {},
>   "auto_mapping": null,
>   "base_model_name_or_path": "meta-llama/Llama-2-7b-hf",
>   "bias": "none",
>   "fan_in_fan_out": false,
>   "inference_mode": true,
>   "init_lora_weights": true,
>   "layers_pattern": null,
>   "layers_to_transform": null,
>   "lora_alpha": 16,
>   "lora_dropout": 0.1,
>   "modules_to_save": null,
>   "peft_type": "LORA",
>   "r": 64,
>   "rank_pattern": {},
>   "revision": null,
>   "target_modules": [
>     "v_proj",
>     "q_proj"
>   ],
>   "task_type": "CAUSAL_LM"
> }
> ```
> 
> Thank you very much in advance!

Please note that this problem can be solved by commenting [this line](https://github.com/troph-team/vllm/blob/support_peft/vllm/model_executor/adapters/lora.py#L34).

```python
# self.active_adapter = adapter_name
```

And thank you very much again for your excellent work! @mymusise

**Comment by SuperBruceJia** [comment]
> @Saiteja-Tallam-Infrrd what fork are you referring to? I pip installed the [troph-team:support_peft](https://github.com/troph-team/vllm/tree/support_peft) fork on the support_peft branch and got the same error as @FarziBuilder when trying to run `from vllm.model_executor.adapters import lora` : There is no module named 'vllm.model_executor.adapters'

```shell
git clone --branch support_peft https://github.com/troph-team/vllm.git
```

**Comment by corbt** [comment]
Note that for anyone else watching this issue who missed the news, there's an active PR in to vLLM to add most of the tricks from the S-LoRA paper, which is a very elegant way of serving up to thousands of LoRAs simultaneously! https://github.com/vllm-project/vllm/pull/1804

**Comment by SuperBruceJia** [comment]
> Note that for anyone else watching this issue who missed the news, there's an active PR in to vLLM to add most of the tricks from the S-LoRA paper, which is a very elegant way of serving up to thousands of LoRAs simultaneously! #1804

@corbt That sounds great! Thank you so much for the update!

**Comment by oushu1zhangxiangxuan1** [comment]
Great work, I'm waiting for this FEATURE, when will this PR be merged?

**Comment by callanwu** [comment]
mark

**Comment by allzero-kwon** [comment]
mark. Is this any merged PR for LoRA?

**Comment by echo669** [comment]
Traceback (most recent call last):
  File "../lora_inference.py", line 62, in <module>
    lora.LoRAModel.from_pretrained(llm.llm_engine.workers[0].model, "....")
  File ".../python3.10/site-packagesllm/model_executor/adapters/lora.py", line 62, in from_pretrained
    cls.load_adapter(layers, config)
  File ".../python3.10/site-packagesllm/model_executor/adapters/lora.py", line 70, in load_adapter
    new_model = VllmLoRA(
  File "../python3.10/site-packagesllm/model_executor/adapters/lora.py", line 27, in __init__
    ColumnParallelLinear.__init__(self, input_size, output_size, *args, **kwargs)
  File ".../python3.10/site-packagesllm/model_executor/parallel_utils/tensor_parallel/layers.py", line 272, in __init__
    self.weight = Parameter(torch.empty(
  File "../python3.10/site-packages/torch/nn/modules/module.py", line 1712, in __setattr__
    self.register_parameter(name, value)
  File "../python3.10/site-packages/torch/nn/modules/module.py", line 577, in register_parameter
    elif hasattr(self, name) and name not in self._parameters:
  File "../python3.10/site-packages/peft/tuners/tuners_utils.py", line 355, in weight
    weight = base_layer.weight
  File "../python3.10/site-packages/peft/tuners/tuners_utils.py", line 355, in weight
    weight = base_layer.weight
  File "../python3.10/site-packages/peft/tuners/tuners_utils.py", line 355, in weight
    weight = base_layer.weight
  [Previous line repeated 984 more times]
  File "../python3.10/site-packages/peft/tuners/tuners_utils.py", line 349, in weight
    base_layer = self.get_base_layer()
  File "../python3.10/site-packages/peft/tuners/tuners_utils.py", line 338, in get_base_layer
    while hasattr(base_layer, "base_layer"):
  File "../python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
RecursionError: maximum recursion depth exceeded while calling a Python object

Does anyone have the same error as me?

**Comment by SuperBruceJia** [comment]
> Traceback (most recent call last): File "../lora_inference.py", line 62, in lora.LoRAModel.from_pretrained(llm.llm_engine.workers[0].model, "....") File ".../python3.10/site-packagesllm/model_executor/adapters/lora.py", line 62, in from_pretrained cls.load_adapter(layers, config) File ".../python3.10/site-packagesllm/model_executor/adapters/lora.py", line 70, in load_adapter new_model = VllmLoRA( File "../python3.10/site-packagesllm/model_executor/adapters/lora.py", line 27, in **init** ColumnParallelLinear.**init**(self, input_size, output_size, *args, **kwargs) File ".../python3.10/site-packagesllm/model_executor/parallel_utils/tensor_parallel/layers.py", line 272, in **init** self.weight = Parameter(torch.empty( File "../python3.10/site-packages/torch/nn/modules/module.py", line 1712, in **setattr** self.register_parameter(name, value) File "../python3.10/site-packages/torch/nn/modules/module.py", line 577, in register_parameter elif hasattr(self, name) and name not in self._parameters: File "../python3.10/site-packages/peft/tuners/tuners_utils.py", line 355, in weight weight = base_layer.weight File "../python3.10/site-packages/peft/tuners/tuners_utils.py", line 355, in weight weight = base_layer.weight File "../python3.10/site-packages/peft/tuners/tuners_utils.py", line 355, in weight weight = base_layer.weight [Previous line repeated 984 more times] File "../python3.10/site-packages/peft/tuners/tuners_utils.py", line 349, in weight base_layer = self.get_base_layer() File "../python3.10/site-packages/peft/tuners/tuners_utils.py", line 338, in get_base_layer while hasattr(base_layer, "base_layer"): File "../python3.10/site-packages/torch/nn/modules/module.py", line 1695, in **getattr** raise AttributeError(f"'{type(self).**name**}' object has no attribute '{name}'") RecursionError: maximum recursion depth exceeded while calling a Python object
> 
> Does anyone have the same error as me?

Please check my solution: https://github.com/SuperBruceJia/vllm

```shell
git clone --branch support_peft https://github.com/SuperBruceJia/vllm.git
cd vllm
pip install -e . --user
```

**Special Notice**:
1. Only support 

```python
target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
        ],
```

2. Only support inference by one GPU

Please let me know if you have any questions!

Best regards,

Shuyue
Dec. 30th, 2023

**Comment by Senna1960321** [comment]
@mymusise 
Thank you for your code. I can now load the LoRa generated from fine-tuning the LLama2-7b-chat-hf bin model. I've noticed that it performs quite consistently in generative tasks, but when it comes to detailed inference tasks, its output results are unstable, and the error rate is relatively high. If I don't load it through vllm, I can consistently infer the correct content. Have you encountered this situation before?

**Comment by xiaobo-Chen** [comment]
@SuperBruceJia, does your solution accommodate the ChatGLM2 model? If I intend to utilize ChatGLM2, which codes should I modify? I presume I need to add a MODEL_LAYER_MAPPING in mapping.py, yet the layer names differ from those of Llama,and 
It seems that the code does not adapt to the structure .I greatly appreciate your assistance

**Comment by SuperBruceJia** [comment]
> @SuperBruceJia, does your solution accommodate the ChatGLM2 model? If I intend to utilize ChatGLM2, which codes should I modify? I presume I need to add a MODEL_LAYER_MAPPING in mapping.py, yet the layer names differ from those of Llama,and It seems that the code does not adapt to the structure .I greatly appreciate your assistance

**I think you could, but you need to have a LoRa adapter for the ChatGLM2 model.**

**First of all, you are suggested to add a LoRA adapter to your base ChatGLM2 Model**:
```python
from peft import LoraConfig, TaskType
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
)

model = AutoModelForCausalLM.from_pretrained("THUDM/chatglm2-6b")

lora_config = LoraConfig(
    r=lora_r,
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    bias="none",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
    ],
    task_type=TaskType.CAUSAL_LM,
)
model.add_adapter(lora_config, adapter_name="adapter")
model.enable_adapters()
```

**After connecting (and maybe going through several rounds of training) the adapter, you need to save it to a folder in your local directory**.
```python
trainer.train()  # Train the adapter
trainer.model.save_pretrained(save_path)  # Only the adapter will be saved.
```

**Afterwards, you can load the `base model + adapter` using vLLM**:
```python
from vllm import LLM, SamplingParams
from vllm.model_executor.adapters import lora

# Create an LLM.
llm = LLM(model="THUDM/chatglm2-6b", gpu_memory_utilization=0.85)

# Add LoRA adapter
lora.LoRAModel.from_pretrained(llm.llm_engine.workers[0].model, "save_path")

prompts = [
    "Hello, my name is",
    "The capital of France is",
    "The future of AI is",
]

sampling_params = SamplingParams(temperature=0, top_k=-1)
outputs = llm.generate(prompts, sampling_params)

for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

If you have any further questions, please let me know.

Best regards,

Shuyue
Jan. 16th, 2023

**Comment by SuperBruceJia** [comment]
> @SuperBruceJia, does your solution accommodate the ChatGLM2 model? If I intend to utilize ChatGLM2, which codes should I modify? I presume I need to add a MODEL_LAYER_MAPPING in mapping.py, yet the layer names differ from those of Llama,and It seems that the code does not adapt to the structure .I greatly appreciate your assistance

Please take a look at the fine-tuning codes of the LLaMA 2 (7B) model.
**Main execution file**: https://github.com/SuperBruceJia/MetaMath-Fine-Tune-with-LoRA/blob/main/main.py
**Model loader**: https://github.com/SuperBruceJia/MetaMath-Fine-Tune-with-LoRA/blob/main/lib/model_loader.py#L98-L108
**Evaluation**: https://github.com/SuperBruceJia/MetaMath-Fine-Tune-with-LoRA/blob/main/lib/evaluation.py#L129-L137

Best regards,

Shuyue
Jan. 16th, 2024

**Comment by Senna1960321** [comment]
@SuperBruceJia Hello, I can now load the LoRa generated from fine-tuning the LLama2-7b-chat-hf bin model. I've noticed that it performs quite consistently in generative tasks, but when it comes to detailed inference tasks, its output results are unstable, and the error rate is relatively high. If I don't load it through vllm, I can consistently infer the correct content. Have you encountered this situation before?

**Comment by SuperBruceJia** [comment]
> @SuperBruceJia Hello, I can now load the LoRa generated from fine-tuning the LLama2-7b-chat-hf bin model. I've noticed that it performs quite consistently in generative tasks, but when it comes to detailed inference tasks, its output results are unstable, and the error rate is relatively high. If I don't load it through vllm, I can consistently infer the correct content. Have you encountered this situation before?

During inference using the fine-tuned pre-trained model, the model's generations were worse. **However, the performance was pretty good under the setting `fixed pre-trained models + trained LoRA adapters`.**

Like this:

```python
llama_path = "YOUR_LLAMA_MODEL_PATH"  # The original pre-trained model is not fine-tuned
adapter_path = "YOUR_SAVED_ADAPTER_PATH"  # Only the LoRA adapter is fine-tuned
llm = LLM(model=llama_path, tensor_parallel_size=1, gpu_memory_utilization=0.85)
lora.LoRAModel.from_pretrained(llm.llm_engine.workers[0].model, adapter_path) 
```

**Please inform me if you have found a solution.**

Best regards,

Shuyue
Jan. 22nd, 2024

**Comment by Senna1960321** [comment]
> > @SuperBruceJia Hello, I can now load the LoRa generated from fine-tuning the LLama2-7b-chat-hf bin model. I've noticed that it performs quite consistently in generative tasks, but when it comes to detailed inference tasks, its output results are unstable, and the error rate is relatively high. If I don't load it through vllm, I can consistently infer the correct content. Have you encountered this situation before?
> 
> During inference using the fine-tuned pre-trained model, the model's generations were worse. **However, the performance was pretty good under the setting `fixed pre-trained models + trained LoRA adapters`.**
> 
> Like this:
> 
> ```python
> llama_path = "YOUR_LLAMA_MODEL_PATH"  # The original pre-trained model is not fine-tuned
> adapter_path = "YOUR_SAVED_ADAPTER_PATH"  # Only the LoRA adapter is fine-tuned
> llm = LLM(model=llama_path, tensor_parallel_size=1, gpu_memory_utilization=0.85)
> lora.LoRAModel.from_pretrained(llm.llm_engine.workers[0].model, adapter_path) 
> ```
> 
> **Please inform me if you have found a solution.**
> 
> Best regards,
> 
> Shuyue Jan. 22nd, 2024

@SuperBruceJia Thank you for your code. This way can make the response better, but it still worse than the way without vllm.

**Comment by zhuohan123** [comment]
Solved by #1804

**Comment by meiru-cam** [comment]
Hi @SuperBruceJia, Thank you for providing the lora support code. I tried to install from source. But received error with pyproject. Do you have any idea on how to fix this? 


image

**Comment by SuperBruceJia** [comment]
> Hi @SuperBruceJia, Thank you for providing the lora support code. I tried to install from source. But received error with pyproject. Do you have any idea on how to fix this?
> 
> image

Sorry,  I haven't met this issue yet. 

It seems that the issue is related to the version of CUDA being used, as described [here](https://github.com/vllm-project/vllm/issues/1391#issuecomment-1890072301).

**Comment by meiru-cam** [comment]
@SuperBruceJia Thanks. May I ask the CUDA version that is applicable? I tried CUDA12.1 which is not working, as well as CUDA11.8

**Comment by SuperBruceJia** [comment]
> @SuperBruceJia Thanks. May I ask the CUDA version that is applicable? I tried CUDA12.1 which is not working, as well as CUDA11.8

Please open your terminal and check the CUDA version on your laptop via the `nvidia-smi` command.

**Pull request closed without merging**
