### PR TITLE
[Doc] Add github links for source code references

### PR DESCRIPTION
**Pull request by russellb**
Previously, the use of `sphinx.ext.viewcode` generated new pages that
included the raw source code. This change adds the
`sphinx.ext.linkcode` extension, which allows defining a custom method
for generating source code URLs given a code reference. This now
includes links to the appropriate file and line number on github for
code references.

For now I left the `viewcode` extension in place. The result is that
code references now have 2 `[source]` links - one for the copy of the
source in the docs, and one to github. If the github links seem to
work well enough, we can drop `viewcode` later.

Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Hmm, the links don't work inside PR builds. I think we should fallback to `main` branch in this case.

**Comment by russellb** [comment]
@DarkLight1337 PR build seems to be working now

**Comment by DarkLight1337** [comment]
Looks good overall. There is still one failing case, `vllm.multimodal.MULTIMODAL_REGISTRY`: https://vllm--10672.org.readthedocs.build/en/10672/design/multimodal/multimodal_index.html#registry

**Comment by russellb** [comment]
> Looks good overall. There is still one failing case, `vllm.multimodal.MULTIMODAL_REGISTRY`: https://vllm--10672.org.readthedocs.build/en/10672/design/multimodal/multimodal_index.html#registry

Thanks. I just improved this one. It's a link to the class `MultiModalRegistry` instead of the specific instance of that class, `MULTIMODAL_REGISTRY`, because `inspect` raises an exception if you pass it an instance of a class. This isn't perfect, but it's better than what it did before with a totally broken link.

**Review by DarkLight1337 — APPROVED** [review]
It works now, thanks for spending the time and effort on polishing this!

**Pull request merged**
