### PR TITLE
Fix #826 - TypeError: issubclass() arg 1 must be a class

### LINKED ISSUE #826: OpenAI-Compatible Server throwing error inside Docker
After using this command inside the docker container  " python -m vllm.entrypoints.openai.api_server \
--model facebook/opt-125m " 

root@e4c01cdbf8f2:/workspace# python -m vllm.entrypoints.openai.api_server     --model facebook/opt-125m
INFO 08-22 09:09:12 llm_engine.py:70] Initializing an LLM engine with config: model='facebook/opt-125m', tokenizer='facebook/opt-125m', tokenizer_mode=auto, trust_remote_code=False, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 589, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 101, in __init__
    self._init_workers(distributed_init_method)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 119, in _init_workers
    from vllm.worker.worker import Worker  # pylint: disable=import-outside-toplevel
  File "/usr/local/lib/python3.8/dist-packages/vllm/worker/worker.py", line 10, in <module>
    from vllm.model_executor import get_model, InputMetadata, set_random_seed
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/__init__.py", line 2, in <module>
    from vllm.model_executor.model_loader import get_model
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/model_loader.py", line 9, in <module>
    from vllm.model_executor.models import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/__init__.py", line 1, in <module>
    from vllm.model_executor.models.baichuan import (BaiChuanForCausalLM,
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/baichuan.py", line 33, in <module>
    from vllm.model_executor.layers.activation import SiluAndMul
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/layers/activation.py", line 5, in <module>
    from vllm import activation_ops
ImportError: /usr/local/lib/python3.8/dist-packages/vllm/activation_ops.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### PR DESCRIPTION
**Pull request by adarshxs**
Fix #826 
```
python -m vllm.entrypoints.openai.api_server --model facebook/opt-125m
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 21, in <module>
    from vllm.entrypoints.openai.protocol import (
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/protocol.py", line 106, in <module>
    class CompletionResponseChoice(BaseModel):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

```

### CODE REVIEW

**Comment by WoosukKwon** [comment]
Hi @adarshxs, which version of vLLM do you use?

I thought this problem was solved by #1429

**Comment by adarshxs** [comment]
Hey!
I'm using the latest vllm 0.2.1.post1

The issue with #1429 I think is that fastapi 0.104.1 now requires typing-extensions>=4.8.0 whereas #1429 explicitly mentions using typing-extensions==4.5.0

image

**Comment by adarshxs** [comment]
Hey! @WoosukKwon any updates?

**Comment by WoosukKwon** [comment]
Hi @adarshxs, if I understand correctly, the problem was fixed in #1429 (which was merged after `v0.2.1.post1` was released). We've just released v0.2.2 and it seems the error does not happen (I've checked it out in `nvcr.io/nvidia/pytorch:23.10-py3`. Please let us know if the bug persists.

**Comment by adarshxs** [comment]
ya #1429 fixed it. Thank you!

**Pull request closed without merging**
