### PR TITLE
[Bugfix] fix sharded state loader for lora

### PR DESCRIPTION
**Pull request by aurickq**
Short fix for the `ShardedStateLoader` when `enable_lora=True`. Users need to save the model also using `enable_lora=True`

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by sfc-gh-zhwang — APPROVED** [review]

**Comment by aurickq** [comment]
@Yard1

**Comment by Yard1** [comment]
LoRA tensors will always be bigger or equal to base tensors, so we can just copy the loaded data into a slice. How about we just take that into account if lora is enabled? I think it should work in all cases.

**Comment by aurickq** [comment]
right, that was the original approach but we found a bug with it. since the checkpoint is already sharded, but lora appends values to the end of the unsharded tensor, it left some weights empty where they shouldn't be. it was giving some garbage outputs which we don't see anymore with this fix

**Comment by Yard1** [comment]
Hmm that's interesting! Let me think a little more about this. Do you have a script to reproduce?

**Comment by Yard1** [comment]
Here's what I am thinking:
currently, LoRA added embeddings work in the following fashion:
```
TP 2:

[ base_embedding_0, base_embedding_1, base_embedding_2, base_embedding_3] ->[ base_embedding_0, base_embedding_1], [base_embedding_2, base_embedding_3]

[ base_embedding_0, base_embedding_1, base_embedding_2, base_embedding_3, lora_embedding_0, lora_embedding_1 ] -> [ base_embedding_0, base_embedding_1, base_embedding_2 ], [ base_embedding_3, lora_embedding_0, lora_embedding_1 ]
```
indeed, the way we shard LoRA embeddings means that we will not be able to reuse the shards made for the base case. However, we should  be able to easily do the following instead:
```
[ base_embedding_0, base_embedding_1, base_embedding_2, base_embedding_3] AND [ lora_embedding_0, lora_embedding_1 ] -> [ base_embedding_0, base_embedding_1, lora_embedding_0], [ base_embedding_2, base_embedding_3, lora_embedding_1 ]
```
we split the added LoRA embeddings into n-parts, and append each part to the original shards. Then we just need to modify the logic in https://github.com/vllm-project/vllm/blob/ee3eea0a1b2c690557455d97074d8829d5a98320/vllm/model_executor/layers/vocab_parallel_embedding.py#L90-L96 to account for that.

I should be able to get something out before EOW. Let me know if this makes sense (happy to also sync offline).

**Comment by sfc-gh-zhwang** [comment]
@Yard1 are you suggesting we actually change the way we pad and shard embedding+lora?

**Comment by Yard1** [comment]
@sfc-gh-zhwang Yes, it should be a straightforward change. We simply distribute the LoRA-added embeddings differently so that they are always appended to base embedding shards. It should have the same runtime performance, too. I am happy to make that change.

**Comment by sfc-gh-zhwang** [comment]
> @sfc-gh-zhwang Yes, it should be a straightforward change. We simply distribute the LoRA-added embeddings differently so that they are always appended to base embedding shards. It should have the same runtime performance, too. I am happy to make that change.

Oh I didn't know we were able to change this, if it's straightforward, then yeah, i think it's easier to do and less hacky. And going forward, we should follow the same principle for any potential paddings introduced by Lora 😄

**Comment by aurickq** [comment]
> Hmm that's interesting! I think I see the issue now, with the way the embeddings are sharded. Let me think a little more about this. Ideally we wouldn't need to have separate checkpoints. Do you have a script to reproduce?

thanks for looking into it! steps to reproduce are:

1. Download llama 3 8b: `huggingface_hub.snapshot_download("meta-llama/Meta-Llama-3-8B")`
2. Save the sharded checkpoint: `python examples/save_sharded_state.py --model $HF_HOME/hub/models--meta-llama--Meta-Llama-3-8B/snapshots/62bd457b6fe961a42a631306577e622c83876cb6/ --tensor-parallel-size 8 --output ~/llama3-8b-tp8 --enable-lora`
3. Run `examples/offline_inference.py` with `model="~/llama3-8b-tp8"`, `tensor_parallel_size=8`, and `load_format="sharded_state"`

**Pull request closed without merging**
