### PR TITLE
[CI/Build] Print running script to enhance CI log readability

### PR DESCRIPTION
**Pull request by jeejeelee**
Some tests in CI involve executing Python scripts, making it difficult to quickly identify which script is causing failure. It is recommended to print script information before running such tests to help quickly locate the corresponding script.

@DarkLight1337

### CODE REVIEW

**Review by DarkLight1337 — APPROVED** [review]

**Review by DarkLight1337 — CHANGES_REQUESTED** [review]
We should use single quotes inside the yaml file since the content of this file is being expanded inside jinja template strings.

**Review by DarkLight1337 — APPROVED** [review]

**Comment by jeejeelee** [comment]
[The output](https://buildkite.com/vllm/ci-aws/builds/11714#019359c3-a047-42a0-98eb-9483d1a22811/194-260) meets the expectations of this PR, and the example test  failure also shows that #10450  is not the reason

**Comment by youkaichao** [comment]
we should do it in the ci repo level , see https://github.com/vllm-project/buildkite-ci/pull/52

**Comment by jeejeelee** [comment]
@youkaichao It looks like  https://github.com/vllm-project/buildkite-ci/pull/52 has implemented this functionality, right? If so, I will close this PR.

**Comment by youkaichao** [comment]
> @youkaichao It looks like [vllm-project/buildkite-ci#52](https://github.com/vllm-project/buildkite-ci/pull/52) has implemented this functionality, right? If so, I will close this PR.

let me check for some ci jobs

**Comment by jeejeelee** [comment]
@youkaichao @DarkLight1337 
It seems that merging this branch into forked main triggered an automatic merge. I apologize, I didn't notice this point.​​​​​​​​​​​​​​​​

**Comment by youkaichao** [comment]
no worry. i have reverted the change.

**Pull request merged**
