### PR TITLE
Bump up the version to v0.1.5

### PR DESCRIPTION
**Pull request by WoosukKwon**
Let's bump up the version after merging the following PRs:

- [x] #646, #857
- [x] #938
- [x] #941
- [x] #943

### CODE REVIEW

**Comment by zhuohan123** [comment]
LGTM!

**Review by zhuohan123 — APPROVED** [review]

**Comment by WoosukKwon** [comment]
@zhuohan123 Thanks! Let me do final testing before merging this PR and making a new release.

**Comment by Yard1** [comment]
@WoosukKwon @zhuohan123 I had a report that the async engine still gets stuck, I will try to reproduce that tomorrow - can you wait with release until that's cleared? In the worst case we can revert the async engine change for now.

**Comment by WoosukKwon** [comment]
@Yard1 Thanks for bringing it up. Please let us know when you have tested it. We will wait until then.

**Pull request merged**
