### PR TITLE
[Kernel] Add punica dimension for Qwen2 LoRA

### PR DESCRIPTION
**Pull request by jinzhen-lin**
The intermediate size of all qwen2 models is not supported by punica yet.

- qwen2-0.5b: [4864](https://huggingface.co/Qwen/Qwen2-0.5B-Instruct/blob/main/config.json)
- qwen2-1.5b: [8960](https://huggingface.co/Qwen/Qwen2-1.5B-Instruct/blob/main/config.json)
- qwen2-7b: [18944](https://huggingface.co/Qwen/Qwen2-7B-Instruct/blob/main/config.json)
- qwen2-72b: [29568](https://huggingface.co/Qwen/Qwen2-72B-Instruct/blob/main/config.json)、[29696](https://huggingface.co/Qwen/Qwen2-72B-Instruct-GPTQ-Int4/blob/main/config.json) (gptq/awq version)

This pr add punica dimension for qwen2 LoRA. It also support qwen2 lora with some tensor parallel sizes.

### CODE REVIEW

**Comment by jeejeelee** [comment]
ping @simon-mo  @Yard1

**Comment by jeejeelee** [comment]
@jinzhen-lin  It seems that we also need  add `896`, is that right?

**Comment by jinzhen-lin** [comment]
> @jinzhen-lin It seems that we also need add `896`, is that right?

Why `896` ? I am not familiar with punica implement, so I only add all related dimensions.

**Comment by jeejeelee** [comment]
Qwen2-0.5b‘s hidden_size is `896`.

**Comment by jinzhen-lin** [comment]
> Qwen2-0.5b‘s hidden_size is `896`.

Oh, I forgot the hidden size. Thanks.

**Comment by puppet101** [comment]
when using Qwen2-72b-instruct, it occurs the below error.:
RuntimeError: No suitable kernel. h_in=16 h_out=3696 dtype=Float out_dtype=Half.

Why do you only add 3712 instead of 3696?

**Comment by jinzhen-lin** [comment]
> when using Qwen2-72b-instruct, it occurs the below error.: RuntimeError: No suitable kernel. h_in=16 h_out=3696 dtype=Float out_dtype=Half.
> 
> Why do you only add 3712 instead of 3696?

3696 is not diviable by `64 = vec_size * 8`, it cannot pass this assert:

https://github.com/vllm-project/vllm/blob/88407532e7ec2dd3313f6cb3a31d8dd1fa868178/csrc/punica/bgmv/bgmv_impl.cuh#L349-L351

To support 3696, more modification is needed, but I am not familiar with punica implement now.

If your loras only include module in attention, https://github.com/vllm-project/vllm/pull/5483 can be a solution.

**Comment by marcelbra** [comment]
Will you merge this soon? I am in an managed environment and I cannot just modify stuff myself. Thanks!

**Review by starmemda — APPROVED** [review]

**Comment by starmemda** [comment]
@youkaichao @WoosukKwon @zhuohan123 @simon-mo @Yard1 @DarkLight1337 @rkooo567 
Could you please merge this PR soon? Supporting Qianwen2 LoRA is crucial for vLLM to enhance the availability.

**Review by simon-mo — APPROVED** [review]

**Comment by starmemda** [comment]
@youkaichao @WoosukKwon @zhuohan123 @simon-mo @Yard1 @DarkLight1337 @rkooo567
Could you release the newest docker image by the way? OR is there any plan to build the newest docker image to support Qwen2 LoRA?
Qianwen2 LoRA  is much efficient than previous Qwen version.

**Comment by duwonders** [comment]
Our team use qwen2-LoRA too. waiting for new image of vllm to save our predict performance~

**Pull request merged**
