### PR TITLE
[Core] Add Sliding Window Support with Flashinfer

### LINKED ISSUE #9854: [help wanted]: add sliding window support for flashinfer
### Anything you want to discuss about vllm.

flashinfer already supports sliding window in https://github.com/flashinfer-ai/flashinfer/issues/159 , and we should update our code and pass sliding window to flashinfer , to remove this restriction: 

https://github.com/vllm-project/vllm/blob/5f8d8075f957d5376b2f1cc451e35a2a757e95a5/vllm/attention/backends/flashinfer.py#L739-L740

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by pavanimajety**
Fix #9854

Tests following.

### CODE REVIEW

**Comment by youkaichao** [comment]
Looking forward to it! Please ping me when it is ready.

**Review by mgoin — APPROVED** [review]
LGTM pending green CI, thanks cc @youkaichao

**Review by youkaichao — APPROVED** [review]
thanks for the great contribution!

**Comment by pavanimajety** [comment]
Just rebased, seems like a few fixes went in main. The test failures seem unrelated to this PR

**Pull request merged**
