### PR TITLE
ChatGLM2 Support

### PR DESCRIPTION
**Pull request by GoHomeToMacDonal**
An implementation of ChatGLM 2 based on vLLM. This implementation adapts `PagedAttentionWithRoPE` and `ParallelLinear` layers for model inference.

### CODE REVIEW

**Comment by Lzhang-hub** [comment]
@GoHomeToMacDonal  I clone your repo and `pip install -e .` lanch a test.py

```
from vllm import LLM, SamplingParams
  
def build_prompt(prompt):
    return "[Round 1]\n\n问：{}\n\n答：".format(prompt)

content = "你好"
prompts = [
    content,
    "晚上睡不着应该怎么办"
]
prompts = [build_prompt(item) for item in prompts]
# edit this model_url
model_url = '/chatglm2-6b'

sampling_params = SamplingParams(temperature=0.8, top_p=0.95, max_tokens=8192)
llm = LLM(model=model_url, gpu_memory_utilization=0.98, dtype="float16", trust_remote_code=True)
outputs = llm.generate(prompts, sampling_params)

# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

```

get the error:
```
Traceback (most recent call last):
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/faster-infer/model-serving/pkg/scripts/test_chatglm.py", line 16, in <module>
    llm = LLM(model=model_url, gpu_memory_utilization=0.98, dtype="float16", trust_remote_code=True)
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/faster-infer/model-serving/pkg/chatglm2-vllm/vllm/entrypoints/llm.py", line 93, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/faster-infer/model-serving/pkg/chatglm2-vllm/vllm/engine/llm_engine.py", line 231, in from_engine_args
    engine = cls(*engine_configs,
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/faster-infer/model-serving/pkg/chatglm2-vllm/vllm/engine/llm_engine.py", line 96, in __init__
    self._verify_args()
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/faster-infer/model-serving/pkg/chatglm2-vllm/vllm/engine/llm_engine.py", line 187, in _verify_args
    self.model_config.verify_with_parallel_config(self.parallel_config)
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/faster-infer/model-serving/pkg/chatglm2-vllm/vllm/config.py", line 128, in verify_with_parallel_config
    total_num_hidden_layers = self.hf_config.num_hidden_layers
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/ke-vllm/lib/python3.10/site-packages/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'ChatGLMConfig' object has no attribute 'num_hidden_layers'
```

is need a special transformers version ?

**Comment by simon-mo** [comment]
Thank you for the contribution, unfortunately this PR seems to have some merge conflict and ChatGLM3 also came out. Feel free to coordinate the contribution here if you have bandwidth! 

https://github.com/vllm-project/vllm/issues/1552

**Comment by GoHomeToMacDonal** [comment]
@simon-mo Hi, we have resolved the code conflict, and it can be directly merged into the main branch.

As chatglm3 does not change the model structure, this implementation can be directly adopted to chatglm3. Below is the testing code:

```
from vllm import LLM, SamplingParams

prompts = ["""<|system|>
You are ChatGLM3, a large language model trained by Zhipu.AI. Follow the user's instructions carefully. Respond using markdown.
<|user|>
Hello
<|assistant|>
"""]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

llm = LLM(model="/home/skim/.cache/modelscope/hub/ZhipuAI/chatglm3-6b", trust_remote_code=True)

outputs = llm.generate(prompts, sampling_params)

# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

```

The output will be `Hello! How can I assist you today?`

**Review by zhuohan123 — APPROVED** [review]
LGTM! Merged with main and fixed a small style issue. The code works with both ChatGLM2 and ChatGLM3 on one GPU in my case. Thank you for your contribution!

**Comment by Midnight-719** [comment]
hi ,can u tell me how to use it , I still have this problem: AttributeError: 'ChatGLMConfig' object has no attribute 'num_hidden_layers', Currently, I have updated to the latest version of VLLM

**Comment by GoHomeToMacDonal** [comment]
This is problem is caused by old version of transformers. I suggest upgrading both your transformers package and ChatGLM model to the recent versions.

**Comment by Midnight-719** [comment]
> This is problem is caused by old version of transformers. I suggest upgrading both your transformers package and ChatGLM model to the recent versions.

Yes, I have tried，transformers==4.35.0

**Comment by GoHomeToMacDonal** [comment]
> > This is problem is caused by old version of transformers. I suggest upgrading both your transformers package and ChatGLM model to the recent versions.
> 
> Yes, I have tried，transformers==4.35.0

Please provide more information of installed packages, and I will try to reproduce your problem later.

**Comment by Jeffwan** [comment]
@GoHomeToMacDonal If you use other prompts, it shows big difference between the native ones.. Seems this PR is not that reliable.

**Comment by magiclogy-** [comment]
> @GoHomeToMacDonal If you use other prompts, it shows big difference between the native model.. Did you try more examples?
> 
> this is one example, seems it stopped after meeting some token image

I guess you used the default `max_tokens=16` in the sampling parameters. I suggest to set `max_tokens` to a larger value, e.g., `1024`. For more details, please refer to [vllm/sampling_params.py](https://github.com/vllm-project/vllm/blob/main/vllm/sampling_params.py). 


In addition, as ChatGLM3 added some special tokens, e.g., `<|system|>`, use `ChatGLMTokenizer.build_chat_input` build the input token ids and feed them into vLLM will generate more stable results.

**Comment by GoHomeToMacDonal** [comment]
> @GoHomeToMacDonal If you use other prompts, it shows big difference between the native model.. Did you try more examples?
> 
> this is one example, seems it stopped after meeting some token image

I guess you used the default `max_tokens=16` in the sampling parameters. I suggest to set `max_tokens` to a larger value, e.g., `1024`. For more details, please refer to [vllm/sampling_params.py](https://github.com/vllm-project/vllm/blob/main/vllm/sampling_params.py). 


In addition, as ChatGLM3 added some special tokens, e.g., `<|system|>`, use `ChatGLMTokenizer.build_chat_input` build the input token ids and feed them into vLLM will generate more stable results.

**Comment by Jeffwan** [comment]
@GoHomeToMacDonal It is the max_tokens setting issue. adding `max_tokens` works as expected. It's my first time using openai wrapper, thanks for the advice. BTW, I plan to use https://github.com/lm-sys/FastChat/pull/2622 to build the conv template, I did some test and the result looks equivalent to what `ChatGLMTokenizer.build_chat_input` generates. 

> build the input token ids and feed them into vLLM will generate more stable results.
Just curious, does vllm provides the token interface?

**Comment by wangruohui** [comment]
Hello, I am using ChatGLM2 but it seems sometimes the output is not aligned with huggingface version. Could anyone help to take a look at #1670 ?

**Comment by zengzikang** [comment]
The latest version already supports GLM. Can GLM3 support official tool calls and other functions? Does it support dialogue function?

**Comment by GoHomeToMacDonal** [comment]
> The latest version already supports GLM. Can GLM3 support official tool calls and other functions? Does it support the dialogue function?

You need to implement the corresponding code for function calls and prompt building. The `vllm` library focuses on model inference, i.e., it can substitute `ChatGLMForConditionalGeneration.generate` to `llm.generate`. I suggest building prompts based on the official ChatGLM 3 repository, and replacing model inference functions, e.g., `ChatGLMForConditionalGeneration.chat`, `ChatGLMForConditionalGeneration.stream_chat` with `vLLM`.

**Comment by junior-zsy** [comment]
@GoHomeToMacDonal This is still not supported for the Chatglm2-6b-32k version ,I have a message for the issue #1725

**Pull request merged**
