### PR TITLE
[Misc] Update config loading for Qwen2-VL and remove Granite

### PR DESCRIPTION
**Pull request by ywang96**
This PR ports Qwen2-VL config from transformers v4.45 but remove rope type override to address config loading issue, and remove ported Granite config that's no longer required.

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Adding or changing kernels</h3>
<p>Each custom kernel needs a schema and one or more implementations to be registered with PyTorch.</p>
<ul>
    <li>Make sure custom ops are registered following PyTorch guidelines: <a href="https://pytorch.org/tutorials/advanced/cpp_custom_ops.html#cpp-custom-ops-tutorial">Custom C++ and CUDA Operators</a> and <a href="https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU">The Custom Operators Manual</a></li>
    <li>Custom operations that return <code>Tensors</code> require meta-functions. Meta-functions should be implemented and registered in python so that dynamic dims can be handled automatically. See above documents for a description of meta-functions.</li>
    <li>Use <a href="https://pytorch.org/docs/stable/library.html#torch.library.opcheck"><code>torch.libary.opcheck()</code></a> to test the function registration and meta-function for any registered ops.  See <code>tests/kernels</code> for examples.</li>
    <li>When changing the C++ signature of an existing op, the schema must be updated to reflect the changes.</li>
    <li>If a new custom type is needed, see the following document: <a href="https://docs.google.com/document/d/18fBMPuOJ0fY5ZQ6YyrHUppw9FA332CpNtgB6SOIgyuA">Custom Class Support in PT2</a>.
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by DarkLight1337 — APPROVED** [review]

**Comment by njhill** [comment]
Thanks @ywang96  ... I pushed a different fix to this to the other PR, could you see if that looks ok and whether this is still needed if so? https://github.com/vllm-project/vllm/pull/8829/commits/ce1d477041a6808a2082e8d311ea1e5f1d4e29ac

Also we have another PR ready with granite updates which removes the custom granite config, was hoping to get that merged as soon as we got the tests fixed: https://github.com/vllm-project/vllm/pull/8206

**Comment by ywang96** [comment]
> Thanks @ywang96 ... I pushed a different fix to this to the other PR, could you see if that looks ok and whether this is still needed if so? [ce1d477](https://github.com/vllm-project/vllm/commit/ce1d477041a6808a2082e8d311ea1e5f1d4e29ac)
> 
> Also we have another PR ready with granite updates which removes the custom granite config, was hoping to get that merged as soon as we got the tests fixed: #8206

@njhill I think either fix should work, but IMO it's probably better and cleaner to address it within the config file itself rather than having code inside `vllm/transformers_utils/config.py` since `mrope` seems specific to Qwen2-VL and we don't know what the final resolution from huggingface is regarding this issue. WDYT?

**Comment by njhill** [comment]
@ywang96 that's fine with me

**Comment by ywang96** [comment]
I have verified Qwen2VL works with this PR and `tests/models/decoder_only/language/test_granite.py` passed locally.
```
➜  vllm git:(qwenv2-config) python3 examples/offline_inference_vision_language.py --model-type qwen2_vl
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.20k/1.20k [00:00<00:00, 11.4MB/s]
You are using a model of type qwen2_vl to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
preprocessor_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 347/347 [00:00<00:00, 4.01MB/s]
INFO 09-26 06:19:53 llm_engine.py:226] Initializing an LLM engine (v0.6.3.dev2+gdc85b853) with config: model='Qwen/Qwen2-VL-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-VL-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2-VL-7B-Instruct, use_v2_block_manager=False, num_scheduler_steps=1, multi_step_stream_outputs=False, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=False, mm_processor_kwargs=None)
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.19k/4.19k [00:00<00:00, 24.4MB/s]
...
INFO 09-26 06:21:30 model_runner.py:1333] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 09-26 06:21:32 model_runner.py:1456] Graph capturing finished in 2 secs.
chat_template.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.05k/1.05k [00:00<00:00, 10.5MB/s]
Processed prompts: 100%|███████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.08it/s, est. speed input: 5567.31 toks/s, output: 124.87 toks/s]
The image shows a tower with a spherical observation deck, surrounded by cherry blossoms in full bloom. The sky is clear and blue, creating a beautiful contrast with the pink flowers. The tower is partially obscured by the branches and blossoms, giving the scene a serene and picturesque quality.
The image depicts a beautiful scene with cherry blossoms in full bloom. The cherry blossoms, with their delicate pink petals, create a natural frame around a tall, cylindrical structure, which appears to be a tower. The clear blue sky in the background adds to the serene and picturesque atmosphere of the scene.
The image shows a beautiful scene with cherry blossoms in full bloom. The cherry blossoms, with their pink petals, are in the foreground, creating a picturesque frame. In the background, partially obscured by the blossoms, is a tall structure, likely a tower or monument. The clear blue sky provides a vibrant backdrop
The image shows a tall tower with a spherical observation deck, surrounded by cherry blossoms in full bloom. The sky is clear and blue, creating a beautiful contrast with the pink flowers. The tower appears to be the Tokyo Skytree, a famous landmark in Tokyo, Japan.
```

**Comment by ywang96** [comment]
cc @fyabc Let us know if you think this fix is okay, otherwise it's a bit tricky to get Qwen2-VL to run given we had to update transformers to >= 4.45 (so the one dev branch wouldn't work)

**Comment by DarkLight1337** [comment]
Since the other tests have not been fixed, we will likely require force merge for this PR.

**Comment by fyabc** [comment]
> cc @fyabc Let us know if you think this fix is okay, otherwise it's a bit tricky to get Qwen2-VL to run given we had to update transformers to >= 4.45 (which means that particular dev branch wouldn't work)

Sorry for late response! I think current solution is okay.

**Pull request merged**
