### PR TITLE
add doc about serving option on dstack

### PR DESCRIPTION
**Pull request by deep-diver**
This PR is to suggest to include an additional serving option on [dstack](https://dstack.ai/).

cc: @peterschmidt85

### CODE REVIEW

**Comment by deep-diver** [comment]
@LiuXiaoxuanPKU any chance that you have looked into this PR yet?

**Comment by ywang96** [comment]
@deep-diver LGTM in general - but I'm going to make a few changes before merging this.

**Review by ywang96 — APPROVED** [review]
Thanks for adding the doc for integration with dstack! @deep-diver

**Comment by deep-diver** [comment]
@ywang96 looks like some CIs failed?

**Comment by ywang96** [comment]
> @ywang96 looks like some CIs failed?

Our CI is currently a bit flaky (sometimes it requires retries and get through) - I will handle it and get it merged.

**Comment by deep-diver** [comment]
@ywang96 

Could you tell me when this is going to be merged? Thanks!

**Comment by deep-diver** [comment]
Thanks!

**Pull request merged**
