### PR TITLE
[Misc] Add support for new autogptq checkpoint_format

### PR DESCRIPTION
**Pull request by Qubitium**
Reason for PR: make sure loading of gptq marlin quants is compatible with latest autogptq

Due to autogpq update https://github.com/AutoGPTQ/AutoGPTQ/pull/603 quants made with autogptq >=0.8.0-dev will use a new `checkpoint_format` property to hold `marlin` and future formats.

Compat tested with both marlin and non-marlin in both old `is_marlin_format` and new `checkpoint_format`

### CODE REVIEW

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks, will review this

**Comment by robertgshaw2-neuralmagic** [comment]
Do you have examples models in each format I can try?

**Comment by Qubitium** [comment]
@robertgshaw2-neuralmagic 

1. Marlin: https://huggingface.co/LnL-AI/TinyLlama-1.1B-Chat-v1.0-GPTQ-Marlin-4bit
2. Non-Marlin: https://huggingface.co/LnL-AI/TinyLlama-1.1B-Chat-v1.0-GPTQ-4bit

To test marlin compat just change the `quntize_config` param:

`"checkpoint_format": "marlin" => "is_marlin_format": true`

**Review by robertgshaw2-redhat — APPROVED** [review]

**Comment by robertgshaw2-neuralmagic** [comment]
Each of the following works:

- new serialization config
```python
from vllm import LLM
model = LLM("LnL-AI/TinyLlama-1.1B-Chat-v1.0-GPTQ-Marlin-4bit")
model.generate("hello my name is")
```

- old serialization config
```python
from vllm import LLM
odel = LLM("neuralmagic/TinyLlama-1.1B-Chat-v1.0-marlin")
model.generate("hello my name is")
```

**Comment by robertgshaw2-neuralmagic** [comment]
@Qubitium Can you merge the PR I posted to your branch, which adds tests for this case?

https://github.com/Qubitium/vllm/pull/1

**Comment by Qubitium** [comment]
@robertgshaw2-neuralmagic  merged

**Review by robertgshaw2-redhat — APPROVED** [review]

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks @Qubitium !

@simon-mo @WoosukKwon @zhuohan123 this is good to go

**Comment by robertgshaw2-neuralmagic** [comment]
@Qubitium can you rerun `./format.sh`? Will merge after

**Review by robertgshaw2-redhat — CHANGES_REQUESTED** [review]
nvm saw you commit. Letting CI run then will merge

**Review by robertgshaw2-redhat — APPROVED** [review]

**Pull request merged**
