### PR TITLE
[Bugfix][Core] fix broken state for recompute

### LINKED ISSUE #3032: [BUG] Prompt logprobs causing tensor broadcast issue in `sampler.py`
Hi, I am trying to obtain the prompt logprobs of 'meta-llama/llama-2-13b-chat-hf' but run into a size mismatch error. 

Here are the sampling params:
```
SamplingParams(temperature=0, max_tokens=512, prompt_logprobs=1)
```
And here's the model: 
```
self.llm = LLM('meta-llama/llama-2-13b-chat-hf', tensor_parallel_size=2)
```
I run into this issue if I pass in a large number or prompts (say 1k prompts) to the LLM. (For smaller sizes it appears to do fine):  

```
File "/home/abhinavr/git_clones/rlkf/src/model/llama_model.py", line 90, in forward
    responses = self.llm.generate(prompts, sampling_params=sampling_params)
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 182, in generate
    return self._run_engine(use_tqdm)
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 208, in _run_engine
    step_outputs = self.llm_engine.step()
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 817, in step
    all_outputs = self._run_workers(
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 1014, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/vllm/worker/worker.py", line 223, in execute_model
    output = self.model_runner.execute_model(seq_group_metadata_list,
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/vllm/worker/model_runner.py", line 582, in execute_model
    output = self.model.sample(
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 342, in sample
    next_tokens = self.sampler(self.lm_head.weight, hidden_states,
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/vllm/model_executor/layers/sampler.py", line 110, in forward
    prompt_logprobs, sample_logprobs = _get_logprobs(
  File "/home/abhinavr/miniconda3/envs/culeval/lib/python3.9/site-packages/vllm/model_executor/layers/sampler.py", line 479, in _get_logprobs
    batched_logprobs_query_result = logprobs[[
IndexError: shape mismatch: indexing tensors could not be broadcast together with shapes [1589], [1181]
```

I believe #1971 has been looking into this for a while but it seems stagnant and doesn't resolve the issue for `prompt_logprobs`. I am not able to identify the root cause of this issue. Still, it looks like there's some size mismatch between `batched_logprobs_query_seq_indices` and `batched_logprobs_query_token_indices` [in this file](https://github.com/vllm-project/vllm/blob/ef978fe4111b0eb91c81eceba4d9791b94c7ffbf/vllm/model_executor/layers/sampler.py#L464C1-L471C68) due to some recomputation policy when pipelining multiple prompts together. 

```
...
        batched_logprobs_query_seq_indices.extend(
            sample_idx + j for j in range(prompt_len - 1))
        batched_logprobs_query_token_indices.extend(
            token_id for token_id in prompt_tokens[1:])
        sample_idx += prompt_len - 1
    batched_logprobs_query_seq_indices.extend(
        [sample_idx + parent_id for parent_id in parent_ids])
    batched_logprobs_query_token_indices.extend(next_token_ids)
...
```

Expected output: No error, and prompt logprobs are returned as usual.

System information:
```
  Operating System: Ubuntu 20.04.6 LTS
            Kernel: Linux 5.15.0-92-generic
      Architecture: x86-64
```

### PR DESCRIPTION
**Pull request by youkaichao**
fixes https://github.com/vllm-project/vllm/issues/3032 
all computed tokens should be prompt tokens after preemption by recompute

### CODE REVIEW

**Review by robertgshaw2-redhat — APPROVED** [review]

**Comment by robertgshaw2-neuralmagic** [comment]
QQs:
- do we have to consider any cases where we have a shared prompt (e.g. with beam search)?
- do we have to consider any cases with automatic prefix caching

**Comment by youkaichao** [comment]
> do we have to consider any cases where we have a shared prompt (e.g. with beam search)?

A sequence group (in beam search) should be preempted together. So it should be fine.

> do we have to consider any cases with automatic prefix caching

it is possible to divide a preempted sequence into prefix-cached and uncomputed. I don't know if this will be implemented in the future.

This PR simply fixes the broken state, if `self._num_computed_tokens == 0` after the sequence is preempted for recompute, then output tokens should be empty, and all tokens should be prompt tokens.

**Comment by njhill** [comment]
We may need to consider how this affects certain sampling / logits processor options which make a distinction between input and output tokens. Like frequency/repetition penalty etc.

**Comment by youkaichao** [comment]
> We may need to consider how this affects certain sampling / logits processor options which make a distinction between input and output tokens. Like frequency/repetition penalty etc.

good point. to achieve this, we have to distinguish:
|--- prompt(input) tokens ------|-------- decode(output) tokens ---------|
|-------computed tokens (have kv cache) ----------|-----uncomputed tokens (waiting for prefill) -------|

currently we assume prompt(input) tokens = computed tokens (have kv cache) + uncomputed tokens (waiting for prefill) in prefill phase. but it might not be the case after preemption.

might require quite a lot change for scheduling logic?

**Comment by njhill** [comment]
@youkaichao maybe just a new offset field indicating how many tokens have been computed? And then for prefill those can be pulled from the prompt token list + output token list as appropriate.

**Pull request closed without merging**
