### PR TITLE
[Model] Automatic conversion of classification and reward models

### LINKED ISSUE #10674: [RFC]: Make any vLLM model a pooling model
### Motivation.

Currently, we have to open new PRs to add pooling functionality for existing architectures supported in vLLM. Since the code involved is basically the same for each model, there is potential to automate away this boilerplate.

### Proposed Change.

Implement a pooling adapter that can be applied to any existing text generation model in vLLM. To preserve features such as LoRA, PP and multimodality, the adapter simply creates a new subclass of the original model.

- [x] Embedding model adapter: #10769
- [ ] Classification model adapter #11469
- [ ] Reward model adapter #11469

The pooling adapter to apply depends on the purpose of the model. To facilitate this, the `embedding` task will be split up, so that the user can specify which adapter to apply to the model via `--task`:

- [x] #10820
- [x] #11457

Meanwhile, current embedding-related classes will be renamed to avoid confusion between `embed` and other pooling tasks:

- [x] #10801

### Feedback Period.

1-2 weeks

### CC List.

@youkaichao @mgoin @robertgshaw2-neuralmagic @maxdebayser

### Any Other Things.

Note that we can still directly map to pooling models in the model registry. This is used when the model architecture has different pooling defaults (e.g. `pooling_type=CLS` for BERT) or additional modules (e.g. `score` in `Qwen2ForRewardModel`). For models that already support pooling, the adapter returns the original model without modifications.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### LINKED ISSUE #11459: [Usage]:  How to infer the reward model of nvidia/Llama-3.1-Nemotron-70B-Reward-HF?
### Your current environment

```text
The output of `python collect_env.py`
```
python3.9

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by DarkLight1337**
This is the last PR to finish off #10674.

CLOSE #10674
FIX #11459

### CODE REVIEW

**Comment by DarkLight1337** [comment]
cc @maxdebayser

**Review by Isotr0py — APPROVED** [review]
LGTM!

**Comment by umie0128** [comment]
@DarkLight1337  hi 我看到vllm0.6.4/0.6.5 更新说有速度上的提升 但是我对比了0.6.2 跑qwen2.5-7B 感觉速度没有变化。请问是为啥呢

**Comment by DarkLight1337** [comment]
> @DarkLight1337  hi 我看到vllm0.6.4/0.6.5 更新说有速度上的提升 但是我对比了0.6.2 跑qwen2.5-7B 感觉速度没有变化。请问是为啥呢

Hi, this PR is about pooling models, not text generation models. Can you open a new issue for this?

**Comment by dengcao** [comment]
You can use Vllm to deploy the Qwen3-Embedding&Qwen3-Reranker large model.There is already a temporary solution:
以下是通过vllm快捷安装Qwen3-Embedding-0.6B/4B/8B，Qwen3-Reranker-0.6B/4B/8B的办法。

Docker 快速部署（一键安装包）：
Docker Compose Quick Installation:

Hugging Face：
https://huggingface.co/dengcao/Qwen3-Embedding-0.6B
https://huggingface.co/dengcao/Qwen3-Embedding-4B
https://huggingface.co/dengcao/Qwen3-Embedding-8B
https://huggingface.co/dengcao/Qwen3-Reranker-0.6B
https://huggingface.co/dengcao/Qwen3-Reranker-4B
https://huggingface.co/dengcao/Qwen3-Reranker-8B

ModelScope：
https://www.modelscope.cn/models/dengcao/Qwen3-Embedding-0.6B
https://www.modelscope.cn/models/dengcao/Qwen3-Embedding-4B
https://www.modelscope.cn/models/dengcao/Qwen3-Embedding-8B
https://www.modelscope.cn/models/dengcao/Qwen3-Reranker-0.6B
https://www.modelscope.cn/models/dengcao/Qwen3-Reranker-4B
https://www.modelscope.cn/models/dengcao/Qwen3-Reranker-8B

GitHub：
https://github.com/dengcao/Qwen3-Reranker-8B
https://github.com/dengcao/Qwen3-Reranker-4B
https://github.com/dengcao/Qwen3-Reranker-0.6B

**Pull request merged**
