### PR TITLE
[Frontend] API support for beam search

### PR DESCRIPTION
**Pull request by LunrEclipse**
Added support for running a higher layer of beam search across openai API server without frontend multiprocessing.

This PR is a continuation of the existing beam search refactors found [here](https://github.com/vllm-project/vllm/pull/8726#issuecomment-2368872745) and [here](https://github.com/vllm-project/vllm/pull/8763#issue-2544522248).

Manually testing conducted to verify that requests are still ran in parallel and output is correct.

server side:

```
$ vllm serve meta-llama/Meta-Llama-3-8B --disable-frontend-multiprocessing
```
client side:

**Completion**
```
from openai import OpenAI

client = OpenAI(
    base_url="http://localhost:8000/v1",
    api_key="key123",
)

prompt = "Capital of France is"

try:
    completion = client.completions.create(
        model="meta-llama/Meta-Llama-3-8B",
        prompt=prompt,
        max_tokens=4,
        extra_body={'use_beam_search': True, 'best_of': 3}
    )
    print(completion.choices[0].text)
except Exception as e:
    print(e)
```

**Chat**
```
from openai import OpenAI

client = OpenAI(
    base_url="http://localhost:8000/v1",
    api_key="key123",
)

prompt = "Capital of France is"

try:
    completion = client.chat.completions.create(
        model="meta-llama/Meta-Llama-3-8B",
        messages = [
            {"role": "system", "content": "You are a helpful AI assistant."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=10,
        extra_body={'use_beam_search': True, 'best_of': 3, 'temperature': 0}
    )
    print(completion)
    print(completion.choices[0].message.content)
except Exception as e:
    print(e)
```

### CODE REVIEW

**Comment by youkaichao** [comment]
@robertgshaw2-neuralmagic  I remember there's a thread to wrap mqllengine into an asyncllm engine like interface. if that is done, we can recover beam search support in the mqllmengine too.

@zhuohan123 after this pr, we should start to remove beam search in the core. the vLLM core does not need to know about beam search. all the beam search logic is handled above the core.

**Review by DarkLight1337 — APPROVED** [review]
The API changes look good to me.

**Comment by BabyChouSr** [comment]
@LunrEclipse great work!

**Comment by youkaichao** [comment]
linking https://github.com/vllm-project/vllm/issues/8306 for reference

**Pull request merged**
