### PR TITLE
RoPE in float32 precision

### LINKED ISSUE #863: RoPE should be applied with float32
It seems that RoPE(sin,cos) should be stored and applied in fp32 and then casted back to fp16/bf16

https://github.com/vllm-project/vllm/blob/791d79de3261402fae1b9d0b1650655071a68095/vllm/model_executor/layers/attention.py#L273

Reference implementation from Llama 2 / Code Llama:

```python
def precompute_freqs_cis(dim: int, end: int, theta: float = 10000.0):
    freqs = 1.0 / (theta ** (torch.arange(0, dim, 2)[: (dim // 2)].float() / dim))
    t = torch.arange(end, device=freqs.device, dtype=torch.float32)  # type: ignore
    freqs = torch.outer(t, freqs)  # type: ignore
    freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    return freqs_cis

def apply_rotary_emb(
    xq: torch.Tensor,
    xk: torch.Tensor,
    freqs_cis: torch.Tensor,
) -> Tuple[torch.Tensor, torch.Tensor]:
    xq_ = torch.view_as_complex(xq.float().reshape(*xq.shape[:-1], -1, 2))
    xk_ = torch.view_as_complex(xk.float().reshape(*xk.shape[:-1], -1, 2))
    freqs_cis = reshape_for_broadcast(freqs_cis, xq_)
    xq_out = torch.view_as_real(xq_ * freqs_cis).flatten(3)
    xk_out = torch.view_as_real(xk_ * freqs_cis).flatten(3)
    return xq_out.type_as(xq), xk_out.type_as(xk)
```

### PR DESCRIPTION
**Pull request by imoneoi**
Fixes #863

### CODE REVIEW

**Comment by esmeetu** [comment]
@imoneoi Many thanks for this PR.

@WoosukKwon Hope you can consider this PR, this will truely support codellama with float16 dtype, and truely support Codellama family.
And also solve many issues related  with codellama gibberish output.

**Comment by esmeetu** [comment]
The changes indeed will affect other model's' performance. I think it's better to change kernel dynamically by 'base' value. If the model base is larger than 10000, we should use this PR strategy, otherwise as usual.

**Comment by WoosukKwon** [comment]
Hi @imoneoi, I've modified and closed the PR by mistake. I'm really sorry. Because the PR is closed, I don't have a permission to revert back your repo. Your original PR can be found [here](https://github.com/vllm-project/vllm/pull/1004/commits/890b3bca917a4cac5ed924bda46d17ea53b6aa07).

I created a new PR #1004, which uses FP32 for initializing RoPE but does not use FP32 in the kernel. I find this more aligned with the HF's implementation. If the precision issue persists after the PR, we will revisit your PR and modify the kernel. Thanks again for your issue and PR.

**Comment by imoneoi** [comment]
It doesn't matter. I re-opened the FP32 RoPE kernel PR in #1061. I'm doing an evaluation of code-llama, you might consider this if precision issues persist.

**Pull request closed without merging**
