### PR TITLE
chore: Update check-wheel-size.py to read VLLM_MAX_SIZE_MB from env

### PR DESCRIPTION
**Pull request by haitwang-cloud**
This commit updates the `check-wheel-size.py` script to read the MAX_SIZE_MB value from the environment variable. The default value is set to 250 MB. This change allows for more flexibility in setting the maximum size of the wheel.

FILL IN THE PR DESCRIPTION HERE

FIX https://github.com/vllm-project/vllm/pull/6704

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by youkaichao — COMMENTED** [review]
can you fix the format, and rename the env var to be `VLLM_MAX_SIZE_MB` to avoid conflict?

**Comment by haitwang-cloud** [comment]
@youkaichao Sure, will do that.

I can provide more details that I am encountering the following error when I tried to build the dockerFile from scratch via `DOCKER_BUILDKIT=1 docker build . --target vllm-openai --tag vllm/vllm-openai`, that why I need to switch to bypass the  `check-wheel-size.py`

### Error logs

```
 => ERROR [build 15/15] RUN python3 check-wheel-size.py dist                                           0.6s
------
 > [build 15/15] RUN python3 check-wheel-size.py dist:
0.506 Wheel dist/vllm-0.5.5+cu124-cp38-abi3-linux_x86_64.whl is too large (286.49945735931396 MB) compare to the allowed size (250 MB).
0.506 vllm/_C.abi3.so: 615.0457992553711 MBs uncompressed.
0.506 vllm/_moe_C.abi3.so: 60.077049255371094 MBs uncompressed.
0.506 vllm/_core_C.abi3.so: 8.069084167480469 MBs uncompressed.
0.506 vllm/engine/llm_engine.py: 0.08058929443359375 MBs uncompressed.
0.506 vllm/config.py: 0.07949447631835938 MBs uncompressed.
0.506 vllm/worker/model_runner.py: 0.07120990753173828 MBs uncompressed.
0.506 vllm/core/scheduler.py: 0.061577796936035156 MBs uncompressed.
0.506 vllm/model_executor/layers/sampler.py: 0.05687141418457031 MBs uncompressed.
0.506 vllm/engine/async_llm_engine.py: 0.051085472106933594 MBs uncompressed.
0.506 vllm/sequence.py: 0.04847431182861328 MBs uncompressed.
```

**Comment by khluu** [comment]
@haitwang-cloud Out of curiosity, what does your environment look like? Are you using a VM from AWS/GCP or any cloud provider? I recently saw an increase in wheel size when building vllm on GCE instances as well.

**Review by youkaichao — APPROVED** [review]
thanks for the contribution!

**Comment by youkaichao** [comment]
failed tests are unrelated (it also appears on main branch)

**Comment by haitwang-cloud** [comment]
> @haitwang-cloud Out of curiosity, what does your environment look like? Are you using a VM from AWS/GCP or any cloud provider? I recently saw an increase in wheel size when building vllm on GCE instances as well.

Yes, I am using a VM from Azure to build the Dockerfile, and I am unsure why the size is increasing. Additionally, I do not need the wheel check because I am building images for our private Kubernetes cluster.

**Pull request merged**
