### PR TITLE
speedup hash_of_block function

### PR DESCRIPTION
**Pull request by flc666star**
The current time complexity of the hash_of_block function is O(n^2). This PR aimed to optimize it to O(n) by including the hash of the predecessor block in the calculation, in addition to the tokens of current block when calculating its hash.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Can you check whether this is still necessary with the introduction of `block_manager_v2`?

**Comment by comaniac** [comment]
> Can you check whether this is still necessary with the introduction of `block_manager_v2`?

Echo on this. As we plan to deprecate block manager v1 in a few week, it would be better to focus on block manager v2. Also cc @sroy745 @rickyyx as you may be interested in this.

**Comment by flc666star** [comment]
> Can you check whether this is still necessary with the introduction of `block_manager_v2`?



> > Can you check whether this is still necessary with the introduction of `block_manager_v2`?
> 
> Echo on this. As we plan to deprecate block manager v1 in a few week, it would be better to focus on block manager v2. Also cc @sroy745 @rickyyx as you may be interested in this.

Ok, thank you for your reminder. So, I should close this pr.

**Comment by rickyyx** [comment]
I think we will probably need to use some similar functions like this for v2 block manager to support prefix caching well (the v2 allocator has a hash function already, but it should probably be refactored too). 

But either way, I think waiting for the deprecation to happen first would be better here and this can be revisited.

**Pull request closed without merging**
