### PR TITLE
[Bugfix] Destroy PP groups properly

### PR DESCRIPTION
**Pull request by andoorve**
Small bug fix to properly delete PP groups when `destroy_model_parallel` is called.

### CODE REVIEW

**Comment by andoorve** [comment]
cc: @youkaichao

**Review by youkaichao — APPROVED** [review]

**Comment by andoorve** [comment]
Hey @youkaichao test failure looks unrelated - can you comment?

**Comment by youkaichao** [comment]
I'm working on https://github.com/vllm-project/vllm/pull/5293 , after that, we don't need separate code for pp and tp anymore. No more copy-pasting. Code will be shared for pp and tp.

**Comment by andoorve** [comment]
Ok, in that case I'll let you decide whether you want to merge this or not. IMO it's relatively safe to merge this in the mean time as it's just a small bugfix, but might not matter either way.

**Pull request closed without merging**
