### PR TITLE
[Bugfix] Fix order of arguments matters in config.yaml

### LINKED ISSUE #8947: [Bug]: vllm serve --config.yaml - Order of arguments matters?
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Rocky Linux release 8.10 (Green Obsidian) (x86_64)
GCC version: (GCC) 11.3.0
Clang version: Could not collect
CMake version: version 3.26.5
Libc version: glibc-2.28

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-553.16.1.el8_10.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100
GPU 1: NVIDIA H100
GPU 2: NVIDIA H100
  MIG 1g.12gb     Device  0:
  MIG 1g.12gb     Device  1:
  MIG 1g.12gb     Device  2:
  MIG 1g.12gb     Device  3:
  MIG 1g.12gb     Device  4:
  MIG 1g.12gb     Device  5:
  MIG 1g.12gb     Device  6:
GPU 3: NVIDIA H100

Nvidia driver version: 550.90.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  1
Core(s) per socket:  48
Socket(s):           2
NUMA node(s):        8
Vendor ID:           GenuineIntel
CPU family:          6
Model:               143
Model name:          Intel(R) Xeon(R) Platinum 8468
Stepping:            8
CPU MHz:             3701.598
CPU max MHz:         3800.0000
CPU min MHz:         800.0000
BogoMIPS:            4200.00
L1d cache:           48K
L1i cache:           32K
L2 cache:            2048K
L3 cache:            107520K
NUMA node0 CPU(s):   0-11
NUMA node1 CPU(s):   12-23
NUMA node2 CPU(s):   24-35
NUMA node3 CPU(s):   36-47
NUMA node4 CPU(s):   48-59
NUMA node5 CPU(s):   60-71
NUMA node6 CPU(s):   72-83
NUMA node7 CPU(s):   84-95
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.6.68
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==26.2.0
[pip3] sentence-transformers==3.0.1
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.45.1
[pip3] triton==3.0.0
[conda] No relevant packages
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.1.dev238+ge2c6e0a82
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    NIC0    NIC1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV6     NV6     NV6     SYS     SYS     0-11    0               N/A
GPU1    NV6      X      NV6     SYS     PIX     SYS     24-35   2               N/A
GPU2    SYS     SYS      X      SYS     SYS     SYS     48-59   4               N/A
GPU3    NV6     SYS     NV6      X      SYS     PIX     72-83   6               N/A
NIC0    SYS     PIX     SYS     SYS      X      SYS
NIC1    SYS     SYS     SYS     PIX     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
```

</details>

### Model Input Dumps

_No response_

### 🐛 Describe the bug

When serving a vllm server with ``vllm serve path/to/model --config path/to/config.yaml`` the position of the argument ``served-model-name`` seems to be cruical to successfully run the server.

P.s. 
Why is `collect_env.py` showing `vLLM Version: 0.6.1.dev238+ge2c6e0a82`
I definitely used vllm=0.6.2 and my pip shows the same.

Config that works flawlessly:
```
served-model-name: "MyModel"
host: "127.0.0.1"
port: 6379
uvicorn-log-level: "info"
```
Here, the server runs and I can call the model using the name "MyModel".

Config that does not work:
```
host: "127.0.0.1"
port: 6379
uvicorn-log-level: "info"
served-model-name: "MyModel"
```

With the latter config, I get the following error:
``vllm serve: error: the following arguments are required: model_tag``

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by Imss27**
FILL IN THE PR DESCRIPTION HERE

FIX #8947 

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Adding or changing kernels</h3>
<p>Each custom kernel needs a schema and one or more implementations to be registered with PyTorch.</p>
<ul>
    <li>Make sure custom ops are registered following PyTorch guidelines: <a href="https://pytorch.org/tutorials/advanced/cpp_custom_ops.html#cpp-custom-ops-tutorial">Custom C++ and CUDA Operators</a> and <a href="https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU">The Custom Operators Manual</a></li>
    <li>Custom operations that return <code>Tensors</code> require meta-functions. Meta-functions should be implemented and registered in python so that dynamic dims can be handled automatically. See above documents for a description of meta-functions.</li>
    <li>Use <a href="https://pytorch.org/docs/stable/library.html#torch.library.opcheck"><code>torch.libary.opcheck()</code></a> to test the function registration and meta-function for any registered ops.  See <code>tests/kernels</code> for examples.</li>
    <li>When changing the C++ signature of an existing op, the schema must be updated to reflect the changes.</li>
    <li>If a new custom type is needed, see the following document: <a href="https://docs.google.com/document/d/18fBMPuOJ0fY5ZQ6YyrHUppw9FA332CpNtgB6SOIgyuA">Custom Class Support in PT2</a>.
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by DarkLight1337** [comment]
I think this change will fail if you provide options before the config. e.g.

```yaml
# config.yaml
tensor-parallel-size: 2
```

```
vllm serve my-model --tensor-parallel-size 4 --config config.yaml
```
This fails to overwrite the value of `--tensor-parallel-size` with the config value.

**Comment by Imss27** [comment]
That's true.....😥

I tried several ways to deal with the order of args, unfortunately there could always be some corner cases to break it and it is not graceful at all. So I think the best solution for now is to note this.😥

**Comment by DarkLight1337** [comment]
Hmm, what about we parse the args three times?

- Omit all the optional CLI args to parse the default arguments
- Read the config (if it exists) to get the config args
- Omit `--config <config_file>` to parse the regular CLI args

Then, we can explicitly overwrite the arguments according to which stage they belong to.

**Comment by Imss27** [comment]
Cool, let me work on this. 
Also, in the future, do you think is there a need to clean the logic of the arguments a bit?😥

**Comment by DarkLight1337** [comment]
> Cool, let me work on this. Also, in the future, do you think is there a need to clean the logic of the arguments a bit?😥

I agree that it's less than ideal now. However we still want the CLI arguments to be available to the user at the top level. What do you suggest?

**Comment by Imss27** [comment]
That's understandable... We need to maintain what users are using already. I don't have good ideas right now tho. Let me just work on this issue first😄

**Comment by Imss27** [comment]
I tried the method you mentioned, but it seems like everytime it needs to pass a model_tag value to parse and previously parsed results are not stored.

Let me know if there is a better way... Happy to iterate on this.

**Comment by DarkLight1337** [comment]
> I tried the method you mentioned, but it seems like everytime it needs to pass a model_tag value to parse and previously parsed results are not stored.
> 
> Let me know if there is a better way... Happy to iterate on this.

Can we keep the `model_tag` (basically all positional arguments) for each parsing run?

**Comment by Imss27** [comment]
> > I tried the method you mentioned, but it seems like everytime it needs to pass a model_tag value to parse and previously parsed results are not stored.
> > Let me know if there is a better way... Happy to iterate on this.
> 
> Can we pass the `model_tag` (basically all positional arguments) to each parsing run?

The strange thing is, if we parse for multiple times, super().parse_args(args, namespace) will only set or overwrite what we pass to it in args. It does not store previously parsed results. Which means other arguments will be reset to defaults and we need to pass model_tag every round. For example
```yaml
# config.yaml
port: 6666
```
```bash
# command
vllm serve mymodel --config config.yaml --max-model-len 10
```
```python
# Change _pull_args_from_config() to return  config and cli args separately
config_args, cli_args = FlexibleArgumentParser._pull_args_from_config(args)
# config_args = ['mymodel', '--port', '6666']
# cli_args = ['mymodel', '--max-model-len', '10']
first_namespace = super().parse_args(config_args, namespace)
print(first_namespace.port) # 6666 
final_namespace = super().parse_args(cli_args, first_namespace)
print(final_namespace.port) # 8000
```
So my current solution is to put model_tag in front of config and cli args and parse all of them at the same time. This still requires assumption that user's command looks like:
```bash
vllm serve <model_tag> <some cli args> --config config.yaml <some cli args>
```

**Comment by DarkLight1337** [comment]
> > > I tried the method you mentioned, but it seems like everytime it needs to pass a model_tag value to parse and previously parsed results are not stored.
> > > Let me know if there is a better way... Happy to iterate on this.
> > 
> > 
> > Can we pass the `model_tag` (basically all positional arguments) to each parsing run?
> 
> The strange thing is, if we parse for multiple times, `super().parse_args(args, namespace)` will only set or overwrite what we pass to it in args. It does not store previously parsed results. Which means other arguments will be reset to defaults and we need to pass model_tag every round. For example
> 
> ```yaml
> # config.yaml
> port: 6666
> ```
> 
> ```shell
> # command
> vllm serve mymodel --config config.yaml --max-model-len 10
> ```
> 
> ```python
> # Change _pull_args_from_config() to return  config and cli args separately
> config_args, cli_args = FlexibleArgumentParser._pull_args_from_config(args)
> # config_args = ['mymodel', '--port', '6666']
> # cli_args = ['mymodel', '--max-model-len', '10']
> first_namespace = super().parse_args(config_args, namespace)
> print(first_namespace.port) # 6666 
> final_namespace = super().parse_args(cli_args, first_namespace)
> print(final_namespace.port) # 8000
> ```
> 
> So my current solution is to put model_tag in front of config and cli args and parse all of them at the same time. This still requires assumption that user's command looks like:
> 
> ```shell
> vllm serve <model_tag> <some cli args> --config config.yaml <some cli args>
> ```

I believe that's the intended function as earlier args take precedence over future ones. How about we create a new namespace object to store the args in each pass to avoid conflicts between them?

**Comment by Imss27** [comment]
> 
> I believe that's the intended function as earlier args take precedence over future ones. How about we create a new namespace object to store the args in each pass to avoid conflicts between them, then merge them manually?

Hmmm... It is likely feasible, but I feel like it is still not graceful and there might be a problem to make it more complicated.
1. We would still require assumptions of command:
```bash
vllm serve <model_tag> <some cli args> --config config.yaml <some cli args>
```
Because we will need `'serve', 'model_tag'` in **each round of parsing** in order not to get errors like
```bash
vllm: error: the following arguments are required: {serve,complete,chat}
vllm serve: error: the following arguments are required: model_tag
```
when calling `super.parse_args()`. So when splitting `config_args` and `cli_args`, we still introduce magic numbers to get `'serve', 'model_tag'`  in front of other args

2. There could be a tricky problem when merging namespaces
```python
# default namespace
port = 8000
# config namespace
port = 7777
# cli namespace: user passes --port 8000 explicitly
port = 8000
```
We would need to overwrite 7777, but how do we know inside a namespace, what args are default values while others are explicitly specified as default values?

 I might be wrong, happy to further iterate on this.

**Comment by DarkLight1337** [comment]
Regarding the first issue, we can assume that all positional arguments are required and extract them from the args list.

The second issue is more tricky... maybe a better way would be to override the default value of each argument with the values found in the config file before parsing them in argparse.

**Comment by Imss27** [comment]
I see.😥
But I just wonder if the first issue is there anyway, why bother parsing for multiple times which introduces the second issue. I feel like the current PR is better or at least a quick solution because we can't fully address the first issue anyway and we will not introduce the second irrelevant issue.

**Comment by DarkLight1337** [comment]
> I see.😥 But I just wonder if the first issue is there anyway, why bother parsing for multiple times which introduces the second issue. I feel like the current PR is better or at least a quick solution because we can't fully address the first issue anyway and we will not introduce the second irrelevant issue.

If we need to do a quick fix, the current solution is still not correct because `vllm chat` and `vllm completion` don't have the additional `model_tag` positional arg.

**Comment by Imss27** [comment]
I see. Then let me look into the `vllm chat/complete` as well. Isn't there unit test on these cases? `pytest tests/test_utils.py` did not fail because of my change locally, it fails because of `FileNotFoundError: [Errno 2] No such file or directory: './data/test_config.yaml'`

**Comment by DarkLight1337** [comment]
> I see. Then let me look into the `vllm chat/complete` as well. Isn't there unit test on these cases? `pytest tests/test_utils.py` did not fail because of my change locally, it fails because of `FileNotFoundError: [Errno 2] No such file or directory: './data/test_config.yaml'`

The current set of unit tests is quite limited. Feel free to add more failing examples!

**Comment by DarkLight1337** [comment]
> `pytest tests/test_utils.py` did not fail because of my change locally, it fails because of `FileNotFoundError: [Errno 2] No such file or directory: './data/test_config.yaml'`

You need to run the test with `tests/` as the working directory.

**Comment by Imss27** [comment]
My solution deals with serve separately, command format for `serve` like below is required. I think before my fix it is already required like this so my solution is somehow acceptable though the whole logic of dealing with args is not elegant enough🤣
```bash
vllm serve <model_tag> <some cli args> --config config.yaml <some cli args>
``` 
For the unit tests, previous tests didn't consider positional args `model_tag`. I added it to previous tests and also added a new `test_no_model_tag` test.

Thanks for the time mentoring me and iterating on this.

**Review by DarkLight1337 — APPROVED** [review]
Sounds good, let's get this merged!

**Pull request merged**
