### PR TITLE
[Hardware] [HPU]add `mark_step` for hpu

### PR DESCRIPTION
**Pull request by jikunshang**
This PR add `mark_step` after each model's  decoder layer, which could benefit performance and not break origin model files.
mark_step [doc](https://docs.habana.ai/en/latest/PyTorch/PyTorch_Model_Porting/Porting_PyTorch_Models_to_Gaudi.html)

cc @kzawora-intel

### CODE REVIEW

**Comment by madamczykhabana** [comment]
Hi @jikunshang . Could the same functionality be implemented using stock PT functionalities like forward hooks (https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.register_forward_hook). I guess we only need to call mark_step() and there's no other complex logic involved.

**Comment by jikunshang** [comment]
> Hi @jikunshang . Could the same functionality be implemented using stock PT functionalities like forward hooks (https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.register_forward_hook)? I guess we only need to call mark_step() and there's no other complex logic involved.

nice catch, addressed your comments. please take a look again, thanks!

**Review by WoosukKwon — APPROVED** [review]

**Comment by WoosukKwon** [comment]
@madamczykhabana Please take a look. I will merge the PR once you approve it.

**Review by madamczyk-intel — APPROVED** [review]
LGTM

**Comment by jikunshang** [comment]
@WoosukKwon Can we merge this now?

**Comment by DarkLight1337** [comment]
Sorry for missing this!

**Pull request merged**
