### PR TITLE
[Model] Pipeline parallel support for Mixtral

### PR DESCRIPTION
**Pull request by binxuan**
Add pipeline support for Mixtral. This is an extension of a previous merged [PR](https://github.com/vllm-project/vllm/pull/4412) 

---

Below are the tests we have performed:

Environment: two AWS P4D instances each with 8 A100.
Model checkpoint: Mixtral-8x22B-Instruct-v0.1 running with TP=8 and PP=2
Case 1:
Input: {"role": "user", "content": "Who won the world series in 2020?"}
Output: {"role":"assistant","content":" The Los Angeles Dodgers won the World Series in 2020. They defeated the Tampa Bay Rays in six games. It was their first championship since 1988. The series was played at Globe Life Field in Arlington, Texas, due to the COVID-19 pandemic.","tool_calls":[]}

Case 2:
Input: {"role": "user", "content": "Who are you?"}
Output: {"role":"assistant","content":" I am an artificial intelligence assistant, designed to help answer questions, provide information, and assist with various tasks. I don't have personal experiences, emotions, or consciousness, but I can process and generate text based on the data I've been trained on.","tool_calls":[]}

### CODE REVIEW

**Comment by youkaichao** [comment]
can you fix the format, and also use the latest change of https://github.com/vllm-project/vllm/pull/6406 ?

**Comment by binxuan** [comment]
> can you fix the format, and also use the latest change of #6406 ?

Yeah sure, will use the format proposed in this PR.

**Comment by binxuan** [comment]
> @binxuan I also need Mixtral PP support. If you don't have bandwidth, I could take over and file another PR with you as a co-author. Plz let me know. Thanks

Sure, feel free to collaborate

**Comment by DarkLight1337** [comment]
Closing as superseded by #6516

**Pull request closed without merging**
