### PR TITLE
fix(server): fix garbled characters stream output

### PR DESCRIPTION
**Pull request by esmeetu**
The reason is: The word which takes up more than one token ids was sent out before it was fully generated. When a new token is generated, and the word length remains unchanged, it indicates that the word at the current position occupies multiple tokens. 
To address this issue, I cached the previous word and modified the output from the current word to the previous word. This allows me to recognize any garbled word and wait for the cached word to be fully generated before outputting it.

This code change works on my WizardCoder model, but haven't test other model with an insufficient cjk vocabulary.

Test case in stream mode: `翻译：mouse`
Generate output: `鼠标`  where `鼠` takes up two tokens.

Hope it's helpful for people using CJK languages..：）

### CODE REVIEW

**Comment by esmeetu** [comment]
@zhuohan123 i think this PR is ready for review. No more changes by me.

**Review by HermitSun — APPROVED** [review]
LGTM. It works well in my cases.

**Comment by leoxing99** [comment]
@esmeetu thanks a lot. Your code correction has solved my problem. However, there is a minor issue: garbled characters have been restored to the correct Chinese characters, but the space character that was originally in front of this Chinese character is now missing. I manually added a space character and it appears to be normal, but it may only be suitable for my particular scenario. Could you please help me check if you have the same problem on your end? Thank you.

**Comment by allenhaozi** [comment]
HI @esmeetu @zhuohan123 
May I ask when this pr is expected to be merged?  We have this problem now. thank you

**Comment by leoxing99** [comment]
@zhuohan123 Yes, I checked #984, it is indeed the issue of missing a space after the dot. This was my problem, and I resolved it by adding a space. However, I hope this issue can be fixed and merged. Thank you.

**Comment by jeurtr** [comment]
> @leoxing99

hello, I also ran into a problem with missing Spaces,Can you tell me how you solved it,thanks

**Comment by HermitSun** [comment]
It seems that this problem has been solved in PR #984 and #1044.

Is there any difference between this PR and PRs mentioned above?

**Comment by esmeetu** [comment]
@HermitSun Yes. I will close this PR.

**Pull request closed without merging**
