### PR TITLE
[[Misc]Upgrade bitsandbytes to the latest version 0.44.0

### PR DESCRIPTION
**Pull request by jeejeelee**
## Motivation

`bitsandbytes` has released its latest version `0.44.0`, which resolves the issue of 4-bit models not supporting CUDA graph(see: [bnb release log](https://github.com/bitsandbytes-foundation/bitsandbytes/releases/tag/v0.44.0)). We conducted tests on our local A800, and the performance gains is as follows:
image

**Although 8-bit BNB models don't currently support CUDA graph,** the gains brought by 4-bit models are still worth upgrading for.

ping @mgoin  @chenqianfzh

### CODE REVIEW

**Comment by chenqianfzh** [comment]
@jeejeelee , the test case of Qlora in examples/lora_with_quantization_inference.py still set enforce_eager=True. Could you also update it?

**Comment by jeejeelee** [comment]
> @jeejeelee , the test case of Qlora in examples/lora_with_quantization_inference.py still set enforce_eager=True. Could you also update it?

Done

**Comment by jeejeelee** [comment]
@mgoin  Although there are CI failures, the tests related to this PR have been passed, could you plz reivew it?

**Review by mgoin — APPROVED** [review]
Thanks for the ping, this checks out with me and works locally with a smoke test

**Pull request merged**
