### PR TITLE
[CI/Build] remove .github from .dockerignore, add dirty repo check

### PR DESCRIPTION
**Pull request by dtrifiro**
Including `.github` in `.dockerignore` results having a dirty repo when copying the source while building the image, causing the version string `setuptools-scm` not to match tags exactly.

Also include `tools/check_repo.sh` to check repo status before building.

See context [here](https://github.com/vllm-project/vllm/pull/4738#issuecomment-2412212700)

### CODE REVIEW

**Comment by simon-mo** [comment]
Can we add a clause in Dockerfile to assert the git repo is in non dirty state (gated by a flag off by default, and turned on by release, similar to wheel size check, although wheel size check is on by default)

**Review by simon-mo — APPROVED** [review]

**Comment by dtrifiro** [comment]
> Can we add a clause in Dockerfile to assert the git repo is in non dirty state (gated by a flag off by default, and turned on by release, similar to wheel size check, although wheel size check is on by default)

Added a clause to check for git repo status (dirty and presence of tags) under the `--build-arg GIT_REPO_CHECK=1`

**Review by simon-mo — APPROVED** [review]
Let's revert the non default Dockerfile changes? I believe given those don't get triggered in release pipeline we don't need to do that.

**Comment by simon-mo** [comment]
[2024-10-17T17:13:54Z] #18 [build 4/8] RUN --mount=type=bind,source=.git,target=.git     if [ "1" != 0 ]; then bash tools/check_repo.sh ; fi
--
  | [2024-10-17T17:13:55Z] #18 0.638 v0.6.3-10-gb007d160
  | [2024-10-17T17:13:55Z] #18 DONE 0.7s

Build pass here https://buildkite.com/vllm/release/builds/1409#01929b76-e6c7-479c-9b7c-f6e25653eec9

**Pull request merged**
