### PR TITLE
Introduce `return_prompt` request option to `api_server` entrypoint

### PR DESCRIPTION
**Pull request by danilopeixoto**
Introduce `return_prompt` request option to `api_server` entrypoint. The default value for `return_prompt` is `False`.

Issue: #1043

### CODE REVIEW

**Comment by viktor-ferenczi** [comment]
Please consider implementing the `echo` option in the OpenAI compatible API server (`endpoints/openai/api_server.py`):

See: https://platform.openai.com/docs/api-reference/completions/create

**Comment by viktor-ferenczi** [comment]
Add simple test cases to cover the flags.

**Comment by danilopeixoto** [comment]
> Add simple test cases to cover the flags.

I will add it.

**Comment by danilopeixoto** [comment]
> Please consider implementing the `echo` option in the OpenAI compatible API server (`endpoints/openai/api_server.py`):
> 
> See: https://platform.openai.com/docs/api-reference/completions/create

I'm considering it. Should I add it in the same PR or new one?

**Comment by viktor-ferenczi** [comment]
Same PR. They belong together, same feature.

**Comment by zhuohan123** [comment]
Thank you for your contribution! Our goal of `api_server.py` is to provide a minimal example of an API server. Adding this parameter will add unnecessary complexity. For your use case, you can make a copy of `api_server.py` and modify the server for your needs accordingly. Feel free to submit a new PR if you believe this is needed.

**Comment by danilopeixoto** [comment]
@zhuohan123 The addition does not look complex at all. We were using this endpoint to run benchmark against another server. The other server has an option to return only the generated text. Thanks anyway!

**Comment by PeterXiaTian** [comment]
这个问题解决了吗？怎么刚测试还有了？

**Comment by PeterXiaTian** [comment]
can use   res["text"][0].replace(promopt,"")  to solve this problem??

**Comment by Kaotic3** [comment]
"can use res["text"][0].replace(promopt,"") to solve this problem??"

You can in simple examples, but for a RAG workflow this is not going to work as you can be sending complex data that will be formatted accordingly when sent and therefore won't be the same when it is returned.

The only way to do that would be to change every document in your RAG workflow to mirror the prompt.

I see this as closed, but I don't see "return_prompt" in the uses for the vllm api server?

```
usage: api_server.py [-h] [--host HOST] [--port PORT] [--allow-credentials] [--allowed-origins ALLOWED_ORIGINS] [--allowed-methods ALLOWED_METHODS]
                     [--allowed-headers ALLOWED_HEADERS] [--api-key API_KEY] [--served-model-name SERVED_MODEL_NAME]
                     [--lora-modules LORA_MODULES [LORA_MODULES ...]] [--chat-template CHAT_TEMPLATE] [--response-role RESPONSE_ROLE] [--ssl-keyfile SSL_KEYFILE]
                     [--ssl-certfile SSL_CERTFILE] [--root-path ROOT_PATH] [--middleware MIDDLEWARE] [--model MODEL] [--tokenizer TOKENIZER] [--revision REVISION]
                     [--code-revision CODE_REVISION] [--tokenizer-revision TOKENIZER_REVISION] [--tokenizer-mode {auto,slow}] [--trust-remote-code]
                     [--download-dir DOWNLOAD_DIR] [--load-format {auto,pt,safetensors,npcache,dummy}] [--dtype {auto,half,float16,bfloat16,float,float32}]
                     [--kv-cache-dtype {auto,fp8_e5m2}] [--max-model-len MAX_MODEL_LEN] [--worker-use-ray] [--pipeline-parallel-size PIPELINE_PARALLEL_SIZE]
                     [--tensor-parallel-size TENSOR_PARALLEL_SIZE] [--max-parallel-loading-workers MAX_PARALLEL_LOADING_WORKERS] [--block-size {8,16,32}]
                     [--seed SEED] [--swap-space SWAP_SPACE] [--gpu-memory-utilization GPU_MEMORY_UTILIZATION] [--max-num-batched-tokens MAX_NUM_BATCHED_TOKENS]
                     [--max-num-seqs MAX_NUM_SEQS] [--max-paddings MAX_PADDINGS] [--disable-log-stats] [--quantization {awq,gptq,squeezellm,None}]
                     [--enforce-eager] [--max-context-len-to-capture MAX_CONTEXT_LEN_TO_CAPTURE] [--disable-custom-all-reduce] [--enable-lora]
                     [--max-loras MAX_LORAS] [--max-lora-rank MAX_LORA_RANK] [--lora-extra-vocab-size LORA_EXTRA_VOCAB_SIZE]
                     [--lora-dtype {auto,float16,bfloat16,float32}] [--max-cpu-loras MAX_CPU_LORAS] [--device {cuda}] [--engine-use-ray] [--disable-log-requests]
                     [--max-log-len MAX_LOG_LEN]
```

**Comment by ywang96** [comment]
Hello @Kaotic3! This issue is closed because the `api_server.py` will no longer be maintained and the OpenAI compatible server is recommended instead. See the comments
https://github.com/vllm-project/vllm/blob/429284dc374bab79d4dfbb25053583901e6e5051/vllm/entrypoints/api_server.py#L2-L6

**Comment by Kaotic3** [comment]
Does this mean that we don't get the echo command then?

It isn't really even a problem with vLLM it is a problem with outlines served via vLLM - but I figured the flags are the same on both, so if it existed here, then I could use it in outlines.

**Comment by ywang96** [comment]
The `echo` option is only available in the openai compatible server afaik.

**Comment by Kaotic3** [comment]
It isn't as that list is from the openai compatible server.

--echo isn't in the list.

**Comment by ywang96** [comment]
You don't pass it as an argument when launching the server. It should be specified in your payload to the `v1/completions` endpoint.
https://github.com/vllm-project/vllm/blob/429284dc374bab79d4dfbb25053583901e6e5051/vllm/entrypoints/openai/serving_completion.py#L231-L242

**Comment by Kaotic3** [comment]
I see, it is false by default so not really utilised it before.

I will try it with outlines, thanks man appreciate the assistance!

**Pull request closed without merging**
