### PR TITLE
[BugFix] Use IP4 localhost form for zmq bind

### PR DESCRIPTION
**Pull request by njhill**
See https://stackoverflow.com/a/8958414

Should address issues https://github.com/vllm-project/vllm/issues/7138, https://github.com/vllm-project/vllm/issues/7118.

### CODE REVIEW

**Review by mgoin — APPROVED** [review]
Nice job finding the reference for this, makes sense!

**Review by youkaichao — APPROVED** [review]
the stackoverflow reference is great!

**Comment by youkaichao** [comment]
It looks strange to me, why @robertgshaw2-neuralmagic does not met this when he test the functionality. Is it ZMQ version specific?

**Comment by njhill** [comment]
> It looks strange to me, why @robertgshaw2-neuralmagic does not met this when he test the functionality. Is it ZMQ version specific?

I had the same thought

**Comment by robertgshaw2-neuralmagic** [comment]
I am also confused why this issue does not arise in automation or locally

**Pull request merged**
