### PR TITLE
[Frontend] Fix tcp port reservation for api server

### LINKED ISSUE #9737: [Bug]: "Address already in use" for 1 minute after crash (since 0.6.2)
### 🐛 Describe the bug

Since version 0.6.2 (happens also in 0.6.3.post1), after the server dies (due to an exception/crash or hitting ctrl-c), for about a minute, it fails to start again with:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/code/debug/.venv/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 585, in <module>
    uvloop.run(run_server(args))
  File "/home/user/code/debug/.venv/lib/python3.10/site-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/user/code/debug/.venv/lib/python3.10/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/home/user/code/debug/.venv/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 544, in run_server
    sock.bind(("", args.port))
OSError: [Errno 98] Address already in use
```
This prolongs recovery from crashes. In example upon crash Kubernetes immediately restarts the container - previously it would immediately start loading the model again, but now it will do several crash/restart loops until the port is freed.

Verified it happens also with `--disable-frontend-multiprocessing`.

To reproduce it, start vllm with default args, in example:
```
python -m vllm.entrypoints.openai.api_server --model TinyLlama/TinyLlama-1.1B-Chat-v1.0
```
and then send at least one chat or completion request to it (without this it won't reproduce).
then hit Ctrl-C to kill the server.
starting vllm again should throw the "Address already in use" error.
This doesn't happen with vllm <= 0.6.1.

I tried to see why the port is busy, and interestingly the vllm process is dead during this ~1 minute and no other process listens on it. However I noticed that there is a socket open *from* the 8000 port. Can see it via:
```
netstat | grep  ':8000'
```
which would show something like:
```
tcp        0      0 localhost:8000          localhost:40452         TIME_WAIT   -
tcp        0      0 localhost:8000          localhost:56324         TIME_WAIT   -
tcp        0      0 localhost:8000          localhost:40466         TIME_WAIT   -
```
After a minute these entries will disappear and then also vllm will manage to start.
I couldn't attribute it to a PID, nor with various `nestat` or `lsof` flags. Maybe it remains open in the kernel due to unclean process exit?

### PR DESCRIPTION
**Pull request by russellb**
PR #8537 changed this code to bind the TCP port prior to the engine
starting to ensure that port isn't used unexpectedly by something
launched during the engine startup. (ray is mentioned in the
discussino history and the comment in the code)

This change introduced some new unexpected behavior as discussed in
issue #9737. Restarting vllm within a short time after handling an API
request where the client hasn't closed its end of the connection would
cause vllm to fail to start with a "port in use" error.

The primary issue was the use of the `fd` option to the uvicorn
config. This option does not actually do what we want. The relevant
code can be found here:

https://github.com/encode/uvicorn/blob/fe3910083e3990695bc19c2ef671dd447262ae18/uvicorn/config.py#L496-L501

The important line to note is this one:

    sock = socket.fromfd(self.fd, socket.AF_UNIX, socket.SOCK_STREAM)

Note that `uvicorn` is expecting the fd to be for an `AF_UNIX` socket.
We are passing in a TCP (`AF_INET`) socket. We seem to be lucky that
this mostly works anyway, though it's surprising it works at all!

Instead of using this `fd` option, set the `SO_REUSEADDR` option on
the socket, which will allow `uvicorn` to bind to the same address and
port.

When reserving the port, we previously always specified `""` for the
host. I fixed that too so that we bind to the host that we pass to
`uvicorn` for it to bind to, as well.

Finally, explicitly `close()` the socket as a final step of cleanup.

Closes #9737

Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Comment by njhill** [comment]
Thanks @russellb. Just fyi there was another recent change to pass the host in https://github.com/vllm-project/vllm/pull/9798 which was reverted due to causing issues with multi-step, I'm not sure what those were or whether that might still apply here.

**Comment by russellb** [comment]
> Thanks @russellb. Just fyi there was another recent change to pass the host in #9798 which was reverted due to causing issues with multi-step, I'm not sure what those were or whether that might still apply here.

Thanks for the pointer! The revert was #9852.

Hopefully that test can run on this PR so we can check?  @khluu

**Comment by khluu** [comment]
> > Thanks @russellb. Just fyi there was another recent change to pass the host in #9798 which was reverted due to causing issues with multi-step, I'm not sure what those were or whether that might still apply here.
> 
> Thanks for the pointer! The revert was #9852.
> 
> Hopefully that test can run on this PR so we can check? @khluu

I marked `ready` so CI can run (also unblocked multistep test)

**Comment by russellb** [comment]
Everything seems to be passing 🎉

**Review by njhill — APPROVED** [review]
Thanks @russellb!

**Pull request merged**
