### PR TITLE
:bug: fix torch memory profiling

### PR DESCRIPTION
**Pull request by joerunde**
This PR updates the logic to determine how much memory is allocated on the gpu not by torch. We had previously made an assumption that models would release all memory held for activation weights during a forward pass, but this is currently not the case with bitsandbytes quantized models. It's unclear to us whether that's intended for those models, however this fix is a much more straightforward and understandable calculation.

We also removed the gpu memory utilization limit in the quantization tests because
1. We have much more accurate memory profiling now, so hopefully we shouldn't need it to be set lower, and
2. We wanted to change the file so that the quantization tests would run for this PR before merging

Here's a profile of two forward() passes through `meta-llama/Llama-Guard-3-8B-INT8` with bitsandbytes quantization. Notice how tensors are allecated in one forward pass and later freed in the next: 
image

Fixes a bug introduced by #9352

cc @tjohnson31415 

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Adding or changing kernels</h3>
<p>Each custom kernel needs a schema and one or more implementations to be registered with PyTorch.</p>
<ul>
    <li>Make sure custom ops are registered following PyTorch guidelines: <a href="https://pytorch.org/tutorials/advanced/cpp_custom_ops.html#cpp-custom-ops-tutorial">Custom C++ and CUDA Operators</a> and <a href="https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU">The Custom Operators Manual</a></li>
    <li>Custom operations that return <code>Tensors</code> require meta-functions. Meta-functions should be implemented and registered in python so that dynamic dims can be handled automatically. See above documents for a description of meta-functions.</li>
    <li>Use <a href="https://pytorch.org/docs/stable/library.html#torch.library.opcheck"><code>torch.libary.opcheck()</code></a> to test the function registration and meta-function for any registered ops.  See <code>tests/kernels</code> for examples.</li>
    <li>When changing the C++ signature of an existing op, the schema must be updated to reflect the changes.</li>
    <li>If a new custom type is needed, see the following document: <a href="https://docs.google.com/document/d/18fBMPuOJ0fY5ZQ6YyrHUppw9FA332CpNtgB6SOIgyuA">Custom Class Support in PT2</a>.
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by chenqianfzh** [comment]
> @chenqianfzh Is this memory usage pattern expected with bitsandbytes quantization?

In bnb-8bit quantization, some data needed be preserved between forward passes. But it is not the case for other bnb quantization variations. 

So the above memory usage pattern is expected in the test of 'meta-llama/Llama-Guard-3-8B-INT8' and 
   "yec019/fbopt-350m-8bit" in the test cases in tests/quantization/test_bitsandbytes.py.
   
   Hope it helps.

**Comment by joerunde** [comment]
> > @chenqianfzh Is this memory usage pattern expected with bitsandbytes quantization?
> 
> In bnb-8bit quantization, some data needed be preserved between forward passes. But it is not the case for other bnb quantization variations.
> 
> So the above memory usage pattern is expected in the test of 'meta-llama/Llama-Guard-3-8B-INT8' and "yec019/fbopt-350m-8bit" in the test cases in tests/quantization/test_bitsandbytes.py.
> 
> Hope it helps.

That does help, thanks!

**Comment by tlrmchlsmth** [comment]
>In bnb-8bit quantization, some data needed be preserved between forward passes. But it is not the case for other bnb quantization variations.

@chenqianfzh Could you explain what data needs to be preserved between forward passes? This is a little surprising to me

**Review by tlrmchlsmth — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by chenqianfzh** [comment]
> > In bnb-8bit quantization, some data needed be preserved between forward passes. But it is not the case for other bnb quantization variations.
> 
> @chenqianfzh Could you explain what data needs to be preserved between forward passes? This is a little surprising to me

sorry for the late response. I was sick last week. 

In bnb 8bit, the tensor of matmul_states of last generation might be used in the current generation and thus use some memory. You can  check func _apply_8bit_weight() in file bitsandbytes.py for more details. HTH.

**Pull request merged**
