### PR TITLE
Add Triton integration example

### PR DESCRIPTION
**Pull request by zhyncs**
Hi vLLM genius @WoosukKwon @zhuohan123 

As mentioned in [NVIDIA Triton support](https://github.com/vllm-project/vllm/issues/541), I have written a simple example for integrating with Triton, hoping to be helpful for future users. Cheers.

### CODE REVIEW

**Comment by zhaotyer** [comment]
In this way, requests will be dynamically batched in vllm, right?

**Comment by zhyncs** [comment]
Hi vLLM genius @WoosukKwon @zhuohan123 

May you review this pull request?

As mentioned in https://github.com/vllm-project/vllm/issues/541#issuecomment-1708854653, I have updated and tested the `model.py` according to [tutorial](https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/README.md) by @tanmayv25

**Comment by zhuohan123** [comment]
@zhyncs Thanks for your contribution! We'll take a look and provide feedbacks.

**Comment by zhyncs** [comment]
ping @WoosukKwon @zhuohan123

**Comment by v1nc3nt27** [comment]
@zhyncs thanks for the example! Do you know if it possible to launch quantized models like this? I can see in https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/README.md, there is a file [vllm_engine_args.json](https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/model_repository/vllm/vllm_engine_args.json), which you did not include in your example. Perhaps this should be added, although I haven't got it running with a quantized model yet.

**Pull request closed without merging**
