### PR TITLE
[FIX] Make `flash_attn` optional

### PR DESCRIPTION
**Pull request by WoosukKwon**
The FlashAttention backend introduced in #3005 causes build errors in some environments and increase the package size significantly (44 MB -> 160 MB) as the vLLM package now includes the `flash-attn` (116 MB) package. This PR addresses this by removing `flash_attn` from vLLM's dependency and enables falling back to xFormers when `flash_attn` is not found.

### CODE REVIEW

**Comment by chenxu2048** [comment]
Hi @WoosukKwon, why you revert your refraction in #3005?

**Review by zhuohan123 — COMMENTED** [review]
Probably we can just use a flag to turn flash_attn off instead of deleting everything? What do you think?

**Comment by AlpinDale** [comment]
I think it would be safe to simply disable the flash attention backend if `flash_attn` is not found - until a more elegant solution is found, at least. At the moment, users can be prompted to manually install flash attention if needed.

**Comment by WoosukKwon** [comment]
@zhuohan123 @AlpinDale Thanks for the suggestion. Just updated the PR accordingly. Please take another look.

**Comment by mgoin** [comment]
Thank you @WoosukKwon, I tested this on a few environments and this restored the original behavior for me.

**Review by zhuohan123 — APPROVED** [review]
LGTM! Do you wanna keep the downloading logic as well?

**Comment by WoosukKwon** [comment]
@zhuohan123 Let's remove it for this fix and bring it back once we find a more stable way to do it.

**Pull request merged**
