### PR TITLE
[CI/Build] [3/3] Reorganize entrypoints tests

### PR DESCRIPTION
**Pull request by DarkLight1337**
To better preserve Git history, I'm splitting this process into multiple PRs.

~Step 1: Split out Chat API tests to another file~ (#5526)
~Step 2: Split out Completion API tests to another file~ (#5904)
**Step 3: Move OpenAI tests to `openai` directory, and LLM tests to `llm` directory.**

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
Before you merge, can you post here the end to end runtime of the entrypoints test in CI so we know whether splitting is needed?

**Review by mawong-amd — CHANGES_REQUESTED** [review]
This line https://github.com/vllm-project/vllm/blob/653849717356e45efc35905b09b8ac7e0091da97/tests/entrypoints/openai/test_chat.py#L80 will introduce issues with the AMD Entrypoints test, as we have discussed in https://github.com/vllm-project/vllm/pull/5422#issuecomment-2189084755.

It was incorrectly introduced in https://github.com/vllm-project/vllm/pull/5526, where AMD CI would have caught the issue had the tests not been cancelled by @DarkLight1337 

Please remove `runtime_env={"working_dir": VLLM_PATH}` from `ray.init`: it doesn't need it. Thanks!

**Comment by DarkLight1337** [comment]
> This line
> 
> https://github.com/vllm-project/vllm/blob/653849717356e45efc35905b09b8ac7e0091da97/tests/entrypoints/openai/test_chat.py#L80
> 
> will introduce issues with the AMD Entrypoints test, as we have discussed in [#5422 (comment)](https://github.com/vllm-project/vllm/pull/5422#issuecomment-2189084755).
> It was incorrectly introduced in #5526, where AMD CI would have caught the issue had the tests not been cancelled by @DarkLight1337
> 
> Please remove `runtime_env={"working_dir": VLLM_PATH}` from `ray.init`: it doesn't need it. Thanks!

Fixed! Sorry for the false negative - I was trying to speed up the queue by cancelling AMD tests when they appear unrelated to the PR.

**Comment by DarkLight1337** [comment]
CUDA entrypoints test are taking 20 minutes (`llm` and `openai` combined) so I don't think we need to split them.

**Comment by DarkLight1337** [comment]
Going to wait until #5949 has been merged first, otherwise this PR would cause merge conflict and further delay the fix.

**Pull request merged**
