### PR TITLE
[Bugfix]Disable the post_norm layer of the vision encoder for LLaVA models

### PR DESCRIPTION
**Pull request by litianjian**
Disable the post_norm layer of vision encoder for `LLaVA-Onevision` models based on #9217.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Does this issue occur for the other LLaVA models as well?

**Comment by litianjian** [comment]
> Does this issue occur for the other LLaVA models as well?

Other LLaVA models can still use `num_hidden_layers_override` to determine whether enable post_layer_norm layer. However, I believe that consistently using this parameter for judgment would be better.

**Comment by DarkLight1337** [comment]
Let's update the other models then, since from a quick look at the HF implementation, they don't use `post_layernorm`.

**Comment by litianjian** [comment]
> Let's update the other models then, since from a quick look at the HF implementation, they don't use `post_layernorm`.

OK, all LLaVA models don't use `post_layernorm`.

**Review by DarkLight1337 — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
