### PR TITLE
[core][distributed] improve shared memory broadcast

### PR DESCRIPTION
**Pull request by youkaichao**
add more comments for explanation
fix race condition
remove reader side initialization check

### CODE REVIEW

**Review by Yard1 — APPROVED** [review]
Can we add a test for the race condition?

**Comment by youkaichao** [comment]
> Can we add a test for the race condition?

quite difficult to control the timing. do you have any ideas?

**Comment by Yard1** [comment]
Not sure, let me think a little about it

**Comment by youkaichao** [comment]
I actually think there will be no race condition after I fix it.

**Comment by Yard1** [comment]
Obviously, but it would be good to prevent regressions! But yeah this would be tricky to test. We'd need some sort of a stress test ideally

**Comment by youkaichao** [comment]
welcome to add it if you have any ideas 👍

**Review by rkooo567 — APPROVED** [review]
@youkaichao the fix makes sense. How did you find this issue in the first place? That can give us hint regarding how to add tests

**Comment by youkaichao** [comment]
I draw the state transition diagram and find it in my mind :)

**Pull request merged**
