### PR TITLE
[Bugfix][Frontend] Enable tools

### PR DESCRIPTION
**Pull request by tomeras91**
This PR enables sending [Tool messages](https://platform.openai.com/docs/api-reference/chat/create#:~:text=Show%20properties-,Tool%20message,-object), assistant messages with [tool calls](https://platform.openai.com/docs/api-reference/chat/create#:~:text=the%20same%20role.-,tool_calls,-array), and other message types, as part of the messages list in `ChatCompletionRequest`.
Looking at [protocol.py](https://github.com/AI21Labs/ai21-vllm/blob/2e5210daa62a6e8d88d8aa402741b594c5fa589a/vllm/entrypoints/openai/protocol.py#L96), this was actually already available. The problem was that when the messages were parsed to send them to `apply_chat_template`, all fields apart from `role` and `content` were ignored. For example, an assistant message with tool calls has an extra `tool_calls` field which is very important and was ignored.

The fix has 2 parts:

* Re-implementing OpenAI's `ChatCompletionAssistantMessageParam` because of a bug in pydantic: https://github.com/pydantic/pydantic/issues/9467 - this was actually a problem even with accepting `tool_calls` and has nothing to do with parsing it to send to `apply_chat_template`.
* In the simple case where `content` is not a list (which is allowed only for User messages that don't have tool_calls anyway), use the original message instead of parsing it into `TextConversationMessage` which has only role and content.

The message parsing logic was missing tests, which are also added in this PR:
* `tests/entrypoints/test_chat_utils.py` with tests for `parse_chat_messages` - all tests that check messages that have more than `role` and `content` fail on main branch.
* Added `test_tool_calls_message_is_parsed_correctly_in_chat_completion_request` to `tests/entrypoints/openai/test_serving_chat.py` that makes sure the [pydantic bug](https://github.com/pydantic/pydantic/issues/9467) mentioned above doesn't affect `tool_calls` sent as part of assistant messages in `ChatCompletionRequest` - this test also fails on main branch

### CODE REVIEW

**Comment by tomeras91** [comment]
I isolated the failed `entrypoints-test` and run them manually, and they pass. I'm pretty sure they failed in the CI because of different reasons.. I saw a log about connection timeouts with HF hub

**Comment by K-Mistele** [comment]
fwiw this should be contained in #5649, along with a bunch of other functionality

**Comment by tomeras91** [comment]
Closed as this is irrelevant after https://github.com/vllm-project/vllm/pull/5649 was merged :)

**Pull request closed without merging**
