### PR TITLE
[misc] error early for old-style class

### PR DESCRIPTION
**Pull request by youkaichao**
as we change to the `vllm_config`, out-of-tree registered models need to be updated.

we give a clear error message here for users to update.

### CODE REVIEW

**Review by russellb — APPROVED** [review]
I haven't tested this, but the change lgtm.

Another way that might be nice for the future would be to create versioned base classes to inherit from, like `ModuleV1`, `ModuleV2`, ... where a new one is created to reflect a new API that is not backwards compatible.

In this code, instead of having to inspect the function signature, you could explicitly check for which version it inherits from.

Anyway, just an idea. This is more interesting in a post-v1 world where maintaining API compatibility is considered more important.

**Comment by youkaichao** [comment]
@russellb thanks for the suggestion! I updated the doc to include some shim code example.

It's not just V1, V0 also has this change.

**Comment by russellb** [comment]
> @russellb thanks for the suggestion! I updated the doc to include some shim code example.
> 
> It's not just V1, V0 also has this change.

Right, I know both have the change. I just mean that once V1 is more locked down, it may be worth being a bit more strict about API changes that impact external consumers, and we could do some things in the code to help with that.

**Comment by youkaichao** [comment]
> it may be worth being a bit more strict about API changes that impact external consumers

we don't guarantee any undocumented details for out-of-tree registered code. They need to catch up. For the new code, it is documented, and we will make that signature backward compatible in the future.

**Comment by russellb** [comment]
> > it may be worth being a bit more strict about API changes that impact external consumers
> 
> we don't guarantee any undocumented details for out-of-tree registered code. They need to catch up. For the new code, it is documented, and we will make that signature backward compatible in the future.

I think we're in agreement!

**Pull request merged**
