### PR TITLE
[DNM][Discussion] Example to decrease live tensors for activation memory.

### PR DESCRIPTION
**Pull request by andoorve**
This is a follow up to https://github.com/vllm-project/vllm/pull/10339 and is intended for discussion. As it is, this PR is not suitable for being merged.

Basically, we are using more memory than required when executing the forward pass of models. This can lead to a significant difference in supportable concurrency in certain cases. This has to do with the way Python/PyTorch works, and partially due to the way vLLM model files are written.

There are two things to consider with PyTorch eager mode.

1. Within a certain scope, differently named tensors will live *for the entire scoped section* unless they are explicitly deleted or reassigned. This is fundamental to Python. This was demonstrated in https://github.com/vllm-project/vllm/pull/10339.
2. When tensors are passed into a function these will live as a separate buffers *even if it would be safe to deallocate them* based on the program semantics. This is by design and is again fundamental to Python refcounting and garbage collection. We don't want to reuse buffers passed into a function even if we could reuse the buffer based on workload semantics because in eager mode we don't know if they might be used in a different part of the code independently. In this case, one way we can solve this is by explicitly inlining if it works for us. Example:

2 buffers
```
def foo(x):
    x = 2*x
    x = act(x)
    return x

def g(x):
    x = torch.ones(2, 3)
    x = foo(x)
    return x
```

vs. 1 buffer for the below

```
def g(x):
    x = torch.ones(2, 3)
    x = 2*x
    x = act(x)
    return x
```

This is the main idea of this PR. You can see the difference in activation tensor liveness here as a result of this PR + https://github.com/vllm-project/vllm/pull/10339 below in the memory profile.

Before:
image

After:
image

This has a big difference on the final concurrency. For example for Llama 405B + Llama 8B Draft + TP8 + 32k context length:

Original: ~1100 blocks
With https://github.com/vllm-project/vllm/pull/10339: ~1450 blocks
With https://github.com/vllm-project/vllm/pull/10339 and this PR: ~2000 blocks

This PR is raised for discussion. Do we just want to rely on `torch.compile` integration (which I think will take care of this for full model compilation) and not care about eager mode for this? What is the cleaner/better way of doing this without inlining in Python? If there is no cleaner way, is it still worth merging this?

Can provide memory profiles on request.

### CODE REVIEW

**Comment by andoorve** [comment]
Would you be able to provide some opinions and advice on this topic? @youkaichao @DarkLight1337 @mgoin @comaniac

**Comment by youkaichao** [comment]
Thanks for investigating it! That's very inspiring.

I think `torch.compile` can do something like this automatically:

```python
import torch

def foo(x):
    x = 2*x
    x = torch.nn.functional.relu(x)
    return x

x = torch.ones(2, 3)

def backend(gm, inputs):
    gm.print_readable()
    return gm

@torch.compile(backend=backend)
def g(x):
    y = x + 1
    y = foo(y)
    return y

g(x)
```

The output:

```python
class GraphModule(torch.nn.Module):
    def forward(self, L_x_: "f32[2, 3]"):
        l_x_ = L_x_
        
        y: "f32[2, 3]" = l_x_ + 1;  l_x_ = None
        
        x: "f32[2, 3]" = 2 * y;  y = None
        
        x_1: "f32[2, 3]" = torch.nn.functional.relu(x);  x = None
        return (x_1,)
```

However, in https://github.com/vllm-project/vllm/pull/10460 , I find `torch.compile` has similar memory footprint as eager mode vllm, which makes me think if `torch.compile` has fused the residual addition and layernorm.

**Comment by comaniac** [comment]
It would be ideal to let torch.compile deal with this for sure (so that we only need to make sure torch.compile works as expected). Meanwhile, we also need to make sure to use torch.compile for the whole forward graph (or piece wise) for all models. Eager mode can stay with the current performance to maintain code readability.

**Comment by andoorve** [comment]
Thanks for your comments.

@youkaichao This is surprising that you see a similar number of blocks with `torch.compile`! I think if you use a larger model with less kv cache blocks the benefit of torch.compile may become more apparent. That being said, is the consensus that we will use `torch.compile` as a first class citizen, and therefore we don't care as much about eager mode memory?

@comaniac This makes sense - do you know any tricks where we can achieve the lower peak memory from this PR while maintaining the readability?

If we cannot maintain readability with any tricks for eager mode AND `torch.compile` is the primary default going forward, I also agree we should just leave the current implementation as is and not make any changes.

**Comment by andoorve** [comment]
@youkaichao Is already following up with PyTorch team on the compile side - hence closing this investigation.

**Pull request closed without merging**
