### PR TITLE
[ci][distributed] add pipeline parallel correctness test

### PR DESCRIPTION
**Pull request by youkaichao**
the correctness is tested against pure tensor parallel.

### CODE REVIEW

**Comment by youkaichao** [comment]
will merge after @andoorve 's review .

**Review by andoorve — APPROVED** [review]
LGTM - using transitive property for TP makes sense. cc: @njhill maybe this helps your test issues?

**Comment by andoorve** [comment]
Looks like multinode test failed though:

Possibly this?

`[2024-07-13T07:43:35Z] ValueError: Ray does not allocate any GPUs on the driver node. Consider adjusting the Ray placement group or running the driver on a GPU node.`

**Comment by youkaichao** [comment]
> `[2024-07-13T07:43:35Z] ValueError: Ray does not allocate any GPUs on the driver node. Consider adjusting the Ray placement group or running the driver on a GPU node.`

this is because multi-node ray causes error on the TP size 🤣  it schedules the actor in another node rather than the head node.

**Pull request merged**
