### PR TITLE
Fix num_gpus when TP > 1

### LINKED ISSUE #1851: Fix num_gpus when TP > 1
@WoosukKwon I see. For now we should do:
```
num_gpus=self.cache_config.gpu_memory_utilization if self.parallel_config.tensor_parallel_size < 2 else 1
```

_Originally posted by @Yard1 in https://github.com/vllm-project/vllm/issues/1821#issuecomment-1833028091_

### PR DESCRIPTION
**Pull request by WoosukKwon**
Fixes #1851

### CODE REVIEW

**Comment by WoosukKwon** [comment]
@Yard1 Should we also fix this: https://github.com/vllm-project/vllm/blob/f07c1ceaa5162e2ad3b127e06b162508dc57e4db/vllm/engine/async_llm_engine.py#L304?

**Comment by WoosukKwon** [comment]
I see. It seems tricky then...

**Comment by Yard1** [comment]
Perhaps make it a method of `ParallelConfig` to get the number of GPUs for Ray?

**Comment by WoosukKwon** [comment]
> Perhaps make it a method of ParallelConfig to get the number of GPUs for Ray?

@Yard1 Can we somehow keep `ParallelConfig` independent of Ray?

**Comment by Yard1** [comment]
Have an independent function taking in the parallel config, then?

**Comment by FlorianJoncour** [comment]
In my opinion its a regression compared to #1821

After further investigations it seems that Ray make CUDA fail with tensor parallelism if the total amount of GPU reservation is less than 1 (wich indeed no make sense).

Should we not raise and exception in that case ?

```
# Ensures that we reserves at least 1 GPU with tensor parallelism
if self.parallel_config.tensor_parallel_size > 1:
    gpu_res = (self.cache_config.gpu_memory_utilization * self.parallel_config.tensor_parallel_size)
    if gpu_res < 1.0:
        raise ValueError(f"`tensor_parallel_size` is set to {self.parallel_config.tensor_parallel_size} but the current placement group bundle reserves less than 1 GPU ({gpu_res}). "
                            f"Try increasing `gpu_memory_utilization`. "
                            f"If you are using Ray Serve you may also need to set a correct `placement_group_bundles` to reserves at least 1 GPU unit.")
```

So it helps the user to set correct configuration and also let it use fractions of GPU with tensor parallelism.
I've tested with and without Ray Serve and we just have to set correct gpu_memory_utilization
And also placement_group_bundles with Ray serve.

**Comment by Yard1** [comment]
So the problem here is that NCCL requires separate devices to operate, but Ray has no insight into that and will try to pack the placement group into as few GPUs as possible. If the number of GPUs Ray chooses is smaller than the tensor parallelism factor, NCCL will not work. There is no easy way to prevent that aside from just not using fractional GPUs if tensor parallelism factor is greater than 1.

**Pull request merged**
