### PR TITLE
[Bugfix] Fix RMSNorm forward in InternViT attention qk_layernorm

### LINKED ISSUE #6977: [Bug]: Wrong image hallucination for InternVL2 model
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

- As reported in #6514, `InternVL2-26B`, `InternVL2-40B` and `InternVL2-76B` all have wrong image hallucination issue. We use this issue for tracking.
- These problematic models all use [InternViT-6B-448px-V1-5](https://huggingface.co/OpenGVLab/InternViT-6B-448px-V1-5) as ViT, while models use [InternViT-300M-448px](https://huggingface.co/OpenGVLab/InternViT-300M-448px) don't have this issue.

### Reproduce Code
```python
import os
from openai import OpenAI

client = OpenAI(
    api_key="EMPTY",
    base_url="http://localhost:8000/v1"
)

stream = True

chat_completion = client.chat.completions.create(
    model="OpenGVLab/InternVL2-40B",
    stream=stream,
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "What's in this image?"
                },
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Llama%2C_peru%2C_machu_picchu.jpg",
                    },
                },
            ],
        }
    ], 
    extra_body={
    "skip_special_tokens": False
}
)
```

### PR DESCRIPTION
**Pull request by Isotr0py**
FILL IN THE PR DESCRIPTION HERE

FIX #6977 (*link existing issues this PR will resolve*)
- The use of fused `RMSNorm` in `InternAttention` causes serious numeric divergence, which may result the image hallucination mentioned in above issue.
- This PR fixes the case by falling back to `native_forward` for `RMSNorm` in `InternAttention` qk_layernorm.

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by Isotr0py** [comment]
@XNLHZ Can you check if this PR can generate correct outputs? 

The forward outputs of [InternViT-6B-448px-V1-5](https://huggingface.co/OpenGVLab/InternViT-6B-448px-V1-5) should converge with this fix. But I'm not sure if the VLM outputs would be correct.

Thanks!

**Comment by jamestwhedbee** [comment]
@Isotr0py I can confirm this fix works for the 76B model

**Review by mgoin — APPROVED** [review]

**Comment by XNLHZ** [comment]
> @XNLHZ Can you check if this PR can generate correct outputs?
> 
> The forward outputs of [InternViT-6B-448px-V1-5](https://huggingface.co/OpenGVLab/InternViT-6B-448px-V1-5) should converge with this fix. But I'm not sure if the VLM outputs would be correct.
> 
> Thanks!

@Isotr0py Sorry for my late reply, I was busy yesterday. I can confirm that the 26B model now generates responses that match the pictures. But it is different from the result I generated directly using the official inference script. I am confused about this. Can you tell me what may be the reason?

question: What is the content of this image?

original：
image

vllm:
image

**Comment by Isotr0py** [comment]
@XNLHZ IMO, a possible reason may be another `RMSNorm`, which used in `InternVisionEncoderLayer`. 

We still used fused `RMSNorm` there, because its numeric difference is acceptable here. You can try to fall back to `native_forward` there to see if the outputs would be improved.

By the way, you can also have a check on `generation_config`, because we use `temperature=0.2` in `examples/offline_inference_vision_language.py` by default.

**Comment by XNLHZ** [comment]
> @XNLHZ IMO, a possible reason may be another `RMSNorm`, which used in `InternVisionEncoderLayer`.
> 
> We still used fused `RMSNorm` there, because its numeric difference is acceptable. You can try to fall back to `native_forward` there as well to see if the outputs would be improved.
> 
> By the way, you can also have a check on `generation_config`, because we use `temperature=0.2` in `examples/offline_inference_vision_language.py` by default.

@Isotr0py Thank you for your reply, I have set the temperature to 0, and add ‘.forward_native’ after the two ‘RMSNorm’ you mentioned just now. However, this only had a negligible impact on the generated results, and it was still difficult to generate answers close to the official reasoning script.

BTW, I also tested several other pictures. The differences between the answers generated by vllm and the official ones are relatively large, but there is no significant difference in the quality of the generated answers. Therefore, this problem should not affect the use of the model.

But I am still curious about this problem. I also encountered this problem in the long text generation of the 2B model. If you have time, can you test whether the long text generation of the 2B model is the same as the official reasoning script?

**Comment by Isotr0py** [comment]
> I also encountered this problem in the long text generation of the 2B model.

OK, I will have a check for this after finishing some refactor work for InternVL.

**Pull request merged**
