### PR TITLE
[Build][Bugfix] Using the correct type hint

### PR DESCRIPTION
**Pull request by gshtras**
Fix type hint error introduced in #10769
This becomes critical when using cython compilation
cc @DarkLight1337

### CODE REVIEW

**Review by mgoin — APPROVED** [review]
Thanks for the patch, makes sense

**Comment by DarkLight1337** [comment]
Does cython not allow subscripting `type`? We are using Python 3.9 already so it should be supported.

**Comment by gshtras** [comment]
> Does cython not allow subscripting `type`? We are using Python 3.9 already so it should be supported in pure Python.

Lowercase `type` is not a type hint, but rather a keyword and a function, for the type hint there is `Type` from typing.
While pure python ignores type hints in runtime, cython builds the compilable C code based on them, with strong runtime checks, and so it fails in runtime due to
`TypeError: 'type' object is not subscriptable`

**Comment by DarkLight1337** [comment]
> > Does cython not allow subscripting `type`? We are using Python 3.9 already so it should be supported in pure Python.
> 
> Lowercase `type` is not a type hint, but rather a keyword and a function, for the type hint there is `Type` from typing. While pure python ignores type hints in runtime, cython builds the compilable C code based on them, with strong runtime checks, and so it fails in runtime due to `TypeError: 'type' object is not subscriptable`

I'm aware that this is not a type hint. Subscripting `type` directly is possible since Python 3.9 thanks to [PEP 585](https://peps.python.org/pep-0585/), which [deprecates](https://docs.python.org/3/library/typing.html#typing.Type) the use of `typing.Type`. Is that not the case for Cython?

**Comment by gshtras** [comment]
> > > Does cython not allow subscripting `type`? We are using Python 3.9 already so it should be supported in pure Python.
> > 
> > 
> > Lowercase `type` is not a type hint, but rather a keyword and a function, for the type hint there is `Type` from typing. While pure python ignores type hints in runtime, cython builds the compilable C code based on them, with strong runtime checks, and so it fails in runtime due to `TypeError: 'type' object is not subscriptable`
> 
> I'm aware that this is not a type hint. The ability to subscript `type` directly was added in Python 3.9 ([PEP 585](https://peps.python.org/pep-0585/)), which [deprecates](https://docs.python.org/3/library/typing.html#typing.Type) the use of `typing.Type`. Is that not the case for Cython?

Apparently not for type. According to the issue tracker it is supposed to be working for collections.

**Pull request merged**
