### PR TITLE
Fix crash when try torch.cuda.set_device in worker

### PR DESCRIPTION
**Pull request by leiwen83**
The new usage status collector add vllm.model_executor.model_loader import which cause transformers start to init the context with the cuda environment which hasn't configured by _init_workers_ray@RayGPUExecutor with set_cuda_visible_devices func yet.

So that with wrong context inited, it would cause crash when we use tp > 1 case.
```
(RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44] Error executing method init_device. This might cause deadlock in distributed execution. (RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44] Traceback (most recent call last):
(RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44]   File "/data/dev/vllm/vllm/engine/ray_utils.py", line 37, in execute_method
(RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44]     return executor(*args, **kwargs)
(RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44]   File "/data/dev/vllm/vllm/worker/worker.py", line 91, in init_device
(RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44]     torch.cuda.set_device(self.device)
(RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 404, in set_device
(RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44]     torch._C._cuda_setDevice(device)
(RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44] RuntimeError: CUDA error: invalid device ordinal
(RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44] For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
(RayWorkerVllm pid=515753) ERROR 04-01 15:42:25 ray_utils.py:44] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
FILL IN THE PR DESCRIPTION HERE

FIX #xxxx (*link existing issues this PR will resolve*)

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by hongxiayang** [comment]
@leiwen83  FYI: We pinned to this version of ray (2.9.3) instead of using 2.10.0, and it worked for us (https://github.com/vllm-project/vllm/pull/3699).

**Comment by hongxiayang** [comment]
@WoosukKwon @simon-mo I wonder why the test `tests/distributed/test_basic_distributed_correctness.py` in CI did not catch the problem?

**Review by njhill — APPROVED** [review]
Thanks @leiwen83, LGTM

**Comment by mgoin** [comment]
I was able to replicate this issue running `CUDA_VISIBLE_DEVICES=0,1 TEST_DIST_MODEL=facebook/opt-125m pytest -s -v tests/distributed/test_basic_distributed_correctness.py`. I am also confused why this wasn't caught in CI

Running right before this fix, I can show that `test_basic_distributed_correctness.py` hangs/fails quickly:
```
> git checkout main~1
> CUDA_VISIBLE_DEVICES=0,1 TEST_DIST_MODEL=facebook/opt-125m pytest -s -v tests/distributed/test_basic_distributed_correctness.py
====================================================================================================================== test session starts =======================================================================================================================
platform linux -- Python 3.10.12, pytest-8.0.0, pluggy-1.4.0 -- /home/michael/venvs/vllm/bin/python3
cachedir: .pytest_cache
rootdir: /home/michael/code/vllm
plugins: anyio-4.2.0
collected 1 item                                                                                                                                                                                                                                                 

tests/distributed/test_basic_distributed_correctness.py::test_models[5-half-facebook/opt-125m] huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
2024-04-02 19:09:04,234 INFO worker.py:1724 -- Started a local Ray instance.
INFO 04-02 19:09:05 llm_engine.py:75] Initializing an LLM engine (v0.4.0) with config: model='facebook/opt-125m', tokenizer='facebook/opt-125m', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=1024, download_dir=None, load_format=auto, tensor_parallel_size=2, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
(raylet) [2024-04-02 19:09:13,176 E 907492 907529] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-04-02_19-09-01_184666_907017 is over 95% full, available space: 236426760192; capacity: 7557149999104. Object creation will fail if spilling is required.
INFO 04-02 19:09:13 selector.py:51] Cannot use FlashAttention because the package is not found. Please install it for better performance.
INFO 04-02 19:09:13 selector.py:25] Using XFormers backend.
(RayWorkerVllm pid=913486) INFO 04-02 19:09:13 selector.py:51] Cannot use FlashAttention because the package is not found. Please install it for better performance.
(RayWorkerVllm pid=913486) INFO 04-02 19:09:13 selector.py:25] Using XFormers backend.
INFO 04-02 19:09:13 pynccl_utils.py:45] vLLM is using nccl==2.18.1
(RayWorkerVllm pid=913486) INFO 04-02 19:09:13 pynccl_utils.py:45] vLLM is using nccl==2.18.1
INFO 04-02 19:09:15 weight_utils.py:177] Using model weights format ['*.bin']
(RayWorkerVllm pid=913486) INFO 04-02 19:09:15 weight_utils.py:177] Using model weights format ['*.bin']
INFO 04-02 19:09:16 model_runner.py:104] Loading model weights took 0.1185 GB
(RayWorkerVllm pid=913486) INFO 04-02 19:09:16 model_runner.py:104] Loading model weights took 0.1189 GB
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44] Error executing method profile_num_available_blocks. This might cause deadlock in distributed execution.
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44] Traceback (most recent call last):
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/engine/ray_utils.py", line 37, in execute_method
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return executor(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return func(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/worker/worker.py", line 131, in profile_num_available_blocks
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     self.model_runner.profile_run()
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return func(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/worker/model_runner.py", line 742, in profile_run
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     self.execute_model(seqs, kv_caches)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return func(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/worker/model_runner.py", line 663, in execute_model
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     hidden_states = model_executable(**execute_model_kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return self._call_impl(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return forward_call(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/model_executor/models/opt.py", line 301, in forward
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     hidden_states = self.model(input_ids, positions, kv_caches,
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return self._call_impl(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return forward_call(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/model_executor/models/opt.py", line 276, in forward
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return self.decoder(input_ids, positions, kv_caches, attn_metadata)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return self._call_impl(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return forward_call(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/model_executor/models/opt.py", line 250, in forward
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     hidden_states = layer(hidden_states, kv_caches[i], attn_metadata)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return self._call_impl(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return forward_call(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/model_executor/models/opt.py", line 158, in forward
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     hidden_states = self.self_attn(hidden_states=hidden_states,
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return self._call_impl(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return forward_call(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/model_executor/models/opt.py", line 102, in forward
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return self._call_impl(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return forward_call(*args, **kwargs)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/attention/layer.py", line 46, in forward
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return self.impl.forward(query, key, value, kv_cache, attn_metadata)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/attention/backends/xformers.py", line 258, in forward
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     output = self._run_memory_efficient_xformers_forward(
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/code/vllm/vllm/attention/backends/xformers.py", line 335, in _run_memory_efficient_xformers_forward
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     out = xops.memory_efficient_attention_forward(
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 244, in memory_efficient_attention_forward
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return _memory_efficient_attention_forward(
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 337, in _memory_efficient_attention_forward
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     op = _dispatch_fw(inp, False)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 120, in _dispatch_fw
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     return _run_priority_list(
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 53, in _run_priority_list
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     not_supported = op.not_supported_reasons(inp)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/decoder.py", line 41, in not_supported_reasons
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     reasons = super(FwOp, cls).not_supported_reasons(d)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/common.py", line 304, in not_supported_reasons
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     device_capability = torch.cuda.get_device_capability(d.device)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/cuda/__init__.py", line 435, in get_device_capability
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     prop = get_device_properties(device)
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]   File "/home/michael/venvs/vllm/lib/python3.10/site-packages/torch/cuda/__init__.py", line 452, in get_device_properties
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44]     raise AssertionError("Invalid device id")
(RayWorkerVllm pid=913486) ERROR 04-02 19:09:17 ray_utils.py:44] AssertionError: Invalid device id
(raylet) [2024-04-02 19:09:23,188 E 907492 907529] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-04-02_19-09-01_184666_907017 is over 95% full, available space: 236426715136; capacity: 7557149999104. Object creation will fail if spilling is required.
```

Running with this change on main, it works fine:
```
> git checkout main
> CUDA_VISIBLE_DEVICES=0,1 TEST_DIST_MODEL=facebook/opt-125m pytest -s -v tests/distributed/test_basic_distributed_correctness.py
====================================================================================================================== test session starts =======================================================================================================================
platform linux -- Python 3.10.12, pytest-8.0.0, pluggy-1.4.0 -- /home/michael/venvs/vllm/bin/python3
cachedir: .pytest_cache
rootdir: /home/michael/code/vllm
plugins: anyio-4.2.0
collected 1 item                                                                                                                                                                                                                                                 

tests/distributed/test_basic_distributed_correctness.py::test_models[5-half-facebook/opt-125m] huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
2024-04-02 19:10:08,058 INFO worker.py:1724 -- Started a local Ray instance.
INFO 04-02 19:10:09 llm_engine.py:74] Initializing an LLM engine (v0.4.0) with config: model='facebook/opt-125m', tokenizer='facebook/opt-125m', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=1024, download_dir=None, load_format=auto, tensor_parallel_size=2, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 04-02 19:10:13 selector.py:51] Cannot use FlashAttention because the package is not found. Please install it for better performance.
INFO 04-02 19:10:13 selector.py:25] Using XFormers backend.
(RayWorkerVllm pid=921495) INFO 04-02 19:10:15 selector.py:51] Cannot use FlashAttention because the package is not found. Please install it for better performance.
(RayWorkerVllm pid=921495) INFO 04-02 19:10:15 selector.py:25] Using XFormers backend.
INFO 04-02 19:10:15 pynccl_utils.py:45] vLLM is using nccl==2.18.1
(RayWorkerVllm pid=921495) INFO 04-02 19:10:15 pynccl_utils.py:45] vLLM is using nccl==2.18.1
INFO 04-02 19:10:17 weight_utils.py:177] Using model weights format ['*.bin']
(RayWorkerVllm pid=921495) INFO 04-02 19:10:17 weight_utils.py:177] Using model weights format ['*.bin']
(raylet) [2024-04-02 19:10:18,005 E 915565 915599] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-04-02_19-10-06_009742_915090 is over 95% full, available space: 236425453568; capacity: 7557149999104. Object creation will fail if spilling is required.
INFO 04-02 19:10:18 model_runner.py:104] Loading model weights took 0.1185 GB
(RayWorkerVllm pid=921495) INFO 04-02 19:10:18 model_runner.py:104] Loading model weights took 0.1189 GB
INFO 04-02 19:10:19 ray_gpu_executor.py:240] # GPU blocks: 152793, # CPU blocks: 0
INFO 04-02 19:10:19 model_runner.py:791] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 04-02 19:10:19 model_runner.py:795] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(RayWorkerVllm pid=921495) INFO 04-02 19:10:19 model_runner.py:791] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(RayWorkerVllm pid=921495) INFO 04-02 19:10:19 model_runner.py:795] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 04-02 19:10:23 model_runner.py:867] Graph capturing finished in 4 secs.
(RayWorkerVllm pid=921495) INFO 04-02 19:10:23 model_runner.py:867] Graph capturing finished in 4 secs.
Processed prompts: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 79.99it/s]
PASSED

======================================================================================================================== warnings summary ========================================================================================================================
tests/distributed/test_basic_distributed_correctness.py::test_models[5-half-facebook/opt-125m]
  /home/michael/venvs/vllm/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
    return self.fget.__get__(instance, owner)()

tests/distributed/test_basic_distributed_correctness.py::test_models[5-half-facebook/opt-125m]
  /home/michael/venvs/vllm/lib/python3.10/site-packages/ray/_private/pydantic_compat.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import packaging

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================================================= 1 passed, 2 warnings in 21.46s =================================================================================================================

**Comment by njhill** [comment]
Based on @hongxiayang's comment above, it may be due to a different version of Ray being used in the CI workers?

**Pull request merged**
