### PR TITLE
Add FlashInfer to default Dockerfile

### LINKED ISSUE #6169: [Bug]: TypeError: 'NoneType' object is not callable when loading Gemma 2 9B with new 0.5.1 version
### Your current environment

Idk how to run it inside a docker

### 🐛 Describe the bug

Simply run the following command
`docker run --runtime nvidia --gpus all     -v ~/.cache/huggingface:/root/.cache/huggingface     --env "HUGGING_FACE_HUB_TOKEN=<my secret>" --env "VLLM_ATTENTION_BACKEND=FLASHINFER"    -p 8000:8000     --ipc=host     vllm/vllm-openai:latest     --model google/gemma-2-9b-it`

It doesn't work.

Log:
```
INFO 07-06 07:29:27 api_server.py:206] vLLM API server version 0.5.1
INFO 07-06 07:29:27 api_server.py:207] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='google/gemma-2-9b-it', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, device='auto', scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 07-06 07:29:28 utils.py:562] Gemma 2 uses sliding window attention for every odd layer, which is currently not supported by vLLM. Disabling sliding window and capping the max length to the sliding window size (4096).
INFO 07-06 07:29:28 llm_engine.py:169] Initializing an LLM engine (v0.5.1) with config: model='google/gemma-2-9b-it', speculative_config=None, tokenizer='google/gemma-2-9b-it', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=google/gemma-2-9b-it, use_v2_block_manager=False, enable_prefix_caching=False)
INFO 07-06 07:29:29 selector.py:79] Using Flashinfer backend.
WARNING 07-06 07:29:29 selector.py:80] Flashinfer will be stuck on llama-2-7b, please avoid using Flashinfer as the backend when running on llama-2-7b.
INFO 07-06 07:29:29 selector.py:79] Using Flashinfer backend.
WARNING 07-06 07:29:29 selector.py:80] Flashinfer will be stuck on llama-2-7b, please avoid using Flashinfer as the backend when running on llama-2-7b.
INFO 07-06 07:29:29 weight_utils.py:218] Using model weights format ['*.safetensors']
INFO 07-06 07:29:55 model_runner.py:255] Loading model weights took 17.3781 GB
[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 216, in <module>
[rank0]:     engine = AsyncLLMEngine.from_engine_args(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 431, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 360, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 507, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 256, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 353, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 76, in determine_num_available_blocks
[rank0]:     return self.driver_worker.determine_num_available_blocks()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 173, in determine_num_available_blocks
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 874, in profile_run
[rank0]:     self.execute_model(model_input, kv_caches, intermediate_tensors)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 1201, in execute_model
[rank0]:     BatchDecodeWithPagedKVCacheWrapper(
[rank0]: TypeError: 'NoneType' object is not callable
```

I'm on a Google Cloud VM with Nvidia L4, 4 cores and 32GB RAM, using the DeepLearning 12.1 CUDA image provided by Google. The same error come out when running via standard python using the following command:
`python -m vllm.entrypoints.openai.api_server --model "google/gemma-2-9b-it"`
Obviously already setted the env for enable FlashInfer backend and my hugging face key

### PR DESCRIPTION
**Pull request by simon-mo**
Closes #6169 

Testing with 
```
docker run --gpus all -p 8000:8000 -e HF_TOKEN --ipc=host --env "VLLM_ATTENTION_BACKEND=FLASHINFER" -v /data/xmo/hub:/root/.cache/huggingface vllm/vllm-openai --model google/gemma-2-9b-it
```

```
$ curl http://localhost:8000/v1/completions  -H "Content-Type: application/json"      -d '{
"model": "google/gemma-2-9b-it",
"prompt":"Who won the world series in 2020?",
"max_tokens": 100,
"ignore_eos": true
}'
{"id":"cmpl-8ce64ceae52449e2b04988b08f3f42f9","object":"text_completion","created":1720253967,"model":"google/gemma-2-9b-it","choices":[{"index":0,"text":"\n\nThe **Los Angeles Dodgers** won the World Series in 2020. \n\\\\\n  \\\\\n\n\n\\\\\n\\\\\n\\\n\n\\\\\n\\\\\n\n\n\n\n.\n\n\n'.\n\n\n\n\n\n **\n\n\n\n\n。","logprobs":null,"finish_reason":"length","stop_reason":null}],"usage":{"prompt_tokens":13,"total_tokens":113,"completion_tokens":100}}(miniconda3) (base) [xmo@flow-matic:/data/xmo/vllm]$ 
```

The docker image for `vllm/vllm-openai:latest` and `vllm/vllm-openai:v0.5.1` has been built and updated. This doesn't effect the wheel build.

### CODE REVIEW

**Review by WoosukKwon — APPROVED** [review]
LGTM!

**Review by zhyncs — COMMENTED** [review]
[FlashInfer 0.9.0](https://github.com/flashinfer-ai/flashinfer/pull/359) has been optimized for GQA, maybe we can wait until version 0.9.0 is released before integrating it into the Dockerfile.

**Comment by simon-mo** [comment]
We already released v0.8.0 and will be able to update right after!

**Comment by zhyncs** [comment]
ok

**Pull request merged**
