### PR TITLE
[Misc] SpecDecodeWorker supports profiling

### PR DESCRIPTION
**Pull request by Abatom**
1. SpecDecodeWorker supports profiling by reusing the profiler of the Worker class.

### CODE REVIEW

**Review by comaniac — APPROVED** [review]

**Comment by comaniac** [comment]
Please fix DCO by signing off all your commits.

**Comment by Abatom** [comment]
> Please fix DCO by signing off all your commits.

Thank you for your reply! DCO has been fixed.

**Comment by Abatom** [comment]
> Please fix DCO by signing off all your commits.

Thank you for your reply! DCO has been fixed.

**Comment by Abatom** [comment]
> Please fix DCO by signing off all your commits.

Thank you for your reply! DCO has been fixed.

**Pull request merged**
