### PR TITLE
SamplingParams add min_tokens

### PR DESCRIPTION
**Pull request by shanekong**
in order to avoid llm generates too short tokens, we need min_tokens.

### CODE REVIEW

**Comment by simon-mo** [comment]
Hi @shanekong, can you tell us more about in what scenarios `min_tokens` will be useful? Is it for benchmarking? Previously we ask the users to directly set `ignore_eos` and `max_tokens`.

**Comment by shanekong** [comment]
> Hi @shanekong, can you tell us more about in what scenarios `min_tokens` will be useful? Is it for benchmarking? Previously we ask the users to directly set `ignore_eos` and `max_tokens`.

We are using LLM in chatbot for NPC role play. There are two scenarios we need min_tokens:
1. we use delimiter('\n') as stop tokens, LLM may first generate '\n' in some cases，which may lead to empty results;
2. for some NPCs, who is set to be talkative, we need LLM avoid to generate too short sentences. if we use ignore_eos and max_tokens in our scenarios, which may lead to too long result(max_tokens length) for every round of interaction which is unnatural.

**Comment by hijkzzz** [comment]
Is there any progress? a very important feature!

**Comment by simon-mo** [comment]
@shanekong do you have bandwidth to address this? thank you!

**Comment by tjohnson31415** [comment]
Hello. I am interested in this feature as well!
@shanekong: Will you be able to carry this PR forward? If you don't have the time, I'm willing to pick it up and work to get the functionality merged.

**Comment by simon-mo** [comment]
@tjohnson31415 please feel free to open another PR and tag me to review

**Comment by simon-mo** [comment]
Replaced by #3124

**Pull request closed without merging**
