### PR TITLE
Fix StableLMEpochForCausalLM Class name in __init__.py

### PR DESCRIPTION
**Pull request by dakotamahan-stability**

### CODE REVIEW

**Comment by WoosukKwon** [comment]
Hi @dakotamahan-stability, thanks for the pr. Could you elaborate more on why this change is needed?

**Comment by dakotamahan-stability** [comment]
Sure @WoosukKwon , the current class name doesn't match the StableLM modeling code, so when trying to run a model it will raise a ValueError here: https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/model_loader.py#L30

**Comment by WoosukKwon** [comment]
@dakotamahan-stability, thanks for the prompt reply. Could you share a script that can reproduce the bug?

**Comment by dakotamahan-stability** [comment]
Sorry this was my mistake, had an error when manually merging some code and thought the model names in the modeling file were the same as the names in the transformers modeling code.

**Pull request closed without merging**
