### PR TITLE
[BugFix] Fix Falcon tied embeddings

### PR DESCRIPTION
**Pull request by WoosukKwon**
Supersedes #3579

This PR fixes a bug that vLLM does not use tied embeddings for Falcon models. This bug didn't appear on Falcon-7B since the checkpoint has duplicated weights for word embeddings and LM head. However, the bug appeared for other Falcon models who don't duplicate the weights. The PR was tested on both Falcon-7B and Falcon-40B.

### CODE REVIEW

**Comment by WoosukKwon** [comment]
@44670 Could you take a look? If I understand correctly, we can simply use tied embeddings for all cases.

**Comment by 44670** [comment]
I'm not quite sure if all Falcon models use tied embeddings (as far as I know, the 40b and 180b do). 

My suggested approach is: if the model's checkpoint contains `lm_head`, assume there is no tie and use the `lm_head`'s weights directly. If the checkpoint does not contain an `lm_head`, then copy the `word_embedding`'s weights to the lm_head (or directly share them to save VRAM).

**Comment by WoosukKwon** [comment]
@44670 I believe we can safely assume that all Falcon models use tied embeddings, since the model is defined so in HF transformers: https://github.com/huggingface/transformers/blob/76a33a10923ccc1074917f6b6a1e719e626b7dc9/src/transformers/models/falcon/modeling_falcon.py#L1201

**Comment by youkaichao** [comment]
Just jumping in, not sure if it works: we can load the model on a "meta" device (i.e. do not allocate space, but just shape, dtype meta data, see https://huggingface.co/blog/accelerate-large-models for details), and check the state dict. In addition, huggingface safetensors have this support: https://huggingface.co/docs/safetensors/en/torch_shared_tensors , not sure if we can use it:

```python
from safetensors.torch import load_model, save_model

save_model(model, "model.safetensors")
# Instead of save_file(model.state_dict(), "model.safetensors")

load_model(model, "model.safetensors")
# Instead of model.load_state_dict(load_file("model.safetensors"))
```

It will automatically deal with shared tensors.

**Comment by WoosukKwon** [comment]
@youkaichao Thanks for the idea. I'm not familiar with `meta` device, so not sure how it will work with our model partitioning and loading. If using the `meta` device is becoming the standard, we should probably use it.

That being said, I think it's outside the scope of this PR since the PR just follows HF transformer's semantics and we are doing the same thing for all models using tied embeddings. So maybe I can just merge this?

**Comment by youkaichao** [comment]
> So maybe I can just merge this?

Yes you can merge this PR. I will investigate in the future whether we need to embrace new ways of loading model weights.

**Comment by 44670** [comment]
Falcon-11B has no tied-embeddings, maybe we should parse the config file now?

https://huggingface.co/tiiuae/falcon-11B/blob/main/config.json

**Comment by s-smits** [comment]
Also interested in making Falcon-11B work for vllm.

**Pull request merged**
