### PR TITLE
[Ported][CI/Build] Share HuggingFace downloads between test runs

### PR DESCRIPTION
**Pull request by DarkLight1337**
The models tests keep getting interrupted (presumably due to running too long). This PR attempts to reduce the running time via:

- ~~Share the HuggingFace cache between Kubernetes containers during CI by storing it in a `hostPath` volume.~~
- ~~Disabling graph construction (considering that the vLLM model is only run once per test, not including the profile run).~~
- Reuse the HuggingFace cache between Docker containers via a shared volume.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Using eager mode doesn't seem to lead to significant improvement. It seems that the bottleneck is in downloading the models, so we should parallelize this process.

**Comment by DarkLight1337** [comment]
I'm not that experienced in Kubernetes but from my understanding, placing the HuggingFace cache inside a Volume ([#78f64a4](https://github.com/vllm-project/vllm/pull/4874/commits/78f64a499c21b06cf493fd2343b3d31de99b400c)) should avoid the need to redownload the models when tests are run again in the same Pod.

**Comment by rkooo567** [comment]
Hmm I am not super familiar with how CI works actually (idk if we even use k8s under the hood). cc @simon-mo for thoughts..

**Comment by DarkLight1337** [comment]
@khluu since you're involved with CI, can you help out with this?

**Comment by simon-mo** [comment]
I believe we should download the model each time. @robertgshaw2-neuralmagic mentioned that putting them on NFS is a bit tricky because it might reaches rate limit.

**Comment by simon-mo** [comment]
hostPath a possible workaround.

**Comment by rkooo567** [comment]
> Disabling graph construction (considering that the vLLM model is only run once per test, not including the profile run).

Hmm I am against this. Imo we should test the default config for those tests (especially the test_model)

**Comment by DarkLight1337** [comment]
Looks like this shaved around 10 minutes off the duration of model tests.

**Comment by DarkLight1337** [comment]
> Looks like this shaved around 10 minutes off the duration of model tests. Going to rerun the test just to be sure.

This doesn't seem to be the case anymore. It's hard to really see the effect since the test runs aren't necessarily performed on the same machine (from my understanding).

**Comment by DarkLight1337** [comment]
Due to #5757, I have moved this PR to vllm-project/buildkite-ci#8.

**Pull request closed without merging**
