### PR TITLE
fix context_len when excede sliding_window

### PR DESCRIPTION
**Pull request by apache2046**
the last block may not contains all valid filled slots

### CODE REVIEW

**Comment by WoosukKwon** [comment]
Hi @apache2046 could you elaborate more on this PR? I don't understand why the current logic is wrong and this PR is correct.

**Comment by apache2046** [comment]
After examining the paged_attention_kernel, I thought that it extracts context_len tokens from the beginning block's first slot in the kv-cache to calculate the attention for the query vector.

In a scenario where block_size ==  16 and seq_data.get_len()== 4097 and len(seq_group_metadata.block_tables[seq_id]) == 257, it appears that only the first slot of the last block is filled. Assuming a sliding_window of 4096, the expression` block_table = block_table[-sliding_window_blocks:]` trims the block_table to contain the last 256 blocks out of 257, including the last one-slot valid block. However, paged_attention_kernel seems to use 4096 as context_len, treating all  16 slots of the last block as if they have been filled.

I'm not sure if I've misunderstood some critical aspects of this process.

**Comment by nittaya111** [comment]
Hello my family. Merry Christmas 🎁 How are you doing today. I miss my
family

เมื่อ ศ. 22 ธ.ค. 2566 เวลา 16:09 apache2046 ***@***.***>
เขียนว่า:

**Comment by WoosukKwon** [comment]
Hi @apache2046, thanks for the further explanation. I believe your understanding of the current logic is right, but I also believe the current logic is correct. In your example, the token IDs in the last block will be [4096, 1, 2, ..., block_size - 1], and the PagedAttention kernel will attend to all tokens in the block. This exactly implements the sliding window attention (that is, the 4096-th token attends to all tokens except the 0-th token).

One potential problem in this implementation is the `token_idx` in the PagedAttention kernel can be wrong. However, I think this is ok since it only matters when using ALiBi bias along with the sliding window attention.

Please feel free to ask any question if you need further clarification.

**Pull request closed without merging**
