### PR TITLE
[Feature] SYCL kernel support for Intel GPU 

### PR DESCRIPTION
**Pull request by abhilash1910**
Thanks for creating the project. This is an initial effort to upstream SYCL  kernel support for our Intel GPUs. (cxx compiler)

### CODE REVIEW

**Comment by WoosukKwon** [comment]
Hi @abhilash1910, thanks for submitting the great work! Can we chat about the PR? We'd like to know more about the background and your (team's) plan. If you're interested, please reach out to my email: woosuk.kwon[at]berkeley.edu

**Comment by abhilash1910** [comment]
Thanks @WoosukKwon  , I will connect with you .

**Comment by jikunshang** [comment]
Hi @abhilash1910 @WoosukKwon, Thanks for your great effort to provide this PR. It's really a good start but it seems not able to build or run. Instead of migrating CUDA kernels to SYCL directly, we redesigned Intel XPU support for vllm via dispatching operators to customized SYCL kernels/functions.
Currently, our approach could run an easy e2e example(offline_inference.py) using opt-125m model. The development is in progress, still have a lot to be done. Details can be found in PR #2378. Please take a review, thanks!
cc @bigPYJ1151 @maktukmak

**Comment by abhilash1910** [comment]
Diverted to #2378  for consolidated porting.

**Comment by WoosukKwon** [comment]
Closing this PR as we merged #3814

**Pull request closed without merging**
