### PR TITLE
Docs: Add Haystack integration details

### PR DESCRIPTION
**Pull request by bilgeyucel**
vLLM has an integration with Haystack: https://haystack.deepset.ai/integrations/vllm. 

This PR aims to update the documentation with the details of that integration.

### CODE REVIEW

**Comment by simon-mo** [comment]
Hi @bilgeyucel, I believe because vLLM supports OpenAI protocol, you don't need this special integration? Please correct me if i'm wrong. Thank you for your contribution.

**Comment by bilgeyucel** [comment]
Hi @simon-mo, thank you for your reply! I'm not sure if I understand your question correctly. Let me try to explain my take: [Haystack](https://github.com/deepset-ai/haystack) is an open source Python framework for building custom LLM applications. The addition of vLLM introduces the capability to deploy self-hosted LLMs for using Haystack pipelines, making it a valuable integration. With this PR, I wanted to showcase this integration in vLLM's documentation

Let me know if anything is not clear or if you have any questions

**Comment by simon-mo** [comment]
Ah sorry for the confusion. My point is that because vLLM offers OpenAI compatible API, and Haystack must have a connector directly be able to talk to OpenAI. Is the vLLM special connector necessary? It adds maintenance cost for you all.

**Comment by bilgeyucel** [comment]
You have a fair point 👍  The upcoming Haystack 2.0 version (in the beta phase now) has a connector for OpenAI compatible API but vLLM is the only option for Haystack 1.0 users that we'll support till the end of 2024. The idea is quite similar to this one -> https://github.com/vllm-project/vllm/blob/main/docs/source/serving/serving_with_langchain.rst

**Pull request closed without merging**
