### PR TITLE
[Core] Combined support for multi-step scheduling, chunked prefill & prefix caching

### PR DESCRIPTION
**Pull request by afeldman-nm**
Add combined support for multi-step scheduling, chunked prefill & prefix caching.

FIX #xxxx (*link existing issues this PR will resolve*)

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Adding or changing kernels</h3>
<p>Each custom kernel needs a schema and one or more implementations to be registered with PyTorch.</p>
<ul>
    <li>Make sure custom ops are registered following PyTorch guidelines: <a href="https://pytorch.org/tutorials/advanced/cpp_custom_ops.html#cpp-custom-ops-tutorial">Custom C++ and CUDA Operators</a> and <a href="https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU">The Custom Operators Manual</a></li>
    <li>Custom operations that return <code>Tensors</code> require meta-functions. Meta-functions should be implemented and registered in python so that dynamic dims can be handled automatically. See above documents for a description of meta-functions.</li>
    <li>Use <a href="https://pytorch.org/docs/stable/library.html#torch.library.opcheck"><code>torch.libary.opcheck()</code></a> to test the function registration and meta-function for any registered ops.  See <code>tests/kernels</code> for examples.</li>
    <li>When changing the C++ signature of an existing op, the schema must be updated to reflect the changes.</li>
    <li>If a new custom type is needed, see the following document: <a href="https://docs.google.com/document/d/18fBMPuOJ0fY5ZQ6YyrHUppw9FA332CpNtgB6SOIgyuA">Custom Class Support in PT2</a>.
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by afeldman-nm** [comment]
# Comparative benchmark of baseline multi-step scheduling, multi-step + prefix-caching, and multi-step + chunked prefill (with async output processor)

This benchmark is performed against the branch `neuralmagic/vllm:varun/p4-multi-step-chunked-prefill` which adds limited chunked prefill support to multi-step (multi-step + prefix caching was already supported.)

## Benchmarking setup

Each benchmark is performed twice, in order to capture run-to-run variation.

The client-side benchmarking tool metric summary & the logged outputs from the server are recorded.

### Testbench setup

```
1x H100 80GB HBM3
```

### Client-side benchmarking tool command

```
python benchmarks/benchmark_serving.py     --backend vllm   --model meta-llama/Meta-Llama-3-8B     --dataset-name sharegpt     --dataset-path ../sharegpt.json --port 9000
```

## Baseline: multi-step scheduling benchmark

### Server-side CLI call

```
python  -m vllm.entrypoints.openai.api_server     --model meta-llama/Meta-Llama-3-8B --swap-space 16     --disable-log-requests  --use-v2-block-manager   --tensor-parallel-size 1  --pipeline-parallel-size 1  --gpu-memory-utilization 0.90  --num-scheduler-steps 8 --port 9000  --worker-use-ray 2>&1 | tee output.log
```

### Benchmark run 1

```
============ Serving Benchmark Result ============
Successful requests:                     1000      
Benchmark duration (s):                  19.37     
Total input tokens:                      215196    
Total generated tokens:                  128375    
Request throughput (req/s):              51.63     
Output token throughput (tok/s):         6628.49   
Total Token throughput (tok/s):          17739.89  
---------------Time to First Token----------------
Mean TTFT (ms):                          3819.32   
Median TTFT (ms):                        3076.68   
P99 TTFT (ms):                           12275.36  
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          35.84     
Median TPOT (ms):                        25.35     
P99 TPOT (ms):                           303.33    
---------------Inter-token Latency----------------
Mean ITL (ms):                           182.94    
Median ITL (ms):                         156.32    
P99 ITL (ms):                            680.66    
==================================================

INFO 09-25 13:29:14 metrics.py:351] Avg prompt throughput: 3141.3 tokens/s, Avg generation throughput: 17.8 tokens/s, Running: 96 reqs, Swapped: 0 reqs, Pending: 877 reqs, GPU KV cache usage: 3.2%, CPU KV cache usage: 0.0%.
INFO 09-25 13:29:19 metrics.py:351] Avg prompt throughput: 22999.4 tokens/s, Avg generation throughput: 895.1 tokens/s, Running: 256 reqs, Swapped: 0 reqs, Pending: 356 reqs, GPU KV cache usage: 11.5%, CPU KV cache usage: 0.0%.
INFO 09-25 13:29:24 metrics.py:351] Avg prompt throughput: 14589.1 tokens/s, Avg generation throughput: 1238.2 tokens/s, Running: 252 reqs, Swapped: 0 reqs, Pending: 34 reqs, GPU KV cache usage: 15.4%, CPU KV cache usage: 0.0%.
INFO 09-25 13:29:29 metrics.py:351] Avg prompt throughput: 2043.9 tokens/s, Avg generation throughput: 1118.9 tokens/s, Running: 24 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.0%, CPU KV cache usage: 0.0%.
```

### Benchmark run 2

```
============ Serving Benchmark Result ============
Successful requests:                     1000      
Benchmark duration (s):                  19.50     
Total input tokens:                      215196    
Total generated tokens:                  128075    
Request throughput (req/s):              51.29     
Output token throughput (tok/s):         6568.36   
Total Token throughput (tok/s):          17604.73  
---------------Time to First Token----------------
Mean TTFT (ms):                          3813.53   
Median TTFT (ms):                        2989.32   
P99 TTFT (ms):                           12417.85  
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          38.05     
Median TPOT (ms):                        26.04     
P99 TPOT (ms):                           247.41    
---------------Inter-token Latency----------------
Mean ITL (ms):                           184.10    
Median ITL (ms):                         156.26    
P99 ITL (ms):                            542.89    
==================================================

INFO 09-25 13:30:21 metrics.py:351] Avg prompt throughput: 16333.6 tokens/s, Avg generation throughput: 174.1 tokens/s, Running: 253 reqs, Swapped: 0 reqs, Pending: 555 reqs, GPU KV cache usage: 8.0%, CPU KV cache usage: 0.0%.
INFO 09-25 13:30:26 metrics.py:351] Avg prompt throughput: 14117.7 tokens/s, Avg generation throughput: 1294.4 tokens/s, Running: 249 reqs, Swapped: 0 reqs, Pending: 227 reqs, GPU KV cache usage: 13.2%, CPU KV cache usage: 0.0%.
INFO 09-25 13:30:31 metrics.py:351] Avg prompt throughput: 11827.1 tokens/s, Avg generation throughput: 1245.3 tokens/s, Running: 146 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 12.3%, CPU KV cache usage: 0.0%.
```

## Multi-step + prefix-caching benchmark

### Server-side CLI call

```
python  -m vllm.entrypoints.openai.api_server     --model meta-llama/Meta-Llama-3-8B --swap-space 16     --disable-log-requests  --use-v2-block-manager   --tensor-parallel-size 1  --pipeline-parallel-size 1  --gpu-memory-utilization 0.90  --num-scheduler-steps 8 --enable-prefix-caching --port 9000  --worker-use-ray 2>&1 | tee output.log
```

### Benchmark run 1

```
============ Serving Benchmark Result ============
Successful requests:                     1000      
Benchmark duration (s):                  20.33     
Total input tokens:                      215196    
Total generated tokens:                  128347    
Request throughput (req/s):              49.18     
Output token throughput (tok/s):         6312.36   
Total Token throughput (tok/s):          16896.12  
---------------Time to First Token----------------
Mean TTFT (ms):                          4090.94   
Median TTFT (ms):                        3477.49   
P99 TTFT (ms):                           12854.20  
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          41.87     
Median TPOT (ms):                        26.42     
P99 TPOT (ms):                           301.38    
---------------Inter-token Latency----------------
Mean ITL (ms):                           188.70    
Median ITL (ms):                         171.75    
P99 ITL (ms):                            646.08    
==================================================

INFO 09-25 13:24:47 metrics.py:351] Avg prompt throughput: 14910.6 tokens/s, Avg generation throughput: 77.4 tokens/s, Running: 255 reqs, Swapped: 0 reqs, Pending: 624 reqs, GPU KV cache usage: 7.3%, CPU KV cache usage: 0.0%.
INFO 09-25 13:24:47 metrics.py:367] Prefix cache hit rate: GPU: 0.00%, CPU: 0.00%
INFO 09-25 13:24:52 metrics.py:351] Avg prompt throughput: 14603.9 tokens/s, Avg generation throughput: 1201.1 tokens/s, Running: 253 reqs, Swapped: 0 reqs, Pending: 271 reqs, GPU KV cache usage: 13.1%, CPU KV cache usage: 0.0%.
INFO 09-25 13:24:52 metrics.py:367] Prefix cache hit rate: GPU: 0.70%, CPU: 0.00%
INFO 09-25 13:24:57 metrics.py:351] Avg prompt throughput: 13333.5 tokens/s, Avg generation throughput: 1241.1 tokens/s, Running: 200 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 14.4%, CPU KV cache usage: 0.0%.
INFO 09-25 13:24:57 metrics.py:367] Prefix cache hit rate: GPU: 0.86%, CPU: 0.00%
```

### Benchmark run 2

```
============ Serving Benchmark Result ============
Successful requests:                     1000      
Benchmark duration (s):                  16.27     
Total input tokens:                      215196    
Total generated tokens:                  129032    
Request throughput (req/s):              61.45     
Output token throughput (tok/s):         7929.48   
Total Token throughput (tok/s):          21154.04  
---------------Time to First Token----------------
Mean TTFT (ms):                          2722.92   
Median TTFT (ms):                        2217.71   
P99 TTFT (ms):                           9035.30   
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          21.33     
Median TPOT (ms):                        20.52     
P99 TPOT (ms):                           68.70     
---------------Inter-token Latency----------------
Mean ITL (ms):                           142.77    
Median ITL (ms):                         142.50    
P99 ITL (ms):                            412.14    
==================================================

INFO 09-25 13:26:00 metrics.py:351] Avg prompt throughput: 23720.1 tokens/s, Avg generation throughput: 608.3 tokens/s, Running: 255 reqs, Swapped: 0 reqs, Pending: 407 reqs, GPU KV cache usage: 9.0%, CPU KV cache usage: 0.0%.
INFO 09-25 13:26:00 metrics.py:367] Prefix cache hit rate: GPU: 36.34%, CPU: 0.00%
INFO 09-25 13:26:05 metrics.py:351] Avg prompt throughput: 17404.5 tokens/s, Avg generation throughput: 1558.5 tokens/s, Running: 256 reqs, Swapped: 0 reqs, Pending: 25 reqs, GPU KV cache usage: 15.8%, CPU KV cache usage: 0.0%.
INFO 09-25 13:26:05 metrics.py:367] Prefix cache hit rate: GPU: 49.53%, CPU: 0.00%
INFO 09-25 13:26:10 metrics.py:351] Avg prompt throughput: 1865.3 tokens/s, Avg generation throughput: 1135.5 tokens/s, Running: 21 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.5%, CPU KV cache usage: 0.0%.
INFO 09-25 13:26:10 metrics.py:367] Prefix cache hit rate: GPU: 50.43%, CPU: 0.00%
```

## Multi-step + chunked prefill

### Server-side CLI call

```
python  -m vllm.entrypoints.openai.api_server     --model meta-llama/Meta-Llama-3-8B --swap-space 16     --disable-log-requests  --use-v2-block-manager   --tensor-parallel-size 1  --pipeline-parallel-size 1  --gpu-memory-utilization 0.90  --num-scheduler-steps 8 --enable-chunked-prefill --port 9000  --worker-use-ray 2>&1 | tee output.log
```

### Benchmark run 1

```
============ Serving Benchmark Result ============
Successful requests:                     1000      
Benchmark duration (s):                  19.48     
Total input tokens:                      215196    
Total generated tokens:                  127912    
Request throughput (req/s):              51.34     
Output token throughput (tok/s):         6567.28   
Total Token throughput (tok/s):          17615.90  
---------------Time to First Token----------------
Mean TTFT (ms):                          4212.85   
Median TTFT (ms):                        3556.35   
P99 TTFT (ms):                           12671.61  
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          19.76     
Median TPOT (ms):                        21.75     
P99 TPOT (ms):                           33.41     
---------------Inter-token Latency----------------
Mean ITL (ms):                           168.08    
Median ITL (ms):                         168.46    
P99 ITL (ms):                            427.21    
==================================================

INFO 09-25 13:20:42 metrics.py:351] Avg prompt throughput: 3943.4 tokens/s, Avg generation throughput: 8317.6 tokens/s, Running: 190 reqs, Swapped: 0 reqs, Pending: 651 reqs, GPU KV cache usage: 6.7%, CPU KV cache usage: 0.0%.
INFO 09-25 13:20:47 metrics.py:351] Avg prompt throughput: 5420.4 tokens/s, Avg generation throughput: 13291.1 tokens/s, Running: 256 reqs, Swapped: 0 reqs, Pending: 227 reqs, GPU KV cache usage: 14.3%, CPU KV cache usage: 0.0%.
INFO 09-25 13:20:52 metrics.py:351] Avg prompt throughput: 3391.1 tokens/s, Avg generation throughput: 10051.0 tokens/s, Running: 131 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 11.3%, CPU KV cache usage: 0.0%.
```
### Benchmark run 2

```
============ Serving Benchmark Result ============
Successful requests:                     1000      
Benchmark duration (s):                  19.54     
Total input tokens:                      215196    
Total generated tokens:                  126461    
Request throughput (req/s):              51.17     
Output token throughput (tok/s):         6470.85   
Total Token throughput (tok/s):          17482.16  
---------------Time to First Token----------------
Mean TTFT (ms):                          4116.34   
Median TTFT (ms):                        3638.66   
P99 TTFT (ms):                           12561.80  
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          19.80     
Median TPOT (ms):                        21.98     
P99 TPOT (ms):                           32.90     
---------------Inter-token Latency----------------
Mean ITL (ms):                           168.09    
Median ITL (ms):                         164.48    
P99 ITL (ms):                            459.70    
==================================================

INFO 09-25 13:21:51 metrics.py:351] Avg prompt throughput: 7395.1 tokens/s, Avg generation throughput: 17788.9 tokens/s, Running: 255 reqs, Swapped: 0 reqs, Pending: 376 reqs, GPU KV cache usage: 10.5%, CPU KV cache usage: 0.0%.
INFO 09-25 13:21:56 metrics.py:351] Avg prompt throughput: 4870.8 tokens/s, Avg generation throughput: 11951.1 tokens/s, Running: 256 reqs, Swapped: 0 reqs, Pending: 36 reqs, GPU KV cache usage: 15.8%, CPU KV cache usage: 0.0%.
```

**Comment by afeldman-nm** [comment]
After removing the assert which prevents multi-step, chunked prefill & prefix cache from being enabled simultaneously, there is in fact an underlying incompatibility at the level of the multi-step `advance_step` CUDA code.

Server command:
```
python  -m vllm.entrypoints.openai.api_server     --model JackFram/llama-160m --swap-space 16     --disable-log-requests  --use-v2-block-manager   --tensor-parallel-size 1  --pipeline-parallel-size 1  --gpu-memory-utilization 0.90  --num-scheduler-steps 8 --enable-prefix-caching --enable-chunked-prefill --port 9001  --worker-use-ray 2>&1 | tee output.log
```

Client command:
```
python benchmarks/benchmark_serving.py  --backend vllm  --model JackFram/llama-160m  --dataset-name sharegpt     --dataset-path ../sharegpt.json --port 9001
```

Exception in `advance_step`:
```
ERROR 09-26 09:11:43 worker_base.py:464] Error executing method execute_model. This might cause deadlock in distributed execution.
ERROR 09-26 09:11:43 worker_base.py:464] Traceback (most recent call last):
ERROR 09-26 09:11:43 worker_base.py:464]   File "/home/abf149/git_clones/vllm/vllm/worker/worker_base.py", line 456, in execute_method
ERROR 09-26 09:11:43 worker_base.py:464]     return executor(*args, **kwargs)
ERROR 09-26 09:11:43 worker_base.py:464]   File "/home/abf149/git_clones/vllm/vllm/worker/worker_base.py", line 327, in execute_model
ERROR 09-26 09:11:43 worker_base.py:464]     output = self.model_runner.execute_model(
ERROR 09-26 09:11:43 worker_base.py:464]   File "/home/abf149/git_clones/vllm/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 09-26 09:11:43 worker_base.py:464]     return func(*args, **kwargs)
ERROR 09-26 09:11:43 worker_base.py:464]   File "/home/abf149/git_clones/vllm/vllm/worker/multi_step_model_runner.py", line 476, in execute_model
ERROR 09-26 09:11:43 worker_base.py:464]     model_input = self._advance_step(
ERROR 09-26 09:11:43 worker_base.py:464]   File "/home/abf149/git_clones/vllm/vllm/worker/multi_step_model_runner.py", line 601, in _advance_step
ERROR 09-26 09:11:43 worker_base.py:464]     attn_metadata.advance_step(
ERROR 09-26 09:11:43 worker_base.py:464]   File "/home/abf149/git_clones/vllm/vllm/attention/backends/flash_attn.py", line 408, in advance_step
ERROR 09-26 09:11:43 worker_base.py:464]     ops.advance_step_flashattn(num_seqs=num_seqs,
ERROR 09-26 09:11:43 worker_base.py:464]   File "/home/abf149/git_clones/vllm/vllm/_custom_ops.py", line 34, in wrapper
ERROR 09-26 09:11:43 worker_base.py:464]     return fn(*args, **kwargs)
ERROR 09-26 09:11:43 worker_base.py:464]   File "/home/abf149/git_clones/vllm/vllm/_custom_ops.py", line 202, in advance_step_flashattn
ERROR 09-26 09:11:43 worker_base.py:464]     return torch.ops._C.advance_step_flashattn(num_seqs, num_queries,
ERROR 09-26 09:11:43 worker_base.py:464]   File "/home/abf149/git_clones/vllm/venv/lib/python3.8/site-packages/torch/_ops.py", line 1061, in __call__
ERROR 09-26 09:11:43 worker_base.py:464]     return self_._op(*args, **(kwargs or {}))
ERROR 09-26 09:11:43 worker_base.py:464] RuntimeError: tensor: name = sampled_token_ids, shape = [9, 1] is_cont = 1, type = long int is not as expected: shape = [10, 1], type = Long
```

**Comment by njhill** [comment]
@afeldman-nm does this overlap with https://github.com/vllm-project/vllm/pull/8378 which was recently merged? I guess that doesn't include compatibility with prefix caching?

**Comment by afeldman-nm** [comment]
> @afeldman-nm does this overlap with https://github.com/vllm-project/vllm/pull/8378 which was recently merged? I guess that doesn't include compatibility with prefix caching?

Hi @njhill that is correct, @varun-sundar-rabindranath 's PR enables multi-step + chunked prefill but not multi-step + chunked prefill + prefix caching

**Review by comaniac — APPROVED** [review]
LGTM

**Pull request merged**
