### PR TITLE
use flash-attn via xformers

### LINKED ISSUE #485: Flash Attention V2
https://github.com/Dao-AILab/flash-attention

Flash attention v2 was released claiming 2x speedups. Making an issue to remind myself to have a look at it. And also if anyone else wants to try implement it.

### PR DESCRIPTION
**Pull request by tmm1**
fixes https://github.com/vllm-project/vllm/issues/485#issuecomment-1693821853

### CODE REVIEW

**Comment by WoosukKwon** [comment]
Hi @tmm1 thanks for letting us know the performance issue and submitting the PR.

While using FA2 might improve the performance, we have concerns in using it because it does not support 1) attention bias like ALiBi, V100 GPUs, FP32 data type, and head_size 256 (which is used for GPT-J). So, to use FA2, I believe we should make a fallback option to xformers cutlass backend.

**Comment by tmm1** [comment]
> So, to use FA2, I believe we should make a fallback option to xformers cutlass backend.

thanks @WoosukKwon, I updated the PR to allow xformers to fallback

**Comment by zhaoyang-star** [comment]
> > So, to use FA2, I believe we should make a fallback option to xformers cutlass backend.
> 
> thanks @WoosukKwon, I updated the PR to allow xformers to fallback
> 
> cc @danthe3rd

Hi @tmm1 , I am very interested in your PR. I see the PR does not allow xformers to fallback.

**Comment by danthe3rd** [comment]
Hi, xformers maintainer here
The way it's setup in this PR allows xformers to decide which backend to use - this is also what we recommend. It will use by default Flashv2 if available, but will fallback to cutlass if it's not available (eg if using a custom bias, fp32 or v100).

**Comment by zhaoyang-star** [comment]
Hi @danthe3rd , thanks for your explanation. I just wonder why `xformers.ops.memory_efficient_attention_forward` does not been used in the decoding stage? The API has used in the prefill stage in vLLM.  Hand-written kernel may have lower perf than xformers if we are not an expert of CUDA.

**Comment by danthe3rd** [comment]
At the moment, `memory_efficient_attention` is optimized the training mostly. We have a backend for inference, but it's not fully optimized for all cases, but we're working on it :)

**Comment by zhaoyang-star** [comment]
> At the moment, `memory_efficient_attention` is optimized the training mostly - which is similar to the prefilling stage in terms of problem sizes. We have a backend for next token decoding, but it's not fully optimized for all cases, but we're working on it :)

Thanks a lot. So it makes sense that most llm inference framworks has hand-written cuda kernel for fused attention impl.

**Review by zhuohan123 — APPROVED** [review]
LGTM! Thank you for your contribution!

**Comment by Lvjinhong** [comment]
For [allow xformers to pick the best available implementation](https://github.com/vllm-project/vllm/pull/877/commits/4fcdddba17348c560625be57790b3b61641a08c4), I don't quite understand this change, so how should I use flash?

**Pull request merged**
