### PR TITLE
macos / ARM support for vllm

### PR DESCRIPTION
**Pull request by pathorn**
Built on top of a rebased version of:
* #1028

# Build instructions:

Make sure to install openmp from https://mac.r-project.org/openmp/

Not using docker. Tested in miniconda3 env

## To build:
Just the .so:
```
VLLM_TARGET_DEVICE=cpu python3 setup.py build_ext
```
Build the full thing:
```
VLLM_TARGET_DEVICE=cpu python3 setup.py build
VLLM_TARGET_DEVICE=cpu python3 setup.py install
# Seems to give an error the first time.
# error: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

# I can't reproduce the error if I run it again. It does seem to run.
VLLM_TARGET_DEVICE=cpu python3 setup.py install
```

(NOTE: The .so file will not load on macos if your current working directory is the repository root. Change directory before running.)

Run the api server with
```
# Make sure you are not in the vllm repository root.
python3 -m vllm.entrypoints.openai.api_server --device cpu --enforce-eager --port 8000
```

## Testing

Tested a few prompts on Mistral-7B and verified against the output returned by DeepInfra.
```
curl http://localhost:8000/v1/completions -H 'Content-Type: application/json' -d '{"model":"mistralai/Mistral-7B-Instruct-v0.1","temperature":0.0,"stop":"side","prompt":"Why did the chicken cross the road?\n","stop":"side", "max_tokens":50}'; echo
```
Mistral 7B gets about 0.6 tokens per second on my plain Macbook M3. It's not going to be as fast as a dedicated GPU, and does not support GPTQ (such as 4bit quantization), so llama.cpp knocks this PR out of the park in terms of performance, getting around 20 TPS on the same macbook hardware.
Screenshot 2023-12-22 at 5 48 36 AM

I do also hope this PR serves as documentation for some of the new bfloat16 ARM instructions added in recent years, for example `vcvtq_high_bf16_f32(vcvtq_low_bf16_f32(a), b)` to convert between bf16 and fp32, or the implementation of fused multiply-add which took a few hours of research, due to [the `vbfmlaltq` and `vbfmlalbq` bfloat instructions](https://community.arm.com/arm-community-blogs/b/ai-and-ml-blog/posts/bfloat16-processing-for-neural-networks-on-armv8_2d00_a) (The ARM equivalent of `_mm512_dpbf16_ps` ("DPBF16PS") on AVX512 being almost completely ungooglable. I think I was a bit intrigued to be one of the first people to use these ARMv8.6-a+bf16 instructions or write about them:

```cpp
inline FP32Vec16 fma(BF16Vec32 &a, BF16Vec32 &b, FP32Vec16 &c) {
  return FP32Vec16(float32x4x4_t({
    vbfmlaltq_f32(vbfmlalbq_f32(c.reg.val[0], a.reg.val[0], b.reg.val[0]), a.reg.val[0], b.reg.val[0]),
    vbfmlaltq_f32(vbfmlalbq_f32(c.reg.val[1], a.reg.val[1], b.reg.val[1]), a.reg.val[1], b.reg.val[1]),
    vbfmlaltq_f32(vbfmlalbq_f32(c.reg.val[2], a.reg.val[2], b.reg.val[2]), a.reg.val[2], b.reg.val[2]),
    vbfmlaltq_f32(vbfmlalbq_f32(c.reg.val[3], a.reg.val[3], b.reg.val[3]), a.reg.val[3], b.reg.val[3]),
  }));
}
```

Fixes
* #1397 
* #1921 
* #176

### CODE REVIEW

**Comment by nivibilla** [comment]
Is there scope to make use of metal backend to improve performance?

**Comment by pathorn** [comment]
My original goal for this project was to spend 1 day to get something that I can use for development on macos. Using CPU vector instructions was sufficient to achieve my goal, so I will not promise to put effort into developing a metal backend.

One good thing this change does is it adds a --device command line option: in theory, it might be possible to pass `--device mps` . [PyTorch already supports the mps backend](https://pytorch.org/docs/stable/notes/mps.html), but you are going to have to figure out a plan for porting the cuda code in `csrc/` to metal.

The good news is there is now a `cpu` implementation in `csrc/` in addition to `cuda`, with a wrapper function named `_dispatch`. The dispatch function and two example implementations might make it easier to add an additional `mps` / metal implementation. But I am sorry to say that I do not have time to help with this.

**Comment by nivibilla** [comment]
Np, thanks for explaining

**Comment by sandangel** [comment]
hi @pathorn , have you looked at https://github.com/ml-explore/mlx ? I think it will give better performance running on mac without much effort and will utilize Unified Memory on Apple Silicon devices. Do you think it's not a complex task to add a wrapper for mlx and use it as a vllm backend for mac devices? I'm looking into that but my limit understanding of ML dev make it look like not an easy task for me. They have many examples here including running inference on mac. What I can do best propably using the interface from the wrapper and connect it with the OpenAI API endpoints.

**Comment by rahuja23** [comment]
Is this issue resolved and merged?

**Comment by coolcloudcol** [comment]
python3 -m vllm.entrypoints.openai.api_server --device cpu --enforce-eager --port 8000
INFO 02-26 11:09:18 api_server.py:727] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, model='facebook/opt-125m', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', device='cpu', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 02-26 11:09:18 config.py:471] float16 is not supported on CPU, casting to bfloat16.
WARNING 02-26 11:09:18 config.py:483] Casting torch.float16 to torch.bfloat16.
INFO 02-26 11:09:18 config.py:358] CPU-only mode doesn't support parallel execution currently.
INFO 02-26 11:09:18 llm_engine.py:73] Initializing an LLM engine with config: model='facebook/opt-125m', tokenizer='facebook/opt-125m', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, enforce_eager=True, seed=0)
INFO 02-26 11:09:26 llm_engine.py:223] # GPU blocks: 0, # CPU blocks: 7281
WARNING 02-26 11:09:26 api_server.py:123] No chat template provided. Chat API will not work.
INFO:     Started server process [38099]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO 02-26 11:09:31 async_llm_engine.py:379] Received request cmpl-c9ee897087764f7d935004ab10259a26: prompt: 'Why did the chicken cross the road?\n', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['side'], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=50, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: [2, 7608, 222, 5, 5884, 2116, 5, 921, 116, 50118].
INFO 02-26 11:09:31 llm_engine.py:666] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
[1]    38099 illegal hardware instruction  python3 -m vllm.entrypoints.openai.api_server --device cpu --enforce-eager
/Users/wangxiaoyun/miniconda3/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by pathorn** [comment]
Rebased onto latest vllm. Tested with OPT-175B

Still missing some ops such as `gelu_and_mul` such as used in gemma.

**Comment by pathorn** [comment]
Rebased and updated with gelu ops for Gemma.

google/gemma-2b runs pretty well on my macbook.

**Comment by BodhiHu** [comment]
The mlc-llm/tvm is perhaps more suited for this. Tested on M1 with really good performance.

**Comment by AmeerHajAli** [comment]
Looking forward to seeing this in upstream :-)

**Comment by youkaichao** [comment]
I'm going to close this PR.

Right now we can build vllm on macos, with a workaround: https://docs.vllm.ai/en/latest/getting_started/arm-installation.html 

You need to use docker, and repurpose the vllm's cpu backend.

We welcome contribution to improve the experience, so that `pip install -e .` directly works for macos.

**Comment by sammcj** [comment]
@youkaichao does that use metal acceleration with the CPU/APU though?

**Comment by youkaichao** [comment]
no metal acceleration, only use the cpu for computation.

**Pull request closed without merging**
