### PR TITLE
[build][misc] limit numpy version

### PR DESCRIPTION
**Pull request by youkaichao**
numpy 2.0 is just officially released. it has many breaking changes, as observed in https://buildkite.com/vllm/ci-aws/builds/1631#019022aa-6e00-4979-970c-20c73d4396d9 .

### CODE REVIEW

**Comment by youkaichao** [comment]
also reported in https://github.com/outlines-dev/outlines/issues/976 .

**Review by WoosukKwon — APPROVED** [review]
Should we make a new release?

**Comment by WoosukKwon** [comment]
To be clear, Numpy 2.0 does not break PyTorch (CUDA) itself, but affects other libraries such as Outlines and Tensorizer. This is critical for us because vLLM currently always imports outlines for the OpenAI server.

**Comment by youkaichao** [comment]
> Should we make a new release?

cc @simon-mo 

several previous versions of `vllm` cannot be installed via `pip install vllm` out-of-the-box now, because we don't specify the `numpy` version :(

**Comment by WoosukKwon** [comment]
> several previous versions of vllm cannot be installed via pip install vllm out-of-the-box now, because we don't specify the numpy version :(

@youkaichao I think they will actually work if Outlines update their dependency.

**Comment by youkaichao** [comment]
> I think they will actually work if Outlines update their dependency.

you are right. let's see when `Outlines` will do it.

**Comment by WoosukKwon** [comment]
Also, in principle, I think the Numpy version should be fixed in those libraries affected, not by us. Since we do not use any advanced features in Numpy, we are not responsible for this. We should revert this change in the future.

**Pull request merged**
