### PR TITLE
[CI/Build] replace yapf with ruff

### PR DESCRIPTION
**Pull request by dtrifiro**
`ruff` also has a [formatter](https://docs.astral.sh/ruff/formatter/) which is `isort` and `black` compatible (not compatible with yapf unfortunately), but is also much faster.

Unfortunately, using `ruff` as formatter this results in a pretty large diff:

```
504 files would be reformatted, 75 files already formatted
504 files changed, 35007 insertions(+), 23512 deletions(-)
```

### CODE REVIEW

**Comment by DarkLight1337** [comment]
You are not the first one to think of this. Also see #1688. How should we go about migrating this?

**Comment by dtrifiro** [comment]
>You are not the first one to think of this (https://github.com/vllm-project/vllm/pull/1688). How should we go about migrating the formatter?

@DarkLight1337 Thanks, I did not see that PR.

Migrating to `ruff format` could be done gradually using [pre-commit](https://github.com/pre-commit/pre-commit): this can only run on the modified files (e.g. compared to main), so it will not change all of the codebase at once. It will still be annoying at times (e.g. small changes in large files will have a lot of unneeded formatting changes), but it will make it possible to gradually migrate.

I can propose a patch, if you think it's worth it, although there still will be some annoyances during the transition period.

**Comment by simon-mo** [comment]
IMO, we are unfortunately kind of too late to do this kind of change. Not only there are hundreds of PR opened, there are as many in development branches, as well as several high profile public or private forks of the project. Additionally, while yapf is fairly outdated and I'm not the biggest fan of its style, the speed of yapf formatting has improved a lot and become tolerable.

**Comment by dtrifiro** [comment]
Although I reckon `pre-commit` is not that different than the [format.sh](https://github.com/opendatahub-io/vllm/tree/main/format.sh) script

**Comment by zhuohan123** [comment]
> IMO, we are unfortunately kind of too late to do this kind of change. Not only there are hundreds of PR opened, there are as many in development branches, as well as several high profile public or private forks of the project. Additionally, while yapf is fairly outdated and I'm not the biggest fan of its style, the speed of yapf formatting has improved a lot and become tolerable.

Probably our next chance is Christmas later this year 🥲

**Pull request closed without merging**
