### PR TITLE
[core][distributed] fix custom allreduce in pytorch 2.5

### LINKED ISSUE #9774: [Bug]: [help wanted] MoE + TP + custom allreduce bug
### Your current environment

main branch, H100

### Model Input Dumps

_No response_

### 🐛 Describe the bug

when I try this simple command `vllm serve allenai/OLMoE-1B-7B-0924 -tp 2` on the main branch, it hits an error:

`Failed: Cuda error /workspace/csrc/custom_all_reduce.cuh:336 'invalid argument'`

removing `-tp` works, and disabling custom allreduce also works.

not sure what's happening. if anyone is familiar with the moe code, please help.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by youkaichao**
fixes https://github.com/vllm-project/vllm/issues/9774

pytorch changes the binary format of the ipc handle.

### CODE REVIEW

**Comment by youkaichao** [comment]
cc @hanzhi713 

can you please improve the code if you have time? ideally we should use pytorch's user-facing api, rather than this private api.

example of user-facing api:

```python
# producer:

import torch
from torch.multiprocessing.reductions import reduce_tensor

inp = torch.randn(5, 5).cuda()

out = reduce_tensor(inp)

# send `out` to consumer

# consumer

func = out[0]
tensor = func(*out[1])
```

this way, we won't suffer from too many pytorch internal details.

and once we share the tensor from python side, c++ side code will be much simpler.

**Comment by cedonley** [comment]
FYI - can confirm this fixes the issue with TP=2 on NVLink A6000's that was introduced with the upgrade to pytorch 2.5. Nice catch on the handle format change. I thought I was going crazy, but hadn't noticed the 2-byte change in length of the handle itself when I compared the data doing into the ipc functions in the two versions.

**Comment by youkaichao** [comment]
@cedonley thanks for your report and investigation!

**Comment by hanzhi713** [comment]
@youkaichao There're no user facing API for getting a shareable handle. To avoid using internal Pytorch API, I think we can just call `cudaIpcGetMemHandle` directly on pytorch allocated tensors like here 

https://github.com/vllm-project/vllm/blob/04a3ae0acae3d522299ec90b5730f876daa845e6/csrc/custom_all_reduce.cuh#L359

The downside would be that we will lose pytorch's safeguards against leaks, but I think that might not be a problem since allocations in custom allreduce are one-time allocations.

**Comment by hanzhi713** [comment]
I will have some time this weekend to work on this.

**Comment by youkaichao** [comment]
do you really need a handle?

we can get an ipc-shared tensor directly:

```python
# producer:

import torch
from torch.multiprocessing.reductions import reduce_tensor

inp = torch.randn(5, 5).cuda()

out = reduce_tensor(inp)

# send `out` to consumer

# consumer

func = out[0]
tensor = func(*out[1])
```

**Comment by youkaichao** [comment]
@hanzhi713 welcome to join our new slack https://slack.vllm.ai for chatting and collaborating!

**Comment by hanzhi713** [comment]
How do you share such a handle to other processes? I think vllm still runs one process per GPU right?

**Comment by youkaichao** [comment]
> Is it just sending pickled data through torch.distributed?

yes. 

> IMHO torch.multiprocessing is designed for sharing handles through multiprocessing.Process

it applies to general processes, no matter how the process is launched.

**Pull request merged**
