### PR TITLE
[distributed][kernel]support tensor-parallelism in bitsandbytes quant…

### PR DESCRIPTION
**Pull request by chenqianfzh**
This PR provides tensor parallelism to bitsandbytes quantization, which was added to vLLM in https://github.com/vllm-project/vllm/pull/4776.

### CODE REVIEW

**Comment by chenqianfzh** [comment]
@mgoin @Yard1 

This is the continuing effort on QLoRA/BitsAndBytes from PR https://github.com/vllm-project/vllm/pull/4776, which was approved by you. Wonder whether you can take a look at your convenience?

**Comment by mgoin** [comment]
Thanks @chenqianfzh, could you take a look at some of the current issues with bnb before continuing with additional features? https://github.com/vllm-project/vllm/issues/5569

**Comment by chenqianfzh** [comment]
> Thanks @chenqianfzh, could you take a look at some of the current issues with bnb before continuing with additional features? #5569

sure, looking  now.

**Comment by mgoin** [comment]
Happy to review if you want to revive this work!

**Comment by chenqianfzh** [comment]
yeah, I will continue this work once [the PR ](https://github.com/vllm-project/vllm/pull/7445) is done

**Pull request closed without merging**
