### PR TITLE
Fix verify tokens with the correct bonus token

### PR DESCRIPTION
**Pull request by jiqing-feng**
The real bonus token should be the first unmatched token. For example, the `draft_token_ids` is `[1, 2, 3, 5, 7]`, and the `target_token_ids` is `[1, 2, 3, 4, 6, 8]`. Then, the matched token should be `[1, 2, 3]`, and the bonus token should be `[4]` because the target model will output `[4]` based on the input `[1, 2, 3]` in the next round generation. So we can select the bonus token `[4]` in this round without any precision regression.

It will increase the performance from 89 tokens/s to 110 tokens/s in `typical_acceptance_sampler` in A100 single card with (num_speculative_tokens=2, max_num_seqs=1, model="meta-llama/Llama-2-7b-chat-hf", speculative_model="Felladrin/Llama-68M-Chat-v1"). The outputs are exactly the same before and after my changes.

Do you mind review this PR? @cadedaniel 
cc @LiuXiaoxuanPKU

### CODE REVIEW

**Comment by LiuXiaoxuanPKU** [comment]
After second thoughts, I feel this is a good optimization. We can actually skip rejection sampling in the greedy decoding case.

**Comment by yao-matrix** [comment]
> After second thoughts, I feel this is a good optimization. We can actually skip rejection sampling in the greedy decoding case, which explains the speedup you get. I also suggestion trying the flashinfer [backend](https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.1.6) and you should also see good speedup.

Thx Xiaoxuan, so do you think this optimization idea is qualified to merge to vllm. We treat this as a platform independent optimization(orthogonal w/ backend optimizations like flashinfer), which can benefit other device backends like CPU/XPU, and we see similar performance issue.

**Comment by jiqing-feng** [comment]
This change is to align the verify token function to the transformers [speculative sampling algorithm](https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L4187-L4209), it always selectes the next sample token from the target model.

**Comment by LiuXiaoxuanPKU** [comment]
> This change is to align the verify token function to the transformers [speculative sampling algorithm](https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L4187-L4209), it always selectes the next sample token from the target model.

From reading the code, it seems it adjusts the distribution and resamples (line 4195 - 4203)?

**Comment by LiuXiaoxuanPKU** [comment]
> > After second thoughts, I feel this is a good optimization. We can actually skip rejection sampling in the greedy decoding case, which explains the speedup you get. I also suggestion trying the flashinfer [backend](https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.1.6) and you should also see good speedup.
> 
> Thx Xiaoxuan, so do you think this optimization idea is qualified to merge to vllm. We treat this as a platform independent optimization(orthogonal w/ backend optimizations like flashinfer), which can benefit other device backends like CPU/XPU, and we see similar performance issue.

Could you double check the correctness here? If the optimization can pass the rejection sampling tests, yeah happy to review and get it in.

**Comment by jiqing-feng** [comment]
> From reading the code, it seems it adjusts the distribution and resamples (line 4195 - 4203)?

Yes, but the point is the output will always contain the first unmatched token (which is the next sample token from the target model).


> Could you double check the correctness here? If the optimization can pass the rejection sampling tests, yeah happy to review and get it in.

The error comes from sampling. We can not guarantee the output will be all matched even if the target model is the same as the draft model because sampling will introduce random factors. So I disabled sampling by setting `temperature=False` so we can make sure all tokens will be matched.

**Comment by comaniac** [comment]
> The error comes from sampling. We can not guarantee the output will be all matched even if the target model is the same as the draft model because sampling will introduce random factors. So I disabled sampling by setting `temperature=0` so we can make sure all tokens will be matched.

This is the intention because you cannot force users to set temperature=0. That's why @LiuXiaoxuanPKU suggested we could bypass rejected sampling when temperature=0, but we cannot remove rejected sampling.

**Comment by jiqing-feng** [comment]
> This is the intention because you cannot force users to set temperature=0. That's why @LiuXiaoxuanPKU suggested we could bypass rejected sampling when temperature=0, but we cannot remove rejected sampling.

We cannot expect the output length of speculative decoding if sampling is applied, it could be in `[1, num_speculative_tokens]`. How about changing the test to verify the output token number in a reasonable interval instead of finishing after 2 steps?

**Comment by jiqing-feng** [comment]
OK, I removed `temperature=0` but changed the `max_tokens` and `num_speculative_tokens` to avoid tests failed by sampling. Please let me know your opinion about this test.

**Comment by LiuXiaoxuanPKU** [comment]
I'm confused. It seems this PR removes rejection sampling. Then how do you do speculative decoding with temperature != 0?

**Comment by jiqing-feng** [comment]
> I'm confused. It seems this PR removes rejection sampling. Then how do you do speculative decoding with temperature != 0?

I didn't remove rejection sampling, just removed recovered_token since it is not needed. The newly defined bonus_token covers the recovered_token case. Besides, I kept the temperature in default value in the test.

**Comment by LiuXiaoxuanPKU** [comment]
The recovered token should not be from the target token ids if temperature != 0. It should be sampled from a new distribution. Correct me if I misunderstand anything.

**Comment by jiqing-feng** [comment]
> The recovered token should not be from the target token ids if temperature != 0. It should be sampled from a new distribution. Correct me if I misunderstand anything.

I see your point, the `recovered_token` is selected from a new distribution, but I just select it from target_token which is more convenient and also makes sense. Please let me know if you want me to revert it to keep the original `recovered_token`, thanks.

**Comment by yao-matrix** [comment]
> > The recovered token should not be from the target token ids if temperature != 0. It should be sampled from a new distribution. Correct me if I misunderstand anything.
> 
> I see your point, the `recovered_token` is selected from a new distribution, but I just select it from target_token. It is more convenient and also makes sense.
> 
> I know adjusting the distribution of `target_prob` is from the original paper, but I didn't see any advantages compared to just selecting from `target_token_ids`, and it also introduces a customized multinomial function and some overheads.
> 
> Please let me know if you want me to revert it to keep the original `recovered_token` from the adjusted target probs, thanks.

I don't think change original paper algorithm is a good idea without data proving, and I don't think change behavior is the target of this PR. This PR's target is performance optimization. @jiqing-feng, pls only optimize performance for temperature == 0, and don't change the logic of others.
You can submit another PR or issue if you wanna discuss it, keeping the PR only for one thing is better for cognition burden and make things move fast forward.

**Comment by jiqing-feng** [comment]
> The recovered token should not be from the target token ids if temperature != 0. It should be sampled from a new distribution. Correct me if I misunderstand anything.

Yes, you were right. I have fixed the recovered token and selected it from the new distribution (torch.clamp(target_prob-draft_prob), min=0). Please take a review. Thx.

**Comment by jiqing-feng** [comment]
Hi @LiuXiaoxuanPKU . I checked the rejection sampler codes in detail and found there is no need to change it because you can get the correct recovered token ids.  Only 2 things:
1. The [_multinomial](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/rejection_sampler.py#L408) function just selects the tokens with the largest probability which is different with torch.multinomial
2. The recovered token ids can not exist with bonus token ids at the same case because it can only return 1 token from Mp
image

I am okay with the 2 little differences btw vllm and the original paper because I cannot get speed-up on rejection sampling with this PR, but it could get significant speed-up on typical acceptance sampler. So I opened another PR to only change typical acceptance sampler, see #8562 . Please take a review, thx.

**Pull request closed without merging**
