### PR TITLE
[Tests] Add block manager and scheduler tests

### PR DESCRIPTION
**Pull request by rkooo567**
This upstream unit tests inside Anyscale that test block manager and scheduler. Several new features that will be upstreamed will update this file (e.g., chunked prefill).

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @simon-mo

**Comment by rkooo567** [comment]
This PR is ready to be reviewed.

**Comment by zhuohan123** [comment]
Will this PR conflict with #2762?

**Comment by rkooo567** [comment]
@zhuohan123 does it change the behavior of scheduler and block manager? I can merge the latest master

**Comment by rkooo567** [comment]
Seems to still pass tests after merging the latest master!

**Review by Yard1 — APPROVED** [review]

**Pull request merged**
