### PR TITLE
[Bugfix][Hardware] Fix model input for decode

### PR DESCRIPTION
**Pull request by yma11**
CPU backend is fixed by #9044 , but I think we can make below changes so that no more fix needed for other backends. Verified on XPU backend.

@LiuXiaoxuanPKU

### CODE REVIEW

**Comment by DarkLight1337** [comment]
I prefer fixing the issue on each model runner as IMO passing an empty list instead of `None` is semantically wrong.

**Comment by DarkLight1337** [comment]
Not sure what others think?

**Comment by jikunshang** [comment]
I think this will break multi step features(which num_seqs should be num_steps).
I have a fix here  https://github.com/vllm-project/vllm/pull/9145

**Comment by njhill** [comment]
@DarkLight1337 I agree, it’s potentially more misleading otherwise.

**Comment by yma11** [comment]
Thanks for everyone's comments. Sorry for not familiar with other path calls about this variable. Let me close it.

**Pull request closed without merging**
