### PR TITLE
[ci][gh200] dockerfile clean up

### PR DESCRIPTION
**Pull request by youkaichao**
built upon https://github.com/vllm-project/vllm/pull/11302 , check it out with another branch in the upstream repo so that we can test it before merging.

### CODE REVIEW

**Comment by youkaichao** [comment]
thanks for the great work from @cennn 

and also cc @drikster80 FYI , we decided to treat GH200 build a use case of "use existing torch", instead of hardcode the platform in requirements.txt .

**Comment by youkaichao** [comment]
the build is successful at https://buildkite.com/vllm/ci/builds/10942#0193e181-8519-48fc-857d-8ac350833690

**Comment by cennn** [comment]
look good to me!

**Review by cennn — APPROVED** [review]
LGTM

**Review by cennn — APPROVED** [review]
approved

**Pull request merged**
