### PR TITLE
[Core] Avoid metrics log noise when idle

### PR DESCRIPTION
**Pull request by russellb**
1a789ae7 [Core] Avoid metrics log noise when idle

commit 1a789ae76695bca801b55c9d4531e5438a3378c4
Author: Russell Bryant <rbryant@redhat.com>
Date:   Thu Sep 26 20:56:41 2024 +0000

    [Core] Avoid metrics log noise when idle
    
    Prior to this change, there was always a log message every 10 seconds,
    even when the system is idle. The noise when the metrics are all zeros
    doesn't seem very interesting, so this change makes it so the log
    message is only emitted while active. It will log a message whenever
    metrics are non-zero, or when returning to idle from non-idle.
    Repeated messages during idle now go to DEBUG instead of INFO.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Comment by vrdn-23** [comment]
@russellb I think this is a great small QoL improvement. Is this still something get worked on?

**Comment by russellb** [comment]
> @russellb I think this is a great small QoL improvement. Is this still something get worked on?

It's ready for review when someone has time.

**Review by stmcginnis — APPROVED** [review]
This would be great to have!

**Comment by vrdn-23** [comment]
@simon-mo @mgoin Is this something we can merge before the next release?

**Review by mgoin — COMMENTED** [review]
I personally like keeping the log as a sort of "heartbeat" to let me know the server is functioning fine even if there is nothing running. So I'm okay with this but would like another committer who feels more strongly about this as an improvement

**Comment by russellb** [comment]
> > I personally like keeping the log as a sort of "heartbeat" to let me know the server is functioning fine even if there is nothing running
> 
> I think the functionality of `/health` endpoint should be what indicates this rather than a log message showing idle numbers.

A compromise could be to emit them as DEBUG instead of INFO once the system goes idle.

**Comment by vrdn-23** [comment]
> A compromise could be to emit them as DEBUG instead of INFO once the system goes idle.

That sounds like a valid solution to me. Should also enable users who would prefer to have the logs enable it. Thoughts @mgoin ?

**Comment by russellb** [comment]
> > A compromise could be to emit them as DEBUG instead of INFO once the system goes idle.
> 
> That sounds like a valid solution to me. Should also enable users who would prefer to have the logs enable it. Thoughts @mgoin ?

I updated the PR to do this.

**Comment by vrdn-23** [comment]
@mgoin can we go ahead with this approach?

**Review by mgoin — APPROVED** [review]
Yeah let's go with this, thanks!

**Comment by comaniac** [comment]
Just to check, do we have other DEBUG logging? Like if I enabled DEBUG would I see lots of other logs and even slow the performance?

**Comment by russellb** [comment]
> Just to check, do we have other DEBUG logging? Like if I enabled DEBUG would I see lots of other logs and even slow the performance?

It looks like `logger.debug()` is called in 120 places right now. 

```
$ git grep 'logger.debug(' | wc -l
120
```

On an idle system, I get all of this every 10 seconds (`vllm serve <model> --tensor-parallel-size 4`):

```
DEBUG 11-19 16:29:44 client.py:186] Waiting for output from MQLLMEngine.
DEBUG 11-19 16:29:44 client.py:186] Waiting for output from MQLLMEngine.
DEBUG 11-19 16:29:44 client.py:186] Waiting for output from MQLLMEngine.
DEBUG 11-19 16:29:44 client.py:186] Waiting for output from MQLLMEngine.
DEBUG 11-19 16:29:44 client.py:186] Waiting for output from MQLLMEngine.
DEBUG 11-19 16:29:44 client.py:186] Waiting for output from MQLLMEngine.
DEBUG 11-19 16:29:44 client.py:186] Waiting for output from MQLLMEngine.
DEBUG 11-19 16:29:44 client.py:186] Waiting for output from MQLLMEngine.
DEBUG 11-19 16:29:44 client.py:186] Waiting for output from MQLLMEngine.
DEBUG 11-19 16:29:44 client.py:186] Waiting for output from MQLLMEngine.
DEBUG 11-19 16:29:51 client.py:165] Heartbeat successful.
INFO 11-19 16:29:51 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
DEBUG 11-19 16:29:51 client.py:165] Heartbeat successful.
DEBUG 11-19 16:29:51 engine.py:190] Waiting for new requests in engine loop.
```

When I hit the openai API server with a simple generate request, I got zero additional debug messages (just a few INFO messages).

**Comment by comaniac** [comment]
Thanks for the confirmation. From the log it seems not necessary to keep the message even in DEBUG level, because this level already has heartbeat logs. But I'll just leave this comment for reference and won't block the PR for merging.

**Comment by stmcginnis** [comment]
> My main thing was that I think the default production config should have a quiet log when idle.

I would like to second this. I have several instances running with log shipping to a central place, and it is causing a lot of useless log messages to be collected. If we can reduce at least some of the noise, that would be ideal.

**Comment by vrdn-23** [comment]
@russellb I realize this might not matter in the grand scheme of things going on, but is this something we can also implement in the V1 engine logs?

**Comment by russellb** [comment]
> @russellb I realize this might not matter in the grand scheme of things going on, but is this something we can also implement in the V1 engine logs?

Yeah, I'd personally like it in V1, as well. I just haven't prioritized it, yet. Feel free to port it over if you're interested!

**Comment by russellb** [comment]
a port of these changes to V1: https://github.com/vllm-project/vllm/pull/16735

**Pull request merged**
