### PR TITLE
Heterogeneous Speculative Decoding (CPU + GPU)

### PR DESCRIPTION
**Pull request by jiqing-feng**
This PR enables heterogeneous speculative decoding by the parameter `cpu_draft_worker`

To make it happen, some changes need to be reviewed:
1. compile CPU ops in cuda backend.
2. tensor-driven dispatch for custom_ops

### CODE REVIEW

**Comment by jiqing-feng** [comment]
Hi @cadedaniel. This PR extended the usage of speculative decoding, which enables the draft models to run on the CPU. I only replaced the proposal worker with CPUWorker. However, the performance is not acceptable because the draft model in the CPU is slow.

I'd like to know if we could do it with an async method, which means the CPU and CUDA can run at the same time. The process can be: CPU run 1st req -> async CUDA run 1st req -> CPU run 2nd req -> await CUDA finish 1st req -> CUDA run 2nd req -> CPU run 1st req ......


It could be exciting and maybe the most benefit of heterogenous speculative decoding. 

I was looking for some instructions like how to run 2 requests at the same time and if it is possible to use the [async llm engine](https://github.com/vllm-project/vllm/blob/main/vllm/engine/async_llm_engine.py#L210)?

Thx!

cc @LiuXiaoxuanPKU

**Comment by cadedaniel** [comment]
It's challenging to do this because even if you get async draft model, it won't have the latest accepted tokens from the target model during drafting. Probably means need a faster proposal method on CPU, like a high quality ngram model.

**Comment by jiqing-feng** [comment]
Hi @cadedaniel . I think this PR should be ready to be reviewed since issue #6285 has been fixed. Do you mind reviewing it? Thx!

**Comment by jiqing-feng** [comment]
> Hi @cadedaniel . I think this PR should be ready to be reviewed since issue #6285 has been fixed. Do you mind reviewing it? Thx!
> 
> The main problem is that I compile both CPU and GPU ops, so we need to figure out a way if users want to only run on CPU, would like to hear your advice :)

Once we figure out a solution for this issue, I could update the Cmake file to pass the tests.

**Comment by cadedaniel** [comment]
Hello @jiqing-feng . I can review the PR if you can show a performance benefit in some configuration that users will benefit from. Can you demonstrate a performance improvement and the configuration used with this PR? See below for the current performance improvement on GPU models.

Thanks.

Cade

image

**Comment by jiqing-feng** [comment]
> Hello @jiqing-feng . I can review the PR if you can show a performance benefit in some configuration that users will benefit from. Can you demonstrate a performance improvement and the configuration used with this PR? See below for the current performance improvement on GPU models.
> 
> Thanks.
> 
> Cade
> 
> image

Sure! I am preparing the benchmark script and environments. I cannot run too big models such as 70B because I have limited computation results. The llama-7b + llama-68m will be my choice.

The performance data will be posted here once it's finished, thx!

**Comment by jiqing-feng** [comment]
Hi @cadedaniel 

I tested this PR with llama-7b + llama-68m in 1 SPR(Intel 4th gen Xeon) with a Nvidia 4090 card. The result is:
greedy: 59 tokens/s
num_tokens = 1: 64 tokens/s
num_tokens = 2: 64 tokens/s
num_tokens = 3: 60 tokens/s
num_tokens = 4: 60 tokens/s

I initialize the llm by
```python
llm = LLM(
            model=model,
            dtype=torch.float16,
            speculative_model=assistant_model, # The draft model. Must have same vocabulary as target model.
            tensor_parallel_size=1,
            num_speculative_tokens=2 if assistant_model else None, # The number of speculative tokens to score.
            use_v2_block_manager=True if assistant_model else None,
            max_num_seqs=args.max_num_seqs,
            enforce_eager=True,
            cpu_draft_worker=True if assistant_model else None,
        )
```

I only tested `max_num_seqs=1`, do you think it is enough? If not, please let me know how to test and how to set the QPS as in your chart. Thx!

**Comment by cadedaniel** [comment]
I feel the improvements are too marginal to support this proposer unfortunately.

**Comment by cadedaniel** [comment]
Is there a faster cpu model you can try?

**Comment by jiqing-feng** [comment]
> Is there a faster cpu model you can try? may also be worth trying 70B base model since the cost ratio is larger

Hi @cadedaniel . I can't find a faster CPU model, but I got a faster CPU which is EMR (Intel 5th Gen Xeon). The performance is as follows:
baseline: 63.5 tokens/s
num_speculative_tokens= 1: 78.3 tokens/s
num_speculative_tokens= 2: 78.5 tokens/s
num_speculative_tokens= 3: 78.5 tokens/s
num_speculative_tokens= 4: 81.5 tokens/s
num_speculative_tokens= 5: 73.8 tokens/s

Do you think it is acceptable?

**Comment by cadedaniel** [comment]
What QPS is this benchmark running?

**Comment by jiqing-feng** [comment]
> What QPS is this benchmark running? Note my graph shows various QPS and how the speedup reduces over time.

I only test offline with some samples selected from [wikipedia](https://huggingface.co/datasets/wikimedia/wikipedia) and set `max_num_seqs=1`. Do you have any guides for testing QPS? Thx!

**Comment by jiqing-feng** [comment]
Hi @cadedaniel . Do you mind starting to review this PR? I have cleaned all the tests except the AMD failed tests. There are still 2 issues that need your help:
1. Why AMD tests failed and how to reproduce to debug it?
2. Where and what kind of tests I should add?

**Comment by jiqing-feng** [comment]
Hi @cadedaniel . This PR is ready to be reviewed, I have cleaned all tests and added an end-to-end test for this feature. Please let me know your opinion. Thx!

**Comment by jiqing-feng** [comment]
Performance offline
image

**Comment by jiqing-feng** [comment]
Hi @LiuXiaoxuanPKU . There are still 3 failed tests, and they seem not related to my changes:
1.  AMD kernel tests FAILED kernels/test_awq.py::test_awq_dequantize_opcheck - AttributeError: '_OpNamespace' '_C' object has no attribute 'awq_dequantize'
2. LoRA Long Context FAILED lora/test_long_context.py::test_batched_rope_kernel - IndexError: list index out of range
3. AMD: Entrypoints Test ERROR entrypoints/openai/test_lora_lineage.py::test_check_lora_lineage - RuntimeError: Server exited unexpectedly. Due to connection error.

**Comment by simon-mo** [comment]
Hi @jiqing-feng, 

Thank you for sending this PR and demonstrating its performance. I have the following feedback:
* We are not comfortable with the changes to the build process, vllm/_custom_ops.py, and Dockerfile. If this feature is merge, it should be an optional feature. Currently, this is requiring the common code path to understand and check whether it is running on CPU or GPU. 
* One potential way I can see this merged:
  * A CPUDraftWorker that utilizes Triton or Torch Compile 
  * Demonstrate better speedup compare to the GPU based draft model. The baseline should not be without acceleration, rather, it should compare against GPU worker. 
  * Overall, the changes should be clean and not intrusive.

**Comment by jiqing-feng** [comment]
Hi @simon-mo , thanks for your review. Is it okay to add a flag that controls cpu building in Cuda backend? For example, we can set an env variable `export _CPU_CUDA=1`, and we will add `include(${CMAKE_CURRENT_LIST_DIR}/cmake/cpu_extension.cmake)` only if we detected `_CPU_CUDA=1` in CMakeLists.txt. The same in `custom_ops.py`, we will patch ops by input device only when `_C_cpu` is found.

**Comment by jiqing-feng** [comment]
Currently, the main block changes are not strictly related to speculative decoding, so we can focus on if we can build cpu ops in cuda backend vllm.  We can discuss it here #9224

**Comment by jiqing-feng** [comment]
I opened a new PR for the native path cpu draft model, see #9266 . In that case, we don't need to change anything in the build process.

**Pull request closed without merging**
