### PR TITLE
[Misc] Bump up transformers to v4.39.0 & Remove StarCoder2Config

### PR DESCRIPTION
**Pull request by WoosukKwon**
This PR bump up the transformers version to v4.39.0. Thanks to the version up, we can delete `StarCoder2Config`.

### CODE REVIEW

**Review by ywang96 — APPROVED** [review]
LGTM! I went through the release log and don't seem to find any breaking changes  related to our `transformers` usage from upgrading it to 4.39.

**Comment by WoosukKwon** [comment]
@ywang96 Thanks for the quick review!

**Review by esmeetu — APPROVED** [review]

**Comment by esmeetu** [comment]
@WoosukKwon I have addressed conflicts that related to the Jais model.

**Comment by WoosukKwon** [comment]
@esmeetu Thanks for fixing the merge error! I actually added him as a co-author in the commit message 😅 . That's why I disabled and re-enabled auto-merge.

**Comment by WoosukKwon** [comment]
Oh it was in the commit message for the scheduled squash merge, so wasn’t visible.

**Comment by bufferoverflow** [comment]
There is a patch release out, see https://github.com/huggingface/transformers/releases/tag/v4.39.1 maybe bump to this already?

**Comment by ywang96** [comment]
> There is a patch release out, see https://github.com/huggingface/transformers/releases/tag/v4.39.1 maybe bump to this already?

@bufferoverflow Thank you for bringing this up! Yes we were aware of this patch (In fact `4.39.0` was breaking https://github.com/vllm-project/vllm/pull/3042 so we had to raise an issue on `transformers` because of it https://github.com/huggingface/transformers/issues/29789)

@WoosukKwon What's your opinion on explicitly requiring `transformers >= 4.39.1`?

**Comment by WoosukKwon** [comment]
We should do it. Could you submit a PR? Otherwise I will do it tmr.

**Pull request merged**
