### PR TITLE
added support for quantize on LLM module

### PR DESCRIPTION
**Pull request by orellavie1212**

### CODE REVIEW

**Comment by orellavie1212** [comment]
fixing the problem arise via init (even if kwargs mentioned)
engine_args = EngineArgs(
TypeError: __init__() got an unexpected keyword argument 'quantization'

**Comment by WoosukKwon** [comment]
@orellavie1212 Thanks for the PR.

> fixing the problem arise via init (even if kwargs mentioned)
engine_args = EngineArgs(
TypeError: init() got an unexpected keyword argument 'quantization'

Could you explain the problem in more detail? While I'm good with adding the quantization parameter to the `LLM` class for clarity, I believe it should already work. I've checked that `llm = LLM(model="casperhansen/vicuna-7b-v1.5-awq", quantization="awq")` just works.

**Comment by orellavie1212** [comment]
I did exactly as you mentioned, I thought too, on python 3.9 (aws sagemaker) it doesn't work and quantize param didn't work, only after I made the change, it worked.
It could depend on the python version or other configuration, but to make it robust you could merge

**Review by WoosukKwon — APPROVED** [review]
@orellavie1212 LGTM! I made minor changes on the docstring. Thanks again for submitting the PR.

**Pull request merged**
