### PR TITLE
[Misc] typo find in sampling_metadata.py

### PR DESCRIPTION
**Pull request by noooop**
https://github.com/vllm-project/vllm/pull/5639

Forgot to copy

```
sampling_params = seq_group.sampling_params
```

Sampling part is too complicated, can anyone refactor it?

### CODE REVIEW

**Review by DarkLight1337 — APPROVED** [review]
Looks reasonable, thanks for fixing!

**Comment by youkaichao** [comment]
I think lots of sequence group related code can be deleted now, after https://github.com/vllm-project/vllm/pull/9302 . but I don't have bandwidth recently.

**Comment by noooop** [comment]
> I think lots of sequence group related code can be deleted now, after #9302 . but I don't have bandwidth recently.

I am carefully deleting the sequence group step by step in my project. It is really a headache.

**Comment by youkaichao** [comment]
@noooop can you join vllm slack? we can discuss it to plan how to remove it. the url for vllm slack is https://slack.vllm.ai .

**Pull request merged**
