### PR TITLE
[Bugfix]Fix Phi-3 BNB online quantization   

### LINKED ISSUE #9937: [Bug]: Phi-3 cannot be used with bitsandbytes
### Your current environment

vllm version `0.6.3.post1`

### Model Input Dumps

_No response_

### 🐛 Describe the bug

here is the testing script:
```python
llm = LLM(model= llm_name, dtype='float16',
            tensor_parallel_size=4, gpu_memory_utilization= 0.96, #seed=None,
            trust_remote_code=True,
            quantization="bitsandbytes", load_format="bitsandbytes", enforce_eager=True, 
            enable_lora=False,
            cpu_offload_gb = 48
            #tokenizer_mode= "mistral" if args.llm_name.startswith('mistralai') else 'auto'
        ) 
```

when `llm_name` is `microsoft/Phi-3.5-mini-instruct`, or `microsoft/Phi-3-mini-128k-instruct` or other models under the same series, inference causes error `[rank0]: KeyError: 'layers.21.mlp.gate_up_proj.weight'`

full error message:

> INFO 11-01 17:09:41 model_runner.py:1056] Starting to load model microsoft/Phi-3-mini-128k-instruct...
> INFO 11-01 17:09:41 selector.py:224] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
> INFO 11-01 17:09:41 selector.py:115] Using XFormers backend.
> INFO 11-01 17:09:42 loader.py:1051] Loading weights with BitsAndBytes quantization.  May take a while ...
> INFO 11-01 17:09:42 weight_utils.py:243] Using model weights format ['*.safetensors']
> model-00002-of-00002.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.67G/2.67G [08:06<00:00, 5.49MB/s]
> model-00001-of-00002.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.97G/4.97G [11:17<00:00, 7.34MB/s]
> Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/home/yanan/test_vllm.py", line 11, in <module>
> [rank0]:     llm = LLM(model= args.llm_name, dtype='half',# max_model_len= 4096, 
> [rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 177, in __init__
> [rank0]:     self.llm_engine = LLMEngine.from_engine_args(
> [rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 573, in from_engine_args
> [rank0]:     engine = cls(
> [rank0]:              ^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 334, in __init__
> [rank0]:     self.model_executor = executor_class(
> [rank0]:                           ^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 47, in __init__
> [rank0]:     self._init_executor()
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
> [rank0]:     self.driver_worker.load_model()
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/worker/worker.py", line 183, in load_model
> [rank0]:     self.model_runner.load_model()
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1058, in load_model
> [rank0]:     self.model = get_model(model_config=self.model_config,
> [rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
> [rank0]:     return loader.load_model(model_config=model_config,
> [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 1148, in load_model
> [rank0]:     self._load_weights(model_config, model)
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 1082, in _load_weights
> [rank0]:     model.load_weights(qweight_iterator)
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 582, in load_weights
> [rank0]:     loader.load_weights(
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 203, in load_weights
> [rank0]:     autoloaded_weights = list(self._load_module("", self.module, weights))
> [rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 182, in _load_module
> [rank0]:     yield from self._load_module(prefix,
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 169, in _load_module
> [rank0]:     module_load_weights(weights)
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 414, in load_weights
> [rank0]:     param = params_dict[name]
> [rank0]:             ~~~~~~~~~~~^^^^^^
> [rank0]: KeyError: 'layers.21.mlp.gate_up_proj.weight'
> Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by jeejeelee**
FIX #9937 

### Work
- 1. Fix Phi-3 BNB config
- 2. For current models like Phi-3,Baichuan, ChaGLM, there is a bug in BNB quantization. This is because their merged linear( mlp )weights are already merged in the disk, and the current BNB implementation doesn't account for this scenario,fix this

### TODO
For these types of models, there is still a remaining issue regarding TP  weight partitioning during online quantization. This will be addressed in the following  PR.

ping @mgoin

### CODE REVIEW

**Comment by jeejeelee** [comment]
> ### Work
> * 1. Fix Phi-3 BNB config
> * 2. For current models like Phi-3,Baichuan, ChaGLM, there is a bug in BNB quantization. This is because their merged linear( mlp )weights are already merged in the disk, and the current BNB implementation doesn't account for this scenario,fix this
> 
> ### TODO
> For these types of models, there is still a remaining issue regarding TP weight partitioning during online quantization. This will be addressed in the following PR.

ping @mgoin

**Comment by Isotr0py** [comment]
FYI, I have implemented the TP support for Phi-3 BNB in my branch, it might be useful for addressing the issue you mentioned: https://github.com/Isotr0py/vllm/blob/79f0b5f725ea74f19d8f4a73b9c9df72fb3ac605/vllm/model_executor/model_loader/loader.py#L909-L934

**Comment by jeejeelee** [comment]
> FYI, I have implemented the TP support for Phi-3 BNB in my branch, it might be useful for addressing the issue you mentioned: https://github.com/Isotr0py/vllm/blob/79f0b5f725ea74f19d8f4a73b9c9df72fb3ac605/vllm/model_executor/model_loader/loader.py#L909-L934


thanks,I will look at this asap

**Review by mgoin — APPROVED** [review]
Thanks for improving the comments as well

**Pull request merged**
