### PR TITLE
[ci][distributed] fix phi-3v test failure

### PR DESCRIPTION
**Pull request by youkaichao**
Looks like we initialize the hf config class too early, and that class is not pickle-able. we need to use fork method to start multi-processing.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Hmm, but I thought this line meant that we must use `spawn` to test the models:

https://github.com/vllm-project/vllm/blob/54331fcddb58e54cc5495f604bc85e1f88952f0c/.buildkite/test-pipeline.yaml#L50

**Comment by youkaichao** [comment]
That line `export VLLM_WORKER_MULTIPROC_METHOD=spawn` is designed for `pytest -v -s distributed/test_basic_distributed_correctness.py` . It turns out `pytest -v -s distributed/test_multimodal_broadcast.py` has different requirements.

I don't know why this does not appear in pre-merge ci.

I hope I can figure out all of these stuff someday, but I don't have bandwidth recently :(

**Comment by DarkLight1337** [comment]
FYI the AMD distributed tests are timing out now (seems that most of the time is spent on model download, at least looking at vision language models test), so we may have to split them out.

**Comment by DarkLight1337** [comment]
Closing as superseded by #5991

**Pull request closed without merging**
