### PR TITLE
[CI/Build] Make shellcheck happy

### PR DESCRIPTION
**Pull request by DarkLight1337**
This PR fixes the INFO-level issues when running `format.sh` locally. cc @russellb 

To avoid similar issues in the future, `shellcheck.sh` has been updated to fail CI when this happens.

### CODE REVIEW

**Review by russellb — APPROVED** [review]
The changes look good.

It's an accident that this isn't failing CI! If you want, you could add `set -ex` to `tools/shellcheck.sh`, which I think will fix that. Otherwise, I can do it in a follow-up PR.

**Comment by DarkLight1337** [comment]
I added this line to `shellcheck.sh`, but `format.sh` still outputs "Format check passed!" even when the return code is non-zero.

**Comment by russellb** [comment]
> I added this line to `shellcheck.sh`, but `format.sh` still outputs "Format check passed!" even when the return code is non-zero.

OK, I'll look into it.

**Review by russellb — CHANGES_REQUESTED** [review]
This change works for me:

```diff
diff --git a/tools/shellcheck.sh b/tools/shellcheck.sh
index a13c49eb..d99fa77b 100755
--- a/tools/shellcheck.sh
+++ b/tools/shellcheck.sh
@@ -19,4 +19,4 @@ if ! [ -x "$(command -v shellcheck)" ]; then
 fi
 
 # TODO - fix warnings in .buildkite/run-amd-test.sh
-find . -name "*.sh" -not -path "./.buildkite/run-amd-test.sh" -exec sh -c 'git check-ignore -q $1 || shellcheck $1' _ {} \;
+find . -name "*.sh" -not -path "./.buildkite/run-amd-test.sh" -print0 | xargs -0 -I {} sh -c 'git check-ignore -q "{}" || shellcheck "{}"'
```

**Review by russellb — APPROVED** [review]
lgtm, sorry for the trouble!

**Comment by DarkLight1337** [comment]
@youkaichao can you stamp this?

**Review by youkaichao — APPROVED** [review]

**Pull request merged**
