### PR TITLE
Configuration to allow output of special tokens

### PR DESCRIPTION
**Pull request by blahblahasdf**
I have a model that generates special tokens with important meaning to generation tasks.  At present there is no way to get these special tokens back in the generated text because of the hardcoded input to `detokenize_incrementally` in `llm_engine`.

This PR adds an option at start up to `--keep-special-tokens` which resolves this limitation.

I elected to resolve this with a `ModelConfig` change instead of changing `SamplingParams` but I could see an argument the other way.

### CODE REVIEW

**Comment by blahblahasdf** [comment]
This is an approach to addressing #893.

**Comment by WoosukKwon** [comment]
Hi @blahblahasdf, sorry for the late response. Could you elaborate more on the reason you add it as a model parameter instead of a sampling parameter?

**Comment by blahblahasdf** [comment]
No worries @WoosukKwon .  For my use cases I want the special tokens for every request.  To me, this meant it should be a configuration of the model more than the request. As I said I could easily see it the other way and I'd be happy to change this to an option on `SamplingParams` instead if that fits better with your design.

**Comment by WoosukKwon** [comment]
@blahblahasdf Thanks! I believe HF transformers also views it as a generation parameter, rather than a model's hyper parameter. Could you fix the code?

**Comment by blahblahasdf** [comment]
Great, will do!

**Comment by blahblahasdf** [comment]
I created a new PR for the different approach.  https://github.com/vllm-project/vllm/pull/1186

**Pull request closed without merging**
