### PR TITLE
[misc][doc] try to add warning for latest html

### PR DESCRIPTION
**Pull request by youkaichao**
first step to make the latest html default

### CODE REVIEW

**Review by DarkLight1337 — APPROVED** [review]
Hope that this will reduce the number of issues resulting from users reading latest docs while using stable release.

You can merge this once you're ready.

**Comment by youkaichao** [comment]
I'm fighting with css/html 😅

**Comment by youkaichao** [comment]
@simon-mo how do you like this style?

https://vllm--5979.org.readthedocs.build/en/5979/

**Comment by DarkLight1337** [comment]
Personally I prefer using the same font as the main text.

**Comment by DarkLight1337** [comment]
@simon-mo any update on this?

**Comment by simon-mo** [comment]
Looks a bit off in dark mode :( 

image

**Comment by youkaichao** [comment]
@simon-mo  feel free to update the PR if you know how to make it work with dark mode. I know little about html/css :( I just ask ChatGPT.

**Comment by DarkLight1337** [comment]
Use `[data-theme=dark]` selector for dark theme and `[data-theme=light]` for light theme.

**Comment by youkaichao** [comment]
@DarkLight1337  can you update the pr directly?

**Comment by DarkLight1337** [comment]
Looks like I fixed it.

**Comment by DarkLight1337** [comment]
@simon-mo how about now?

**Comment by DarkLight1337** [comment]
Would be nice if we can get this into the release, otherwise we won't see the effects of this PR until the next release after this one...

**Pull request merged**
