### PR TITLE
[Misc] Log cudagraph memory usage

### PR DESCRIPTION
**Pull request by ymwangg**
This PR adds logging for cudagraph memory usage, which may be helpful for debugging memory issues.

```
INFO 06-13 21:26:05 model_runner.py:967] Graph capturing finished in 14 secs, and took 0.6172 GB
```

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by mgoin — COMMENTED** [review]
Could you use the existing CudaMemoryProfiler as we currently use that for model weight measurement? https://github.com/vllm-project/vllm/blob/e38042d4af1ddb390c3dd9340250de25bee37c62/vllm/worker/model_runner.py#L146-L161

**Comment by ymwangg** [comment]
For some reason, CudaMemoryProfiler is not giving the correct results.
With:
```diff
diff --git a/vllm/worker/worker.py b/vllm/worker/worker.py
index 7a378a86..0e57576c 100644
--- a/vllm/worker/worker.py
+++ b/vllm/worker/worker.py
@@ -209,8 +209,11 @@ class Worker(WorkerBase):
         self.gpu_cache = self.cache_engine.gpu_cache
 
     def _warm_up_model(self) -> None:
+        from vllm.utils import CudaMemoryProfiler
         if not self.model_config.enforce_eager:
-            self.model_runner.capture_model(self.gpu_cache)
+            with CudaMemoryProfiler() as m:
+                self.model_runner.capture_model(self.gpu_cache)
+            print(f"Cudagraph took {m.consumed_memory / 2**30:.4f} GB")
         # Reset the seed to ensure that the random state is not affected by
         # the model initialization and profiling.
         set_random_seed(self.model_config.seed)
```

and running with:
```
llm = LLM(model="/home/ubuntu/models/llama-3-70b-instruct-awq",
          tensor_parallel_size=8,
          distributed_executor_backend="ray",
          gpu_memory_utilization=0.85)
```
I got `Cudagraph took 0.0124 GB`. However, with this PR I got `Cudagraph took 0.6172 GB`.

**Comment by mgoin** [comment]
You might have been measuring peak memory usage during cudagraph creation. CudaMemoryProfiler strictly measures the difference of current memory usage at the end of the context. I think storing the finished cudagraphs doesn't require much memory (just a few megabytes) but the peak memory during its creation is likely much more due to the forward pass. I have a PR here to add peak memory usage to the object if you are still interested in peak usage: https://github.com/vllm-project/vllm/pull/5580

**Comment by davidthomas426** [comment]
It's not peak. It's because cuda graph memory is not part of torch's cuda allocator memory.

**Comment by ymwangg** [comment]
I also suspect cudagraph memory usage is not recorded in `torch.cuda.max_memory_allocated`. In https://github.com/pytorch/pytorch/blob/2b72e2a596ba4b6d97304f8e378b4c9144ce5f5e/c10/cuda/CUDACachingAllocator.cpp#L103-L108, it says cudagraph is using a private pool.

**Comment by mgoin** [comment]
This feature has been added already!

**Pull request closed without merging**
