### PR TITLE
[Minor] Add Phi 2 to supported models

### PR DESCRIPTION
**Pull request by WoosukKwon**
I've checked that vLLM's Phi 2 outputs match HF's.

### CODE REVIEW

**Review by zhuohan123 — APPROVED** [review]
LGTM!

**Comment by WoosukKwon** [comment]
@zhuohan123 Are you also good with changing the dtype of `test_models` to `float`?

**Comment by zhuohan123** [comment]
Yes I think this is better than having a test that always fail. I think in the future we need to have a simpler test in fp16

**Comment by WoosukKwon** [comment]
@zhuohan123 Sounds good! Thanks for the quick review!

**Comment by iaoxuesheng** [comment]
请问我安装的是0.1.4版本，这个版本不支持phi-2嘛

**Pull request merged**
