### PR TITLE
Support specify template in OpenAI server

### PR DESCRIPTION
**Pull request by kai01ai**
Currently, the OpenAI API server uses `request.model` as the template name. This approach isn't convenient when deploying custom models (e.g., a custom fine-tuned chat model that uses the chatgpt/llama2 template).

This patch addresses the issue by introducing a `template` field in the `CompletionRequest`/`ChatCompletionRequest`. If the template field isn't specified, it will default to the value of `model` to maintain backward compatibility.

### CODE REVIEW

**Comment by Tostino** [comment]
Well, it looks like we are working on somewhat related features. Not exactly the same thing, but these would be incompatible if both PRs were accepted right now.

https://github.com/vllm-project/vllm/pull/1294

**Comment by kai01ai** [comment]
@Tostino Your implementation does offer more flexibility. However, I personally prefer using [Prompt templating](https://huggingface.co/docs/transformers/main/chat_templating) introduced in transformers 4.34.0. This would allow us to not rely on fastchat and to create custom templates stored in the tokenizer config files. Admittedly, this represents a significant change.

**Comment by Tostino** [comment]
Right. I agree something like that is a much better solution...but I am unable to use my model with vLLM right now without patching it, and that was the solution that was suggested to me in Discord, so I went with it and submitted a PR because it is useful "right now". I'd expect it to be replaced when an implementation of HF prompt templates is in place, and I very much look forward to this madness being solved.

**Comment by Tostino** [comment]
Just FYI, I am going to work on a PR for supporting the HF tokenizer prompt templating. Closed my other one since it hadn't been accepted yet.

**Comment by kai01ai** [comment]
Very nice! I will close this PR since the HF tokenizer prompt templating work

**Comment by kai01ai** [comment]
Closed due to https://github.com/vllm-project/vllm/pull/1756. Many thanks to @Tostino for the contribution.

**Pull request closed without merging**
