### PR TITLE
[Doc] Use intersphinx and update entrypoints docs

### PR DESCRIPTION
**Pull request by DarkLight1337**
This makes the API reference easier to follow.

I have also slightly modified the docs for LLM entrypoints to indicate legacy behaviour (plus some cleanup).

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
Hmm the build was not successful

https://vllm--5125.org.readthedocs.build/en/5125/dev/engine/async_llm_engine.html

**Comment by simon-mo** [comment]
Log here https://readthedocs.org/projects/vllm/builds/24534860/

**Comment by DarkLight1337** [comment]
> Log here https://readthedocs.org/projects/vllm/builds/24534860/

That is odd. The page is built successfully on my end, and the CI didn't report any errors.

**Comment by DarkLight1337** [comment]
Let me try adding back the `autodoc_mock_imports`.

**Comment by DarkLight1337** [comment]
That didn't fix the problem...

**Comment by DarkLight1337** [comment]
After clearing my cache, the autodoc pages now appear correctly.

**Comment by DarkLight1337** [comment]
I think we can merge this then; no reason to re-run the other tests.

**Pull request merged**
