### PR TITLE
[Misc] Suppress duplicated logging regarding multimodal input pipeline

### PR DESCRIPTION
**Pull request by ywang96**
This message regarding deprecation of legacy multimodal input processing pipeline should really be a print-once info otherwise every request will log it.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
I am hesitant to change the log level to warning since the merged processor isn't fully working yet.

**Comment by ywang96** [comment]
> I am hesitant to change the log level to warning since the merged processor isn't fully working yet.

I can make a new util function `print_log_once` if that works, otherwise this will make the console output too noisy

**Comment by DarkLight1337** [comment]
> > I am hesitant to change the log level to warning since the merged processor isn't fully working yet.
> 
> I can make a new util function `print_log_once` if that works, otherwise this will make the console output too noisy 

Sure, that sounds good!

**Comment by ywang96** [comment]
Confirmed this is working as expected

```
INFO 11-21 09:49:30 gpu_model_runner.py:515] Loading model weights took 13.1342 GB
INFO 11-21 09:49:32 gpu_executor.py:63] # GPU blocks: 7213
WARNING 11-21 09:49:32 gpu_model_runner.py:549] Skipping CUDA graph capture. Please add -O 3 to use CUDA graphs.
INFO 11-21 09:49:32 preprocess.py:215] Your model uses the legacy input pipeline instead of the new multi-modal processor. Please note that the legacy pipeline will be removed in a future release. For more details, see: https://github.com/vllm-project/vllm/issues/10114
Processed prompts: 100%|████████████████████████████████████████████████████████████████████████| 1000/1000 [00:40<00:00, 24.79it/s, est. speed input: 14773.29 toks/s, output: 1582.72 toks/s]

```

**Review by DarkLight1337 — APPROVED** [review]

**Pull request merged**
