### PR TITLE
[Bugfix] Error handling when model multimodal config initialisation fails

### LINKED ISSUE #8923: [Bug]: Model multimodal config initialisation unhandled and irrelevant error when no architectures found
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 15.0 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 15.0.0 (clang-1500.3.9.4)] (64-bit runtime)
Python platform: macOS-15.0-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] No relevant packages
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: N/A
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect
```

</details>

### Model Input Dumps

_No response_

### 🐛 Describe the bug

When initialising multimodal model config, if no architectures are found, an unhandled error happens and a not helpful error is show.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by AminAlam**
Error handling and informative error message when model multimodal config initialisation fails due to lack of architecture in the config

FIX #8923

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Actually, we have quite a few places where we try to find `architectures` from the HF config. Would it make more sense to factor this out so that we can also provide more useful errors in the other place as well?

**Comment by ywang96** [comment]
Hey @AminAlam Thanks for the PR!

In vLLM, we assume that model repos that are in the huggingface format will have `architectures` in their `config.json`. If this is not the case, could you point me to the model repos that do not have such key in their config file?

**Comment by AminAlam** [comment]
> Actually, I found that we have quite a few places where we try to find `architectures` from the HF config. Would it make more sense to factor this out (to some file under `vllm.transformers_utils`) to provide more useful errors in those other places as well?

That's a good idea @DarkLight1337 

> Hey @AminAlam Thanks for the PR!
> 
> In vLLM, we assume that model repos that are in the huggingface format will have `architectures` in their `config.json`. If this is not the case, could you point me to the model repos that do not have such key in their config file?

Hey @ywang96, This is the model I'm trying to deploy: [TheBloke/LLaMa-7B-GGML](https://huggingface.co/TheBloke/LLaMa-7B-GGML)

**Comment by ywang96** [comment]
> Hey @ywang96, This is the model I'm trying to deploy: [TheBloke/LLaMa-7B-GGML](https://huggingface.co/TheBloke/LLaMa-7B-GGML)

We don’t support deploying from GGML format on vLLM currently.

**Comment by AminAlam** [comment]
> > Hey @ywang96, This is the model I'm trying to deploy: [TheBloke/LLaMa-7B-GGML](https://huggingface.co/TheBloke/LLaMa-7B-GGML)
> 
> We don’t support deploying from GGML format on vLLM currently.

I see, thanks for mentioning it. I think it makes sense to keep the error handling add some more info to the error messages in case someone used a wrong format

**Comment by DarkLight1337** [comment]
> Actually, I found that we have quite a few places where we try to find architectures from the HF config. Would it make more sense to factor this out (to some file under vllm.transformers_utils) to provide more useful errors in those other places as well?

Closing as superseded by #7168

**Pull request closed without merging**
