### PR TITLE
[Model] Cohere CommandR+

### PR DESCRIPTION
**Pull request by saurabhdash2512**
FILL IN THE PR DESCRIPTION HERE

Adding support for Cohere CommandR+ (CohereForAI/c4ai-command-r-plus)

@youkaichao Could you please take a look at the changes?

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by saurabhdash2512** [comment]
The model executes correctly but gives this error at the end:
```
Exception ignored in: <function NCCLCommunicator.__del__ at 0x7fb652b996c0>
Traceback (most recent call last):
  File "/workspace/vllm/vllm/model_executor/parallel_utils/pynccl.py", line 264, in __del__
TypeError: 'NoneType' object is not callable
```

**Comment by esmeetu** [comment]
> The model executes correctly but gives this error at the end. Does any one know what might be the issue?
> 
> ```
> Exception ignored in: <function NCCLCommunicator.__del__ at 0x7fb652b996c0>
> Traceback (most recent call last):
>   File "/workspace/vllm/vllm/model_executor/parallel_utils/pynccl.py", line 264, in __del__
> TypeError: 'NoneType' object is not callable
> ```

Is this error related this PR? If not, you can submit a new issue with detail env and error info.

**Comment by saurabhdash2512** [comment]
> > The model executes correctly but gives this error at the end. Does any one know what might be the issue?
> > ```
> > Exception ignored in: <function NCCLCommunicator.__del__ at 0x7fb652b996c0>
> > Traceback (most recent call last):
> >   File "/workspace/vllm/vllm/model_executor/parallel_utils/pynccl.py", line 264, in __del__
> > TypeError: 'NoneType' object is not callable
> > ```
> 
> Is this error related this PR? If not, you can submit a new issue with detail env and error info.

Yup, it's related to the changes I've made.

**Comment by esmeetu** [comment]
@saurabhdash2512 I see you used tensor parallelism for `LayerNorm`, could you try without splitting norm weight?

**Comment by saurabhdash2512** [comment]
> @saurabhdash2512 I see you used tensor parallelism for `LayerNorm`, could you try without splitting norm weight?

The norm weights need to be split

**Comment by esmeetu** [comment]
Hmm, sorry i missed that it's related to query and key vector normalization. @youkaichao Any ideas about that `pynccl` error?

**Comment by saurabhdash2512** [comment]
> @saurabhdash2512 @esmeetu I updated this branch with the current `main` and was able to successfully run the model without the error. Could you please try again?

I get this error now:
```
TypeError: reshape_and_cache(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: torch.Tensor, arg5: str) -> None
  ```

**Comment by saurabhdash2512** [comment]
> @saurabhdash2512 You have to rebuild vLLM since the kernel has changed.

@WoosukKwon 
I still see the same log.
If it helps this is the nccl version
```
(RayWorkerVllm pid=3991115) INFO 04-04 15:33:36 pynccl_utils.py:45] vLLM is using nccl==2.18.1
```

**Comment by WoosukKwon** [comment]
@youkaichao Could you please take a look at the issue?

**Comment by youkaichao** [comment]
> Exception ignored in: <function NCCLCommunicator.__del__ at 0x7fb652b996c0>
> Traceback (most recent call last):
>   File "/workspace/vllm/vllm/model_executor/parallel_utils/pynccl.py", line 264, in __del__
> TypeError: 'NoneType' object is not callable

Seems to be related with https://github.com/vllm-project/vllm/pull/3702 , about the cleanup order of objects.

Maybe related with this code, where `_c_ncclCommDestroy` is already destructed:

https://github.com/vllm-project/vllm/blob/ca81ff5196b2fa82b7a9d553cd6e30eab9e72aca/vllm/model_executor/parallel_utils/pynccl.py#L270-L274

But anyway, this says `Exception ignored`, so it should not cause problem.

@saurabhdash2512 does this "error message" break your program?

**Comment by WoosukKwon** [comment]
@saurabhdash2512 do you have the same issue for other models? Say, could you run `facebook/opt-125m` with the same TP degree and check whether the same error message appears?

**Review by WoosukKwon — APPROVED** [review]
@saurabhdash2512 Thanks for contributing to vLLM! Super excited to have this SOTA model. Looking forward to what will be built on top of the model!

*I believe the issue above is orthogonal to the current PR. So let's merge this first.

**Comment by huyang19881115** [comment]
Cohere CommandR+  使用vllm是如何启动的呢？有启动的例子的吗？必须vllm 0.4.1 版本以及以上的吗？

**Comment by huyang19881115** [comment]
INFO 05-09 09:36:49 api_server.py:228] args: Namespace(host='0.0.0.0', port=8007, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name='qwen-4bit', lora_modules=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, root_path=None, middleware=[], model='/data/models/c4ai-command-r-plus-4bit/c4ai-command-r-plus-4bit', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='float16', kv_cache_dtype='auto', max_model_len=8192, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.7, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization='gptq', enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=None, device='auto', engine_use_ray=False, disable_log_requests=False, max_log_len=None)
Traceback (most recent call last):
  File "/data/miniconda3/minicondaenv/envs/qwen2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/miniconda3/minicondaenv/envs/qwen2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/miniconda3/minicondaenv/envs/qwen2/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 236, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/data/miniconda3/minicondaenv/envs/qwen2/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 622, in from_engine_args
    engine_configs = engine_args.create_engine_configs()
  File "/data/miniconda3/minicondaenv/envs/qwen2/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 287, in create_engine_configs
    model_config = ModelConfig(
  File "/data/miniconda3/minicondaenv/envs/qwen2/lib/python3.10/site-packages/vllm/config.py", line 118, in __init__
    self._verify_quantization()
  File "/data/miniconda3/minicondaenv/envs/qwen2/lib/python3.10/site-packages/vllm/config.py", line 176, in _verify_quantization
    raise ValueError(
ValueError: Quantization method specified in the model config (bitsandbytes) does not match the quantization method specified in the `quantization` argument (gptq)

**Comment by huyang19881115** [comment]
Traceback (most recent call last):
  File "/data/miniconda3/minicondaenv/envs/vllm4/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/miniconda3/minicondaenv/envs/vllm4/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/miniconda3/minicondaenv/envs/vllm4/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 168, in <module>
    engine = AsyncLLMEngine.from_engine_args(
  File "/data/miniconda3/minicondaenv/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 346, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/data/miniconda3/minicondaenv/envs/vllm4/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 520, in create_engine_config
    model_config = ModelConfig(
  File "/data/miniconda3/minicondaenv/envs/vllm4/lib/python3.10/site-packages/vllm/config.py", line 131, in __init__
    self._verify_quantization()
  File "/data/miniconda3/minicondaenv/envs/vllm4/lib/python3.10/site-packages/vllm/config.py", line 188, in _verify_quantization
    raise ValueError(
ValueError: Quantization method specified in the model config (bitsandbytes) does not match the quantization method specified in the `quantization` argument (marlin).

**Pull request merged**
