### PR TITLE
[ROCm] include gfx908 as supported

### PR DESCRIPTION
**Pull request by jamestwhedbee**
ROCm/flash-attention [supports](https://github.com/ROCm/flash-attention/commit/ae7928c5aed53cf6e75cc792baa9126b2abfcf1a) the `gfx908` architecture.

Without this change, vLLM appears to build successfully for me, but serving an LLM on an MI100 results in gibberish output.

With this change, everything works as expected.

### CODE REVIEW

**Comment by jamestwhedbee** [comment]
@zhuohan123 would you have time to review this?

**Comment by jamestwhedbee** [comment]
@WoosukKwon is there anything I should be doing differently to get a review here?

**Review by zhuohan123 — APPROVED** [review]
LGTM! Thanks for the fix!

**Comment by linchen111** [comment]
> ROCm/flash-attention [supports](https://github.com/ROCm/flash-attention/commit/ae7928c5aed53cf6e75cc792baa9126b2abfcf1a) the `gfx908` architecture.
> 
> Without this change, vLLM appears to build successfully for me, but serving an LLM on an MI100 results in gibberish output.
> 
> With this change, everything works as expected.

get this error in MI100:
RuntimeError: HIP error: invalid argument
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

**Pull request merged**
