### PR TITLE
[Frontend][Core] Override HF `config.json` via CLI

### LINKED ISSUE #1542: Feature request: Controlling `config.json` of HF's models
Thanks for this great project!

A quick feature request: [When loading models from the HuggingFace Hub](https://github.com/vllm-project/vllm/blob/7e90a2d11785b4cba5172f13178adb6d194a867f/vllm/config.py#L79), allow providing custom values to overwrite the default `config.json`. For example, change [the value of `max_position_embeddings` from `32768`](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1/blob/7ad5799710574ba1c1d953eba3077af582f3a773/config.json#L11) to `100000`, to allow longer prompts.

### LINKED ISSUE #2547: Allow passing hf config args with openai server
Hi,

Is there a specific reason for why can't we allow passing of args from the openai server to the HF config class, there are very reasonable use cases where i would want to override the existing args in a config while running the model dynamically though the server.

[reference line](https://github.com/vllm-project/vllm/blob/18bfcdd05c657e6997b132488e6f4e74307d6cee/vllm/transformers_utils/config.py#L23)

simply allowing `*args` in the openai server that are passed to this while loading the model, i believe there are internal checks for failing if anything configured is wrong anyway.

supported documentation in the transformers library:

```
        >>> # Change some config attributes when loading a pretrained config.
        >>> config = AutoConfig.from_pretrained("bert-base-uncased", output_attentions=True, foo=False)
        >>> config.output_attentions
        True
```

### LINKED ISSUE #5205: [Feature]: Option to override HuggingFace's configurations
### 🚀 The feature, motivation and pitch

The configuration files on HuggingFace may have missing information (e.g. #2051) or contain bugs (e.g. #4008). In such cases, it may be necessary to provide/override the configuration files to enable the model to be loaded correctly. However, apart from chat templates, there is currently no method of doing so; we have to update the source HuggingFace repository directly. It may take time for the authors of those repositories to respond, especially if they are unofficial ones which are not as well-maintained.

It would be great if we could provide our own `config.json`, `tokenizer_config.json`, etc., through the vLLM CLI to apply patches as necessary.

### Related work

#1756 lets us specify alternative chat templates or provide a chat template when it is missing from `tokenizer_config.json`. However, it currently only applies to the OpenAI API-compatible server. #5049 will add chat method to the main LLM entrypoint, but does not provide a built-in way to load the chat template automatically like in #1756.

Some vLLM models have already hardcoded patches to HuggingFace `config.json`; these can be found under `vllm/transformers_utils/configs`.

### PR DESCRIPTION
**Pull request by KrishnaM251**
FIX #1542
FIX #2547
FIX #5205

<h3>PR Title and Classification</h3>
[Frontend] [Core]

<h3>Notes</h3>

- While I believe the implementation is almost complete, the test I wrote only checks if the new `Optional[dict]` parameter `hf_kwargs` is succesfully set in `ModelConfig`.
- I would like to write a test that detects a change in the `LLMEngine` output when `kf_kwargs` is added as a `EngineArgs` parameter. 
- But I have two questions:
  - How can I write another test that runs `hf_kwargs` through an OpenAI compatible server? I wanted to repurpose a test in [test_openai_server.py](https://github.com/vllm-project/vllm/blob/dd248f76756adba4a1637b882e79ab639f957feb/tests/entrypoints/test_openai_server.py#L92), however the `EngineArgs` params are set before all tests are run.
  - What are some test values that I can set in `hf_kwargs` which will generate output detectable in a function like: `completion = client.completions.create(...)` ([motivating example](https://github.com/vllm-project/vllm/blob/dd248f76756adba4a1637b882e79ab639f957feb/tests/entrypoints/test_openai_server.py#L137)). If this is not the best approach for testing, then any recommendations?

### CODE REVIEW

**Comment by simon-mo** [comment]
@DarkLight1337 can you help answer the question since you recently touched the testing harness. 

Additionally, there might be other places we want override including tokenizer or generation config. Addressing those will be nice to have.

**Comment by DarkLight1337** [comment]
Thanks for picking this up! To answer your questions:

>   - How can I write another test that runs `hf_kwargs` through an OpenAI compatible server? I wanted to repurpose a test in [test_openai_server.py](https://github.com/vllm-project/vllm/blob/dd248f76756adba4a1637b882e79ab639f957feb/tests/entrypoints/test_openai_server.py#L92), however the `EngineArgs` params are set before all tests are run.

You should launch a new instance of the server. Each `RemoteOpenAIServer` instance creates a new subprocess that invokes the OpenAI entrypoint through the command line, so you can't change the `hf_config` after instantiating it.

>   - What are some test values that I can set in `hf_kwargs` which will generate output detectable in a function like: `completion = client.completions.create(...)` ([motivating example](https://github.com/vllm-project/vllm/blob/dd248f76756adba4a1637b882e79ab639f957feb/tests/entrypoints/test_openai_server.py#L137)). If this is not the best approach for testing, then any recommendations? 

As mentioned above, you should start a different server for each unique `hf_config` since it cannot be adjusted at runtime.

**Comment by KrishnaM251** [comment]
@DarkLight1337 I appreciate the response. I will do as you suggested.

**Comment by vpellegrain** [comment]
Hi @KrishnaM251,

Any news on this? 

I have a specific use case in which I'd like to deploy a Phi3.5-vision model on a vLLM openai server entrypoint ; but i'd like to specify the argument `num_crops=16` (which is by default 4 in [the preprocessor config file](https://huggingface.co/microsoft/Phi-3.5-vision-instruct/blob/main/preprocessor_config.json)).

**Comment by DarkLight1337** [comment]
> Hi @KrishnaM251,
> 
> Any news on this?
> 
> I have a specific use case in which I'd like to deploy a Phi3.5-vision model on a vLLM openai server entrypoint ; but i'd like to specify the argument `num_crops=16` (which is by default 4 in [the preprocessor config file](https://huggingface.co/microsoft/Phi-3.5-vision-instruct/blob/main/preprocessor_config.json)).

@alex-jw-brooks is currently working on a PR that lets you pass options to the HF processor on demand instead of at startup time (the latter is what this PR focuses on). Stay tuned!

**Comment by DarkLight1337** [comment]
Sorry for forgetting about this! I think we now have a valid use case which is to patch out incorrect HF configs. cc @K-Mistele

**Comment by K-Mistele** [comment]
right, would be good to be able to adjust RoPE/YARN configurations in `config.json` at startup-time. I left comments about this on some other issues I just can't seem to find them right this second

**Comment by DarkLight1337** [comment]
I have updated this PR and also changed the tests to check overriding `rope_scaling` and `rope_theta`.

**Review by DarkLight1337 — APPROVED** [review]
Since now we have a use case for this, I'm approving the PR.

**Pull request merged**
