### PR TITLE
Add support for baichuan

### LINKED ISSUE #303: why not support baichuan-7b?

### PR DESCRIPTION
**Pull request by codethazine**
Closes #303 

Should be merged after #364 - as the model requires its remote tokenizer to run correctly

### CODE REVIEW

**Comment by gesanqiu** [comment]
Thanks, but I think still need to add a conversation template in FastChat since /v1/chat/completion API requires it. BTW can you give a prompt template for /v1/completions, I can't wait to try this model.

**Comment by codethazine** [comment]
Ahh sorry wasn't there on the initial push, I'll integrate it tomorrow

**Comment by codethazine** [comment]
I played around with the chat/completion a little bit, and it consistently reverted to stuff like ### USER, so this is a good prompt template I came up with for the completions: 
```
curl http://localhost:8000/v1/completions \
    -d '{
    "model": "baichuan-inc/baichuan-7b",
        "prompt": "A chat between a curious user and an artificial intelligence assistant. \n### USER: Hello!\n### ASSISTANT:",
        "stop": "\n",
        "max_tokens": 42
    }'
```

**Comment by lucasjinreal** [comment]
Any updates on this?

I saw there a some PRs try support baichuan now, please consider merge one otherwise none of them can be properly supported

**Review by zhuohan123 — APPROVED** [review]
Thank you for your excellent contribution! This PR looks good to me. Sorry that we have been busy in the past several weeks so we didn't get a chance to review this. I just tested this out and it works great!

**Pull request merged**
