### PR TITLE
[Bugfix] Fix offline mode when using `mistral_common`

### PR DESCRIPTION
**Pull request by sasha0552**

### CODE REVIEW

**Review by mgoin — APPROVED** [review]
LGTM thanks for moving to use list_repo_files! It would be nice to add this as a test case to https://github.com/vllm-project/vllm/blob/dbfa8d31d5e7627a84671c6068ecc8fa58acd1d1/tests/entrypoints/offline_mode/test_offline_mode.py

**Comment by sasha0552** [comment]
@mgoin Tests passed and PR is ready to merge.

**Comment by sasha0552** [comment]
@mgoin Could you please merge the PR? The unrelated test failed.

**Comment by mgoin** [comment]
I can't force merge, @simon-mo could you please?

**Pull request merged**
