### PR TITLE
[CI/Test] expand ruff and yapf for all supported python version

### PR DESCRIPTION
**Pull request by youkaichao**
With this, https://github.com/vllm-project/vllm/issues/4035 should not happen again.

### CODE REVIEW

**Comment by youkaichao** [comment]
Emmm, type check is not included in ruff or yapf. But maybe we can still add this, as they are github hosted ci and freee to use @simon-mo

**Comment by rkooo567** [comment]
@youkaichao it is actually added to mypy.yaml in the master!

**Review by rkooo567 — APPROVED** [review]
Runtime of these CIs are not really affected right?

**Comment by youkaichao** [comment]
> Runtime of these CIs are not really affected right?

Yes. These jobs are run by github. They are free ci resource :)

**Review by mgoin — APPROVED** [review]
Nice

**Comment by youkaichao** [comment]
@cadedaniel can you stamp on this pr for merge?

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
