### PR TITLE
 migrate pydantic from v1 to v2

### LINKED ISSUE #1396: bump pydantic to v2
Would be it be possible to bump pydantic to v2 as ray [serve] is now compatible with pydantic v2? See [Ray PR](https://github.com/ray-project/ray/pull/40222).

Follow up on issue #423 and PR #429.

### LINKED ISSUE #2313: Outdated Pydantic Version
OpenAI's Python library now allows for Pydantic versions >= 1.9.0, < 3 (see openai [requirements](https://github.com/openai/openai-python/blob/f1c7d714914e3321ca2e72839fe2d132a8646e7f/pyproject.toml#L12C27-L12C27)). Would it be possible to bump the pinned version for vLLM to match?

### PR DESCRIPTION
**Pull request by joennlae**
Following this guide here: https://docs.pydantic.dev/dev/migration/

Previous attempts: #2468 #2322

closes https://github.com/vllm-project/vllm/issues/1396
closes https://github.com/vllm-project/vllm/issues/2313
closes https://github.com/vllm-project/vllm/pull/2322

It also includes a fix to error code propagation for the OpenAI-compatible server.

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by joennlae** [comment]
I was just fixing this also in parallel :-)

**Comment by simon-mo** [comment]
Thank you for the contribution!

**Comment by Lvjinhong** [comment]
Why does it still show ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
vllm 0.2.7 requires pydantic==1.10.13, but you have pydantic 2.5.3 which is incompatible.

**Comment by simon-mo** [comment]
This commit will be part of up coming vLLM 0.2.8, which will be releaesed in <1 week

**Comment by yippp** [comment]
Seems pydantic v2 leads to a problem meet in #2619

**Pull request merged**
