### PR TITLE
Fix: MI100 Support By Bypassing Custom Paged Attention

### PR DESCRIPTION
**Pull request by MErkinSag**
FIX #[8963](https://github.com/vllm-project/vllm/issues/8963) 

### Why is it needed?

* Currently, Custom Paged Attention for ROCm on vLLM is only supported for MI250 and MI300. This limitation is enforced by the _use_rocm_custom_paged_attention function, which, when run on other GPUs like the MI100, causes the program to hit an UNREACHABLE_CODE path and fail.
---------------------
* By the proposed changes this function can return False if the architecture is not of MI300 or MI250, and this works for my setup (Using AsyncLLMEngine on Ray Serve running on MI100s).

Any feedback is highly appreciated to make this a feasible and a generic solution for non-MI250 and MI300 GPUs.

### CODE REVIEW

**Comment by DarkLight1337** [comment]
Is it possible to tie this to `current_platform.get_device_capability` instead of directly referencing the `gcnArchName`?

**Comment by erkintelnyx** [comment]
> Is it possible to tie this to `current_platform.get_device_capability` instead of directly referencing the `gcnArchName`?

@DarkLight1337 Could you clarify how could that work?
As an alternative would it make sense to use `current_platform.get_device_name()` (output: 'AMD Instinct MI100') to match the GPU model?

**Comment by MErkinSag** [comment]
> Is it possible to tie this to `current_platform.get_device_capability` instead of directly referencing the `gcnArchName`?

@DarkLight1337 Could you clarify how could that work?
As an alternative would it make sense to use `current_platform.get_device_name()` (output: 'AMD Instinct MI100') to match the GPU model?

**Comment by DarkLight1337** [comment]
> > Is it possible to tie this to `current_platform.get_device_capability` instead of directly referencing the `gcnArchName`?
> 
> @DarkLight1337 Could you clarify how could that work? As an alternative would it make sense to use `current_platform.get_device_name()` (output: 'AMD Instinct MI100') to match the GPU model?

Currently, `current_platform.get_device_capability` is used to select backends for CUDA devices. I'm wondering whether we can do the same for AMD using the same interface. For example, do we have a known mapping from `gcnArchName` to `current_platform.get_device_capability` (which for AMD is currently just `torch.cuda.get_device_capability`)?

**Comment by MErkinSag** [comment]
> Currently, `current_platform.get_device_capability` is used to select backends for NVIDIA devices. I'm wondering whether we can do the same for AMD using the same interface. For example, do we have a known mapping from `gcnArchName` to `current_platform.get_device_capability` (which for AMD is currently just `torch.cuda.get_device_capability`)?

@DarkLight1337 I couldn't find much except the minor CC version changes between MI300x and MI100.
```
torch.cuda.get_device_capability()
(9, 4)
```
```
torch.cuda.get_device_capability()
(9, 0)
```
Hi @hongxiayang. Is there any possible solution you could refer using `current_platform.get_device_capability` with this?

**Comment by MErkinSag** [comment]
Would it be okay to proceed with this solution for now @DarkLight1337 @WoosukKwon?

**Comment by DarkLight1337** [comment]
Please merge from main and fix the linter errors.

**Comment by DarkLight1337** [comment]
If there is no other way to do it, `gcnArchName` is fine with me.

**Review by DarkLight1337 — APPROVED** [review]

**Comment by DarkLight1337** [comment]
The linter is still failing.

**Pull request merged**
