### PR TITLE
Fix docker python version

### PR DESCRIPTION
**Pull request by NikolaBorisov**
Docker images were broken because we build the extensions with python3.8 but then we try to run them with other version of python.

This results in exception error
```
  File "/workspace/vllm/model_executor/layers/quantization/awq.py", line 6, in <module>
    from vllm._C import ops
ModuleNotFoundError: No module named 'vllm._C'
```

I think if we want to make sure vllm works in older versions of python we should do something else.

To reproduce
`docker build .`
`docker run ... ` 
It crashes with the above exception. I think as part of the CI there should be something that checks if the docker build containers work.

### CODE REVIEW

**Comment by NikolaBorisov** [comment]
#2716 caused the issue

**Comment by NikolaBorisov** [comment]
@simon-mo @WoosukKwon can someone take a look?

**Comment by NikolaBorisov** [comment]
#2811 Also broke the docker images. This PR should fix it as well

**Comment by Pernekhan** [comment]
LGTM!

**Comment by simon-mo** [comment]
Ah great catch! can you help refactor the Dockerfile so the test target uses 3.8 and everything else uses latest stable?

**Comment by simon-mo** [comment]
I guess this will close https://github.com/vllm-project/vllm/issues/2773 as well?

**Review by simon-mo — APPROVED** [review]

**Comment by NikolaBorisov** [comment]
Yes this will fix #2773. I don't think we can have the python 3.8 just in the test target, because the issue was that c code was build with 3.8 but then it could not be imported in 3.10. I think to make sure 3.8 works we could build a different docker file or target that starts with 3.8 python and install vllm from pip? You will not catch it fast.

**Pull request merged**
