### PR TITLE
[WIP] [V1] VLM hashing and mapper caching

### PR DESCRIPTION
**Pull request by alexm-redhat**
This PR is the first step towards caching of VLM images and skipping of the encoder execution. Currently it adds:

1. Hashing support for images
2. Simple LRU cache based on OrderedDict
3. Caching of MM mapper results

TODO:
1. Integrate with Ricky's KVCacheManager refactor
2. Skip the encoder execution for cached embeds

### CODE REVIEW

**Comment by comaniac** [comment]
@alexm-neuralmagic is it possible to break this PR to 2 PRs so that we could merge the mm_hash sooner to unblock the embedding cache?

Also cc @yue-anyscale

**Comment by alexm-neuralmagic** [comment]
@comaniac yeah will try to break the PR to 2 pieces.

**Comment by alexm-neuralmagic** [comment]
Depends on https://github.com/vllm-project/vllm/pull/11020

**Comment by alexm-neuralmagic** [comment]
Not necessary anymore, replaced by https://github.com/vllm-project/vllm/pull/11020

**Pull request closed without merging**
