### PR TITLE
Prefix Prompt Cache

### PR DESCRIPTION
**Pull request by InkdyeHuang**
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2299.7">

<body>
<p class="p1"><b>流程</b></p>
<ol class="ol1">
<li class="li2">prompt cache 生成阶段</li>
<ul class="ul1">
<li class="li2"><span class="s1"></span>提供一个接口，让用户可以添加若干个prefix</li>
<ul class="ul1">
<li class="li2"><span class="s1"></span>def add_prefix_template({prefix_name, prefix_content})</li>
<ol class="ol1">
<li class="li2">让vllm 生成对应prefix_content的kv cache，并且进行存储</li>
</ol>
</ul>
</ul>
<li class="li2">request阶段</li>
<ul class="ul1">
<li class="li2"><span class="s1"></span>def add_request增加一个参数prefix_name</li>
<ul class="ul1">
<li class="li2"><span class="s1"></span>如果配置了，那么代表使用这个prefix_content的</li>
<li class="li2"><span class="s1"></span>如果传入没有生成过的prefix_name，报错（后续再根据使用情况调整）</li>
</ul>
</ul>
</ol>
<p class="p3"><br></p>
<p class="p1"><b>实现</b></p>
<ol class="ol1">
<li class="li2">prompt cache生成阶段</li>
<ul class="ul1">
<li class="li2"><span class="s1"></span>add_prefix_template 存放在llm_engine里</li>
<ul class="ul1">
<li class="li2"><span class="s1"></span>worker里面搞一个execute_prefix来生成prefix的kv cache，并且存储</li>
<li class="li2"><span class="s1"></span>model计算中生成离散kv</li>
<li class="li2"><span class="s1"></span>计算后gather一下，生成连续</li>
<li class="li2"><span class="s1"></span>一个全局的dict，里面一个prefix_name对应一个seq_group，seq_group额外包含</li>
<ol class="ol1">
<li class="li2">kv cache的离散显存, 如果prefix_token_id % block_table != 0 ，需要copy</li>
<li class="li2">kv cache的连续显存</li>
</ol>
</ul>
</ul>
<li class="li2">request阶段</li>
<ul class="ul1">
<li class="li2"><span class="s1"></span>add_request：</li>
<ul class="ul1">
<li class="li2"><span class="s1"></span>对应的kv cache保存两份</li>
<ol class="ol1">
<li class="li2">一份连续：便于prompt 计算，尽量避免显存申请</li>
<li class="li2">一份离散：便于generate计算</li>
</ol>
</ul>
</ul>
</ol>
<p class="p1"><b>性能测试</b></p>

prefix_tokens:prompt_tokens =1:3.05 | qps | prefix_prompt_throghput(tokens/s) | prompt_throghput | generate_throghput | prompt_time:generate_time | prompt_tokens:generate_tokens
-- | -- | -- | -- | -- | -- | --
prompt_cache | 26 | 17008.81 | 12814.70034 | 6360.76 | 66.84:4.87 | 36.72:1
no_prompt_cache | 21.849 | 13307.92 | 13307.92 | 6091 | 84.51:4.28 | 36.72:1

<p class="p2">prefix:prompt=0.32:1 ,prompt<span class="s2">速度提升</span>26%</p>
</body>
</html>

### CODE REVIEW

**Comment by chenxu2048** [comment]
Hi @InkdyeHuang, thanks for your contribution. Did you get the same or similar results when using prompt prefix caching? Our team tried your code with llama but obtained incorrect results. Any suggestion is welcome.

**Comment by InkdyeHuang** [comment]
> Hi @InkdyeHuang, thanks for your contribution. Did you get the same or similar results when using prompt prefix caching? Our team tried your code with llama but obtained incorrect results. Any suggestion is welcome.

**Comment by InkdyeHuang** [comment]
> Hi @InkdyeHuang, thanks for your contribution. Did you get the same or similar results when using prompt prefix caching? Our team tried your code with llama but obtained incorrect results. Any suggestion is welcome.

I has fix some bug, and try with llama model and get the same result when using prompt prefix caching. you can pull the lastest pr to try again.

**Comment by miguel12Y4** [comment]
Hello, I have an error when I try using 'pip install -e .' My computer crashes, it consumes all the RAM. I don't know why.

It starts consuming RAM at:

Building wheels for collected packages: vllm
Building editable for vllm (pyproject.toml)

**Comment by zhuohan123** [comment]
Close this issue since we have merged #1669. Please see our follow up plan on automated prefix caching in #2614

**Pull request closed without merging**
