### PR TITLE
[Kernel] Turn off CUTLASS scaled_mm for Ada Lovelace

### LINKED ISSUE #6240: [Bug]: Performance : slow inference for FP8 on L20 with 0.5.1(v0.5.0.post1 was fine)
### Your current environment

```text
Collecting environment information...
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.0
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA L20
GPU 1: NVIDIA L20
GPU 2: NVIDIA L20
GPU 3: NVIDIA L20
GPU 4: NVIDIA L20
GPU 5: NVIDIA L20
GPU 6: NVIDIA L20
GPU 7: NVIDIA L20

Nvidia driver version: 550.54.15
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] flashinfer==0.0.8+cu121torch2.3
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] torch==2.3.0
[pip3] torchvision==0.18.0
[pip3] transformers==4.42.3
[pip3] triton==2.3.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	PIX	PIX	PIX	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0		N/A
GPU1	PIX	 X 	PIX	PIX	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0		N/A
GPU2	PIX	PIX	 X 	PIX	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0		N/A
GPU3	PIX	PIX	PIX	 X 	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0		N/A
GPU4	SYS	SYS	SYS	SYS	 X 	PIX	PIX	PIX	SYS	24-47,72-95	1		N/A
GPU5	SYS	SYS	SYS	SYS	PIX	 X 	PIX	PIX	SYS	24-47,72-95	1		N/A
GPU6	SYS	SYS	SYS	SYS	PIX	PIX	 X 	PIX	SYS	24-47,72-95	1		N/A
GPU7	SYS	SYS	SYS	SYS	PIX	PIX	PIX	 X 	SYS	24-47,72-95	1		N/A
NIC0	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0
```

### 🐛 Describe the bug

The inference speed of vllm0.5.1 with fp8 quantization on L20 is even slower than fp16.

qwen2-7b @ L20*1:
| vllm version | quant | speed | 
|:-----:|:-----:|:-----:| 
| 0.5.0 | fp8 | 59.41 token/s | 
| 0.5.0 | fp16 | 44.05 token/s | 
| 0.5.1 | fp8 | **26.50** token/s | 
| 0.5.1 | fp16 | 43.60 token/s |

### PR DESCRIPTION
**Pull request by tlrmchlsmth**
We haven't tuned the cutlass kernels for SM89 and performance is very bad.

The following benchmarks were run on an L40 with
```
    python benchmarks/benchmark_serving.py \
    --backend openai \
    --model neuralmagic/Meta-Llama-3-8B-Instruct-FP8 \
    --dataset-path ShareGPT_V3_unfiltered_cleaned_split.json \
    --request-rate 1 \
    --num-prompts 200 \
    --port 8000
```

Using the CUTLASS kernels:
```
============ Serving Benchmark Result ============
Successful requests:                     200
Benchmark duration (s):                  211.44
Total input tokens:                      42659
Total generated tokens:                  41049
Request throughput (req/s):              0.95
Input token throughput (tok/s):          201.76
Output token throughput (tok/s):         194.14
---------------Time to First Token----------------
Mean TTFT (ms):                          71.19
Median TTFT (ms):                        63.17
P99 TTFT (ms):                           159.21
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          35.87
Median TPOT (ms):                        35.42
P99 TPOT (ms):                           46.35
---------------Inter-token Latency----------------
Mean ITL (ms):                           35.67
Median ITL (ms):                         33.55
P99 ITL (ms):                            102.87
==================================================
```

Using torch.scaled_mm:
```
============ Serving Benchmark Result ============
Successful requests:                     200
Benchmark duration (s):                  202.07
Total input tokens:                      42659
Total generated tokens:                  40851
Request throughput (req/s):              0.99
Input token throughput (tok/s):          211.11
Output token throughput (tok/s):         202.16
---------------Time to First Token----------------
Mean TTFT (ms):                          30.50
Median TTFT (ms):                        29.03
P99 TTFT (ms):                           60.73
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          16.58
Median TPOT (ms):                        16.46
P99 TPOT (ms):                           19.92
---------------Inter-token Latency----------------
Mean ITL (ms):                           16.52
Median ITL (ms):                         16.09
P99 ITL (ms):                            33.85
==================================================
```

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by tlrmchlsmth** [comment]
This should fix https://github.com/vllm-project/vllm/issues/6240

In a future PR we'll tune the CUTLASS SM89 FP8 kernels. We will need to do this anyway for the int8 case as well.

**Review by mgoin — APPROVED** [review]

**Review by pcmoritz — APPROVED** [review]

**Comment by robertgshaw2-neuralmagic** [comment]
@tlrmchlsmth FYI - the lm-eval score for llama changed a bit for fp8 with this change. I just tweaked the values in the config. 

Note: we are only running 250 samples for this model. I will re-run with 1000 samples so its a bit more stable

**Comment by tlrmchlsmth** [comment]
@robertgshaw2-neuralmagic thanks. Looks like we're failing on the GPTQ marlin tests as well. Are those flakey?

**Comment by robertgshaw2-neuralmagic** [comment]
> @robertgshaw2-neuralmagic thanks. Looks like we're failing on the GPTQ marlin tests as well. Are those flakey?

yes due to nondeteminism. will rerun

**Pull request merged**
