### PR TITLE
[Bugfix] Fix precisions in Gemma 1

### PR DESCRIPTION
**Pull request by WoosukKwon**
Should be merged after #5908.

NOTE: This PR might decrease the speed of Gemma 1, since it uses unoptimized (but more accurate) `GemmaRMSNorm` for Gemma 1.

### CODE REVIEW

**Comment by WoosukKwon** [comment]
@ywang96 Please take a look!

**Comment by ywang96** [comment]
@WoosukKwon Thanks for fixing Gemma! Does this mean the model will correctly match hf implementation now? Should we add gemma (e.g., `google/gemma-1.1-2b-it`) to `test_models.py`?

**Comment by WoosukKwon** [comment]
@ywang96 Unfortunately it seems there still exit some differences possibly due to other optimizations like FlashAttention.

**Comment by ywang96** [comment]
> @ywang96 Unfortunately it seems there still exit some differences possibly due to other optimizations like FlashAttention.

I see - let me do some testing locally and get back to this later!

**Review by lanking520 — APPROVED** [review]

**Comment by DarkLight1337** [comment]
To speed up the CI queue for #5905, I've cancelled the distributed tests for the latest CI run in this PR since they won't pass anyway until #5905 has been merged. Please merge `main` into your branch after that happens so that the CI can pass once again.

**Review by ywang96 — APPROVED** [review]
Confirmed `google/gemma-1.1-2b-it` passed the model test locally in this branch, but I'll leave it to you to decide if you want to actually add it as part of the test suite.

Going to approve this PR, thank you for fixing this model! @WoosukKwon

**Comment by WoosukKwon** [comment]
@ywang96 Amazing, thanks! Added it as it can also be a good proxy for Gemma 2. Once Gemma2 2B is released, maybe we can switch.

**Comment by WoosukKwon** [comment]
@zhouyuan @bigPYJ1151 @jikunshang It seems the HF token in CPU CI machine doesn't have access to the Gemma 1 2B model. Could you please check it out?

Also, please obtain access to other popular models like Gemma 2, etc. to avoid this error in the future.

**Comment by zhouyuan** [comment]
@WoosukKwon Hi, just made the change and the HF token should have access to Gemma models now. Please help to trigger the CPU check again to verify.

thanks, -yuan

**Pull request merged**
