### PR TITLE
[BUG FIX]fix compile error when building with torch2.1

### PR DESCRIPTION
**Pull request by maidabu**

### CODE REVIEW

**Comment by mgoin** [comment]
Can you share what the error was when building for torch 2.1? Most cpp compilers should support std::optional.. could you just add `#include <optional>` to the aqlm file?

**Comment by maidabu** [comment]
> Can you share what the error was when building for torch 2.1? Most cpp compilers should support std::optional.. could you just add `#include <optional>` to the aqlm file?

This error is not because the c++ compiler does not support std::optional, but because torch2.1 does not support std::optional. The detailed error information is as follows:

[2/3] Building CXX object CMakeFiles/_C.dir/csrc/torch_bindings.cpp.o
FAILED: CMakeFiles/_C.dir/csrc/torch_bindings.cpp.o 
/usr/bin/c++ -DPy_LIMITED_API=3 -DTORCH_EXTENSION_NAME=_C -DUSE_C10D_GLOO -DUSE_C10D_NCCL -DUSE_DISTRIBUTED -DUSE_RPC -DUSE_TENSORPIPE -D_C_EXPORTS -I/vllm/csrc -I/vllm/build/temp.linux-x86_64-3.8/_deps/cutlass-src/include -I/vllm/build/temp.linux-x86_64-3.8/_deps/cutlass-src/tools/util/include -isystem /usr/include/python3.8 -isystem /usr/local/lib/python3.8/dist-packages/torch/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/cuda/include -O2 -g -DNDEBUG -std=gnu++17 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -MD -MT CMakeFiles/_C.dir/csrc/torch_bindings.cpp.o -MF CMakeFiles/_C.dir/csrc/torch_bindings.cpp.o.d -o CMakeFiles/_C.dir/csrc/torch_bindings.cpp.o -c /vllm/csrc/torch_bindings.cpp
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/ivalue.h:1499,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/List_inl.h:4,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/List.h:490,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/IListRef_inl.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/IListRef.h:632,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/WrapDimUtils.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/TensorNames.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/NamedTensorUtils.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/autograd/variable.h:11,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /vllm/csrc/cache.h:3,
                 from /vllm/csrc/torch_bindings.cpp:1:
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/ivalue_inl.h: In instantiation of ‘T c10::generic_to(c10::IValue, c10::_fake_type<T>) [with T = std::optional<at::Tensor>]’:
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/ivalue_inl.h:1933:20:   required from ‘T c10::IValue::to() && [with T = std::optional<at::Tensor>]’
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h:321:33:   required from ‘static decltype(auto) c10::impl::ivalue_to_arg<T, AllowDeprecatedTypes>::call(c10::IValue&) [with T = std::optional<at::Tensor>; bool AllowDeprecatedTypes = false]’
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h:500:94:   required from ‘std::decay_t<typename c10::guts::infer_function_traits<Functor>::type::return_type> c10::impl::call_functor_with_args_from_stack_(c10::OperatorKernel*, c10::DispatchKeySet, c10::Stack*, std::index_sequence<_Idx ...>, c10::guts::typelist::typelist<ArgTypes ...>*) [with Functor = c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&), at::Tensor, c10::guts::typelist::typelist<const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&> >; bool AllowDeprecatedTypes = false; long unsigned int ...ivalue_arg_indices = {0, 1, 2, 3, 4, 5}; ArgTypes = {const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&}; std::decay_t<typename c10::guts::infer_function_traits<Functor>::type::return_type> = at::Tensor; c10::Stack = std::vector<c10::IValue>; std::index_sequence<_Idx ...> = std::integer_sequence<long unsigned int, 0, 1, 2, 3, 4, 5>]’
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h:514:77:   required from ‘std::decay_t<typename c10::guts::infer_function_traits<Functor>::type::return_type> c10::impl::call_functor_with_args_from_stack(c10::OperatorKernel*, c10::DispatchKeySet, c10::Stack*) [with Functor = c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&), at::Tensor, c10::guts::typelist::typelist<const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&> >; bool AllowDeprecatedTypes = false; std::decay_t<typename c10::guts::infer_function_traits<Functor>::type::return_type> = at::Tensor; c10::Stack = std::vector<c10::IValue>]’
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h:580:100:   required from ‘static void c10::impl::make_boxed_from_unboxed_functor<KernelFunctor, AllowDeprecatedTypes>::call(c10::OperatorKernel*, const c10::OperatorHandle&, c10::DispatchKeySet, c10::Stack*) [with KernelFunctor = c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&), at::Tensor, c10::guts::typelist::typelist<const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&> >; bool AllowDeprecatedTypes = false; c10::Stack = std::vector<c10::IValue>]’
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/boxing/KernelFunction_impl.h:159:9:   required from ‘static c10::KernelFunction c10::KernelFunction::makeFromUnboxedFunctor(std::unique_ptr<c10::OperatorKernel>) [with bool AllowLegacyTypes = false; KernelFunctor = c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&), at::Tensor, c10::guts::typelist::typelist<const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&> >]’
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/boxing/KernelFunction_impl.h:196:114:   required from ‘static c10::KernelFunction c10::KernelFunction::makeFromUnboxedRuntimeFunction(FuncType*) [with bool AllowLegacyTypes = false; FuncType = at::Tensor(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&)]’
/usr/local/lib/python3.8/dist-packages/torch/include/torch/library.h:114:66:   required from ‘torch::CppFunction::CppFunction(Func*, std::enable_if_t<c10::guts::is_function_type<FuncType_>::value, std::nullptr_t>) [with Func = at::Tensor(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&); std::enable_if_t<c10::guts::is_function_type<FuncType_>::value, std::nullptr_t> = std::nullptr_t]’
/usr/local/lib/python3.8/dist-packages/torch/include/torch/library.h:629:17:   required from ‘torch::Library& torch::Library::def(NameOrSchema&&, Func&&) & [with NameOrSchema = const char (&)[10]; Func = at::Tensor (*)(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const std::optional<at::Tensor>&)]’
/vllm/csrc/torch_bindings.cpp:109:34:   required from here
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/ivalue_inl.h:1801:9: error: no type named ‘element_type’ in ‘std::__remove_pointer_helper<std::optional<at::Tensor>, std::optional<at::Tensor> >::type’ {aka ‘class std::optional<at::Tensor>’}
 1801 |   using ElemType = typename std::remove_pointer<T>::type::element_type;
      |         ^~~~~~~~
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/ivalue_inl.h:1802:52: error: no matching function for call to ‘c10::IValue::<expression error>()’
 1802 |   return std::move(ivalue).toCustomClass<ElemType>();
      |                                                    ^
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/List_inl.h:4,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/List.h:490,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/IListRef_inl.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/IListRef.h:632,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/WrapDimUtils.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/TensorNames.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/NamedTensorUtils.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/autograd/variable.h:11,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /vllm/csrc/cache.h:3,
                 from /vllm/csrc/torch_bindings.cpp:1:
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/ivalue.h:504:25: note: candidate: ‘template<class T> c10::intrusive_ptr<T> c10::IValue::toCustomClass() &&’
  504 |   c10::intrusive_ptr<T> toCustomClass() &&;
      |                         ^~~~~~~~~~~~~
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/ivalue.h:504:25: note:   template argument deduction/substitution failed:
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/ivalue.h:506:25: note: candidate: ‘template<class T> c10::intrusive_ptr<T> c10::IValue::toCustomClass() const &’
  506 |   c10::intrusive_ptr<T> toCustomClass() const&;
      |                         ^~~~~~~~~~~~~
/usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/ivalue.h:506:25: note:   template argument deduction/substitution failed:

**Comment by mgoin** [comment]
@bnellnm do you know anything on this?

**Comment by maidabu** [comment]
> @bnellnm do you know anything on this?

I'm not sure.This is the answer of GPT4.😅

no type named ‘element_type’ in ‘std::__remove_pointer_helper<std::optional<at::Tensor>, std::optional<at::Tensor>::type’ {aka ‘class std::optional<at::Tensor>}

indicates that you are trying to use std::remove_pointer or equivalent type trait on a std::optional<at::Tensor> type, which is incorrect. std::remove_pointer is designed to operate on pointer types, and it will remove the pointer to yield the pointed-to type. std::optional is a templated wrapper type, not a pointer, and there is no element_type member available in std::optional.

In C++, when you have a template type like std::shared_ptr, std::unique_ptr, or std::weak_ptr, these pointer-like types have a member type element_type defined. For example:

std::shared_ptr<int>::element_type a = 10; // a is int
When dealing with std::optional<at::Tensor>, if you want to get the type at::Tensor from it, you don't need std::remove_pointer because std::optional itself is not a pointer. Instead, you should directly refer to the value_type of std::optional, like this:

std::optional<at::Tensor>::value_type my_tensor;
Here, my_tensor will be of type at::Tensor.

**Pull request closed without merging**
