### PR TITLE
[dbrx] refactor dbrx experts to extend FusedMoe class

### PR DESCRIPTION
**Pull request by divakar-amd**
This PR refactors DbrxExperts to use FusedMoe as the base class with custom weight loader. This is useful to expose the existing features of FusedMoe class for this model.

### CODE REVIEW

**Comment by divakar-amd** [comment]
@simon-mo  @khluu  Could you add me to Buildkite org so that I can trigger the CI build? 
Thanks

**Review by mgoin — APPROVED** [review]
Nice to see, thank you for the contribution! cc @dsikka for the FusedMoE refactor

**Pull request merged**
