### PR TITLE
Support chatglm2

### PR DESCRIPTION
**Pull request by sanfuyee**

### CODE REVIEW

**Comment by exceedzhang** [comment]
image
API Changed! Error!

**Comment by exceedzhang** [comment]
vllm version 0.2.1
ModuleNotFoundError: No module named 'vllm.model_executor.parallel_utils.tensor_parallel'

Then i change vllm.model_executor.parallel_utils.layers ，work error！

image

**Comment by exceedzhang** [comment]
ModuleNotFoundError: No module named 'vllm.model_executor.parallel_utils.tensor_parallel'
Then i change vllm.model_executor.parallel_utils.layers , it work error!

image

**Comment by allenhaozi** [comment]
An error occurred while trying to run locally
```
python3 vllm/entrypoints/openai/api_server.py --served-model-name chatglm3-6b --model /home/vllm/model/chatglm3-6b --trust-remote-code --tokenizer-mode auto --max-num-batched-tokens 8192 --tensor-parallel-size 1
WARNING 10-30 12:40:53 config.py:398] The model's config.json does not contain any of the following keys to determine the original maximum length of the model: ['max_position_embeddings', 'n_positions', 'max_seq_len', 'max_sequence_length', 'max_seq_length', 'seq_len']. Assuming the model's maximum length is 2048.
...
/home/vllm/vllm/model_executor/models/chatglm.py", line 325, in forward
    key_layer = torch.repeat_interleave(
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by simon-mo** [comment]
Thank you for the contribution, unfortunately this PR seems to have some issue and ChatGLM3 also came out. Feel free to coordinate the contribution here if you have bandwidth! 

https://github.com/vllm-project/vllm/issues/1552

**Comment by zhuohan123** [comment]
Again, thank you for your contribution! We merged https://github.com/vllm-project/vllm/pull/1261 and the current main branch supports ChatGLM now. Let us know if the main branch does not look good and feel free to propose any changes!

**Pull request closed without merging**
