### PR TITLE
[Kernel] Initial commit containing new Triton kernels for multi lora serving.

### PR DESCRIPTION
**Pull request by FurtherAI**
SGMV Triton Kernels
---
New Triton kernels for multi lora computation. These (should) handle any shape and data type, apply to loras in a paged format and compute at the actual lora rank and also speed up for grouped lora requests (especially prefill).

The PR contains the kernels, tests for the kernels and benchmarks. A follow up PR will work on adding the ability to use these in vLLM.

ping @Yard1

### CODE REVIEW

**Comment by FurtherAI** [comment]
@Yard1 Any idea why the import fails? Works locally, but the kernel is in a new folder so maybe that path has to be added somewhere?

**Comment by Conless** [comment]
@FurtherAI I am interested in this work. I attempted to integrate SGMV with multi LoRA rank support but encountered difficulties adapting it to the original vllm design.

Could you please share your ideas on how to adapt the SGMV kernels to vllm? Thank you very much!

**Comment by FurtherAI** [comment]
@Yard1 Is there a way to rerun the tests without an empty commit?

**Comment by tensimixt** [comment]
@FurtherAI Does this allow for larger vocabulary Sizes? For example NeMO-12B has a vocab size of 131072 
 If i run this version of vllm from the pull request with LoRA enabled = True will it still say 
 
  ` When using LoRA, vocab size must be  "32000 >= vocab_size <= 128512" `

**Comment by FurtherAI** [comment]
@tensimixt Yeah I think it does. It shouldn't have any issues with different sizes. I'll test it at some point

**Pull request closed without merging**
