### PR TITLE
[WIP] Ray Backend V1

### PR DESCRIPTION
**Pull request by rkooo567**
Only working for TP 1 now.

### CODE REVIEW

**Comment by robertgshaw2-neuralmagic** [comment]
@rkooo567 - QQ, what does Ray give us for V1?

**Comment by rkooo567** [comment]
> @rkooo567 - QQ, what does Ray give us for V1? I thought mp for the workers ended up being more performant in V0

I think compiled graphs can address performance issue. But we will verify that. For the shorter term, I think it can provide 2 benefits;
- remote debugger
- pipeline parallelism performance

For the second part, it can implement PP with cleaner way & provide automatic overlap compute/comm/infiniband support, etc.

**Comment by njhill** [comment]
Irrespective of the mechanism used, for V1 IMO we should rethink the executor abstraction/hierarchy rather than transferring the same structure from V0 and start with something minimal. IIRC we aren't planning to include PP in the first iteration of V1?

**Comment by rkooo567** [comment]
@njhill can you tell me more details about the meaning of "minimal" here? are you saying you want to only support 1 backend?

**Comment by rkooo567** [comment]
Here are some of my thoughts! I'd love to discuss more details @njhill!

- although PP is not considered in the very initial design, we will need it soon anyway, so considering the different backend abstraction now is not a big deal.
- IMO, the executor backend abstraction was okay in the original design and introduced not much complexity
- Even for TP, it can provide additional features like a remote debugger out of the box that's helpful for debugging.

**Comment by njhill** [comment]
Thanks @rkooo567, it might just be my personal feeling, but I've felt for a while that the current executor/worker abstraction could be simplified, and needs some more thought especially w.r.t. how we are supporting different backends and accelerators.

**Comment by rkooo567** [comment]
> Thanks @rkooo567, it might just be my personal feeling, but I've felt for a while that the current executor/worker abstraction could be simplified, and needs some more thought especially w.r.t. how we are supporting different backends and accelerators.

I'd love to talk if you feel this way! Let me make tp > 1 work by today or tomorrow, and we can discuss what interface can be trimmed down. Do you have some time end of this week?

**Comment by andoorve** [comment]
@njhill @rkooo567 Have you had a chance to discuss this yet? Would be great to hear any conclusions.

**Comment by njhill** [comment]
@andoorve @rkooo567 apologies for not getting back to this, I won't have much chance for the next week since I'll be traveling on vacation :-/

But I added some of the thoughts in @tlrmchlsmth's existing V1 TP PR [here](https://github.com/vllm-project/vllm/pull/9856#issuecomment-2467050570), and have been looking more into how we can further hide/overlap the IPC overheads.

**Comment by rkooo567** [comment]
Hi, I am catching up this now. 

Ray Compiled Graph comes with shared memory automatically, so with serialization optimization, it should provide the best performance already.

@njhill @andoorve how's the tp work going on with mp? Do you think having a talk in person can help here?

**Comment by andoorve** [comment]
@rkooo567 We didn't have a chance to discuss yet, but would be interested in case @njhill has new ideas!

**Comment by njhill** [comment]
@rkooo567 yes we can discuss in person too... it was mainly that we're iterating on the architecture still for v1 including simplifying the executor abstraction and concurrency etc.

**Comment by rkooo567** [comment]
The PR is moved to https://github.com/vllm-project/vllm/pull/10725

**Pull request closed without merging**
