### PR TITLE
can allocate when cached_blocks contain all seq needed blocks.

### PR DESCRIPTION
**Pull request by AllenDou**
Before calculating num_free_gpu_blocks is enough or not, gpu_allocator could check if seq's all needed blocks are stored in cached_blocks{}, this scenario happend when --enable-prefix-caching enabled.

### CODE REVIEW

**Review by rkooo567 — COMMENTED** [review]
Consider adding a unit test to block_manager test?

**Comment by AllenDou** [comment]
> Consider adding a unit test to block_manager test?

ok, i will do it.

**Comment by cadedaniel** [comment]
Hi @AllenDou , can you help me understand the impact of this PR? It seems the impact on throughput is minimal (the existing worse-case assumption of 1 new physical block per logical block in reduced to <1 new physical block per logical block).

**Comment by AllenDou** [comment]
> Hi @AllenDou , can you help me understand the impact of this PR? It seems the impact on throughput is minimal (the existing worse-case assumption of 1 new physical block per logical block in reduced to <1 new physical block per logical block).

Yes, it is, Actually, my first purpose was to 'can_allocate' when num_free_gpu_blocks is not enough but these blocks are already stored in cache_blocks{}, Later, I thought that new generated tokens could be stored on gpu mem. this PR could be aborted, thanks for your response.

**Comment by cadedaniel** [comment]
Sounds good, will close.

Thanks and other improvements are welcome :)

**Pull request closed without merging**
