### PR TITLE
[Misc] Collect model support info in a single process per model

### PR DESCRIPTION
**Pull request by DarkLight1337**
Follow-up to #9208

### CODE REVIEW

**Review by youkaichao — APPROVED** [review]
LGTM

**Comment by youkaichao** [comment]
please fix the error. it looks oot registered models are not processed correctly.

**Comment by DarkLight1337** [comment]
It looks like changes to the registry (via `register_model`) aren't being preserved in other processes. Is there a good way to solve this?

**Comment by DarkLight1337** [comment]
I'm thinking of loading the plugin for each process.

**Comment by DarkLight1337** [comment]
I have fixed this by moving the `load_general_plugins` call from `EngineArgs.__post_init__` to all `from_engine_args` methods.

**Comment by youkaichao** [comment]
> It looks like changes to the registry (via `register_model`) aren't being preserved in other processes. Is there a good way to solve this?

good point. the new process does not load plugins. maybe we can just add one line of loading plugin in the `if __name__ == "__main__":`

**Comment by tlrmchlsmth** [comment]
Really timely PR, as I was about to make this worse in #6484 😀

**Pull request merged**
