### PR TITLE
Disable Ray usage stats collection

### PR DESCRIPTION
**Pull request by WoosukKwon**
I just got to know that Ray collects usage data by default. Let's disable it.

### CODE REVIEW

**Comment by Lvjinhong** [comment]
> I just got to know that Ray collects usage data by default. Let's disable it.


So, will this have any impact on performance, or is it just a personal preference? I am passionate about high-performance inference, so I'm considering replacing Ray with TorchRun to potentially boost the performance of vLLM.

**Comment by zhuohan123** [comment]
> > I just got to know that Ray collects usage data by default. Let's disable it.
> 
> So, will this have any impact on performance, or is it just a personal preference? I am passionate about high-performance inference, so I'm considering replacing Ray with TorchRun to potentially boost the performance of vLLM.

This is not related to performance. The changes in https://github.com/vllm-project/vllm/pull/2221 are more related to performance. Will include more details there.

**Review by zhuohan123 — APPROVED** [review]
LGTM!

**Comment by richardliaw** [comment]
No action needed, but just adding a bit of clarification -- this PR will not do anything because the usage stats collection was already disabled before this PR.

I believe vLLM does not force the user to run `ray start` or `ray up` in the CLI, which is the only way where usage stats collection is enabled ([documentation here](https://docs.ray.io/en/latest/cluster/usage-stats.html#how-does-it-work)).

Let me know if I missed anything!

> usage stats collection is not enabled when using local dev clusters started via ray.init() unless it’s a nightly wheel. This means that Ray will never collect data from third-party library users not using Ray directly.

**Comment by WoosukKwon** [comment]
@richardliaw Thanks for the clarification! I recently used Ray nightly and misunderstood that this was enabled by default.

**Pull request merged**
