### PR TITLE
CodeGen Converter

### PR DESCRIPTION
**Pull request by michaelfeil**
This PR aims to integrate CodeGen. Work in progress, not ready.

### CODE REVIEW

**Comment by zhuohan123** [comment]
Please let us know when this PR is ready for review!

**Comment by zhuohan123** [comment]
@michaelfeil Are you still working on the CodeGen model support? Do you need any help from our side?

**Comment by michaelfeil** [comment]
I'll try to get back to you in the coming days!

**Comment by WoosukKwon** [comment]
Closed as this PR is too old.

**Pull request closed without merging**
