### PR TITLE
[CI/Build] Add `is_quant_method_supported` to control quantization test configurations

### PR DESCRIPTION
**Pull request by mgoin**
There were many separate uses of checking CUDA compute capability in order to run quantization tests, so it is best practice to have one function to be the source-of-truth to check support.

Instead of each quantization test having duplicated code such as:
```python
from vllm.model_executor.layers.quantization import QUANTIZATION_METHODS

aqlm_not_supported = True

if torch.cuda.is_available():
    capability = torch.cuda.get_device_capability()
    capability = capability[0] * 10 + capability[1]
    aqlm_not_supported = (capability <
                          QUANTIZATION_METHODS["aqlm"].get_min_capability())
```

It can be replaced with:
```python
from tests.quantization.utils import is_quant_method_supported

aqlm_not_supported = not is_quant_method_supported("aqlm")
```

### CODE REVIEW

**Review by bnellnm — APPROVED** [review]
LGTM

**Review by robertgshaw2-redhat — APPROVED** [review]
much nicer

**Comment by simon-mo** [comment]
sorry i was flipping a flag for CI and this PR got auto-merged. but it actually fail here: https://buildkite.com/vllm/ci/builds/9852#0190082b-69b0-4c9d-9103-6ae6f0cbecfd

**Comment by simon-mo** [comment]
Please open a new PR!

**Pull request merged**
