### PR TITLE
[Hardware][AMD]: Replace HIPCC version with more precise ROCm version

### PR DESCRIPTION
**Pull request by kairos-yu**
Hi all, Ifound that the representation of the ROCm version is somewhat unclear. For instance, in the case of the current ROCm version 6.2.0, the version specified in setup.py is 624, which corresponds to the HIPCC version. To represent the ROCm version more accurately, I opted to utilize the version representation provided in the rocm-core package, which retrieves the ROCm version through the available version query interfaces.
see https://github.com/ROCm/rocm-core/blob/d11f5c20d500f729c393680a01fa902ebf92094b/rocm_version.cpp#L21

On the other hand, the HIPCC version can be directly obtained via torch.version.hip. 

You can also directly use the ROCM_VERSION information provided by the torch package，https://github.com/pytorch/pytorch/blob/cf76c05b4dc629ac989d1fb8e789d4fac04a095a/torch/utils/cpp_extension.py#L244

### CODE REVIEW

**Review by hongxiayang — COMMENTED** [review]
LGTM. Please address the ruff/yapf failures.
Adding @tjtanaa to review too.

**Comment by tjtanaa** [comment]
LGTM as well. RDNA also works.

**Review by hongxiayang — APPROVED** [review]
It can be merged as long as the CI passes.

**Review by DarkLight1337 — APPROVED** [review]
Thanks for helping to review this!

**Pull request merged**
