### PR TITLE
Add support for aquila

### PR DESCRIPTION
**Pull request by shunxing1234**

### CODE REVIEW

**Comment by shunxing1234** [comment]
In order to merge this PR, do I need to provide any additional information?

**Comment by zhuohan123** [comment]
@shunxing1234 Thank you for your great contribution! Can you make sure you pass the format checks and give one example that this model is outputting correct results?

**Comment by shunxing1234** [comment]
> @shunxing1234 Thank you for your great contribution! Can you make sure you pass the format checks and give one example that this model is outputting correct results?

https://github.com/FlagAI-Open/FlagAI/tree/master/examples/Aquila
Hi, thanks for your reply. here is the outputting of aquila
image

**Comment by gesanqiu** [comment]
I have been verified the greedy output of transforemers and vLLM on BAAI/AquilaChat-7B last week, they are the same. What needs pay attention to is Aquila has several stop str, such as '###', '</s>', '[UNK]', and I just made a [PR](https://github.com/lm-sys/FastChat/pull/2192) to FastChat.

**Comment by shunxing1234** [comment]
> I have been verified the greedy output of transforemers and vLLM on BAAI/AquilaChat-7B last week, they are the same. What needs pay attention to is Aquila has several stop str, such as '###', '', '[UNK]', and I just made a [PR](https://github.com/lm-sys/FastChat/pull/2192) to FastChat, after merged we can use openai_api.py on BAAI/AquilaChat-7B.

@gesanqiu Thanks for  your Contribution!

**Review by zhuohan123 — APPROVED** [review]
LGTM! Just tested out `BAAI/AquilaChat-7B` and it works great on a single A100. Thank you for your contribution!

**Comment by ftgreat** [comment]
@zhuohan123 one typo pr https://github.com/vllm-project/vllm/pull/836 , please review it. thanks.

**Pull request merged**
