### PR TITLE
avoid multiple redefinition

### PR DESCRIPTION
**Pull request by MitchellX**
By including these guards, you ensure that if ops.h is included multiple times in different files, its contents will only be processed once by the compiler, avoiding redefinition errors and saving time

### CODE REVIEW

**Comment by simon-mo** [comment]
thank you for your contribution! can you check is this the case for all other header files

**Review by simon-mo — APPROVED** [review]

**Comment by WoosukKwon** [comment]
@MitchellX Thanks for the PR! As Simon mentioned, it seems there are several header files that do not have the guards. Could you please add the guards to all theses header files?

**Comment by MitchellX** [comment]
@simon-mo @WoosukKwon Sure, I'll do it later.

**Comment by WoosukKwon** [comment]
@MitchellX Are you still working on this PR?

**Comment by MitchellX** [comment]
@WoosukKwon My apologies for the oversight. I was so overwhelmed the last few weeks, forgetting to modify the head files. Yes, I'm still working on a vllm related project, and I can help address this issue on Saturday.

**Comment by WoosukKwon** [comment]
@MitchellX I see. Thanks for letting us know. In this case, can I directly modify this PR to accelerate the process? I think we got your point and just needed to add `#pragma once` to other header files. I can take this if you are ok with it.

**Comment by MitchellX** [comment]
@WoosukKwon Sure, do as you wish.

**Review by WoosukKwon — APPROVED** [review]
LGTM. Thanks for pointing this out!

**Pull request merged**
