### PR TITLE
[Speculative decoding] Fix async executing

### PR DESCRIPTION
**Pull request by zxdvd**
I'm try with speculative decoding and got problems with async engine. I think this fix it.
@cadedaniel Could you help to review this?

### CODE REVIEW

**Comment by cadedaniel** [comment]
Will take a look today

**Comment by cadedaniel** [comment]
Hi @zxdvd , thanks for the PR!
* Can you add the stacktrace of the crash you saw to the PR description?
* Can you add a test for async engine + spec decode, so we catch this in the future?

**Comment by cadedaniel** [comment]
I put a suggestion here for how to do the async test https://github.com/vllm-project/vllm/pull/4165#issuecomment-2071124337

**Comment by comaniac** [comment]
@zxdvd thanks for the timely PR! We also need this fix to unblock performance evaluation of #4353 so it'd be better to get it merged ASAP. Did you get a chance working on this PR?

**Comment by cadedaniel** [comment]
I think this one is closer https://github.com/vllm-project/vllm/pull/4249

**Comment by zxdvd** [comment]
I'll close this since it is duplicated to #4165

**Pull request closed without merging**
