### PR TITLE
✨ support local cache for models

### PR DESCRIPTION
**Pull request by prashantgupta24**
Updates how files are pulled from HF Hub to support offline usage with cached files and a fallback in case of networking issues or if HF Hub is down. 

(Without this change, you have to pass the explicit path to the model in your local HF cache as the model name.)

Taken bits from https://github.com/vllm-project/vllm/pull/3125

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]
This looks pretty reasonable to me. Another place we use `snapshot_download` is when loading the tokenizer and other config. It would be useful to search for `snapshot download` or `.from_pretrained` call. 

Any suggestion on how to test this?

**Comment by prashantgupta24** [comment]
What I can do is create another function that does `snapshot_download` 2 times, one with local_files false, if that fails, try with local_files True. Then both `download_weights_from_hf` and `get_quant_config` can use that function to avoid duplication of code. I will remove the existing `try` `catch` from `loader.py`. 

For the `tokenizer`, it uses `modelscope.hub.snapshot_download`, I will see if that has the same functionality as HF's `snapshot_download` for local_files mode.

**Comment by prashantgupta24** [comment]
Or better yet, I can do this
```
 hf_folder = snapshot_download(
            model_name_or_path,
            allow_patterns=allow_patterns,
            cache_dir=cache_dir,
            tqdm_class=DisabledTqdm,
            revision=revision,
            local_files_only=HF_HUB_OFFLINE,
        )
```
?
That way, a network connection attempt is made ONLY if `HF_HUB_OFFLINE` is unset.

**Review by njhill — COMMENTED** [review]
Thanks @prashantgupta24 (and to @tjohnson31415 for the original PR).

Not sure whether you tested this, but in theory the `local_files_only=HF_HUB_OFFLINE` shouldn't be necessary with HF's `snapshot_download` since it already honors this env var.

But it also doesn't harm I guess, and looks like it might still need to be passed like this to modelscope's `snapshot_download`.

There's another instance of that in [loader.py](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/model_loader/loader.py#L135) which should be similarly updated I think?

**Comment by prashantgupta24** [comment]
@njhill whoops forgot that one, updated it, thanks!

And yeah I added `HF_HUB_OFFLINE` to make it consistent across both.

**Comment by prashantgupta24** [comment]
Adding a test case for this shortly!

**Review by rkooo567 — COMMENTED** [review]
I think we should test it? why don't we download the model -> remove instance -> restart the instance with a local file?

**Comment by prashantgupta24** [comment]
> I think we should test it? why don't we download the model -> remove instance -> restart the instance with a local file?

Yes I am planning to add that

**Review by njhill — APPROVED** [review]
Thanks @prashantgupta24 and @tjohnson31415!

**Comment by saivarunk** [comment]
Is there any documentation on how to use the offline option for downloading Huggingface model? 

@njhill @prashantgupta24 @tjohnson31415

**Comment by prashantgupta24** [comment]
@saivarunk if offline mode is enabled, no networking calls are made and models are not downloaded from HF, instead vllm will try to look for that model in the local cache.

**Comment by rkooo567** [comment]
@prashantgupta24 maybe we can update this to the doc (model section) https://docs.vllm.ai/en/latest/?

**Pull request merged**
