### PR TITLE
[CI/Build] [1/3] Reorganize entrypoints tests

### PR DESCRIPTION
**Pull request by DarkLight1337**
To better preserve Git history, I'm splitting this process into multiple PRs.

**Step 1: Split out Chat API tests to another file**
Step 2: Split out Completion API tests to another file
Step 3: Move OpenAI tests to `openai` directory, and LLM tests to `llm` directory.

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]
LGTM. The test seems to be failing though

**Comment by DarkLight1337** [comment]
I think there may be something wrong with the implementation for guided decoding, in that the request handling isn't (externally) stateless. If I swap the order of `guided_decoding_backend` to use in the test from `["outlines", "lm-format-enforcer"]` to `["lm-format-enforcer", "outlines"]` , then the test fails for `"outlines"` backend instead of the current `"lm-format-enforcer"`.

**Comment by DarkLight1337** [comment]
If I add this, the test passes, but later on, `test_response_format_json_object` straight up hangs.

```diff,py
 async def test_guided_choice_chat(client: openai.AsyncOpenAI,
         "content":
         "The best language for type-safe systems programming is "
     }]
+
+    with pytest.raises(openai.BadRequestError):
+        _ = await client.chat.completions.create(model=MODEL_NAME,
+                                                 messages=messages,
+                                                 extra_body=dict(guided_regex={
+                                                     1: "Python",
+                                                     2: "C++"
+                                                 }))
+
     chat_completion = await client.chat.completions.create(
         model=MODEL_NAME,
         messages=messages,
```

**Comment by DarkLight1337** [comment]
Since the failure is not really due to the test itself, I have rearranged the tests so that CI passes and added a note so it can be fixed later.

**Comment by mawong-amd** [comment]
[This line](https://github.com/DarkLight1337/vllm-rocm/blob/8f7b7f8fb4dc3776ee6257b34c67634c075a6ce1/tests/entrypoints/test_openai_chat.py#L82) introduces a regression in the AMD Entrypoints test which we discussed was unnecessary here https://github.com/vllm-project/vllm/pull/5422#issuecomment-2189084755.

If the AMD tests were not cancelled in the last 2 commits of this PR, this regression would have been caught. But AMD tests were not only cancelled here, they were also cancelled in the commit after this PR was merged to main.

**Comment by DarkLight1337** [comment]
I'll tack that on to #5966, thanks for bringing that up!

**Pull request merged**
