### PR TITLE
[Model] Support Solar Model

### PR DESCRIPTION
**Pull request by shing100**
Solar 22B model has been newly uploaded, I hope this PR helps.

HuggingFace: [upstage/solar-pro-preview-instruct](https://huggingface.co/upstage/solar-pro-preview-instruct)

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Adding or changing kernels</h3>
<p>Each custom kernel needs a schema and one or more implementations to be registered with PyTorch.</p>
<ul>
    <li>Make sure custom ops are registered following PyTorch guidelines: <a href="https://pytorch.org/tutorials/advanced/cpp_custom_ops.html#cpp-custom-ops-tutorial">Custom C++ and CUDA Operators</a> and <a href="https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU">The Custom Operators Manual</a></li>
    <li>Custom operations that return <code>Tensors</code> require meta-functions. Meta-functions should be implemented and registered in python so that dynamic dims can be handled automatically. See above documents for a description of meta-functions.</li>
    <li>Use <a href="https://pytorch.org/docs/stable/library.html#torch.library.opcheck"><code>torch.libary.opcheck()</code></a> to test the function registration and meta-function for any registered ops.  See <code>tests/kernels</code> for examples.</li>
    <li>When changing the C++ signature of an existing op, the schema must be updated to reflect the changes.</li>
    <li>If a new custom type is needed, see the following document: <a href="https://docs.google.com/document/d/18fBMPuOJ0fY5ZQ6YyrHUppw9FA332CpNtgB6SOIgyuA">Custom Class Support in PT2</a>.
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by shing100** [comment]
## Summary of changes
### Add SolarModel
vllm/model_executor/models/init.py
vllm/model_executor/models/solar.py

### Add SolarConfig
vllm/transformers_utils/config.py
vllm/transformers_utils/configs/init.py
vllm/transformers_utils/configs/solar.py

Thanks

**Comment by mgoin** [comment]
Could you describe the major differences of this architecture against llama? From a glance looking at the config and modeling code, it seems quite similar

**Comment by shing100** [comment]
This PR introduces the Solar model, a new language model architecture with the following key features:

| Feature | Description |
|---------|-------------|
| BSKCN Structure | Block-Sparse K-Chain Network for efficient layer output reuse |
| Flexible RoPE | Adaptable Rotary Position Embedding implementation |
| Fine-grained Control | Additional config options (bskcn_1, bskcn_2, etc.) for detailed tuning |

This is what I've checked so far.

**Comment by shing100** [comment]
https://huggingface.co/upstage/solar-pro-preview-instruct/discussions/10

**Comment by mgoin** [comment]
These seem like reasonable differences then. Could you fix the formatting first? It should just be `pip install -r requirements-lint.txt` and then `./format.sh`

**Comment by shing100** [comment]
I've run this script before, but the variable name is too long, so there's a problem.

스크린샷 2024-09-18 오전 1 00 25

**Comment by shing100** [comment]
Thank you, I modified the format.

**Comment by mgoin** [comment]
There was a small issue with the SamplerOutput import that I fixed in the latest commit. After that, the model looks to be performing as expected!

```
lm_eval --model vllm --model_args pretrained=upstage/solar-pro-preview-instruct,max_model_len=4096 --tasks gsm8k --num_fewshot 5 --batch_size auto

vllm (pretrained=upstage/solar-pro-preview-instruct,max_model_len=4096), gen_kwargs: (None), limit: None, num_fewshot: 5, batch_size: auto
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|
|-----|------:|----------------|-----:|-----------|---|-----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.8719|±  |0.0092|
|     |       |strict-match    |     5|exact_match|↑  |0.8673|±  |0.0093|
```

**Review by mgoin — APPROVED** [review]

**Comment by yoonniverse** [comment]
Thank you for integrating our Solar model into vLLM, @shing100! It will be very helpful for users exploring Solar.

Just to clarify: `BSKCN` actually stands for **`Block level SKip CoNnection`**, not `Block-Sparse K-Chain Network`. It is an architectural feature we added to the model.

For those interested, our original implementation for Solar vLLM (used in this PR) can be found [here](https://huggingface.co/upstage/solar-pro-preview-instruct/blob/main/vllm_solar.py).

**Pull request merged**
