### PR TITLE
Docker file

### PR DESCRIPTION
**Pull request by NikolaBorisov**
Adding docker file to the project.
Building the c++ extensions in another container and copy the .so files over. This makes the final container smaller.
Build speed could be improved if the extensions are build in parallel.

### CODE REVIEW

**Comment by NikolaBorisov** [comment]
@WoosukKwon @zhuohan123 Would you guys be able to review this? Any feedback is welcome.

**Comment by simon-mo** [comment]
There's concurrent work with #1350. cc @skrider. It seems to me that we can accept both where one Dockerfile focus on build from scartch and another for dev. But it would be great if both can align into one style and approach.

**Comment by skrider** [comment]
I think the way to go would be to have one image for building a wheel from source + dev dependencies and a smaller image for production that has only runtime deps. Could use the builder image in CI to publish the wheel to pypi and also publish the production image to the docker registry.

> This makes the final container smaller.

Definitely a good idea to prune/minify the production container, however the extensions are dominated by the size of the pip install

**Comment by NikolaBorisov** [comment]
I think we can consolidate around #1350.
The advantage of this PR#1415 is that changes to the python code does not cause the docker to rebuild the the c++ code which is the slowest thing. It is important to me to be able to quickly add few lines of python and have the docker image build in 1-2 secs. I think we can modify #1350 to build the .so files and copy them over. 

The other big difference are the base images. I tried to pick bigger base images that already have pytorch installed since of the dependencies this is the biggest one. That is why I thought if we build on top of pytorch image the docker build will be faster. In my PR I'm not sure I got it all working super well because I think we end up installing torch again and getting rid of the old one. I think the #1350 base images might be better. 

Is it ok I make few suggestions to #1350?

**Comment by skrider** [comment]
@NikolaBorisov Yes that would be great - very clever way of speeding up builds. I will update #1350 to support this. Regarding pytorch base images, my thinking was that most of the dependencies in the cuda runtime image are not used, so better to use cuda base. I'm working on pruning the container to get the footprint down even smaller.

**Comment by NikolaBorisov** [comment]
Closing this in because we ported most of the ideas into #1350

**Pull request closed without merging**
