### PR TITLE
[Kernel] Prototype integration of bytedance/flux kernels

### PR DESCRIPTION
**Pull request by tlrmchlsmth**
### Summary
This is a _rough_ prototype integration of the fused Gemm-ReduceScatter and AllGather-Gemm kernels from https://github.com/bytedance/flux.

The overall goal is to improve performance in the multi-GPU case by hiding the latency of collective communications by overlapping compute and data movement.

### Instructions
To use this PR, first follow the instructions from the flux repo to build a wheel and then install it. You will also need to source the `flux_env.sh` file included in this PR. I had to manually set `LD_LIBRARY_PATH` to contain my venv's `lib` directory as well.

### Performance

I am running the following to measure the latency of a request dominated by a large prefill:
```
python3 benchmarks/benchmark_latency.py --model meta-llama/Meta-Llama-3-8B-Instruct \
    --num-iters 100  --batch-size 1 --input-len 2048 --output-len 1 \
    --enforce-eager --tensor-parallel-size 4 --dtype float16
```

On 4 A100's:

This PR:
```
Avg latency: 0.04923512919805944 seconds
10% percentile latency: 0.048771245032548906 seconds
25% percentile latency: 0.04908173996955156 seconds
50% percentile latency: 0.04925268283113837 seconds
75% percentile latency: 0.04937761859036982 seconds
90% percentile latency: 0.04951343145221472 seconds
99% percentile latency: 0.050627540834248065 seconds
```

main:
```
Avg latency: 0.05624247697182 seconds
10% percentile latency: 0.05587919522076845 seconds
25% percentile latency: 0.05596787924878299 seconds
50% percentile latency: 0.05612784903496504 seconds
75% percentile latency: 0.05637543648481369 seconds
90% percentile latency: 0.05679564494639635 seconds
99% percentile latency: 0.05786421288736165 seconds
```

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Frontend]</code> For changes on the vLLM frontend (e.g., OpenAI API server, <code>LLM</code> class, etc.) </li>
    <li><code>[Kernel]</code> for changes affecting CUDA kernels or other compute kernels.</li>
    <li><code>[Core]</code> for changes in the core vLLM logic (e.g., <code>LLMEngine</code>, <code>AsyncLLMEngine</code>, <code>Scheduler</code>, etc.)</li>
    <li><code>[Hardware][Vendor]</code> for hardware-specific changes. Vendor name should appear in the prefix (e.g., <code>[Hardware][AMD]</code>).</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>We adhere to <a href="https://google.github.io/styleguide/pyguide.html">Google Python style guide</a> and <a href="https://google.github.io/styleguide/cppguide.html">Google C++ style guide</a>.</li>
    <li>Pass all linter checks. Please use <a href="https://github.com/vllm-project/vllm/blob/main/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li>Include sufficient tests to ensure the project to stay correct and robust. This includes both unit tests and integration tests.</li>
    <li>Please add documentation to <code>docs/source/</code> if the PR modifies the user-facing behaviors of vLLM. It helps vLLM user understand and utilize the new features or changes.</li>
</ul>

<h3>Notes for Large Changes</h3>
<p>Please keep the changes as concise as possible. For major architectural changes (>500 LOC excluding kernel/data/config/test), we would expect a GitHub issue (RFC) discussing the technical design and justification. Otherwise, we will tag it with <code>rfc-required</code> and might not go through the PR.</p>

<h3>What to Expect for the Reviews</h3>

<p>The goal of the vLLM team is to be a <i>transparent reviewing machine</i>. We would like to make the review process transparent and efficient and make sure no contributor feel confused or frustrated. However, the vLLM team is small, so we need to prioritize some PRs over others. Here is what you can expect from the review process: </p>

<ul>
    <li> After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.</li>
    <li> After the PR is assigned, the reviewer will provide status update every 2-3 days. If the PR is not reviewed within 7 days, please feel free to ping the reviewer or the vLLM team.</li>
    <li> After the review, the reviewer will put an <code> action-required</code> label on the PR if there are changes required. The contributor should address the comments and ping the reviewer to re-review the PR.</li>
    <li> Please respond to all comments within a reasonable time frame. If a comment isn't clear or you disagree with a suggestion, feel free to ask for clarification or discuss the suggestion.
 </li>
</ul>

<h3>Thank You</h3>

<p> Finally, thank you for taking the time to read these guidelines and for your interest in contributing to vLLM. Your contributions make vLLM a great tool for everyone! </p>

</details>

### CODE REVIEW

**Comment by Rainlin007** [comment]
Tested in 13B model, it is more than 40% slower than the main branch. Is there a better optimization solution? Thanks

**Comment by tlrmchlsmth** [comment]
@Rainlin007 Could you share your test setup and numbers? 

There are a couple of things that can be done to improve this PR's performance:
1. The call to `self.ag_gemm_op.reset_signals` can be removed now that https://github.com/bytedance/flux/pull/19 has landed
2. The argument `fuse_reduction=True` to the GemmRS kernel should be changed to False, but I am running into issues with that (see https://github.com/bytedance/flux/issues/10)

After that, I think we'll see speedup on prefills and hopefully large batch size decodes.

**Comment by zheng-ningxin** [comment]
> Tested in 13B model, it is more than 40% slower than the main branch. Is there a better optimization solution? Thanks

Which shape/model are you using? It’s possible that the default GEMM configuration performs poorly at this size. I can retune a GEMM configuration. Thank you.

**Comment by tlrmchlsmth** [comment]
@zheng-ningxin, @Rainlin007's comment was also posted on an earlier version of this PR, so @Rainlin007 you might want to try again now that I'm seeing speedup on my end.

**Comment by wenlei-bao** [comment]
Hey @tlrmchlsmth, is there any blocking issue to merge this PR? Please let us know if anything we could help to make this happen. :)  cc @zheng-ningxin 
Best.

**Comment by tlrmchlsmth** [comment]
Hey @wenlei-bao, one blocking issue is that this PR requires `enforce_eager` be true. That is, the last time I tried it, the Flux kernels don't support CUDA graphs. Do you know if this is still the case?

Beyond that, I need to do some benchmarking and develop some heuristics to decide when this optimization makes sense. The other thing worth mentioning is that ultimately, we don't want to rely on changing the model definition for the integration of the Flux kernels, but I think that the torch.compile rewrites are going slowly enough that it shouldn't block this PR from landing.

**Comment by Pinkypoopoo** [comment]
Unsubscribe

**Comment by wenlei-bao** [comment]
> Hey @wenlei-bao, one blocking issue is that this PR requires `enforce_eager` be true. That is, the last time I tried it, the Flux kernels don't support CUDA graphs. Do you know if this is still the case?

Yes, we don't support/need CUDA graph yet. 
 
> Beyond that, I need to do some benchmarking and develop some heuristics to decide when this optimization makes sense. 

Regarding the heuristics, you might also want to explore the scripts that in Flux tools/ folder for tuning different workloads (if apply), and incorporate different tiling choices for example to your heuristics (if to skip) or (in Flux tuning_config/ config files 
 if you want to config and apply Flux) as well to maximize the performance.

> The other thing worth mentioning is that ultimately, we don't want to rely on changing the model definition for the integration of the Flux kernels, but I think that the torch.compile rewrites are going slowly enough that it shouldn't block this PR from landing.

Sounds great! Looking forward to it. @tlrmchlsmth

**Comment by tlrmchlsmth** [comment]
Abandoning this in favor of https://github.com/vllm-project/vllm/pull/9886!

**Comment by wplf** [comment]
@wenlei-bao Hi, thank you for great works.

I'd like to ask one simple question.
If seqlen of input tensor does not mod tp_size, that is `seqlen % tp_size != 0`,  what will it be?
Will you pad seqlen to mod tp_size ?
If padding, will you remove pad before attn?

**Pull request closed without merging**
