### PR TITLE
[CI/CD] Upgrade PyTorch version to v2.1.1

### PR DESCRIPTION
**Pull request by WoosukKwon**
The latest xformers (v0.0.23) requires PyTorch v2.1.1.

### CODE REVIEW

**Comment by simon-mo** [comment]
update requirements.txt as well?

**Review by simon-mo — APPROVED** [review]
see other comments

**Comment by WoosukKwon** [comment]
@simon-mo Good point. Fixed. I intentionally didn't fix ROCm dependencies, because its patch depends on `xformers==0.0.22.post7`.

**Comment by chiragjn** [comment]
Does this also mean cu118 is no longer supported with vLLM even if torch 2.1.1 supports cu118?

**Comment by WoosukKwon** [comment]
@chiragjn It was an error. We just uploaded the cuda 11.8 wheels to the release notes. Please check them out!

**Pull request merged**
