### PR TITLE
[ci][misc] fix more device count

### PR DESCRIPTION
**Pull request by youkaichao**

### CODE REVIEW

**Comment by youkaichao** [comment]
I'm writing a debug guide for this.

**Comment by DarkLight1337** [comment]
Are you going to fix other occurrences of `torch.cuda.device_count` in this PR? I see that it is called in some other tests as well.

**Comment by youkaichao** [comment]
@DarkLight1337  this pr fixes implicit call to `torch.cuda.device_count()` . Those explicit call can be removed later in a followup PR.

**Comment by DarkLight1337** [comment]
I found that using lazy import in vllm.transformer_utils.image_processor` seems to remove the need for lazy importing the multimodal modules.

**Comment by youkaichao** [comment]
You can see my stack trace at https://github.com/vllm-project/vllm/issues/6056#issue-2385297429 . Yes, image_processor is the part to blame. Lazy import either one would work.

**Comment by DarkLight1337** [comment]
> I found that using lazy import in `vllm.transformer_utils.image_processor` seems to remove the need for lazy importing the multimodal modules. See the changes to that file in #5276.

Let's do it this way since `vllm.transformer_utils.image_processor` is the source of the problem.

**Comment by DarkLight1337** [comment]
#5276 is getting pretty close to merge so I'm inclined to just use that PR.

**Comment by youkaichao** [comment]
close as #5276 will include the fix

**Pull request closed without merging**
