### PR TITLE
Implement Dynamic Token Restriction with allowed_tokens_fn in Sampler

### PR DESCRIPTION
**Pull request by Etelis**
## Summary
This pull request introduces the `allowed_tokens_fn` feature in the `Sampler` class, enabling dynamic token restriction during the text generation process. This functionality allows users to specify a function that determines the set of allowed tokens at each generation step.

## Changes
- Extended `SamplingParams` to include an `allowed_tokens_fn` parameter, which is a callable that takes the current sequence of tokens and the position for the next token, returning a list of allowed token IDs.
- Modified the `Sampler` class to utilize the `allowed_tokens_fn` during the token generation process. The logits are adjusted based on the allowed tokens, effectively removing disallowed tokens from consideration.
- Added logic in the `forward` method of the `Sampler` class to apply the `allowed_tokens_fn` after computing the initial logits and before applying penalties, temperature scaling, and truncation.

## Motivation
The addition of the `allowed_tokens_fn` feature aligns with the functionality available in Hugging Face's Transformers library, specifically the `prefix_allowed_tokens_fn` used in the `generate()` method. This feature is particularly useful for applications requiring controlled or constrained text generation, such as guided dialogue generation, content filtering, or enforcing specific linguistic patterns.

## Notes
- The implementation of `allowed_tokens_fn` aims to be flexible, allowing users to define custom logic for token restriction based on the specific needs of their application.
- This feature enhances the VLLM library's capabilities in text generation, providing users with an additional tool for customizing model outputs.

## Issue Reference
This pull request addresses issue #415: "I want to use the function `prefix_allowed_tokens_fn` of Hugging Face's `model.generate()` in VLLM's source code."

Looking forward to feedback and suggestions on this implementation!

### CODE REVIEW

**Comment by simon-mo** [comment]
Can you explain how is this different from logits processors?

**Comment by Etelis** [comment]
> Can you explain how is this different from logits processors?

allowed_tokens_fn is like having a strict rule that decides exactly which words can or cannot be used at each step in writing a sentence. On the other hand, logits processors are more like giving gentle hints or suggestions on which words might be better to use next, without completely ruling out any specific words.

Maybe I missed something out here? but it seemed more intuitive that way.

**Comment by simon-mo** [comment]
>  The logits are adjusted based on the allowed tokens, effectively removing disallowed tokens from consideration.

> prefix_allowed_tokens_fn (Callable[[int, torch.Tensor], List[int]], optional) — If provided, this function constraints the beam search to allowed tokens only at each step. This argument is useful for constrained generation conditioned on the prefix, as described in [Autoregressive Entity Retrieval](https://arxiv.org/abs/2010.00904)

I believe you can achieve this with logits processors, if you can modify the implementation to use logits processors instead, that would very simply the code. 

To perform the restriction, you can just set the logits of disallowed tokens to -inf so it won't be sampled at all. The logits processors have the API of `fn(past_tokens, curr_logits) -> new_logits`. 

Please let me know if I still had mistaken the role of prefix_allowed_tokens_fn 🙇‍♂️

**Comment by imiraoui** [comment]
This will be huge!

**Comment by Etelis** [comment]
I will make it happen today / 2moro

**Comment by hmellor** [comment]
Closing because:
- PR is 3 months stale
- PR functionality can be achieved using existing features (logit processors)

**Comment by WANGBohaO-jpg** [comment]
> logits processors

But how to use prefix_allowed_tokens_fn when using beam search? Thanks!

**Comment by cocoshe** [comment]
try to use like this may work:
https://github.com/huggingface/transformers/blob/242eb9cbdc2513d347fe528f4ff7111e90bb4372/src/transformers/generation/logits_process.py#L1371-L1440

wrap it into the logits_process

**Pull request closed without merging**
